### PR TITLE
Remove Some Of The Windows Code

### PR DESCRIPTION
**Pull request by Gibberditoslumber**
^
|
|
|

### CODE REVIEW

**Comment by Joalor64GH** [comment]
i don't get it

**Comment by TahirArch** [comment]
you might wanna look at this

https://github.com/ShadowMario/FNF-PsychEngine/pull/8377

**Comment by Gibberditoslumber** [comment]
it won't compile

**Comment by TahirArch** [comment]
yes it will

**Comment by Gibberditoslumber** [comment]
ive tried to compile it it wont work look image

**Comment by Stilic** [comment]
> ive tried to compile it it wont work look image

try to follow https://github.com/Stilic/FNF-PsychEngine/blob/main/README.md#installation

**Comment by Gibberditoslumber** [comment]
i did

**Comment by Gibberditoslumber** [comment]
and after updating it this happens 
'source/PlayState.hx:8: characters 8-24 : Type not found : vlc.VideoHandler
source/FunkinLua.hx:37: characters 8-23 : Type not found : vlc.VideoSprite
source/PlayState.hx:269: characters 19-31 : Type not found : VideoHandler
source/StrumNote.hx:9: lines 9-165 : Defined in this class
source/PlayState.hx:110: characters 2-47 : Method set_songSpeed required by property songSpeed is missing
source/animateatlas/AtlasFrameMaker.hx:49: characters 23-37 : PlayState has no field addTextToDebug
source/FunkinLua.hx:1978: characters 23-37 : PlayState has no field addTextToDebug
source/FunkinLua.hx:2094: characters 29-35 : PlayState has no field isDead
source/FunkinLua.hx:440: characters 26-36 : PlayState has no field callOnLuas
source/FunkinLua.hx:453: characters 26-36 : PlayState has no field callOnLuas
source/FunkinLua.hx:466: characters 26-36 : PlayState has no field callOnLuas
source/FunkinLua.hx:479: characters 26-36 : PlayState has no field callOnLuas
source/FunkinLua.hx:492: characters 26-36 : PlayState has no field callOnLuas
source/FunkinLua.hx:511: characters 26-36 : PlayState has no field callOnLuas
source/FunkinLua.hx:528: characters 26-36 : PlayState has no field callOnLuas
source/FunkinLua.hx:542: characters 26-36 : PlayState has no field callOnLuas
source/FunkinLua.hx:556: characters 26-36 : PlayState has no field callOnLuas
source/FunkinLua.hx:570: characters 26-36 : PlayState has no field callOnLuas
source/FunkinLua.hx:616: characters 26-36 : PlayState has no field callOnLuas
source/FunkinLua.hx:630: characters 26-36 : PlayState has no field callOnLuas
source/FunkinLua.hx:647: characters 24-34 : PlayState has no field callOnLuas
source/FunkinLua.hx:647: characters 61-70 : Arrays of mixed types are only allowed if the type is forced to Array<Dynamic>
source/FunkinLua.hx:647: characters 61-70 : Int should be String
source/FunkinLua.hx:690: characters 23-40 : PlayState has no field RecalculateRating
source/FunkinLua.hx:694: characters 23-40 : PlayState has no field RecalculateRating
source/FunkinLua.hx:698: characters 23-40 : PlayState has no field RecalculateRating
source/FunkinLua.hx:702: characters 23-40 : PlayState has no field RecalculateRating
source/FunkinLua.hx:706: characters 23-40 : PlayState has no field RecalculateRating
source/FunkinLua.hx:710: characters 23-40 : PlayState has no field RecalculateRating
source/FunkinLua.hx:730: characters 43-53 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:731: characters 43-53 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:732: characters 41-51 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:733: characters 44-54 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:734: characters 45-55 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:735: characters 43-53 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:736: characters 44-54 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:737: characters 44-54 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:745: characters 43-53 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:746: characters 43-53 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:747: characters 41-51 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:748: characters 44-54 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:756: characters 43-53 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:757: characters 43-53 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:758: characters 41-51 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:759: characters 44-54 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:770: characters 23-41 : PlayState has no field addCharacterToList
source/FunkinLua.hx:784: characters 23-39 : PlayState has no field triggerEventNote
source/FunkinLua.hx:789: characters 23-37 : PlayState has no field startCountdown (Suggestion: skipCountdown)
source/FunkinLua.hx:792: characters 23-32 : PlayState has no field KillNotes
source/FunkinLua.hx:793: characters 23-30 : PlayState has no field endSong
source/PauseSubState.hx:268: characters 22-28 : PlayState has no field paused
source/FunkinLua.hx:806: characters 14-34 : Class<PlayState> has no field cancelMusicFadeTween
source/FunkinLua.hx:819: characters 23-36 : PlayState has no field transitioning (Suggestions: transitionIn, transitionOut)
source/FunkinLua.hx:870: characters 23-33 : PlayState has no field moveCamera
source/FunkinLua.hx:887: characters 23-36 : PlayState has no field ratingPercent
source/FunkinLua.hx:890: characters 23-33 : PlayState has no field ratingName'

**Comment by Stilic** [comment]
> and after updating it this happens source/PlayState.hx:8: characters 8-24 : Type not found : vlc.VideoHandler source/FunkinLua.hx:37: characters 8-23 : Type not found : vlc.VideoSprite source/PlayState.hx:269: characters 19-31 : Type not found : VideoHandler source/StrumNote.hx:9: lines 9-165 : Defined in this class source/PlayState.hx:110: characters 2-47 : Method set_songSpeed required by property songSpeed is missing source/animateatlas/AtlasFrameMaker.hx:49: characters 23-37 : PlayState has no field addTextToDebug source/FunkinLua.hx:1978: characters 23-37 : PlayState has no field addTextToDebug source/FunkinLua.hx:2094: characters 29-35 : PlayState has no field isDead source/FunkinLua.hx:440: characters 26-36 : PlayState has no field callOnLuas source/FunkinLua.hx:453: characters 26-36 : PlayState has no field callOnLuas source/FunkinLua.hx:466: characters 26-36 : PlayState has no field callOnLuas source/FunkinLua.hx:479: characters 26-36 : PlayState has no field callOnLuas source/FunkinLua.hx:492: characters 26-36 : PlayState has no field callOnLuas source/FunkinLua.hx:511: characters 26-36 : PlayState has no field callOnLuas source/FunkinLua.hx:528: characters 26-36 : PlayState has no field callOnLuas source/FunkinLua.hx:542: characters 26-36 : PlayState has no field callOnLuas source/FunkinLua.hx:556: characters 26-36 : PlayState has no field callOnLuas source/FunkinLua.hx:570: characters 26-36 : PlayState has no field callOnLuas source/FunkinLua.hx:616: characters 26-36 : PlayState has no field callOnLuas source/FunkinLua.hx:630: characters 26-36 : PlayState has no field callOnLuas source/FunkinLua.hx:647: characters 24-34 : PlayState has no field callOnLuas source/FunkinLua.hx:647: characters 61-70 : Arrays of mixed types are only allowed if the type is forced to Array source/FunkinLua.hx:647: characters 61-70 : Int should be String source/FunkinLua.hx:690: characters 23-40 : PlayState has no field RecalculateRating source/FunkinLua.hx:694: characters 23-40 : PlayState has no field RecalculateRating source/FunkinLua.hx:698: characters 23-40 : PlayState has no field RecalculateRating source/FunkinLua.hx:702: characters 23-40 : PlayState has no field RecalculateRating source/FunkinLua.hx:706: characters 23-40 : PlayState has no field RecalculateRating source/FunkinLua.hx:710: characters 23-40 : PlayState has no field RecalculateRating source/FunkinLua.hx:730: characters 43-53 : PlayState has no field getControl (Suggestion: get_controls) source/FunkinLua.hx:731: characters 43-53 : PlayState has no field getControl (Suggestion: get_controls) source/FunkinLua.hx:732: characters 41-51 : PlayState has no field getControl (Suggestion: get_controls) source/FunkinLua.hx:733: characters 44-54 : PlayState has no field getControl (Suggestion: get_controls) source/FunkinLua.hx:734: characters 45-55 : PlayState has no field getControl (Suggestion: get_controls) source/FunkinLua.hx:735: characters 43-53 : PlayState has no field getControl (Suggestion: get_controls) source/FunkinLua.hx:736: characters 44-54 : PlayState has no field getControl (Suggestion: get_controls) source/FunkinLua.hx:737: characters 44-54 : PlayState has no field getControl (Suggestion: get_controls) source/FunkinLua.hx:745: characters 43-53 : PlayState has no field getControl (Suggestion: get_controls) source/FunkinLua.hx:746: characters 43-53 : PlayState has no field getControl (Suggestion: get_controls) source/FunkinLua.hx:747: characters 41-51 : PlayState has no field getControl (Suggestion: get_controls) source/FunkinLua.hx:748: characters 44-54 : PlayState has no field getControl (Suggestion: get_controls) source/FunkinLua.hx:756: characters 43-53 : PlayState has no field getControl (Suggestion: get_controls) source/FunkinLua.hx:757: characters 43-53 : PlayState has no field getControl (Suggestion: get_controls) source/FunkinLua.hx:758: characters 41-51 : PlayState has no field getControl (Suggestion: get_controls) source/FunkinLua.hx:759: characters 44-54 : PlayState has no field getControl (Suggestion: get_controls) source/FunkinLua.hx:770: characters 23-41 : PlayState has no field addCharacterToList source/FunkinLua.hx:784: characters 23-39 : PlayState has no field triggerEventNote source/FunkinLua.hx:789: characters 23-37 : PlayState has no field startCountdown (Suggestion: skipCountdown) source/FunkinLua.hx:792: characters 23-32 : PlayState has no field KillNotes source/FunkinLua.hx:793: characters 23-30 : PlayState has no field endSong source/PauseSubState.hx:268: characters 22-28 : PlayState has no field paused source/FunkinLua.hx:806: characters 14-34 : Class has no field cancelMusicFadeTween source/FunkinLua.hx:819: characters 23-36 : PlayState has no field transitioning (Suggestions: transitionIn, transitionOut) source/FunkinLua.hx:870: characters 23-33 : PlayState has no field moveCamera source/FunkinLua.hx:887: characters 23-36 : PlayState has no field ratingPercent source/FunkinLua.hx:890: characters 23-33 : PlayState has no field ratingName

can we chat about it in my pr instead of talking here?

**Comment by Gibberditoslumber** [comment]
ok

**Comment by hayfii** [comment]
Why you wanna remove it?

**Comment by Gibberditoslumber** [comment]
n o

**Comment by Gibberditoslumber** [comment]
CLOSED CUZ YEAH

**Pull request closed without merging**
