### PR TITLE
Removed Botplay Lag (Idk if works)

### PR DESCRIPTION
**Pull request by Geovis848494**

### CODE REVIEW

**Comment by system32unknown** [comment]
why android

**Comment by Stefan2008Git** [comment]
THE FUCK? Why would you add the thing that even not gonna be officially merged? Average DaB fan

**Comment by Vortex2Oblivion** [comment]
"Idk if it works"
How do you not know if it works??????

**Comment by Stefan2008Git** [comment]
> "Idk if it works" How do you not know if it works??????

It just removes rating pop-up to make player strum notes "unlaggable"

**Comment by CharlesCatYT** [comment]
this is just the 92956893472395937239594637th time someone opened a damn android pr, this time removing the rating popups, like does it really fix the lag?!?!?!?!? probably not cuz someone else managed to fix the botplay lag in their own psych fork without cutting them


again, another android pr, just without rating popups

**Comment by Vortex2Oblivion** [comment]
> It just removes rating pop-up to make player strum notes "unlaggable"

💀

**Comment by Stefan2008Git** [comment]
> this is just the 92956893472395937239594637th time someone opened a damn android pr, this time removing the rating popups, like does it really fix the lag?!?!?!?!? probably not cuz someone else managed to fix the botplay lag in their own psych fork without cutting them
> 
> again, another android pr, just without rating popups

JS Engine? Nah, i really hate that fork for some reason because it's made for asshole Dave and Bambi spmatracks to handle lag with "better strum notes"

**Comment by CharlesCatYT** [comment]
> > this is just the 92956893472395937239594637th time someone opened a damn android pr, this time removing the rating popups, like does it really fix the lag?!?!?!?!? probably not cuz someone else managed to fix the botplay lag in their own psych fork without cutting them
> > again, another android pr, just without rating popups
> 
> JS Engine? Nah, i really hate that fork for some reason because it's made for asshole Dave and Bambi spmatracks to handle lag with "better strum notes"

yeah i kinda hate it too but at least the *"botplay lag"* is there, but i didnt actually try that so

**Comment by Stefan2008Git** [comment]
> > > this is just the 92956893472395937239594637th time someone opened a damn android pr, this time removing the rating popups, like does it really fix the lag?!?!?!?!? probably not cuz someone else managed to fix the botplay lag in their own psych fork without cutting them
> > > again, another android pr, just without rating popups
> > 
> > 
> > JS Engine? Nah, i really hate that fork for some reason because it's made for asshole Dave and Bambi spmatracks to handle lag with "better strum notes"
> 
> yeah i kinda hate it too but at least the _"botplay lag removal"_ is there, but i didnt actually try that so

Who actrually needs that shit honestly? It was your device problem with bad CPU

**Pull request closed without merging**
