### PR TITLE
No more healing on sustain notes

### PR DESCRIPTION
**Pull request by DabbinDude316B**
This is simple, and easy. Don't hate on me please

### CODE REVIEW

**Comment by Mastercopper2346** [comment]
#ripKadeEngine

**Review by Starveldt — COMMENTED** [review]
why?

**Comment by RedstoneRuler** [comment]
please don't merge this

**Comment by Parsellol** [comment]
no

**Comment by EyeDaleHim** [comment]
I do not agree with this change

**Comment by Mastercopper2346** [comment]
@EyeDaleHim read the description

**Comment by SrtHero278** [comment]
this might not get merged since Shadow wants to keep this Engine as vanilla as possible.

**Review by nahiassis — COMMENTED** [review]
i dont hate you but
this is kinda stupid

**Comment by TheRealJake12** [comment]
people actually crying about FNF being too hard and holding on to the hold notes healing.

**Comment by Mastercopper2346** [comment]
Then I’ll make a better pr

**Comment by BeastlyGhost** [comment]
shadow will merge this and then revert the changes just to poke fun at all of you

**Comment by Mastercopper2346** [comment]
@BeastlyGhost Please read the desc

**Review by OasisAcademy2 — CHANGES_REQUESTED** [review]
at least make it an option
because that will get merged if SM gets interested on not reverting it

**Comment by REALHaydenGaming** [comment]
Yep, it's that pull request vandalizer

**Comment by Mastercopper2346** [comment]
Did you read the description?

**Comment by nintendofan44** [comment]
> at least make it an option because that will get merged if SM gets interested on not reverting it

i agree with this guy

**Pull request closed without merging**
