### PR TITLE
Create MainMenuState

### PR DESCRIPTION
**Pull request by gta33gamer**
Say thanks

### CODE REVIEW

**Comment by KarimAkra** [comment]
Not saying thanks

**Comment by mcagabe19** [comment]
omg so useful,..,,.,.,.,.,.,

**Comment by CharlesCatYT** [comment]
you're not welcome

**Comment by Stefan2008Git** [comment]
> omg so useful,..,,.,.,.,.,.,

💀

**Comment by CrusherNotDrip** [comment]
> Say thanks

no thanks

**Comment by Gearybeer** [comment]
I say this respectfully,
# jump off a cliff

**Comment by Fletchunter** [comment]
lol "say thanks"

**Comment by MarioGuyTakenAgain** [comment]
sir its in the damn files, what build of psych engine are you on sir??????

**Comment by ShadowMario** [comment]
kill yourself

**Pull request closed without merging**
