### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Rudyrue**
update README.md so that it has up-to-date features and changes/credits and installation directions

### CODE REVIEW

**Comment by Unholywanderer** [comment]
who are you

**Comment by Rudyrue** [comment]
👿

**Comment by Rudyrue** [comment]
stop failing action builds

**Review by moxie-coder — APPROVED** [review]

**Comment by Unholywanderer** [comment]
fix it you british ass mf!!!

**Comment by Rudyrue** [comment]
:imp:

**Comment by Unholywanderer** [comment]
👿

**Comment by TheLeerName** [comment]
```
haxelib install hmm
haxelib run hmm install
```
?

**Comment by Rudyrue** [comment]
hmm sucks

**Review by ghost — COMMENTED** [review]
useless

**Comment by Rudyrue** [comment]
??

**Review by NexIsDumb — CHANGES_REQUESTED** [review]
well no pretty much everything you deleted was useful
plus why installing the libs like that if plexus did a whole thing for automatic setup???

**Comment by Rudyrue** [comment]
this pr was made way before crow's pr

**Comment by Rudyrue** [comment]
also MOST of the README was out of date i don't see what i deleted or changed that would've been helpful

**Comment by NexIsDumb** [comment]
> this pr was made way before crow's pr

still i added the hxCodec issue line so people won't create duplicates why are you deleting it lmfao

**Comment by Rudyrue** [comment]
i didn't delete anything related to hxcodec what

**Comment by NexIsDumb** [comment]
> also MOST of the README was out of date i don't see what i deleted or changed that would've been helpful

the hxCodec line preventing ppl from creating duplicate for example

**Comment by NexIsDumb** [comment]
> i didn't delete anything related to hxcodec what

read the issue part

**Comment by Rudyrue** [comment]
that uses hmm which is basically redundant and it's on an old version

i don't see why you couldn't just `haxelib install hxCodec`

**Comment by NexIsDumb** [comment]
> that uses hmm which is basically redundant and it's on an old version
> 
> 
> 
> i don't see why you couldn't just `haxelib install hxCodec`

nop it still happens on the newest hxCodec version
yes if you only install it inside .haxelib using hmm
but it's not hmm fault, it's hxCodec devs fault
plus now you should prob update the readme based on plexus' hmm updates at this point since we're not gonna change them (since its a good actual optimized method)

**Comment by NexIsDumb** [comment]
but since plexus already did it, all of the edited installation part is useless

**Comment by Rudyrue** [comment]
ok but this pr is like weeks old and it's most likely not gonna get merged so im probably just gonna close it

and again i made this pr like a week before crow's so why is that relevant

**Comment by NexIsDumb** [comment]
> ok but this pr is like weeks old and it's most likely not gonna get merged so im probably just gonna close it
> 
> 
> 
> and again i made this pr like a week before crow's so why is that relevant

yeah thats where i wanted to arrive

**Pull request closed without merging**
