### PR TITLE
Fix FPS being incorrectly calculated

### PR DESCRIPTION
**Pull request by crowplexus**
hi rudy hi zyfix

### CODE REVIEW

**Comment by Rudyrue** [comment]
imp emoji

**Comment by Unholywanderer** [comment]
crow!!! you gotta add something like 
`currentFPS = times.length < FlxG.updateFramerate ? times.length : FlxG.updateFramerate;`
or it still wont update because currentFPS wont ever be lower than update framerate after its initially set and reaches it i think idk
it just didnt update until i did this 😔

**Comment by mcagabe19** [comment]
> imp emoji

👿

**Comment by Stefan2008Git** [comment]
I imported to my modified Psych 0.7.1h build, but the FPS is staying on 60 framerates for some reason @crowplexus. Do you know why is happening that?

**Pull request merged**
