### PR TITLE
Funkin Lua

### PR DESCRIPTION
**Pull request by ghost**
This pull request does the same as https://github.com/ShadowMario/FNF-PsychEngine/pull/10272 but better.

* Fixed HScript for good.
* Added FlxSpriteGroup to Luas.
* Calling something on Luas also calls it to HScript.
* Setting something on Luas also sets it to HScript.
* Adding callbacks uses a local function.

### CODE REVIEW

**Review by CrusherNotDrip — APPROVED** [review]

**Review by TheKitBoi — APPROVED** [review]

**Review by MemeHoovy — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by Raltyro — APPROVED** [review]
W!!

**Review by iym1337 — APPROVED** [review]
real

**Review by Parsellol — APPROVED** [review]

**Review by rodney528 — APPROVED** [review]
Wow, that's a lot of change.

**Comment by MemeHoovy** [comment]
> Wow, that's a lot of change.

yep

**Review by Luisinhi010 — APPROVED** [review]

**Comment by MemeHoovy** [comment]
@Luisinhi010 I haven't seen you on github in a while

**Review by stilic — APPROVED** [review]

**Review by Raltyro — COMMENTED** [review]
I tested it just now and this pr broke some of scripts that uses runHaxeCode/addHaxeLibrary, or just straight up doesn't work, do anybody know why?

**Comment by TheWorldMachine** [comment]
> I tested it just now and this pr broke some of scripts that uses runHaxeCode/addHaxeLibrary, or just straight up doesn't work, do anybody know why?
It worked for me, lemme check again.

**Comment by TheWorldMachine** [comment]
Yeah they work properly.

**Comment by Raltyro** [comment]
Alright i will test it again sometime soon

**Review by rodney528 — APPROVED** [review]

**Review by rodney528 — APPROVED** [review]

**Review by MemeHoovy — APPROVED** [review]

**Review by min89xd — APPROVED** [review]

**Comment by Luisinhi010** [comment]
> @Luisinhi010 I haven't seen you on github in a while

i was studying, and my main project is private for now.

**Comment by MemeHoovy** [comment]
> > @Luisinhi010 I haven't seen you on github in a while
> 
> i was studying, and my main project is private for now.

oh

**Review by Luisinhi010 — APPROVED** [review]
it works really well tbh

**Review by Parsellol — APPROVED** [review]

**Review by JorosTheModderPH — APPROVED** [review]

**Review by rodney528 — APPROVED** [review]

**Comment by MemeHoovy** [comment]
why did you close this?

**Comment by TheWorldMachine** [comment]
> why did you close this?

This will probably be rejected anyway.

**Comment by MemeHoovy** [comment]
> > why did you close this?
> 
> This will probably be rejected anyway.

:(

**Pull request closed without merging**
