### PR TITLE
Possible spritemap support for 2019+.

### PR DESCRIPTION
**Pull request by DeadSyntaxdev**
Not sure if it supports lua. Will test later when I find someone to volunteer for that.

### CODE REVIEW

**Review by MemeHoovy — APPROVED** [review]

**Comment by ACrazyTown** [comment]
Why did you add a haxelib library in Project.xml and copy the files to the source folder? Only one of those is neccessary.

**Review by TheKitBoi — APPROVED** [review]

**Comment by TheKitBoi** [comment]
Ima test this by importing the code from the repository
to see if this works
(Theres no changes to the Character Editor because it still uses the bb one)

**Comment by Raltyro** [comment]
Obviously wont work

**Comment by XS09-dev** [comment]
I probably was doing this while I was out of it. Let me re-do it. So don't approve for now.

**Comment by XS09-dev** [comment]
Or close it for now n' stuff.

**Comment by XS09-dev** [comment]
Actually yea I'll close it for now and redo it later on.

**Comment by XS09-dev** [comment]
> 

Also the haxelib was added from one of the project.xml samples on the flxanimate download.

**Pull request closed without merging**
