### PR TITLE
use the fnf alphabet font instead of the vcr font for the text when you dont have any mods in the mods menu

### PR DESCRIPTION
**Pull request by Trayfellow**
changes the text font from this
oldmenutext

to this
newmenutext

it kinda looks nicer

### CODE REVIEW

**Comment by Gui-iago** [comment]
the text blink doesn't work for the second and third texts

I found a woraround, adding a second and third sine, then setting them, simple

**Comment by Gui-iago** [comment]
image

**Comment by trayfellow** [comment]
> image

huh, weird, it worked for me, guess ill update this pr with this soon

**Comment by trayfellow** [comment]
> > image
> 
> huh, weird, the blink worked for me, guess ill update this pr with this soon

**Comment by Gui-iago** [comment]
> > > image
> > 
> > 
> > huh, weird, the blink worked for me, guess ill update this pr with this soon

I just gave it some test, noModsSine3 crashes, I fixed it by removing Sine3

**Comment by cherryiguess** [comment]
not a big change but it looks nicer

**Comment by Doritojoey** [comment]
If you do this for other menus or like the statistics below the health bar then this would be cool cuz im absolute shit at haxe coding and cant do it myself

**Review by ghost — APPROVED** [review]
Ok I Like This 
Edit: I Like This Cause Its A Better Thing Instead Of It

**Comment by Doritojoey** [comment]
How old are you jesus

**Comment by ShadowMario** [comment]
I don't wanna

**Comment by Aidenkp112** [comment]
jesus?

**Pull request closed without merging**
