### PR TITLE
Funkin Mods

### PR DESCRIPTION
**Pull request by NimuFurrySoftUwU**

### CODE REVIEW

**Comment by Randomxdp** [comment]
Callat Nimu

**Comment by LeanDapper** [comment]
whaT kind of sick joke is this

**Comment by VMan-2002** [comment]
why do people keep doing this

**Comment by kingyomoma** [comment]
this is not how pull requests work

**Comment by BeastlyGhost** [comment]
this person also did the same thing on Forever Engine's repository, probably a troll, close this lol

**Comment by HiroMizuki** [comment]
cringe

**Comment by ExpungedRealNoFake** [comment]
NIMUDEVUWU GET OUT AAAAAAAA

**Comment by Joalor64GH** [comment]
hey guys what did i miss? oh wait. just another trash pr.

**Comment by doggogit** [comment]
bruh what the hell bruh

**Comment by Meme1079** [comment]
i feel like this is a troll why? when there's pointless pr like this, it usually attract a lot of people to comment this pointless pr. If it's not a troll then stop making pr like this, this is not how it works. You're just making people wanting to hate you even more.

**Comment by GrexpungedYT** [comment]
what a fatherless act

**Comment by BoloVEVO** [comment]
This is for your own good pal.
image

**Comment by cyn-8** [comment]
you need to make a fork before doing commits because the way you did it its trying to merge to main

**Comment by CrusherMods** [comment]
`package;

class DumbKidLol extends RealDumbass
{
    var bitches:Int = 1;
    var family:Bool = true;
    var gotalife:Bool = true;
    var adopted:Bool = false;
    var STUPID:Bool = false;
    var ratio:Int = 0;
    var hasBrain:Bool = true;
    var stupidKid:String = 'NimuDevUwU';

    override function create()
    {
        if (stupidKid == 'NimuDevUwU') 
        {
            bitches = 0;
            family = false;
            gotalife = false;
            adopted = true;
            STUPID = true;
            ratio++;
            hasBrain = false;
        }
    }
}`

**Comment by Arthurs-code** [comment]
guys could you just stop being some toxic mfs just because this guy made a pr instead of a fork for their mod

**Comment by BoloVEVO** [comment]
> you need to make a fork before doing commits because the way you did it its trying to merge to main

It's not the first time lolk. He does have a fork but idk why the funk he does a pull request to the main branch lol.
image

**Comment by Wither362** [comment]
> guys could you just stop being some toxic mfs just because this guy made a pr instead of a fork for their mod

Lol, I would accept this if I don’t have seen the other 6 pr this person has made

**Comment by CrusherMods** [comment]
> guys could you just stop being some toxic mfs just because this guy made a pr instead of a fork for their mod

he is always doing this though... he did it on this github repo, kade engine, yoshicrafter engine and others
this is obviously not a mistake

**Review by charlesisfeline — COMMENTED** [review]
this is just a fatherless act

**Comment by Wither362** [comment]
Can someone please ban this person please?

**Comment by GrexpungedYT** [comment]
> Can someone please ban this person please?

i cant, but i must tell ShadowMario to close this and ban the person that made this pull request

**Review by BoloVEVO — COMMENTED** [review]
I hope your dad comes back from buying milk.

**Comment by GrexpungedYT** [comment]
@ShadowMario CLOSE THIS NOW!!!!

**Comment by Wither362** [comment]
Really?

This is wrong, it must say: “it has a LOT of conflicts with the base branch”

**Comment by BoloVEVO** [comment]
image

**Comment by CrusherMods** [comment]
> image
> 
> 

best screenshot in existence

**Comment by Wither362** [comment]
WAIT!! I just realized, that @juandavid45, is @NimuDevUwU!! See it here: #8528 !! LOL

**Comment by TheKitBoi** [comment]
image

why

**Comment by TheKitBoi** [comment]
image

i made a better one

**Comment by HiroMizuki** [comment]
and also, @NimuDevUwU
try to be fuckin useful like #8695

**Comment by CrusherMods** [comment]
> > ```
> > package;
> > 
> > class DumbKidLol extends RealDumbass
> > {
> >     var bitches:Int = 1;
> >     var family:Bool = true;
> >     var gotalife:Bool = true;
> >     var adopted:Bool = false;
> >     var STUPID:Bool = false;
> >     var ratio:Int = 0;
> >     var hasBrain:Bool = true;
> >     var stupidKid:String = 'NimuDevUwU';
> > 
> >     override function create()
> >     {
> >         if (stupidKid == 'NimuDevUwU') 
> >         {
> >             bitches = 0;
> >             family = false;
> >             gotalife = false;
> >             adopted = true;
> >             STUPID = true;
> >             ratio++;
> >             hasBrain = false;
> >         }
> >     }
> > }
> > ```
> 
> can i pull this to my fnf repo 💀

if your actually gonna do it then sure why not 💀

**Comment by PrismLight** [comment]
Time to compare the shit from this commit to #3232

Which one is more useless?

**Comment by HaxLua** [comment]
> Time to compare the shit from this commit to #3232
> 
> Which one is more useless?

# ALL OF THEM

**Comment by HiroMizuki** [comment]
> Time to compare the shit from this commit to #3232
> 
> Which one is more useless?

i think the #3232 is the dumbest, but both are shitty and funny to laugh at

**Comment by GrexpungedYT** [comment]
image

**Comment by Swapper1** [comment]
Soft mod? Is this kind of the joke?
image

SoftMinu made Kade Engine? Oh HELL no.
image
And also, what's VS Susie, VS Yari, and Angel Y Erick BTW?

**Comment by Swapper1** [comment]
Speaking of Android support...
https://github.com/NimuDevUwU/VsAngelYJoseus/commits/main

**Comment by BoloVEVO** [comment]
u k bud?
image

**Comment by Wither362** [comment]
Tú @NimuDevUwU! PARA DE HACER ESTO! NOS ESTÁS ENFADANDO A TODOS, TAMBIÉN ERES LLAMADO/A @juandavid45!! TU PARA YA DE HACER ESTO!! SI LO SIGES HACIENDO, TE JURO QUE ENCUENTRO LA FORMA DE BANEARTE

**Comment by Wither362** [comment]
@NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU @NimuDevUwU





FUCK YOU

**Comment by ManMaster707** [comment]
I hope you get banned, asshole.
 I had patience with you, but you act like a 3 year old: insistent, annoying, and gross.
(also, you're 14 AND have an emo profile? disgusting.)

**Review by ManMaster707 — COMMENTED** [review]
You tried to do this EVERYWHERE, now shut your mouth, and don't touch the internet EVER AGAIN.

**Comment by trayfellow** [comment]
hi guys
guyMunchingWatermelon

**Comment by BeastlyGhost** [comment]
> I hope you get banned forever, asshole. I had patience with you, but you act like a 3 year old: persistent, annoying, and gross. (also, you're 14 AND have an emo profile? disgusting.)

honestly at this point I bet 3y olds are that stupid

**Comment by ManMaster707** [comment]
> honestly at this point I bet 3y olds are that stupid

You made me realize that he/she's a 14 YEAR OLD DOING THESE THINGS, I'm 12 and I'm still more mature than him/her, goddamit

**Comment by Wither362** [comment]
> > honestly at this point I bet 3y olds are that stupid
> 
> You made me realize that he/she's a 14 YEAR OLD DOING THESE THINGS, I'm 12 and I'm still more mature than him/her, goddamit

Omg, you’re like @mr-fnf, it _was_ (I don’t know now) less that 13 years old, and github says that if you’re less than 13 years, you can’t use github, sorry @ManMaster707, but if what you have you said is correct, you’ll have to wait until you’re 13 years old or more

**Comment by kingyomoma** [comment]
> hi guys guyMunchingWatermelon [ ](https://user-images.githubusercontent.com/48515908/170260345-b6fb2772-2a92-45d3-b87e-f72d2c99243a.gif) guyMunchingWatermelon [ ](https://user-images.githubusercontent.com/48515908/170260345-b6fb2772-2a92-45d3-b87e-f72d2c99243a.gif)

yum

**Comment by Mastercopper2346** [comment]
...

**Comment by Mastercopper2346** [comment]
i come back online.

**Comment by Mastercopper2346** [comment]
AND SEE THIS?

**Comment by Mastercopper2346** [comment]
EVERYONE

**Comment by Mastercopper2346** [comment]
BEING TOXIC AND RUDE

**Comment by Mastercopper2346** [comment]
i am dissapointed

**Comment by Mastercopper2346** [comment]
this is LITTERALY HOW I WANT TO YELL AT YOU
https://www.youtube.com/watch?v=GKI_4zVTYuI

**Comment by CrusherMods** [comment]
> BEING TOXIC AND RUDE

this is mainly why
image

**Comment by Mastercopper2346** [comment]
So what?

**Comment by Mastercopper2346** [comment]
Does it look like i care about that?

**Comment by Mastercopper2346** [comment]
no

**Comment by Mastercopper2346** [comment]
im blocking everoyone that was toxic and mean

**Comment by BoloVEVO** [comment]
https://user-images.githubusercontent.com/88955176/172022708-562bdb72-6aa4-44d0-a644-aeb0e0eb0042.MOV

**Comment by kingyomoma** [comment]
> Upload.from.GitHub.for.iOS.MOV

fr

**Comment by CrusherMods** [comment]
> im blocking everoyone that was toxic and mean

bro the person who made this pr tried to add amoraltra to psych engine

**Comment by hayfii** [comment]
> guys could you just stop being some toxic mfs just because this guy made a pr instead of a fork for their mod

he was fucking changing the whole game dumbass mf

**Comment by hayfii** [comment]
> im blocking everoyone that was toxic and mean

"everoyone" 🤓 :

**Comment by hayfii** [comment]
> im blocking everoyone that was toxic and mean

i clearly think you're a lua user because YOU DON'T EVEN KNOW HOW THESE WORKS

**Comment by hayfii** [comment]
> im blocking everoyone that was toxic and mean

oh and lua users (aka. you) should not come into source code discussions because u might get confused by EVERYTHING

**Pull request closed without merging**
