### PR TITLE
stupid change no one needs but sprites with rgbpalette can now have color and colortransform

### PR DESCRIPTION
**Pull request by betpowo**
do not accept this

### CODE REVIEW

**Review by Blossomical — APPROVED** [review]
i have a farm and a cow named suzy

**Review by charlesisfeline — APPROVED** [review]

**Review by moxie-coder — APPROVED** [review]
I put the new forgis on the jeep

**Comment by Sword352** [comment]
a

**Comment by Sword352** [comment]
how can we review changes

**Review by Sword352 — COMMENTED** [review]
cool, dunno how to approve tho

**Comment by MemeHovy** [comment]
> cool, dunno how to approve tho

there’s an approve option when you review a PR @Sword352

**Review by Sword352 — APPROVED** [review]
smart

**Comment by Sword352** [comment]
> > cool, dunno how to approve tho
> 
> there’s an approve option when you review a PR @Sword352

thx

**Comment by MemeHovy** [comment]
> > > cool, dunno how to approve tho
> > 
> > 
> > there’s an approve option when you review a PR @Sword352
> 
> thx

yw, always glad to help

**Review by jimmyjamescool — APPROVED** [review]

**Comment by jimmyjamescool** [comment]
> Wait, i can make bf red?

You can make 7 bfs on screen in different colors while charting a YouTube kids video

**Review by libauror-a — APPROVED** [review]
[pretend that this is embedded into github because i cant really embed audio into github](https://cdn.discordapp.com/attachments/1083070583245373564/1122197020929687662/licorice.ogg)

**Pull request merged**
