### PR TITLE
Sustains now wont do anything if the note that start it was missed (See #2813)

### PR DESCRIPTION
**Pull request by tposejank**
https://user-images.githubusercontent.com/81495861/147592403-0e1ca0c6-5b16-4959-b157-0df0fac89c63.mp4

### CODE REVIEW

**Comment by kem0x** [comment]
the head should only be the miss and the sustain parts should do nothing instead counting as mass-misses

**Comment by Rudyrue** [comment]
> the head should only be the miss and the sustain parts should do nothing instead counting as mass-misses

the pr fixed that, the video's just outdated lol
https://github.com/ShadowMario/FNF-PsychEngine/issues/2813#issuecomment-1002215371

**Comment by ShadowMario** [comment]
I don't really want to change how sustains work.

**Comment by tposejank** [comment]
it wasnt meant for that but ok
it was just for the guy that was too cocky about haxeflixel

**Comment by tposejank** [comment]
twitter argument btw

**Comment by AdrianCD5** [comment]
I kind of feel like this is a mistake to not at least consider making changes to sustains from. Despite the way the issue came to light I still think sustains are indeed inherently broken and provide too many false misses while simultaneously cheating the system for health. Maybe this isn’t the exact fix you’re looking for in the long run but I’d recommend considering tweaking it some time.

**Comment by Mastercopper2346** [comment]
how to use (idk how pull requests work)

**Comment by Mastercopper2346** [comment]
nvm

**Comment by Mastercopper2346** [comment]
i rate this 39839483949348348938949822038023/10

**Review by DabbinDude316B — COMMENTED** [review]
should have been merged

**Pull request closed without merging**
