### PR TITLE
sustain splashes / alt+enter fix for accept and pause keybinds

### PR DESCRIPTION
**Pull request by PartnerCapPikachu**
yeah this is kinda dumb
uses a timer to determine when the splash gets destroyed but it works surprisingly well, though it isn't at all handled like in base game

### CODE REVIEW

**Review by Joalor64 — APPROVED** [review]

**Comment by Unholywanderer** [comment]
where is the hold splash preference!!!

**Comment by PartnerCapPikachu** [comment]
> where is the hold splash preference
wip but i might take this down

**Comment by Unholywanderer** [comment]
did not ask buddy... where is it!!!

**Comment by PartnerCapPikachu** [comment]
> did not ask buddy... where is it!!!

kms

**Comment by SMB-5** [comment]
oh shit did not see that my commit would come up

**Comment by SMB-5** [comment]
I hope you don't mind pumpsuki I can remove if requested

**Comment by SMB-5** [comment]
wait did it even show up? I don't get github sometimes

**Pull request closed without merging**
