### PR TITLE
stupidity

### PR DESCRIPTION
**Pull request by Luisinhi010**
when you Ctrl+Right click using VScode, you go to the code line.

### CODE REVIEW

**Comment by MemeHoovy** [comment]
okay, but what is this about?

**Comment by Luisinhi010** [comment]
> okay, but what is this about?

when it crashes, its prints where the code was loaded, with this you can just Ctrl+Right click on VScode's cmd to go to the line

**Review by MemeHoovy — APPROVED** [review]
well okay

**Comment by BeastlyGhost** [comment]
taking this

**Comment by Luisinhi010** [comment]
> taking this

go ahead

**Review by DabbinDude316B — APPROVED** [review]

**Review by CoolingTool — APPROVED** [review]
kek

**Pull request closed without merging**
