### PR TITLE
Note speed setting

### PR DESCRIPTION
**Pull request by Spel0**
Surely it would've been implemented by now, right? **Right??**

[Showcase](https://www.youtube.com/watch?v=ddzOCJbUEWA)

### CODE REVIEW

**Comment by Spel0** [comment]
just noticed something, one sec

**Comment by ShadowMario** [comment]
Once i finish some more mod support stuff i will implement a song setting menu on Freeplay

**Comment by Spel0** [comment]
> Once i finish some more mod support stuff i will implement a song setting menu on Freeplay

Song setting menu as in? I don't think I understood that correctly

**Comment by Spel0** [comment]
Anyway should be ready

[Here's showcase of new event](https://www.youtube.com/watch?v=MkwESmiToWE)

**Comment by ShadowMario** [comment]
A substate that opens when you press Start on Freeplay, with settings that would be saved and etc.
I still have to do mod support and redo the Options menu/Controls code before adding new big features.

**Comment by Spel0** [comment]
> I still have to do mod support and redo the Options menu/Controls code before adding new big features.

Alright i'll close this for now then, just don't forget to include this feature since I hate the fact that it isn't implemented yet

**Pull request closed without merging**
