### PR TITLE
Show/Hide Weeks temporally + Getting/Setting on Source Code

### PR DESCRIPTION
**Pull request by XtraXD1**
With this, you'll be able to control the visibility of the weeks, both in Lua and in Source Code.
The Lua function is:
```
toggleWeekVisibility(name:String, mode:String = '', state:Null<Bool> = null)
```
`name` refers to the week filename.
`mode` means `Story` or `Freeplay`. If not used or anything else is set as `mode`, then the change will affect both Story and Freeplay.
`state` means `true` (Shown) or `false` (Hidden). If `null`, or not used after all, the default value for the Week/Freeplay will be used. The default value means the `hideStoryMode` and `hideFreeplay` checks in the Week Editor.

And the way to use it on Source Code is:
The variable that defines the visibility of the Week is `FlxG.save.data.` + weekFilename + `StoryVisible`, the one for Freeplay is `FlxG.save.data.` + weekFilename + `FreeplayVisible`, and the last 2 variables for the hidden state are:
`FlxG.save.data.` + weekFilename + `StoryHidden` (For Story Mode)
`FlxG.save.data.` + weekFilename + `FreeplayHidden` (For Freeplay)
An example of use is:
```
if(SONG.songName == 'Dadbattle' && misses < 1) {
    FlxG.save.data.week2StoryVisible = true;
    FlxG.save.data.week2StoryHidden = false;
} else {
    FlxG.save.data.week2StoryVisible = false;
    FlxG.save.data.week2StoryHidden = false;
}
```

**=================================================================**

_(I also had to make this to make the week visibility toggling part)_
Also, this Pull Request includes the ability to get/set functions, just like in Lua, but in Source Code. The functions are:
```
CoolUtil.getProperty(variable:String)
CoolUtil.setProperty(variable:String, value:Dynamic)
CoolUtil.getProperty(classVar:String, variable:String)
CoolUtil.setProperty(classVar:String, variable:String, value:Dynamic)
```
As you (maybe) may see, that works like the Lua Getting/Setting functions do.
This is useful for, in case that you have a variable (Or part of it) on a String, and you wanna use the String as a variable name.
**Example:**
```
var weekName:String = 'week1';
CoolUtil.getPropertyFromClass('flixel.FlxG', 'save.data.' + weekName + 'StoryVisible');
```
Or where the `weekName` may vary:
```
var weekNames:Array<String> = [
'week1',
'week2',
'week3',
'gd1' //Week filename from my mod LMAO
];
var weekName:String = weekNames[Math.random(weekNames.length)]
CoolUtil.getPropertyFromClass('flixel.FlxG', 'save.data.' + weekName + 'StoryVisible');
```

**=============**

That's all, thanks for reading. :)

### CODE REVIEW

**Comment by XtraXD1** [comment]
(PD: Had to fix it many times before getting it to work properly, so there are the fixes. LMAO)

**Comment by PoleyMagik** [comment]
Idk if the code is good or not but i want this feature so yes please :)

**Comment by Gui-iago** [comment]
really hoping this gets merged!

**Comment by XtraXD1** [comment]
I also hope this to be merged. By the way, you may download the fules and merge them yourselves in your custom builds, if you want.

**Comment by FurryColtin** [comment]
i may as well download them and import the code myself (because well i have custom coded stages and stuff i dont wanna end up getting rid of!)

**Comment by FurryColtin** [comment]
> i may as well download them and import the code myself (because well i have custom coded stages and stuff i dont wanna end up getting rid of!)

also im in need of a right and left scroll code. if you can help with that ill be grateful but ima use this!

**Comment by XtraXD1** [comment]
Hello. I'm still new to GitHub, but how may I check these verifications? I did the workflow from my fork, but it's still unverified here.

**Comment by Gui-iago** [comment]
> Hello. I'm still new to GitHub, but how may I check these verifications? I did the workflow from my fork, but it's still unverified here.

click on the orange dot, then select "Details" for any of those checks, the checks will start automatically once you do that, just make sure to not close the tab or else they may fail or pause

**Review by Lila-Rogers — APPROVED** [review]
I approve

**Pull request closed without merging**
