### PR TITLE
Fix Hashlink compilation

### PR DESCRIPTION
**Pull request by libauror-a**
i hate cpp

issues that i have to fix:
- [x] crash on entering options menu (cast failure)

some stuff that i can't do yet:
- luajit
- hxcodec
- discord rpc
- memory counter in fps text (the hl gc stats don't work)

hopefully (best case scenario) ill make hl extensions for the missing libraries, but for now this works

### CODE REVIEW

**Comment by ThePlank** [comment]
hopefully i didn't break windows when making this

**Comment by BeastlyGabi** [comment]
you should mark this as a draft

**Review by charlesisfeline — APPROVED** [review]

**Comment by ThePlank** [comment]
> you should mark this as a draft

tbh the only reason i didn't mark this as a draft is because the fix was so easy i thaught that i shoudn't do that but then i got distracted and when i came back i was tired as hell
and today i forgot about this until now

**Comment by Raltyro** [comment]
if we were doing a hl compilation support for psych engine, we might have to use another fork of hxcodec, discordrpc, and linc_luajit that supports hashlink

**Comment by ThePlank** [comment]
Deciding to close this to port this to the dev branch

**Comment by ThePlank** [comment]
nvm i got distracted and im now doing shit for libvlc lua
discordrpc can be done with a websocket

**Pull request closed without merging**
