### PR TITLE
Cool Null Object Reference prevention

### PR DESCRIPTION
**Pull request by Grape-Boy**
Prevents crashes when the game tries to get a chart that doesn't exist, then displays an error message.
First serious PR so tell me if something's wrong and what to improve.

(for Story Menu, Freeplay and the Chart Editor)

### CODE REVIEW

**Review by TheKitBoi — APPROVED** [review]

**Review by Raltyro — APPROVED** [review]
looks cool
maybe make the warning screen as a class instead

**Comment by Grape-Boy** [comment]
> looks cool
> maybe make the warning screen as a class instead

I was considering doing that but I felt like a class was too much, I'll probably do it anyway

**Review by Gostar64 — APPROVED** [review]

**Comment by BeastlyGhost** [comment]
error code could be improved by just creating the variables you made on `MusicBeatState`, since p much all states extend it, they would be able to call that same function for error logs and such

great PR!

**Comment by Grape-Boy** [comment]
> error code could be improved by just creating the variables you made on `MusicBeatState`, since p much all states extend it, they would be able to call that same function for error logs and such
> 
> great PR!

thanks for the ideas, I'm going to push a new commit now

**Review by Raltyro — APPROVED** [review]
AAPPORECE APRROCE APPROVE

**Review by charlesisfeline — APPROVED** [review]

**Review by aaaproooo — APPROVED** [review]

**Pull request closed without merging**
