### PR TITLE
Flixel 5.0.0 and less fix

### PR DESCRIPTION
**Pull request by TheKitBoi**
There was multiple issues on why that happened.

### CODE REVIEW

**Review by UmbratheUmbreon — APPROVED** [review]

**Review by EyeDaleHim — CHANGES_REQUESTED** [review]
The other `#flixel < 5.0.0` checks are unnecessary, you only need to apply that for the `zoom` constructor in `new FlxGame()`.

NOT NEEDED:
```haxe
	#if (flixel < "5.0.0")
	var zoom:Float = -1; // If -1, zoom is automatically calculated to fit the window dimensions.
	#end
```
```haxe
		#if (flixel < "5.0.0")
		if (zoom == -1)
		{
			var ratioX:Float = stageWidth / gameWidth;
			var ratioY:Float = stageHeight / gameHeight;
			zoom = Math.min(ratioX, ratioY);
			gameWidth = Math.ceil(stageWidth / zoom);
			gameHeight = Math.ceil(stageHeight / zoom);
		}

		#end
```

**Comment by EyeDaleHim** [comment]
This is a duplicate of another pull request, so there is no need for this.

[#11294](https://github.com/ShadowMario/FNF-PsychEngine/pull/11294)

**Comment by TheKitBoi** [comment]
> This is a duplicate of another pull request, so there is no need for this.
> 
> [#11294](https://github.com/ShadowMario/FNF-PsychEngine/pull/11294)

ill close this just in case [Heropowerbrine](https://github.com/Heropowerbrine) doesn't do that in 10 days

**Comment by Heropowerbrine** [comment]
> > This is a duplicate of another pull request, so there is no need for this.
> > [#11294](https://github.com/ShadowMario/FNF-PsychEngine/pull/11294)
> 
> ill close this just in case [Heropowerbrine](https://github.com/Heropowerbrine) doesn't do that in 10 days

I'll close mine, yours can work with older flixel versions after all

**Review by Heropowerbrine — APPROVED** [review]

**Comment by TheKitBoi** [comment]
Closed for https://github.com/ShadowMario/FNF-PsychEngine/pull/11388

**Pull request closed without merging**
