### PR TITLE
Friday Night Funkin' Secret Historys Plus

### PR DESCRIPTION
**Pull request by Krisu103**

### CODE REVIEW

**Review by ManMaster707 — COMMENTED** [review]
uh... what?

**Comment by voxovistired** [comment]
I'm sorry w-

**Review by CrusherNotDrip — COMMENTED** [review]
????????????????????????????????????

**Comment by megasssdev** [comment]
fatherless act

**Comment by SonicProYT** [comment]
oh my god another child like that kid who put their own credits to psych

**Comment by SonicProYT** [comment]
except this time they put “title”

**Comment by Helisonbr** [comment]
Orphan be like:

**Comment by DEMOLITIONDON96** [comment]
i swear to god, at this point, the PRs are gonna get closed too if this keeps happening

**Comment by PrismLight** [comment]
OMG SUCH A COOL PR SHADOWMARIO PLZ ADD THIS

**Review by Jaduplex — CHANGES_REQUESTED** [review]
no

**Review by DaveFan19 — APPROVED** [review]
commit pl spl spl spl

**Comment by megasssdev** [comment]
> commit pl spl spl spl

ni

**Pull request closed without merging**
