### PR TITLE
Awards Menu

### PR DESCRIPTION
**Pull request by pradolionel**
The Buttons Archivementsstate

### CODE REVIEW

**Comment by system32unknown** [comment]
Why android

**Comment by Luisinhi010** [comment]
wtf?

**Comment by TheKitBoi** [comment]
> The Buttons Archivementsstate

ew + what are you doing with ur life

**Comment by ShadowMilky** [comment]
> The Buttons Archivementsstate


https://user-images.githubusercontent.com/62410083/216781137-cd464dee-591a-4fbb-8018-ff684e7c899d.mp4

**Comment by ShadowMilky** [comment]
psych forks involving android code shouldnt exist

**Comment by MemeHovy** [comment]
> psych forks involving android code shouldnt exist

agreed

**Comment by KookerFoxYT** [comment]
this shit still isnt even closed .__.

**Comment by KookerFoxYT** [comment]
maybe because shadow didnt even notice this

**Comment by Rom4chek** [comment]
Bruh, mario pls close this shit

**Pull request closed without merging**
