### PR TITLE
Custom NoteSplash Opacity through Options and other minor adjustments

### PR DESCRIPTION
**Pull request by crowplexus**

### CODE REVIEW

**Review by MemeHoovy — APPROVED** [review]

**Review by TheKitBoi — APPROVED** [review]

**Review by DM-kun — APPROVED** [review]

**Review by BeepSheep254 — APPROVED** [review]

**Review by stilic — APPROVED** [review]

**Review by Raltyro — APPROVED** [review]

**Comment by antoSKRLOL** [comment]
cool

**Review by charlesisfeline — APPROVED** [review]

**Review by Dorentix — APPROVED** [review]

**Review by Intancote — APPROVED** [review]

**Review by br4dnblehh — APPROVED** [review]
👍Good job

**Comment by BeastlyGhost** [comment]
gonna be using this to also fix some mistakes I did with previous PRs

**Review by rodney528 — APPROVED** [review]

**Review by rodney528 — APPROVED** [review]

**Review by Grape-Boy — APPROVED** [review]

**Review by rodney528 — APPROVED** [review]
:D

**Review by rodney528 — APPROVED** [review]

**Pull request closed without merging**
