### PR TITLE
I'm so sorry, but before you block me, just hear me out, just this once

### PR DESCRIPTION
**Pull request by Isaiah-Freeman**
Please man, I know you have a heart in there, I'm so very sorry. 😭
I know this seems hypocritical, but please, just hear me out.
I just want to make amends.😥

### CODE REVIEW

**Comment by Axmed119** [comment]
bruh stfu

**Comment by TheKitBoi** [comment]
> Please man, I know you have a heart in there, I'm so very sorry. 😭
> I know this seems hypocritical, but please, just hear me out.
> I just want to make amends.😥

r/ishitmyself

**Comment by Isaiah-Freeman** [comment]
I just wanted to apologize to you people...

**Comment by TheKitBoi** [comment]
For what drama

**Comment by Isaiah-Freeman** [comment]
for what happened with that PR from before

**Comment by kingyomoma** [comment]
bro is related to morgan freeman??????

**Comment by Isaiah-Freeman** [comment]
no, that's my real name

**Comment by Fuckyoumemehoovy** [comment]
Shut.
The.
Fuck.
Up.

**Comment by Isaiah-Freeman** [comment]
why? I just wanted to make amends, and apologize...

**Comment by Fuckyoumemehoovy** [comment]
> why? I just wanted to make amends, and apologize...

Stop guilt tripping you know what you did memehoovy.

**Comment by Isaiah-Freeman** [comment]
I know what I did, and I'm very sorry.

**Comment by Isaiah-Freeman** [comment]
I promise I won't ever do it again.

**Comment by BlueColorsin** [comment]
**Buh?!**

**Comment by Isaiah-Freeman** [comment]
> **Buh?!**

I just wanted to say sorry, and I promise I won't ever post NSFW on here ever again.

**Comment by kingyomoma** [comment]
guh

**Comment by Isaiah-Freeman** [comment]
Please..will you people ever give me a second chance?

**Comment by BlueColorsin** [comment]
kingyourmama didn't cherry say to just leave him alone cause he is just craving attention

**Comment by Isaiah-Freeman** [comment]
No, no I'm not, I'm just apologizing to you people.

**Comment by kingyomoma** [comment]
> kingyourmama didn't cherry say to just leave him alone cause he is just craving attention

I didn't see that
also kingyomoma*

**Comment by Fuckyoumemehoovy** [comment]
https://user-images.githubusercontent.com/117598971/200192030-eedd3c63-a4d0-477f-aad6-1094912685fc.mp4

**Comment by BlueColorsin** [comment]
> No, no I'm not, I'm just apologizing to you people.

who says I am gonna do the same 💀

**Comment by Isaiah-Freeman** [comment]
Please, I genuinely am sorry, I just want to make up for what I've done.

**Comment by CaptainBaldi** [comment]
sorry but who are you?

**Comment by Fuckyoumemehoovy** [comment]
You literally posted scat porn, how can we forgive you when you probably traumatized one or two people.

**Comment by Isaiah-Freeman** [comment]
I'm memehoovy, this is my real name.

**Comment by Fuckyoumemehoovy** [comment]
> sorry but who are you?

Pretty sure it’s memehoovy

**Comment by Isaiah-Freeman** [comment]
> You literally posted scat porn, how can we forgive you when you probably traumatized one or two people.

I know, I really didn't mean to do that, and I regret doing it.

**Comment by Isaiah-Freeman** [comment]
> > sorry but who are you?
> 
> Pretty sure it’s memehoovy

Yeah, it is.

**Comment by Fuckyoumemehoovy** [comment]
https://user-images.githubusercontent.com/117598971/200192137-a76b9642-c7fb-477f-9eda-7ff533691f16.mp4

**Comment by Isaiah-Freeman** [comment]
I just really hope you people can find forgiveness in what I've done.

**Comment by CaptainBaldi** [comment]
> > sorry but who are you?
> 
> Pretty sure it’s memehoovy

k thanks

**Comment by CaptainBaldi** [comment]
> > You literally posted scat porn, how can we forgive you when you probably traumatized one or two people.
> 
> I know, I really didn't mean to do that, and I regret doing it.

ye that was 
really fucked up
where did that even come from

**Comment by Fuckyoumemehoovy** [comment]
> > > You literally posted scat porn, how can we forgive you when you probably traumatized one or two people.
> > 
> > 
> > I know, I really didn't mean to do that, and I regret doing it.
> 
> ye that was really fucked up where did that even come from

Twitter or rule34.com

**Comment by LEVIXDDLMAO** [comment]
dude, i have no rights to say anything, im not gonna be on anyone side. at this point he fucked up, and he said hes sorry, it dosent matter if you forgive him or not, he shouldn't have done that, even if he snapped or whatever. it would have been better if people didnt troll. but i get that someone was trolling but you didnt have to go that far.

**Comment by Isaiah-Freeman** [comment]
I'd rather not say, but look, I truly, _am_ sorry, I just wanted to make amends for the people I've traumatized, and just hope you all can forgive me.

**Comment by Fuckyoumemehoovy** [comment]
https://user-images.githubusercontent.com/117598971/200192357-83bfc81f-adc0-43f2-8664-879746a27314.mov

**Comment by Isaiah-Freeman** [comment]
Please, just give me a second chance. I'm very sorry.

**Comment by Fuckyoumemehoovy** [comment]
We ain’t gonna accept your jakepaul'ish apology bitch, make an actual one rathe4 than “waaaa I’m sorry” + there was a minor in there bitch

**Comment by LEVIXDDLMAO** [comment]
a minor? Really dude...

**Comment by Isaiah-Freeman** [comment]
Alright, I understand there was minors I've possibly traumatized, but I never meant to do that, I didn't want to do any of this.
I don't know what happened but something snapped in me, and I went berserk, I promise on my life, that I will never do any of those nasty things ever again. If there's hope for anything, there's hope for a second chance, look into your hearts, and just please say, that you can give me a second chance.

**Comment by Fuckyoumemehoovy** [comment]
Your acting like an undertale protagonist holy shit

**Comment by Isaiah-Freeman** [comment]
You know, you acting toxic like that is just not gonna get you anywhere in life, you should really get some anger management, and maybe start being nicer to other people. Toxicity is not the key to life.

**Comment by Fuckyoumemehoovy** [comment]
> You know, you acting toxic like that is just not gonna get you anywhere in life, you should really get some anger management, and maybe start being nicer to other people. Toxicity is not the key to life.

You literally posted scat porn bruh how is anybody gonna be nice to you after that 💀

**Comment by Isaiah-Freeman** [comment]
I know, but I wanted to remove those images, and I want to say sorry for what I've done.

**Comment by Fuckyoumemehoovy** [comment]
> I know, but I wanted to remove those images, and I want to say sorry for what I've done.

Even if your got a second chance, pretty sure in 5 - 6 months you would blow it

**Comment by Isaiah-Freeman** [comment]
I promise on my life, I won't ever post NSFW ever again on this site, believe me, I won't, I'll change myself for the better.

**Comment by EyeDaleHim** [comment]
Just because you did something wrong does not mean you are going to be forgiven instantly.

Grow up, don't always expect things in your way, move on.

**Comment by Fuckyoumemehoovy** [comment]
> I promise on my life, I won't ever post NSFW ever again on this site, believe me, I won't, I'll change myself for the better.

That… still doesn’t change the fact you traumatized people.
1930659B-489E-4317-8489-DC825F2C8CCF

**Comment by Isaiah-Freeman** [comment]
> Just because you did something wrong does not mean you are going to be forgiven instantly.
> 
> Grow up, don't always expect things in your way, move on.

I know that, but I hope with time, you people can eventually forgive me.

**Comment by Fuckyoumemehoovy** [comment]
> > Just because you did something wrong does not mean you are going to be forgiven instantly.
> > Grow up, don't always expect things in your way, move on.
> 
> I know that, but I hope with time, you people can eventually forgive me.

Please pretty please stay the fuck out of this repo

**Comment by Isaiah-Freeman** [comment]
I just wanted to make amends to you people, why can't you understand that?

**Comment by Isaiah-Freeman** [comment]
But instead, all I get is rudeness & backlash.

**Comment by Fuckyoumemehoovy** [comment]
> I just wanted to make amends to you people, why can't you understand that?

Because you can’t be apologized instantly bitch

**Comment by EyeDaleHim** [comment]
> I just wanted to make amends to you people, why can't you understand that?

Being forgiven will not fix your mistake, I get that, but it's better to move on instead of clinging to something that will waste your time.

I'm not saying this because I hate you, but I'm trying to help you be a better person.

**Review by Fuckyoumemehoovy — CHANGES_REQUESTED** [review]
May you please close this

**Comment by Isaiah-Freeman** [comment]
> > I just wanted to make amends to you people, why can't you understand that?
> 
> Being forgiven will not fix your mistake, I get that, but it's better to move on instead of clinging to something that will waste your time.
> 
> I'm not saying this because I hate you, but I'm trying to help you be a better person.

...I don't know what to do, I'm just going to leave this PR here in hopes that people can understand that I want to change for the better, and that people understand that I'm very sorry.

**Comment by TheKitBoi** [comment]
That’s just lazy and spreading awareness

**Comment by Isaiah-Freeman** [comment]
Exactly, I just want to spread awareness to people that I'm sorry & hope they can forgive me for my bad decisions.

**Comment by Fuckyoumemehoovy** [comment]
> That’s just lazy and spreading awareness

Bananan sonck

**Comment by tposejank** [comment]
this shit like the Lovealtra drama guh

**Comment by Fuckyoumemehoovy** [comment]
> this shit like the Lovealtra drama guh

“Be gay do crimes” taken to another level 🗿

**Comment by lemz1** [comment]
i love playing with balls

**Pull request closed without merging**
