### PR TITLE
Removal of mac actions builds

### PR DESCRIPTION
**Pull request by ghost**
They work on random it just isnt a good idea to keep it

### CODE REVIEW

**Comment by MayoALT** [comment]
this just sucks whats the point

**Comment by MayoALT** [comment]
out of the last 35 commits, only 2 of them failed and both of them failed on installing haxelib

**Comment by tposejank** [comment]
> out of the last 35 commits, only 2 of them failed and both of them failed on installing haxelib

haxe servers issue

**Comment by tposejank** [comment]
> They work on random it just isnt a good idea to keep it

you cancelled the entire mac community bruh

**Comment by DudeItsJonnycat** [comment]
> > They work on random it just isnt a good idea to keep it
> 
> you cancelled the entire mac community bruh

bro i work on a mac lol

**Comment by Doritojoey** [comment]
> > out of the last 35 commits, only 2 of them failed and both of them failed on installing haxelib
> 
> haxe servers issue

the other 2 platforms worked, its a mac issue

**Comment by Doritojoey** [comment]
> MayoALT

it wasn't a haxe server issue + tons of PRs are failing randomly
overall like it just takes effort to support Mac compared to windows or linux especially when it works literally at random, either passes or fails because of libraries

**Comment by mayo78** [comment]
> > MayoALT
> 
> it wasn't a haxe server issue + tons of PRs are failing randomly overall like it just takes effort to support Mac compared to windows or linux especially when it works literally at random, either passes or fails because of gay github vms

you used gay as an insult opinion discarded
bambi-bambi-body

**Comment by trayfellow** [comment]
this pr is pointless

**Comment by Doritojoey** [comment]
> > > MayoALT
> > 
> > 
> > it wasn't a haxe server issue + tons of PRs are failing randomly overall like it just takes effort to support Mac compared to windows or linux especially when it works literally at random, either passes or fails because of gay github vms
> 
> you used gay as an insult opinion discarded bambi-bambi-body

you're a fan of dave and bambi opinion intolerable
also its not an insult where'd you get that from

**Comment by lemz1** [comment]
> you're a fan of dave and bambi opinion intolerable also its not an insult where'd you get that from

You said


> > MayoALT
> 
> it wasn't a haxe server issue + tons of PRs are failing randomly overall like it just takes effort to support Mac compared to windows or linux especially when it works literally at random, either passes or fails because of gay github vms

If you didn't use gay as an insult then why did you use it. It seemed like you used gay as a negative trait.

**Comment by Doritojoey** [comment]
Yeah i did i was joking. Github vms work at random and especially with mac.

**Comment by fireredfan7** [comment]
@Doritojoey BOOOOOOOOOOOOOOO!!!

**Comment by Doritojoey** [comment]
Bruh its just extra weight to carry for no reason. Psych barely supports mac already lol

**Pull request closed without merging**
