### PR TITLE
Stop overriding flixel, openfl and lime classes

### PR DESCRIPTION
**Pull request by crowplexus**
Solves https://github.com/ShadowMario/FNF-PsychEngine/issues/13590

The overrides are no longer necessary due to the fact the features said overrides were trying to implement and/or fix are already implemented in base flixel

this change *will* require you to use the latest versions of flixel and flixel-addons

since we are already enforcing newer versions of flixel with this, I recommend merging these too https://github.com/ShadowMario/FNF-PsychEngine/pull/13433 and https://github.com/ShadowMario/FNF-PsychEngine/pull/13572

### CODE REVIEW

**Comment by Unholywanderer** [comment]
shit!! grenade!! throw it back private!

**Review by DetectiveBaldi — CHANGES_REQUESTED** [review]
If this enforces use of latest libraries, shouldn't this pull request also fix that issue with camera speed on latest Flixel?

**Comment by BlueColorsin** [comment]
All checks have failed...

**Review by BlueColorsin — APPROVED** [review]

**Comment by crowplexus** [comment]
> If this enforces use of latest libraries, shouldn't this pull request also fix that issue with camera speed on latest Flixel?

yes and in fact I'm gonna edit the original post to include links to those prs too

**Review by DetectiveBaldi — APPROVED** [review]
all good

**Review by libauror-a — APPROVED** [review]
chat is this true or gay porn

**Review by NexIsDumb — APPROVED** [review]
finally

**Comment by Geokureli** [comment]
is this PR dependent on #13572 for CI to work?

**Comment by NexIsDumb** [comment]
> is this PR dependent on #13572 for CI to work?
> 
> > chat is this true or gay porn
> 
> so far, just the first, but the night is young

oh yeah actually now i should delete the custom flxanimate download

**Comment by crowplexus** [comment]
> is this PR dependent on #13572 for CI to work?
> 
> > chat is this true or gay porn
> 
> so far, just the first, but the night is young

yeah, #13572 is required for CI to get back to work!

**Review by EyeDaleHim — APPROVED** [review]

**Review by richTrash21 — APPROVED** [review]
based🔥

**Review by melodiekit — APPROVED** [review]
pretty cool

**Review by ghost — COMMENTED** [review]
let's fucking go

**Review by ghost — APPROVED** [review]

**Comment by CaptainBaldi** [comment]
@crowplexus I'm not sure if this is something that needs to be addressed in this pr but deleting the overridden `FlxAnimationController` seems to cause some animation adding errors with notes and note splashes when in debug
the error in note can be solved by removing like one line but im unsure about the notesplashes

**Comment by crowplexus** [comment]
> @crowplexus I'm not sure if this is something that needs to be addressed in this pr but deleting the overridden `FlxAnimationController` seems to cause some animation adding errors with notes and note splashes when in debug the error in note can be solved by removing like one line but im unsure about the notesplashes

image
made a custom animation controller to mitigate the issue which should be pushed into the fork once I'm done testing

**Comment by crowplexus** [comment]
I'm hoping this mitigates the issues but I still need someone to test it

**Comment by crowplexus** [comment]
> @crowplexus I'm not sure if this is something that needs to be addressed in this pr but deleting the overridden `FlxAnimationController` seems to cause some animation adding errors with notes and note splashes when in debug the error in note can be solved by removing like one line but im unsure about the notesplashes

those seem to be just warnings, they didn't affect anything and animations are working fine

which i guess if you are working with debug you should expect some to pop from time to time.

**Comment by LeonGamerPS4** [comment]
i tried compiling myself and uhh
```
------------------------SScript 7.0.0 Macro------------------------
Special Thanks:
- CrowPlexus

Checking version...
You are using the 4.2.5 version of Haxe, SScript works best with Haxe 4.3.2. Consider updating Haxe.
Continuing...
-------------------------------------------------------------------

C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
source/states/PlayState.hx:37: characters 8-46 : Type not found : flixel.addons.display.FlxRuntimeShader
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
source/psychlua/FunkinLua.hx:15: characters 8-46 : Type not found : flixel.addons.display.FlxRuntimeShader
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
source/states/PlayState.hx:129: characters 40-48 : Type not found : FlxSound
```

**Comment by CaptainBaldi** [comment]
> > @crowplexus I'm not sure if this is something that needs to be addressed in this pr but deleting the overridden `FlxAnimationController` seems to cause some animation adding errors with notes and note splashes when in debug the error in note can be solved by removing like one line but im unsure about the notesplashes
> 
> those seem to be just warnings, they didn't affect anything and animations are working fine
> 
> which i guess if you are working with debug you should expect some to pop from time to time.

honestly, yeah fair enough, i just figured it was something worth mentioning
i probably also should have specified they were just warnings lol!

**Comment by EyeDaleHim** [comment]
> i tried compiling myself and uhh
> 
> ```
> ------------------------SScript 7.0.0 Macro------------------------
> Special Thanks:
> - CrowPlexus
> 
> Checking version...
> You are using the 4.2.5 version of Haxe, SScript works best with Haxe 4.3.2. Consider updating Haxe.
> Continuing...
> -------------------------------------------------------------------
> 
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> source/states/PlayState.hx:37: characters 8-46 : Type not found : flixel.addons.display.FlxRuntimeShader
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> source/psychlua/FunkinLua.hx:15: characters 8-46 : Type not found : flixel.addons.display.FlxRuntimeShader
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> C:\Users\marte\OneDrive\Desktop\source stuff\FNF\FNF-Redux\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
> source/states/PlayState.hx:129: characters 40-48 : Type not found : FlxSound
> ```

update to latest flixel and flixel-addons versions, it was stated at the initial comment of this PR

**Comment by LeonGamerPS4** [comment]
i tried playing a song
```
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 318)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 110)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 90)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 117)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 90)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 57)
objects/Character.hx (line 118)
states/PlayState.hx (line 471)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Invalid char 93 at position 148
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

**Comment by LeonGamerPS4** [comment]
and its like this with every song

**Comment by LeonGamerPS4** [comment]
nvm it's a mistake on my end

**Review by system32unknown — APPROVED** [review]

**Review by Eric-R-Malice — APPROVED** [review]

**Review by Eric-R-Malice — APPROVED** [review]
i am deadass just waiting on this to be pulled before i try to port my mod to latest

**Comment by Eric-R-Malice** [comment]
idk how to delete my first approve that i didnt add a comment to uhhhhh

**Review by Vortex2Oblivion — APPROVED** [review]

**Review by Sword352 — APPROVED** [review]

**Review by hyperkitty99 — APPROVED** [review]

**Comment by crowplexus** [comment]
no more pain !

**Pull request merged**
