### PR TITLE
Added Note Tick settings and Note Speed customization outside of char…

### PR DESCRIPTION
**Pull request by MeowcaTheoRange**
…ting.

Note Tick (seen in ZFans prototype vDOING.YOUR.MOM)
Note Speed in Settings (seen in Kade Engine)

Changed files:
source/ClientPrefs.hx
source/OptionsState.hx
source/PlayState.hx

Required dependencies:
assets/shared/sounds/ChartingTick.mp3
assets/shared/sounds/ChartingTick.ogg
source/ClientPrefs.hx
source/PlayState.hx
source/Paths.hx
..flixel.FlxG

### CODE REVIEW

**Comment by nintendofan44** [comment]
this broke the sustain notes
fix your stuff please

**Comment by MeowcaTheoRange** [comment]
It didn't for me. I'll test again

**Comment by MeowcaTheoRange** [comment]
Turns out it does, so I'll divide the modifier by 2 instead of inputting the raw float.

**Comment by MeowcaTheoRange** [comment]
Fixed alternatively by simply overriding Song.hx's check for the JSON's speed.

**Comment by MeowcaTheoRange** [comment]
Closing because I have a long weekend and I think I'm gonna take that weekend to fix the setting shit ShadowMario is loathing Lol

**Comment by MeowcaTheoRange** [comment]
i was gonna do some shit but decided against it lol

**Comment by ShadowMario** [comment]
Duplicate of https://github.com/ShadowMario/FNF-PsychEngine/pull/26

**Pull request closed without merging**
