### PR TITLE
Help so bf doesn't get blocked by ratings

### PR DESCRIPTION
**Pull request by DabbinDude316B**

### CODE REVIEW

**Review by system32unknown — APPROVED** [review]

**Comment by MemeHoovy** [comment]
no

**Review by iym1337 — COMMENTED** [review]
close this

**Comment by Parsellol** [comment]
💀

**Review by voxovistired — COMMENTED** [review]
This definitely does serve its purpose. But I don’t see how this is necessary in the slightest? If you’re so worried about this just make the changes to your own code. Even then you can’t see your rating or combo which kind of just makes no sense to me?

**Review by BeepSheep254 — COMMENTED** [review]
I'm gonna wait for shadow mario to close this because this isn't necessary

**Comment by Mastercopper2346** [comment]
Whatever

**Pull request closed without merging**
