### PR TITLE
using lua functions without onCreate callback

### PR DESCRIPTION
**Pull request by TheLeerName**
lua: 📈

for example, u can use this line as .lua file, and it will work:
```lua
setProperty('skipArrowStartTween', true)
```

all pr just about do callbacks BEFORE loading lua file (game doing it AFTER)

### CODE REVIEW

**Review by moxie-coder — APPROVED** [review]
hmm, this seems nice

**Review by MemeFlavor — APPROVED** [review]
hell yeah

**Comment by CaptainBaldi** [comment]
what exactly does this do? im kinda confused

**Comment by TheLeerName** [comment]
> what exactly does this do? im kinda confused

earlier u can use script only like this:
```lua
function onCreate()
    setProperty('skipArrowStartTween', true)
end
```

now u can use this script too:
```lua
setProperty('skipArrowStartTween', true)
```

**Comment by doom699** [comment]
loving this

**Pull request merged**
