### PR TITLE
Adding drag and drop for character editor

### LINKED ISSUE #3053: Using mouse on offset editor
### What feature do you want to get added on the **base** engine?

Being able to do drag n drop shit on the character editor as an alternative to using arrow keys. I think kade has this but I dunno

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

### PR DESCRIPTION
**Pull request by blueDev2**
Since FlxG.mouse.overlap() does not take into consideration of offsets, it could not be used to make drag and drop only occur when you click on the character. 
So Instead, drag and drop occurs at all times when you click on anything and move the mouse, except when the mouse is over a UI box. This is to prevent accidental drag and drop when clicking on a drop-down menu. 
resolves #3053

### CODE REVIEW

**Review by Starmapo — APPROVED** [review]

**Comment by cherryiguess** [comment]
so you can move the camera position and character offsets (or placement) with your mouse? feels more convenient and useful then clicking the same button over and over until its good

**Comment by blueDev2** [comment]
I think there is a bit of confusion.
This changes the position of an animation, not the entire character.
The latter is possible, but not with the current setup.

**Review by HiroMizuki — APPROVED** [review]

**Comment by ImaginationSuperHero528** [comment]
> I think there is a bit of confusion. This changes the position of an animation, not the entire character. This is an alternative to the shift and arrows. The latter is possible, but not with the current setup.

For entire character it could just be hold shift

**Comment by blueDev2** [comment]
Advise was taken and implemented.
Though I would have liked to add text about it, but there isn't much space

**Comment by Lsoissus** [comment]
woo, this is pretty cool, i will add it to my version of psych engine made in source code [ill give credit]

**Comment by blueDev2** [comment]
I'm glad somebody has found use in this. I'm not sure if ShadowMario has even noticed this pull request yet, but I think it's at least ok since a lot of other requests have been closed by him.

**Pull request closed without merging**
