### PR TITLE
fix compiling

### PR DESCRIPTION
**Pull request by TehPuertoRicanSpartan**
i just found out about why the actions fail at compiling. i think the latest haxe builds fuck up lime and playstate, so i changed that to the latest _stable_ haxe version, which is 4.3.4.

also changed macos version bcz "arm64 not supported" my ass

### CODE REVIEW

**Review by crowplexus — APPROVED** [review]
image
MidOS L

**Comment by TehPuertoRicanSpartan** [comment]
yeah...

**Comment by TehPuertoRicanSpartan** [comment]
well, i've done all i can do
image_2024-05-29_224129075

**Comment by crowplexus** [comment]
probably change the OS version to 12

**Comment by TehPuertoRicanSpartan** [comment]
oh, thx for telling me

**Review by Fletchunter — APPROVED** [review]

**Review by ACoolioDude — APPROVED** [review]

**Comment by Stefan2008Git** [comment]
Ain't no way it's merged @TehPuertoRicanSpartan

**Pull request merged**
