### PR TITLE
Draggable Camera with Mouse

### PR DESCRIPTION
**Pull request by EyeDaleHim**
Allows you to drag the camera with a mouse rather than a keyboard

https://user-images.githubusercontent.com/71162374/172039725-ef808d28-b492-475a-bf4b-bc218accb124.mp4

### CODE REVIEW

**Review by Raltyro — APPROVED** [review]

**Review by Raltyro — CHANGES_REQUESTED** [review]
Maybe also make it so when a user scroll its mouse, it changes the camera zoom

**Comment by EyeDaleHim** [comment]
it's meant to be "press shift + R to reset camera position"
my bad lol

**Comment by ProgramerGamerZone** [comment]
Ok I know this is completely unrelated but I like the bf skin

**Review by GamerZoneMusic — APPROVED** [review]
also forgot to approve

**Review by stilic — APPROVED** [review]

**Review by TheKitBoi — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by raf13lol — CHANGES_REQUESTED** [review]
I really like this, just maybe make the mouse-less controls an option as well?

**Comment by EyeDaleHim** [comment]
> I really like this, just maybe make the mouse-less controls an option as well?

Don't think that's needed since using a mouse is comfortable, plus everyone uses it 99% of the time when working with stuff usually in this environment.

**Comment by Joalor64GH** [comment]
funkin' approved

**Review by Joalor64 — APPROVED** [review]

**Review by SwickTheGreat — APPROVED** [review]

**Review by Blossomical — APPROVED** [review]

**Review by TheKitBoi — APPROVED** [review]

**Review by MemeFlavor — APPROVED** [review]

**Review by charlesisfeline — APPROVED** [review]

**Review by Raltyro — APPROVED** [review]

**Review by MemeHoovy — APPROVED** [review]

**Comment by StefanBETA2008** [comment]
I Just Accept This Idea. It's Great

**Pull request closed without merging**
