### PR TITLE
Add a "beats until bopping" tag in Character Editor

### PR DESCRIPTION
**Pull request by Djotta11**
Make it so that we can set the bopping pause to a certain number of beats, so it doesn't get too fast or too slow

### CODE REVIEW

**Comment by MemeHovy** [comment]
> Make it so that we can set the bopping pause to a certain number of beats, so it doesn't get too fast or too slow

you set to merge the wrong branch you dumbass

**Comment by NexIsDumb** [comment]
You should close this PR and open a new one for this feature you would like to add since you kinda messed up in this PR by adding the main commits lmfao

**Comment by KookerFoxYT** [comment]
> Make it so that we can set the bopping pause to a certain number of beats, so it doesn't get too fast or too slow

where is your damn fork

**Comment by NexIsDumb** [comment]
man💀

**Comment by NexIsDumb** [comment]
God finally

**Comment by MemeHovy** [comment]
> God finally

yeah, took some time

**Pull request closed without merging**
