### PR TITLE
Per Character Game Over Properties

### PR DESCRIPTION
**Pull request by crowplexus**
this PR adds new parameters for Psych Characters, allowing users to set their own custom game over properties from the Character Editor

image

### CODE REVIEW

**Review by DetectiveBaldi — APPROVED** [review]

**Review by MemeHoovy — APPROVED** [review]

**Comment by antoSKRLOL** [comment]
AMAZING!!!


I can add it to psych engine plus (I'll give you credits when the mod comes out)

**Review by Luisinhi010 — APPROVED** [review]

**Review by DM-kun — APPROVED** [review]

**Review by TheKitBoi — APPROVED** [review]

**Review by aaaproooo — APPROVED** [review]

**Review by Parsellol — APPROVED** [review]
awesome

**Review by Raltyro — APPROVED** [review]

**Review by Raltyro — APPROVED** [review]

**Review by Intancote — APPROVED** [review]

**Review by MaybeMaru — APPROVED** [review]
noice

**Review by DaRealDotZ — APPROVED** [review]
ZAMN

**Review by CoolingTool — APPROVED** [review]
shouldve always been like this

**Review by charlesisfeline — APPROVED** [review]

**Review by Luisinhi010 — APPROVED** [review]

**Review by moxie-coder — APPROVED** [review]

**Comment by Luisinhi010** [comment]
Hello there MemeHoovy

**Comment by MemeHovy** [comment]
> Hello there MemeHoovy

hi Luis

**Review by DM-kun — APPROVED** [review]

**Pull request closed without merging**
