### PR TITLE
add euler and gamma in CoolUtil.hx and in Lua

### PR DESCRIPTION
**Pull request by nahiassis**

### CODE REVIEW

**Comment by GrexpungedYT** [comment]
what

**Comment by nintendofan44** [comment]
its a crazy ass long float just like PI

**Comment by Joalor64GH** [comment]
looks fine to me, i just want to know what it does

**Comment by Stilic** [comment]
no cuz very useless
also you can just create variables in lua for these constants bruh

**Comment by Joalor64GH** [comment]
oh

**Review by rodney528 — COMMENTED** [review]
Uhm... lua exists.

**Comment by ShadowMario** [comment]
You didn't explain what it does.

**Comment by ShadowMilky** [comment]
> You didn't explain what it does.

"its a crazy long decimal number just like PI"

**Pull request closed without merging**
