### PR TITLE
Dark mode option

### PR DESCRIPTION
**Pull request by Joalor64**
Idea by @Lokitot

### CODE REVIEW

**Comment by CaptainBaldi** [comment]
I can't even begin to state how useless this is

**Comment by BeastlyGhost** [comment]
image
bro doesn't know what a ternary operator is

**Comment by Joalor64GH** [comment]
i actually don't know
what is that exactly?

**Comment by BeepSheep254** [comment]
i have been struggling to see the point bruh

**Comment by Joalor64GH** [comment]
okay but idc it's just a pr

**Comment by Luisinhi010** [comment]
this is so useless that my pr is more useful than this, sorry but it's true.

**Comment by Luisinhi010** [comment]
also, you can just do this:
FlxSprite().loadGraphic(Paths.image(ClientPrefs.enableDark ? 'darkmode/menuDesatDark' : 'menuDesat'));

**Comment by kingyomoma** [comment]
> i actually don't know what is that exactly?

https://haxe.org/manual/expression-operators-ternary.html

**Comment by ShadowMilky** [comment]
> i actually don't know
> what is that exactly?

F8BE2D60-9418-412D-93EA-D76FDA96A73F

**Comment by Swapper1** [comment]
Where is this dark mode BG come from, and it is taken from another FNF Engine?

**Comment by Luisinhi010** [comment]
> Where is this dark mode BG come from, and it is taken from another FNF Engine?

the menubg sprite looks familiar to yoshi engine's ones
prob stolen btw

**Comment by SrtHero278** [comment]
menuBGYoshi
nah.

**Comment by BeastlyGhost** [comment]
you can just drop the images on the mods folder ffs

**Comment by Joalor64GH** [comment]
whatever

**Comment by Lokitot** [comment]
homie you forgor OptionsState.hx 💀💀

**Pull request closed without merging**
