### PR TITLE
Bug fixes and helping out lower end devices

### PR DESCRIPTION
**Pull request by jmxamongusmodder**
Credits to some other pull requests but uh i also did some ones from my own
WHAT THIS DOES:
Allows dad battle lights to be disabled
WIP Debug Notes (SPECIAL!!)
Faster dying tankman speed (its random)
More Random Stuff
Tracing current tank speed
WIP Fix For Song Offset
Reasoned out some values and they feel like the originals so it's like they were not even changed!
Remove unused code
A Function for scrolling in story mode menu (idk why i did it)
Changed characterlist.txt to be shorter cuz the game loads characters from jsons anyway
Smaller Spritesheets
Fixed some bugs
WIP Censoring + Violence
Small tweaks to events and offsets
Fixed timestep on the title screen
Alphabet can be paused if you want it to be paused (useful for mods which pause text at a certient point then unpause it then do it again rapidly useful for a glitching effect)
Public cutscene time (idk why i did that i just wanted to see if that could be used instead of some different code didnt work)

### CODE REVIEW

**Comment by Raltyro** [comment]
image
TRAITOR!!! INSTANT DECLINE

**Comment by jmxamongusmodder** [comment]
> image TRAITOR!!! INSTANT DECLINE

ill fix it right away it just an accident ok

**Comment by jmxamongusmodder** [comment]
> > image TRAITOR!!! INSTANT DECLINE
> 
> ill fix it right away it just an accident ok

its fixed @Raltyro

**Comment by Raltyro** [comment]
thanks, could you turn on workflow in ur fork so i can test it thru actions tab?

**Comment by jmxamongusmodder** [comment]
> thanks, could you turn on workflow in ur fork so i can test it thru actions tab?

how to do that

**Comment by jmxamongusmodder** [comment]
> If you wanted to go further, you can pick up a sprite packer like Spritesheet/ XML Generator for Friday Night Funkin'. Instead of leaving pixel space between bitmap data for offsets, the packers properly adjust framewidth/height so sprites can be right next to eachother.
> 
> Here's an example of the loose packing setting: BOYFRIEND

May just do that but IDK

**Comment by jmxamongusmodder** [comment]
> > If you wanted to go further, you can pick up a sprite packer like Spritesheet/ XML Generator for Friday Night Funkin'. Instead of leaving pixel space between bitmap data for offsets, the packers properly adjust framewidth/height so sprites can be right next to eachother.
> > Here's an example of the loose packing setting: BOYFRIEND
> 
> May just do that but IDK

But i get pretty good optimization how i did it

**Comment by jmxamongusmodder** [comment]
> If you wanted to go further, you can pick up a sprite packer like Spritesheet/ XML Generator for Friday Night Funkin'. Instead of leaving pixel space between bitmap data for offsets, the packers properly adjust framewidth/height so sprites can be right next to eachother.
> 
> Here's an example of the loose packing setting: BOYFRIEND



> If you wanted to go further, you can pick up a sprite packer like Spritesheet/ XML Generator for Friday Night Funkin'. Instead of leaving pixel space between bitmap data for offsets, the packers properly adjust framewidth/height so sprites can be right next to eachother.
> 
> Here's an example of the loose packing setting: BOYFRIEND

Yeah ima do this for certiant characters or cutscenes (week 7 cutscenes)
To help preformance for lower end pc's
Thanks!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by xChillax** [comment]
About repacking images, make sure they have at least a few pixels between each sprite (like making them all be about 3 pixels away from each other), otherwise, the pixels from one frame will bleed into the pixels of the other frames. This is caused by antialiasing, which is enabled by default, so this should always be taken into account.

**Comment by jmxamongusmodder** [comment]
> About repacking images, make sure they have at least a few pixels between each sprite (like making them all be about 3 pixels away from each other), otherwise, the pixels from one frame will bleed into the pixels of the other frames. This is caused by antialiasing, which is enabled by default, so this should always be taken into account.

i believe this is true? it looks fine for me.

**Comment by xChillax** [comment]
Even the creators of FNF were unaware of it until I pointed it out, it's something that you might not see at first but it is there.
The only way to fix it is to give it some room (a few pixels) to allow it to blur the image without bleeding into other animations (anti-aliasing), if your animations look completely fine then it is because they happen to already have some pixels free out of pure luck.

**Comment by jmxamongusmodder** [comment]
> Even the creators of FNF were unaware of it until I pointed it out, it's something that you might not see at first but it is there. The only way to fix it is to give it some room (a few pixels) to allow it to blur the image without bleeding into other animations (anti-aliasing), if your animations look completely fine then it is because they happen to already have some pixels free out of pure luck.

eh it works

**Comment by maitian352** [comment]
@jmxamongusmodder hi please reply to sda

**Comment by maitian352** [comment]
@jmxamongusmodder hi please reply to sda

**Comment by definitely-nobody-is-here** [comment]
oof closed without merge. Also, to eliminate the frame bleeding you can just disable anti-aliasing until the final draw onto the screen. It prevents random blurryness and improves performance if done correctly.

**Pull request closed without merging**
