### PR TITLE
Added onCharacterDance and onIconBop callbacks

### PR DESCRIPTION
**Pull request by jayrattt**
`onCharacterDance` allows for you to run code when a character plays their idle animation, with some info about the animation(s).
`onIconBop` allows for you to override and modify the icons' bopping "animation"
I'm not really good at explaining things, so just check [TemplateScript.lua](https://github.com/8bitjake/PsychEngine-Contrib/blob/main/docs/TemplateScript.lua#L131) for information about each callback.
Example Script: Rotating BF & GF + Exaggerated Icons (https://youtu.be/iMd8RFHUipI) | [Download](https://cdn.discordapp.com/attachments/951656724429938741/954472770903875584/testScript.lua)

### CODE REVIEW

**Comment by Cherif107** [comment]
nice

**Review by Blossomical — CHANGES_REQUESTED** [review]
no i meant to choose approve but i choosed request change on accident

**Review by Blossomical — APPROVED** [review]

**Review by HiroMizuki — APPROVED** [review]

**Comment by 8bitjake** [comment]
okay, so i finally made it so you can cancel dances
however it's really buggy and i don't know any other workarounds
turns out that functions with parameters (such as `onCharacterDance`) don't return `Function_Stop` or `Function_Continue` for whatever reason
i don't know if this is a problem with how such things are handled in `PlayState`, `FunkinLua`, or the Lua libraries the game already use
for now though i'm just using a fucky workaround that stops *all* idle animations, `cancelCharacterDances`
returning `Function_Stop` on this function stops all idle animations, easy as that

**Review by TheKitBoi — APPROVED** [review]

**Review by DaveFan19 — APPROVED** [review]
its cool i guess

**Review by Raltyro — APPROVED** [review]

**Review by lunacynne — APPROVED** [review]
dance callback would be very useful in a script im working on

**Review by ghost — APPROVED** [review]
!!

**Comment by tylerandari12** [comment]
Would the event that forces a dance affect this?  (`characterDance()` I think...)

**Comment by GrexpungedYT** [comment]
7A11B74F-3771-4994-A69E-DE8CD39A429C
uhhhhhhh

**Comment by 8bitjake** [comment]
> Would the event that forces a dance affect this? (`characterDance()` I think...)

i don't think it will, onCharacterDance() is called in the function itself

**Comment by 8bitjake** [comment]
found out that some options menus crashed thanks to this pr, should be fixed now

**Pull request closed without merging**
