### PR TITLE
Allow hxCodec to work with other platforms (MacOS, Linux)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by KirbyKid256** [comment]
Okay. Let me explain this the best I can.
[PolybiusProxy made a comment](https://github.com/ShadowMario/FNF-PsychEngine/pull/11793#issuecomment-1406809140) mentioning the fact that Psych Engine is using an older version of hxCodec.

These builds still use hxCodec 2.5.1 since it's installing from hmm.json which specifically grabs 2.5.1 now. #11793
While it does support Linux (even though there's currently something preventing it from compiling), it does NOT support macOS. You need to use hxCodec 2.6.1 (current) which DOES support macOS.

Now, in 2.6.1, MP4Handler still exists but has been moved and renamed to VideoHandler. Therefore, in PlayState.hx, instead of importing from `vlc.MP4Handler`, you'll need to import from `hxcodec.VideoHandler`. Then, you need to replace any instance of MP4Handler with VideoHandler

Once that's done, then you can change the project XML (as you did) to `desktop || web`. Unfortunately, if you don't update hxCodec to 2.6.1, then it simply can't work on macOS.

**Review by Luisinhi010 — APPROVED** [review]

**Comment by KirbyKid256** [comment]
So, I don't know how to fix the issues with Linux yet. You should ask PolybiusProxy for help with it. But until that's fixed, you can use this to ingore Linux: `<define name="VIDEOS_ALLOWED" if="desktop || web" unless="32bits || linux"/>`

**Comment by ActualMandM** [comment]
Maybe it needs to grab from the GitHub repository instead? There's this commit which seemingly fixes the linker error.
https://github.com/polybiusproxy/hxCodec/commit/15d950b103603a976e0e2d5004c8717b4eecc945

**Comment by BeastlyGabi** [comment]
marking as draft as I need to test to see if we can compile to linux with the git builds

**Pull request closed without merging**
