### PR TITLE
Hellclown has halo notes

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by CrusherMods** [comment]
def getting closed without a merge

**Comment by crispyboi24** [comment]
dont just pull an entire fucking mod lmao

**Comment by fnaffan29** [comment]
why is that man pull requesting a modpack

**Comment by CrusherMods** [comment]
> why is that man pull requesting a modpack

idk but its kinda stupid

**Comment by pakieFNF** [comment]
[here's how to change ur fork behavior if ur using github desktop](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/adding-and-cloning-repositories/cloning-and-forking-repositories-from-github-desktop)

**Comment by Gui-iago** [comment]
I can see this being an accident

**Comment by HiroMizuki** [comment]
what
is
this

**Pull request closed without merging**
