### PR TITLE
SScript issue

### PR DESCRIPTION
**Pull request by afeefflox**
idk new ver broke it trust me

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
no.

**Review by moxie-coder — COMMENTED** [review]
image

**Comment by CaptainBaldi** [comment]
according to someone in the psych discord this doesn't fix anything
there is a bug that some people have when compiling that breaks sscript
but this doesn't fix it

**Review by charlesisfeline — CHANGES_REQUESTED** [review]
stupid that never does anything

laugh at this user for not actually fixing the issue

**Comment by MemeHovy** [comment]
> stupid that never does anything
> 
> laugh at this user for not actually fixing the issue

alright, done

SaraivaDarkkunGIF

**Comment by TehPuertoRicanSpartan** [comment]
nuh uh

**Pull request closed without merging**
