### PR TITLE
Change Icon Event

### PR DESCRIPTION
**Pull request by DabbinDude316B**

### CODE REVIEW

**Comment by Itz-Miles** [comment]
This does actually have it's own uses, approved.

**Review by GO-Miles — APPROVED** [review]

**Comment by Mastercopper2346** [comment]
wait try this
```
		case 'Change Icon':
				iconP1.changeIcon(value1);
				iconP2.changeIcon(value2);
				reloadHealthBarColors();
```

**Comment by hayfii** [comment]
> wait try this
> 
> ```
> 		case 'Change Icon':
> 				iconP1.changeIcon(value1);
> 				iconP2.changeIcon(value2);
> 				reloadHealthBarColors();
> ```

What about ChartingState?

**Comment by DMMaster636** [comment]
I would approve, but you can kinda do that in lua now + you didn't put it into charting state...

**Comment by Mastercopper2346** [comment]
OM LOOKING THROUGH PLAYSTATE AND HES ADDING WEEK 7!!!

**Comment by Mastercopper2346** [comment]
> you can kinda do that in lua now

how? I thought that was only in source…

**Comment by DMMaster636** [comment]
@Mastercopper2346 
`function onCreatePost()
loadGraphic('iconP2', 'icons/icon-_icon name_', 150)
end`
or something like that, you should ask in the psych discord server

**Pull request closed without merging**
