### PR TITLE
Create CustomCredits

### PR DESCRIPTION
**Pull request by Iamsamsmich6**

### CODE REVIEW

**Comment by Stilic** [comment]
shut up pr kid

**Comment by DewDrags** [comment]
Bruh

**Review by BombasticTom — CHANGES_REQUESTED** [review]
close this pull

**Review by ghost — CHANGES_REQUESTED** [review]
commit die

**Comment by DewDrags** [comment]
ok : https://www.youtube.com/watch?v=W1iF_93XJAE

**Comment by HiroMizuki** [comment]
what are you

**Comment by ShadowMario** [comment]
i dont get it, kinda unfunny i think

**Pull request closed without merging**
