### PR TITLE
stop creating new FlxPoints!!! (fr this time)

### PR DESCRIPTION
**Pull request by richTrash21**
[ CLOSED ]

So I was actually going to just replace new FlxPoint() with FlxPoint.get() (same with FlxRects), but decided to add some more tweaks and (maybe) optimizations

Full changelog:
- FlxPoint/FlxRect fields now use get() function instead of creating a new instance (+ they also go back into pool after destroy call).
- Bar.bounds are now FlxBounds<Float> instead of a Dynamic with anonymous structure as their value.
- WeekData.songs are now Array<EitherType<String, Array<Int>>> instead of a Dynamic. (thx detective_baldi)
- PlayState.ratingStuff are now Array<EitherType<String, Float>> instead of a Dynamic. (thx detective_baldi again)
- Rating are now recyclable (horray!!), inspired by #12468 but actually do work this time.
- Change Scroll Speed event now use NumTween for optimization purposes.
- PlayState.health now have a setter that bounds HP to the healthBar.bounds.max possible value. Also doDeathCheck() now uses healthBar.bounds.min as the lowest (gameover) point. 
- Changing character's idleSuffix now automatically calls recalculateDanceIdle() if it was really changed.
- Character dance now can be forced (via lua too).
- Better flashing for MenuItem. (w/ help of ShadowMario)
- Menus now use FlxMath.wrap() to wrap around possible values (instead of if/else thing).
- FINALLY fixed followLerp for new flixel versions.
- (Slightly) Better formatting, less mess.
- Removed one second timer in TitleState (if it's removal will break smth i swear to god...).
- And some more! (yeah, im a bit lazy to write all the stuff here, sorry abt that)

really hope i didn't broke shit. will sure alter something/fix stuff.

### CODE REVIEW

**Comment by crowplexus** [comment]
is this ready for review by chance?

**Comment by richTrash21** [comment]
> is this ready for review by chance?

i think yeah

**Review by system32unknown — APPROVED** [review]

**Review by NexIsDumb — APPROVED** [review]
holy fucking shit someone actually had the guts to do all of this
even that midpoint in the gameover screen FINALLY

**Comment by richTrash21** [comment]
i just did this for my mod and thought: fuck it, ima make this into pr

**Comment by CaptainBaldi** [comment]
I would say move the lua point functions into something like LuaUtils but this is pretty good nonetheless

**Review by Burgerballs — APPROVED** [review]
I give this a burger/balls !!

**Review by charlesisfeline — APPROVED** [review]
finally something that makes psych better by absolute infinity

**Comment by mcagabe19** [comment]
NOOOO

**Comment by NexIsDumb** [comment]
never fucking mind

**Pull request closed without merging**
