### PR TITLE
Display milliseconds

### PR DESCRIPTION
**Pull request by ghost**
self explanatory, displays milliseconds above strumline after hitting a note

### CODE REVIEW

**Review by MemeHoovy — APPROVED** [review]

**Review by tposejank — COMMENTED** [review]
this is possible in lua scripts smh....................

**Review by Joalor64 — APPROVED** [review]

**Review by charlesisfeline — APPROVED** [review]

**Comment by EyeDaleHim** [comment]
Useless.

**Comment by MemeHoovy** [comment]
> Useless.

thinking about it now, yeah this is kinda useless, I’m taking my approval back (If I could)

**Comment by ShadowMilky** [comment]
> Useless.

yea since in my mod, i already used a lua file that has this kind of stuff

**Pull request closed without merging**
