### PR TITLE
Made a credits maker.

### PR DESCRIPTION
**Pull request by haoneRG**
I made a credits editor that you can make/edit credits.

Features:
- Add/Remove a credit or title
- Edit title or credit
- Load/Save credits in txt file

image
image
image

### CODE REVIEW

**Review by Joalor64 — APPROVED** [review]
It's alright, but I'd say that you should fix some grammatical errors. But still, it's good.

**Review by charlesisfeline — APPROVED** [review]
pretty cool ig

**Comment by antoSKRLOL** [comment]
This can be a bit useless since you can put credits without the need for a menu but I think this can replace that ugly method

I'm going to use this, I hope you don't mind!! (I will leave credits)

**Review by rodney528 — APPROVED** [review]

**Comment by Gidk-g** [comment]
yoooooo nice

**Review by ManMaster707 — APPROVED** [review]

**Review by TehPuertoRicanSpartan — APPROVED** [review]

**Comment by Pixel-fied** [comment]
something i need in my life

**Review by moxie-coder — APPROVED** [review]

**Review by NexIsDumb — APPROVED** [review]

**Review by NexIsDumb — APPROVED** [review]

**Comment by NexIsDumb** [comment]
Yoo cool

**Comment by Stefan2008Git** [comment]
Can i use this for my engine @haoneRG? I will credit you

**Review by rodney528 — APPROVED** [review]

**Comment by haoneRG** [comment]
> Can i use this for my engine @haoneRG? I will credit you

Yep, sure @Stefan2008Git

**Comment by Stefan2008Git** [comment]
> > Can i use this for my engine @haoneRG? I will credit you
> 
> Yep, sure @Stefan2008Git

Thank you. I liked this credit editor so much, but there is some bug:
 - When you press UP or DOWN, the scrolling thing is looks like this, wait

**Comment by Stefan2008Git** [comment]
> > > Can i use this for my engine @haoneRG? I will credit you
> > 
> > 
> > Yep, sure @Stefan2008Git
> 
> Thank you. I liked this credit editor so much, but there is some bug:
> 
> * When you press UP or DOWN, the scrolling thing is looks like this, wait

Here

https://github.com/ShadowMario/FNF-PsychEngine/assets/126715034/7db39af7-090a-403a-8ded-c3ca853ca2bf

**Comment by haoneRG** [comment]
> > > > Can i use this for my engine @haoneRG? I will credit you
> > > 
> > > 
> > > Yep, sure @Stefan2008Git
> > 
> > 
> > Thank you. I liked this credit editor so much, but there is some bug:
> > 
> > * When you press UP or DOWN, the scrolling thing is looks like this, wait
> 
> Here
> 
>  VID_20231020_085459.mp4

I think that might be a bug related to the android buttons, on pc it works fine

**Comment by Stefan2008Git** [comment]
> > > > > Can i use this for my engine @haoneRG? I will credit you
> > > > 
> > > > 
> > > > Yep, sure @Stefan2008Git
> > > 
> > > 
> > > Thank you. I liked this credit editor so much, but there is some bug:
> > > 
> > > * When you press UP or DOWN, the scrolling thing is looks like this, wait
> > 
> > 
> > Here
> > VID_20231020_085459.mp4
> 
> I think that might be a bug related to the android buttons, on pc it works fine @Stefan2008Git

You sure? It's happening on PC build too.

https://github.com/ShadowMario/FNF-PsychEngine/assets/126715034/594d171e-0b4c-45f1-939a-48ab9e2ae689

**Comment by haoneRG** [comment]
> > > > > > Can i use this for my engine @haoneRG? I will credit you
> > > > > 
> > > > > 
> > > > > Yep, sure @Stefan2008Git
> > > > 
> > > > 
> > > > Thank you. I liked this credit editor so much, but there is some bug:
> > > > 
> > > > * When you press UP or DOWN, the scrolling thing is looks like this, wait
> > > 
> > > 
> > > Here
> > > VID_20231020_085459.mp4
> > 
> > 
> > I think that might be a bug related to the android buttons, on pc it works fine @Stefan2008Git
> 
> You sure? It's happening on PC build too.
> 
>  bandicam.2023-10-20.17-30-03-977.mp4

its been a while since i used this code, i think is supposed to be used in 0.6.3 or something, when i have time ill check it and update it @Stefan2008Git

**Pull request closed without merging**
