### PR TITLE
Change the coordinates(?) of a main menu button with a .JSON file.

### PR DESCRIPTION
**Pull request by Joalor64**
Now that I think of it, it's kind of similar to #9058, but anyways, here's this thing I guess.
This YT video shows how it works. (I copied the file from the video.)
https://www.youtube.com/watch?v=hD2aEAMbGb8

### CODE REVIEW

**Comment by BeastlyGhost** [comment]
you could just make a PR on my repo for it

**Comment by BeastlyGhost** [comment]
would help a lot honestly, i've been trying to make it for a while now

**Comment by Joalor64GH** [comment]
actually that sounds like a good idea

**Comment by antoSKRLOL** [comment]
I actually saw that in a tutorial

**Comment by antoSKRLOL** [comment]
although it doesn't work like that at all, it's not just copying the file and that's it, it's more complicated, you know, modify this, modify that, anyway I'll leave you the tutorial where I got that from, say hi to the guy who did it for me
https://youtu.be/QZQJ701tAqQ

**Comment by Joalor64GH** [comment]
oh okay

**Comment by antoSKRLOL** [comment]
by the way, you should see the other videos of the mod, you might be interested

**Comment by Joalor64GH** [comment]
cool

**Comment by frantastic24** [comment]
This does literally nothing??

**Comment by ShadowMario** [comment]
This doesn't do shit.

**Comment by MilkyTheMilkBlob** [comment]
> This doesn't do shit.

i agree
he should've put the haxe code of the thingamajig, but nope

just the json file
lazy

**Comment by Joalor64GH** [comment]
> > This doesn't do shit.
> 
> i agree he should've put the haxe code of the thingamajig, but nope
> 
> just the json file thats so lazy

Excuse me I didn't know there was more stuff to make the JSON actually work.

**Comment by MilkyTheMilkBlob** [comment]
> > > This doesn't do shit.
> > 
> > 
> > i agree he should've put the haxe code of the thingamajig, but nope
> > just the json file thats so lazy
> 
> Excuse me I didn't know there was more stuff to make the JSON actually work.

yea, i think you might have to put the json stuff in the main menu state hx file and not just the json file
otherwise its never gonna work

**Comment by Joalor64GH** [comment]
> yea, i think you might have to put the json stuff in the main menu state hx file and not just the json file otherwise its never gonna work

okay

**Pull request closed without merging**
