### PR TITLE
loading screen add :)

### PR DESCRIPTION
**Pull request by LaRENIEC**
loading screen add :)

### CODE REVIEW

**Comment by HiroMizuki** [comment]
no

**Comment by CrusherMods** [comment]
no

**Comment by tposejank** [comment]
no

**Comment by SrtHero278** [comment]
no

**Comment by MasterDirector99** [comment]
no

**Comment by MrClogsworthYT** [comment]
`no`

**Comment by Peeyos1** [comment]
no

**Comment by tposejank** [comment]
> unnecessary and I think I saw in a post that shadowmario would not put it

fuck you

**Comment by HiroMizuki** [comment]
> unnecessary and I think I saw in a post that shadowmario would not put it

fuck you

**Comment by JeffersonThePro68** [comment]
:(

**Comment by SonicProYT** [comment]
its kinda useless outside of the web version

**Pull request closed without merging**
