### PR TITLE
no more deprecated warnings

### PR DESCRIPTION
**Pull request by lemz1**
changes/fixes: 

- objects.AchievementPopup.hx
    - fixed the deprecated warnings by using @:privateAcess and getting the defaultCameras like that

### CODE REVIEW

**Review by moxie-coder — APPROVED** [review]
the other changes seem useless tho

**Comment by lemz1** [comment]
yeah i guess but i always hate it when people just send the crash report and you have no information whatsoever.
the biggest issue is when you dont know the version because the error could have a different line for example on version 0.4.2 it could be on line 422 and on version 0.6.2 it could be on line 600.

**Comment by MemeHovy** [comment]
fair

**Review by NexIsDumb — APPROVED** [review]

**Comment by Kn1ghtNight** [comment]
why would you do this
```xml
<haxedef name="no-deprecation-warnings" />
```
is right there

**Comment by MemeHovy** [comment]
> i think the approach with haxedef is bad, because if someone uses a deprecaded function, he isn't going to know.

I mean, you can disable it for debug builds, which is what I did

**Comment by lemz1** [comment]
> I mean, you can disable it for debug builds, which is what I did

I guess thats true, but i'll just keep this pr open, so that if shadowmario actually wants to remove the deprecaded warning, then he can just pull this pr.

**Comment by Kn1ghtNight** [comment]
> i think the approach with haxedef is bad, because if someone uses a deprecaded function, he isn't going to know.

deprecated functions get flagged in the docs???? (well not like most fnf coders read documentation)

**Comment by Kn1ghtNight** [comment]
but literally if they wouldnt read docs they would end up trying to fix it themselves or asking for help
(most likely will do the second option) and most people would just say to ignore it and that its fine.

**Pull request closed without merging**
