### PR TITLE
Play Opponent's Chart Option

### PR DESCRIPTION
**Pull request by lemz1**
Hi,
so I added an Option that lets you play the chart of the opponent.
I saw that there was an option opponentplay and it wasn't used so I guessed that this was meant

### CODE REVIEW

**Comment by SrtHero278** [comment]
Fix the two commits you removed. Mainly the back button one.

**Comment by lemz1** [comment]
The source code on the release page is different from the source code on the main page. That probably was the problem

**Comment by Gui-iago** [comment]
found a bug on middlescroll

https://user-images.githubusercontent.com/45212377/147509638-4a7440cb-60d8-4705-88d2-40414490219e.mp4

**Comment by DeceptedPar** [comment]
I think it should be optional for it to look like that, could be a fun challenge

**Comment by Gui-iago** [comment]
I can't github.

**Comment by DMMaster636** [comment]
added this to my fork cause it's really cool and I also got winning icons to work with this.

**Comment by fnaffan29** [comment]
we need this

**Comment by lemz1** [comment]
I had to repost this pull request bruh (new #3549)

**Pull request closed without merging**
