### PR TITLE
Forget it.

### PR DESCRIPTION
**Pull request by Joalor64**
Not making another pull request here again.

### CODE REVIEW

**Comment by frantastic24** [comment]
Why
There is an entire menu made specifically to credit everyone instead of one person

**Comment by BeastlyGhost** [comment]
there's literally an entire credits menu for that

**Comment by Steviegt6** [comment]
> there's literally an entire credits menu for that

You are an NPC.

**Comment by BeastlyGhost** [comment]
> > there's literally an entire credits menu for that
> 
> You are an NPC.

well, yes

**Comment by Keoiki** [comment]
this pr is dumb, just close it yourself this isn't gonna get anywhere

**Comment by Joalor64GH** [comment]
frick

**Comment by Joalor64GH** [comment]
bruh im not an npc this is my first time making pull requests

**Pull request closed without merging**
