### PR TITLE
Unhide exit because it's not malicious and hide many more potentially malicious functions

### PR DESCRIPTION
**Pull request by superpowers04**

### CODE REVIEW

**Review by lunacynne — CHANGES_REQUESTED** [review]
add these to the disable list
```haxe
os.getenv = nil;
os.remove = nil;
os.rename = nil;
package.loaded.os.getenv = nil;
package.loaded.os.remove = nil;
package.loaded.os.rename = nil;
```

**Review by lunacynne — APPROVED** [review]

**Review by ghost — APPROVED** [review]
Yes.
We can have part of os back.

**Review by ghost — CHANGES_REQUESTED** [review]
But you should also remove some of these.
```hx
os.chdir = nil;
os.popen = nil;
os.close = nil;
os.makedir = nil;
os.makedirs =nil;
package.loaded.os.chdir = nil;
package.loaded.os.popen = nil;
package.loaded.os.close = nil;
package.loaded.os.makedir = nil;
package.loaded.os.makedirs = nil;
```
chdir changes the name of a directory/folder
popen opens a file found in a user. (if it's editable then it can also edit it, like a text editor)
close closes any open file. any. (usually used after popen but still malicious)
mkdir/makedirs makes a directory in a chosen folder

Tbh, I think you should put these in a different pr, or rename this pr.
If not, I can make my own pr.

**Review by ghost — APPROVED** [review]
Don't know why I have to approve it after a change.
But yea nice.
Also you missed a space with os.makedirs.

**Review by Raltyro — APPROVED** [review]
still kinda sad that require is blocked :sob:

**Pull request closed without merging**
