### PR TITLE
Scroll speed for individual notes

### PR DESCRIPTION
**Pull request by te-agma-at**
hopefully this will work

### CODE REVIEW

**Comment by te-agma-at** [comment]
> > hopefully this will work
> 
> it wont? you didnt update funkinlua and edit code to even make it work. theres more then just adding a variable kid.

where though?

**Comment by xChillax** [comment]
You need to make the notes use that variable to make it work, otherwise as it stands, that variable does nothing.

**Comment by Stilic** [comment]
also shadowmario don't want that

**Comment by xChillax** [comment]
Oh, and why is that? I'm surprised how many things are being denied despite giving more creativity to mods.

(besides the point that this right here is not even properly done)

**Comment by Stilic** [comment]
> Oh, and why is that? I'm surprised how many things are being denied despite giving more creativity to mods.
> 
> (besides the point that this right here is not even properly done)

idk

**Comment by hayfii** [comment]
Do you even know what coding is ☠️

**Comment by ShadowMario** [comment]
This doesn't do shit

**Pull request closed without merging**
