### PR TITLE
more platfroms in getBuildTarget

### PR DESCRIPTION
**Pull request by ghost**
probably this is will be good idk

### CODE REVIEW

**Review by moxie-coder — APPROVED** [review]

**Review by charlesisfeline — COMMENTED** [review]
there isnt ios support for psych but

**Review by charlesisfeline — APPROVED** [review]
ok

**Comment by mcagabe19** [comment]
> there isnt ios support for psych but

there's

**Comment by Vortex2Oblivion** [comment]
> there isnt ios support for psych but

What's stopping someone from making it then the variable could be useful to them if they do

**Review by Vortex2Oblivion — CHANGES_REQUESTED** [review]
You're missing a few afaik such as electron

**Comment by mcagabe19** [comment]
> You're missing a few afaik such as electron

electron = browser

**Comment by Vortex2Oblivion** [comment]
Isn't lime test electron a thing iirc? So wouldn't it have its own target define?

**Comment by Vortex2Oblivion** [comment]
https://lime.openfl.org/docs/getting-started/targets/

**Comment by mcagabe19** [comment]
huh odd

**Review by Karim-Akra — APPROVED** [review]

**Review by Vortex2Oblivion — APPROVED** [review]

**Review by TheLeerName — APPROVED** [review]
why not

**Pull request closed without merging**
