### PR TITLE
Minor Patch in StrumNote.hx

### PR DESCRIPTION
**Pull request by Raltyro**
Referencing this issue below
https://github.com/ShadowMario/FNF-PsychEngine/issues/9489

### CODE REVIEW

**Review by Grape-Boy — APPROVED** [review]
Wow, I didn't know `curAnim` could be null.

**Comment by RafPlayz69YT** [comment]
this doesn't fix it.

**Comment by RafPlayz69YT** [comment]
the reason why is because if curAnim = null which it did for the crash, then curAnim (aka null) doesnt have a name object, that is the crash. it still references it in the same if

**Comment by RafPlayz69YT** [comment]
the code should look more like
```haxe
if (animation.curAnim != null) {
   if (animation.curAnim.name == 'confirm' && !PlayState.isPixelStage) 
			centerOrigin();
}
```

**Comment by RafPlayz69YT** [comment]
oh damn, didn't know that

**Review by rodney528 — APPROVED** [review]

**Comment by Raltyro** [comment]
Closed due to pr duplication
https://github.com/ShadowMario/FNF-PsychEngine/pull/9689

**Pull request closed without merging**
