### PR TITLE
Yet Another FunkinLua Night (Changes)

### PR DESCRIPTION
**Pull request by Raltyro**
i am so sorry for yafn reference

anyway here what changed
> no more try/catch in FunkinLua.call (might boost up a performance a bit)
> i dont know why that in the code, it serves no purposes for me atleast

> reuse resultIsAllowed for luaDebugMode traces in FunkinLua.call
> remove FunkinLua.typeToString and use Lua.typename instead of FunkinLua.typeToString

> remove FunkinLua.initLuaShader and replace existing codes of it to Playstate.initLuaShader

### CODE REVIEW

**Review by MemeHoovy — APPROVED** [review]

**Review by lunacynne — APPROVED** [review]

**Review by rodney528 — APPROVED** [review]

**Review by rodney528 — APPROVED** [review]
lol

**Comment by Raltyro** [comment]
I saw some issues saying about crashes still happening even after 0.6.3 release, i will try to fix it in this pull request

**Comment by ImaginationSuperHero528** [comment]
> I saw some issues saying about crashes still happening even after 0.6.3 release, i will try to fix it in this pull request

Yeah like this one port I'm doing just crashes now.

**Comment by Raltyro** [comment]
> > I saw some issues saying about crashes still happening even after 0.6.3 release, i will try to fix it in this pull request
> 
> Yeah like this one port I'm doing just crashes now.

can you give me the port to test?

**Review by TheKitBoi — APPROVED** [review]

**Comment by Raltyro** [comment]
Closed, will bring this up with a new pr introducing another lua reworks.

**Comment by ImaginationSuperHero528** [comment]
> I saw some issues saying about crashes still happening even after 0.6.3 release, i will try to fix it in this pull request

I fixed it

**Pull request closed without merging**
