### PR TITLE
Allow working memory greater than 1 Gig

### PR DESCRIPTION
**Pull request by MAJigsaw77**
The title says all lol

### CODE REVIEW

**Comment by MilkyTheMilkBlob** [comment]
this helps because it prevents lag on low-end laptops like mine

**Review by charlesisfeline — APPROVED** [review]
so i commit approve

**Comment by Raltyro** [comment]
uh actually whats the different here?

**Review by TheKitBoi — APPROVED** [review]

**Comment by MilkyTheMilkBlob** [comment]
> uh actually whats the different here?

it prevents lag on computers that have less than 16 gigabytes, i think

**Comment by jigsaw-4277821** [comment]
it is

**Comment by Raltyro** [comment]
Tested and yeah it does, approve

**Review by Raltyro — APPROVED** [review]

**Review by JorosTheModderPH — APPROVED** [review]

**Review by stilic — APPROVED** [review]

**Pull request merged**
