### PR TITLE
Added stageName

### PR DESCRIPTION
**Pull request by Grape-Boy**
Adds a '`curStage`' variable accessible in Lua.

### CODE REVIEW

**Comment by frantastic24** [comment]
Why??

```lua
function onCreatePost()
     debugPrint(getPropertyFromClass('PlayState', 'curStage')
end
```

**Comment by Grape-Boy** [comment]
> Why??
> 
> ```lua
> function onCreatePost()
>      debugPrint(getPropertyFromClass('PlayState', 'curStage')
> end
> ```

bruhhhh why didn't you tell me on my issue

**Comment by Grape-Boy** [comment]
actually `songName` is a thing, so why not keep this

**Comment by frantastic24** [comment]
Because songName is useful unlike curStage

**Comment by ProgramerGamerZone** [comment]
songName doesn't even work

**Comment by Grape-Boy** [comment]
> songName doesn't even work

It doesn't ?

**Comment by frantastic24** [comment]
Yes it does lmao

**Comment by Itz-Miles** [comment]
I at first thought another variable like stageName was redundant, but maybe this would give inexperienced modders the ability to do some stage shenanigans. (curSong currently influences the stage in source, and the stage influences stage elements if they aren't null.) Aren't luascripts still able to change any variable though?

**Comment by Grape-Boy** [comment]
> I at first thought another variable like stageName was redundant, but maybe this would give inexperienced modders the ability to do some stage shenanigans. (curSong currently influences the stage in source, and the stage influences stage elements if they aren't null.) Aren't luascripts still able to change any variable though?

Yeah I think they can change basically anything, but the value might be changed again by the game.

**Comment by frantastic24** [comment]
What the fuck

**Comment by Grape-Boy** [comment]
UH OH HOW DID THIS HAPPEN

**Comment by Grape-Boy** [comment]
You know what, I'll just close this. 😁

**Comment by frantastic24** [comment]
GitHub is fun to use ain't it

**Comment by Grape-Boy** [comment]
> GitHub is fun to use ain't it

oh yes very fun

**Comment by Itz-Miles** [comment]
Oh yeah, I figured that curStage still works outside of what it's intended for, so my thinking was a mute point. Setting curStage works without any hiccups. (things could be null depending on wether functions using curStage are called before or after)

**Pull request closed without merging**
