### PR TITLE
Bring back softcoded achievements v2

### PR DESCRIPTION
**Pull request by ghost**
This PR brings back the scrapped softcoded achievements.
To make softcoded achievements, you'll need a .json and .lua file.
Here's an example.

So this is an example .json file: 
```json
{
	"name": "Road to Ten Million",
	"desc": "Gain 10 Million scores in total.",
	"save_tag": "ten_million",
	"hidden": false,
	"clearAchievements": true,
        "week_nomiss": null,
        "lua_code": null,
	"global": null,
	"index": -1
}
```
And there is the .lua file (optional, you can just put the code to **lua_code**).
```lua
function onUpdate(elapsed) 
  if getProperty("songScore") >= 10000000 then
    giveAchievement("ten_million");
  end
end
```

### JSON
Mandatory variables:

- **name** is obviously the name of the achievement.
- **desc** is the description of your achievement.
- **save_tag** is the save tag of the achievement, also the file name of the achievement icon.
- **hidden** is the visibility of your achievement. Remains invisible until it's unlocked if true.
- If **index** is null or -1, gets added to end of the achievements.

Optional variables:

### **WARNING**: Using these optional variables is dangerous and using these can cause unstability. Use carefully.
**clearAchievements** clears all of the achievements if true. **SHOULD BE USED ONLY ONCE IN A MODPACK.**
**global** is the most dangerous one. If you want to set **global**, remember all of the other variables will get ignored.
If **global** is not null, it replaces the WHOLE achievements. So a .json file with **global** should be like this:
```json
{
	"name": "",
	"desc": "",
	"save_tag": "",
	"hidden": false,
	"clearAchievements": false,
	"index": null,
        "global":  [
            ["Road to Ten Million", "Gain 10 Million scores in total.", "ten_million", false],
            ["Road to a Billion", "Gain 1 Billion scores in total.", "one_billion", false]
        ]
}
```
This way, achievements gets replaced with **global**. First element is name, second is description.
Third is the save tag and icon file name, fourth is the visibility until unlocked.
### JUST LIKE **clearAchievements**, **global** SHOULD BE ONLY USED ONCE IN A MODPACK.

**week_nomiss** is the week name, just put the file name of the week to it to make a "No miss" achievement.
**week_nomiss should always end with "nomiss"!  For example, if your week name is "week8" and you want
to make a beating week with no misses achievement, just write "week8_nomiss" to week_nomiss!**

**lua_code** is the code of the achievement. If you do not want to create a lua file, just put your code in it!

### LUA
Lua is nothing special, though there are differences.
Just use **giveAchievement(*Achievement's save tag*)** to unlock the achievement.
If achievement is already unlocked or achievements doesn't exist or the lua script is not an achievement script,
**giveAchievement** is ignored.

### Example Images
Using **clearAchievements**:
image

Without using **clearAchievements**:
image

With **index** being 0:
image

With using **global**:
image

### CODE REVIEW

**Review by MemeHoovy — APPROVED** [review]

**Comment by MrGenie151** [comment]
YESSS BEEN WAITING FOR THIS

**Review by MemeFlavor — APPROVED** [review]

**Review by TheKitBoi — APPROVED** [review]

**Comment by RedstoneRuler** [comment]
yes

**Review by DaRealDotZ — APPROVED** [review]
YEAH!

**Comment by CaptainBaldi** [comment]
pretty kewl
dont think it will get merged but still nice

**Review by DetectiveBaldi — APPROVED** [review]

**Comment by TheWorldMachinima** [comment]
> pretty kewl dont think it will get merged but still nice

Same, at least people can use this with their mod .

**Review by ManMaster707 — APPROVED** [review]
Thank you.

**Review by riachuyeah — APPROVED** [review]
this is cool ASF i hope they add it

**Review by Raltyro — APPROVED** [review]

**Review by crowplexus — APPROVED** [review]

**Comment by antoSKRLOL** [comment]
wow...

**Comment by antoSKRLOL** [comment]
I thought of doing this before, I made a pro prototype I didn't get far, can I add this instead?
image

**Review by ghost — APPROVED** [review]
Oh my fucking god yes

**Review by ghost — APPROVED** [review]

**Review by aaaproooo — APPROVED** [review]

**Review by Parsellol — APPROVED** [review]

**Review by ghost — APPROVED** [review]
Cool!

**Review by tposejank — COMMENTED** [review]
I'm going to sue you for copyright infringement!! /j
I'll make my own pr

**Comment by TheWorldMachinima** [comment]
> I thought of doing this before, I made a pro prototype I didn't get far, can I add this instead? image

Süre, just make sure to credit me.

**Review by DM-kun — APPROVED** [review]
nice

**Review by JorosTheModderPH — APPROVED** [review]

**Review by RedstoneRuler — APPROVED** [review]
This needs to be merged

**Comment by antoSKRLOL** [comment]
hello it's me again, I already added this but I had a problem with this line of code
"luaTrace("giveAchievement: This lua file is not a custom achievement lua.", false, false, FlxColor.RED);"

there is no problem with removing it right?

**Comment by TheWorldMachinima** [comment]
Lua file should be in mods/achievements.

**Review by J-Orell — APPROVED** [review]

**Review by lunacynne — APPROVED** [review]

**Comment by Eventretta** [comment]
pretty cool

**Comment by Raltyro** [comment]
hey i came back to check this pr
what happened?

**Comment by TheWorldMachinima** [comment]
> hey i came back to check this pr what happened?

Nothing, still waiting to ShadowMario to approve. It's never going to happen though.

**Review by DisIsNOt — APPROVED** [review]
cool

**Review by rodney528 — APPROVED** [review]
Oo0

**Comment by nbonnie2** [comment]
yooooooooooooooooooooooo

**Review by Burgerballs — APPROVED** [review]

**Review by SillyVyxia — APPROVED** [review]
we need this

**Comment by Temmiekat** [comment]
I cant seem to get giveAchievement to work, is there an example script using it? like in the right folder? I put mine in /achievements and it still wont work?

**Comment by TheWorldMachinima** [comment]
> I cant seem to get giveAchievement to work, is there an example script using it? like in the right folder? I put mine in /achievements and it still wont work?

Did you write in the save tag?

**Comment by Temmiekat** [comment]
> 

yeah i did it like this

lua-
`function onSongStart()
	debugPrint('ran')
	giveAchievement("run_test")
end`
json-
`{
	"name": "Test",
	"desc": "For Testing",
	"save_tag": "run_test",
	"hidden": false,
	"clearAchievements": true,
	"week_nomiss": null,
	"lua_code": null,
	"global": null,
	"index": -1
}`

it shows up in the awards but wont unlock, the debugprint returns run. but it does not give the achevement.

**Comment by TheWorldMachinima** [comment]
> > 
> 
> yeah i did it like this
> 
> lua- `function onSongStart() debugPrint('ran') giveAchievement("run_test") end` json- `{ "name": "Test", "desc": "For Testing", "save_tag": "run_test", "hidden": false, "clearAchievements": true, "week_nomiss": null, "lua_code": null, "global": null, "index": -1 }` [sorry for bad formatting idk how to do it on git] it shows up in the awards but wont unlock, the debugprint returns run. but it does not give the achevement.

Noted, this will get fixed.

**Comment by TheWorldMachinima** [comment]
> > 
> 
> yeah i did it like this
> 
> lua- `function onSongStart() debugPrint('ran') giveAchievement("run_test") end` json- `{ "name": "Test", "desc": "For Testing", "save_tag": "run_test", "hidden": false, "clearAchievements": true, "week_nomiss": null, "lua_code": null, "global": null, "index": -1 }` [sorry for bad formatting idk how to do it on git] it shows up in the awards but wont unlock, the debugprint returns run. but it does not give the achevement.

Just tried the exact same achievement with the same script and it appears to be only broken in onSongStart. You can use `onUpdate` or `onUpdatePost` instead.

**Comment by Temmiekat** [comment]
> 

alright ill test it now

**Comment by Temmiekat** [comment]
> > 
> 
> alright ill test it now

ok tried it again in onupdate, and onupdatepost (and onstephit) in and out of an if/then statement and still got nothing. the source code is identical so maybe im doing the directory's wrong? here are some screenshots so you can correct me if the are wrong. [code is same as before but with function swapped]

image
image
image
image

**Comment by Temmiekat** [comment]
disregard previous issue, worked after disabling most other scripts running. if its conflicting with something ill put it here.

**Comment by Temmiekat** [comment]
I think I figured it out, it seems to only work when its the ONLY lua script running. maybe the code that checks if the "giveAchevement" is ran from a script within /achievements also checks other running scripts? not sure because im horrible with HAXE.

also it does run on other callbacks, as I tested it again with onSongStart() as it being the only running script. and it worked.  

so the issue was not from the callbacks, it's gotta be something to do with that because I could only get it to activate when it was the only script running.

**Comment by Temmiekat** [comment]
image
after removing these lines of code, it now functions correctly.

**Comment by Temmiekat** [comment]
image
after removing these lines of code it now works correctly. 
even went back and checked it with a few different songs with varying amounts of scripts.

**Comment by TheWorldMachinima** [comment]
This PR is getting a rework, it will be opened again later.

**Pull request closed without merging**
