### PR TITLE
Add extended icon support

### PR DESCRIPTION
**Pull request by ghost**
This PR includes custom width and height support, animated icons without lua and forcing antialiasing support.
There is a json example to show how the json file works. 
"forceAntialiasing" in the json file is an array.
For example, if "forceAntialiasing" is set to "[true, false]" it will force no antialiasing.

### CODE REVIEW

**Review by nahiassis — APPROVED** [review]
poggers

**Review by ghost — APPROVED** [review]

**Review by HeliProGamer — APPROVED** [review]
This is wonderful!

**Comment by BombasticTom** [comment]
???

**Comment by TahirArch** [comment]
> ???

what

**Pull request closed without merging**
