### PR TITLE
communitygames is cool channel lol

### PR DESCRIPTION
**Pull request by NimuFurrySoftUwU**
trash mod

### CODE REVIEW

**Comment by XS09-dev** [comment]
Bro this is most certainly not getting accepted. Stupid.

**Comment by CrusherMods** [comment]
ain't no fucking way💀

**Comment by Stilic** [comment]
shut the fuck up pr kid or i eat ur mom

**Review by BombasticTom — CHANGES_REQUESTED** [review]
delete your account

**Comment by BombasticTom** [comment]
> delete your account

(for making a stupid as fuck pull request)

**Review by ManMaster707 — CHANGES_REQUESTED** [review]
You literally deleted the credits for the creators of THE ENGINE and THE FRICKIN' GAME, not to mention you wrote "mod shit XD" for no reason, added two random people I don't even know and REMOVED THE CREDITS MENU ENTIRELY.
In conclusion, close this, don't pull request idiotic things, do your homework, and GET A LIFE AND A WIFE.

**Comment by CrusherMods** [comment]
> You literally deleted the credits for the creators of THE ENGINE and THE FRICKIN' GAME, not to mention you wrote "mod shit XD" for no reason, added two random people I don't even know and REMOVED THE CREDITS MENU ENTIRELY. In conclusion, close this, don't pull request idiotic things, do your homework, and GET A LIFE AND A WIFE.

yo you forgot something he needs to get
**a brain**

**Comment by Joalor64GH** [comment]
Don’t care + didn’t ask + cry about it + stay mad + get real + L + mald seethe cope harder + ho mad + basic + skill issue + ratio + you fell off + the audacity + triggered + any askers + repelled + get a life + ok + and? + cringe + touch grass + donowalled + not based + your a (insert stereotype) + not funny didn’t laugh + you “re” + grammar issues + go outside + get good + reported + ad hominem + GG! + ask deez + ez clap + straight cash + ratio again + final ratio + problematic+ Don’t care + didn’t ask + cry about it + stay mad + get real + L + mald seethe cope harder + ho mad + basic + skill issue + ratio + you fell off + the audacity + triggered + any askers + repelled + get a life + ok + and? + cringe + touch grass + donowalled + not based + your a (insert stereotype) + not funny didn’t laugh + you “re” + grammar issues + go outside + get good + reported + ad hominem + GG! + ask deez + ez clap + straight cash + ratio again + final ratio + problematic+ Don’t care + didn’t ask + cry about it + stay mad + get real + L + mald seethe cope harder + ho mad + basic + skill issue + ratio + you fell off + the audacity + triggered + any askers + repelled + get a life + ok + and? + cringe + touch grass + donowalled + not based + your a (insert stereotype) + not funny didn’t laugh + you “re” + grammar issues + go outside + get good + reported + ad hominem + GG! + ask deez + ez clap + straight cash + ratio agian + final ratio + problematic+ Don’t care + didn’t ask + cry about it + stay mad + get real + L + mald + seethe + cope + harder + ho + mad + basic + skill issue + ratio + you fell off + the audacity + triggered + any askers + repelled + get a life + ok + and? + cringe + touch grass + donowalled + not based + your a (insert stereotype) + not funny didn’t laugh + you “re” + grammar issues + go outside + get good + reported + ad hominem + GG! + ask deez + ez clap + straight cash + ratio again + final ratio + problematic + Don’t care + didn’t ask + cry about it + stay mad + get real + L

**Comment by voxovistired** [comment]
fuck am i looking at
what have i seen
someone tell me this isnt real

**Review by voxovistired — CHANGES_REQUESTED** [review]
just **n o**

**Comment by silvashp** [comment]
dumbass child

**Comment by CrusherMods** [comment]
IT GOT CLOSED LESS GOOOOO

**Comment by Joalor64GH** [comment]
F**K YEAAAAAAAAHAHHAHHAH

**Comment by Mastercopper2346** [comment]
Why must everyone be toxic

**Comment by Mastercopper2346** [comment]
Why can no one take a joke

**Comment by Mastercopper2346** [comment]
bozos i hack him

**Pull request closed without merging**
