### PR TITLE
Music Player for Freeplay

### PR DESCRIPTION
**Pull request by ghost**
Currently Freeplay can play songs but it can't do anything with them, so this PR adds a simplified music player for Freeplay.
It can pause, rewind, fast forward or stop songs.

Pausing:

https://github.com/ShadowMario/FNF-PsychEngine/assets/146023700/f125bb0e-1f8f-4022-91ed-3e723b801834

Rewinding:

https://github.com/ShadowMario/FNF-PsychEngine/assets/146023700/377db404-34c8-40e8-bc48-0c2ddcce29b1

Fast forwarding:

https://github.com/ShadowMario/FNF-PsychEngine/assets/146023700/18d49635-8406-4407-8e25-2836c3fce338

Stopping:

https://github.com/ShadowMario/FNF-PsychEngine/assets/146023700/c835f100-f3a4-4b4f-b204-ee9afa0eec4e

### CODE REVIEW

**Review by Jaduplex — APPROVED** [review]
me likey

**Review by crowplexus — APPROVED** [review]
cool idea

**Review by DetectiveBaldi — APPROVED** [review]
👍 
I think the song playing mechanism has been in need for some tweaking because as of now it is pretty bland.
Only other thing I would like to see is maybe a slider for playback rate, similar to the one in the chart editor, but this is great on its own.

**Comment by TheLeerName** [comment]
make song load by async method (Thread.create)

**Review by DisIsNOt — APPROVED** [review]

**Pull request merged**
