### PR TITLE
some improvements

### PR DESCRIPTION
**Pull request by tposejank**
check files for info

### CODE REVIEW

**Comment by Starmapo** [comment]
This looks awesome

**Comment by jmxamongusmodder** [comment]
just wondering
is this how loadbroswer lua code was meant to be implemented if you added it?
		//Lua_helper.add_callback(lua, "browserLoad", CoolUtil.browserLoad); //Will do this soon tho i uhm am really busy and idc about security
//                      CoolUtil.browserLoad(site);
//		});

**Comment by tposejank** [comment]
> just wondering is this how loadbroswer lua code was meant to be implemented if you added it? //Lua_helper.add_callback(lua, "browserLoad", CoolUtil.browserLoad); //Will do this soon tho i uhm am really busy and idc about security // CoolUtil.browserLoad(site); // });

yes

**Comment by jmxamongusmodder** [comment]
> > just wondering is this how loadbroswer lua code was meant to be implemented if you added it? //Lua_helper.add_callback(lua, "browserLoad", CoolUtil.browserLoad); //Will do this soon tho i uhm am really busy and idc about security // CoolUtil.browserLoad(site); // });
> 
> yes

well im making psych engine epic edition i want to restore features and add some for mod creation who want them wanna help? rn im trying to restore the install and deletion buttons for the mod menu state!

**Comment by tposejank** [comment]
> > > just wondering is this how loadbroswer lua code was meant to be implemented if you added it? //Lua_helper.add_callback(lua, "browserLoad", CoolUtil.browserLoad); //Will do this soon tho i uhm am really busy and idc about security // CoolUtil.browserLoad(site); // });
> > 
> > yes
> 
> well im making psych engine epic edition i want to restore features and add some for mod creation who want them wanna help? rn im trying to restore the install and deletion buttons for the mod menu state!

how old are you

**Comment by jmxamongusmodder** [comment]
> > > > just wondering is this how loadbroswer lua code was meant to be implemented if you added it? //Lua_helper.add_callback(lua, "browserLoad", CoolUtil.browserLoad); //Will do this soon tho i uhm am really busy and idc about security // CoolUtil.browserLoad(site); // });
> > > 
> > > 
> > > yes
> > 
> > 
> > well im making psych engine epic edition i want to restore features and add some for mod creation who want them wanna help? rn im trying to restore the install and deletion buttons for the mod menu state!
> 
> how old are you

uhhh 10?

**Comment by tposejank** [comment]
> > > > > just wondering is this how loadbroswer lua code was meant to be implemented if you added it? //Lua_helper.add_callback(lua, "browserLoad", CoolUtil.browserLoad); //Will do this soon tho i uhm am really busy and idc about security // CoolUtil.browserLoad(site); // });
> > > > 
> > > > 
> > > > yes
> > > 
> > > 
> > > well im making psych engine epic edition i want to restore features and add some for mod creation who want them wanna help? rn im trying to restore the install and deletion buttons for the mod menu state!
> > 
> > 
> > how old are you
> 
> uhhh 10?

:whattheactualfuck:

**Comment by MrClogsworthYT** [comment]
never gonna give you up

**Comment by HafimieForever** [comment]
> > > > > just wondering is this how loadbroswer lua code was meant to be implemented if you added it? //Lua_helper.add_callback(lua, "browserLoad", CoolUtil.browserLoad); //Will do this soon tho i uhm am really busy and idc about security // CoolUtil.browserLoad(site); // });
> > > > 
> > > > 
> > > > yes
> > > 
> > > 
> > > well im making psych engine epic edition i want to restore features and add some for mod creation who want them wanna help? rn im trying to restore the install and deletion buttons for the mod menu state!
> > 
> > 
> > how old are you
> 
> uhhh 10?

sus moment

**Comment by doggogit** [comment]
Hi, used this code for a mod I'm directing.

Everything worked as intended, credited you and put a link to this pull request.

(If you wish for your code to be removed, just contact me and I'll be more than happy to do so)

**Review by lunacynne — APPROVED** [review]
having lerp just be a global thing instead of having to define it in lua sounds pretty nice tbh
the section stuff is good too

**Review by mayo78 — APPROVED** [review]
pretty good changes

**Pull request closed without merging**
