### PR TITLE
Rewrite SScript Implementation

### PR DESCRIPTION
**Pull request by ghost**
This PR rewrites most of the SScript implementation.

- Ditched `doString`, HScript uses now `new` which is better optimized.
- Due to `doString` change, `runHaxeCode` can now use files. `getTextFromFile` is unnecessary.
- `runHaxeCode` now can return values without a function.
- Scripts now gets cleared from memory completely using `destroy()`.
- `global` is used to check for conflicting scripts.
- Rewrote `callOnHScript`, which fixes not being able to call the same function from multiple scripts.
- Replaced `interpName` with `origin` which is used for Lua traces.
- `addHaxeLibrary` now doesn't initialize Haxe scripts for its Lua script, so you can use it after or before `runHaxeCode`.

### CODE REVIEW

**Review by charlesisfeline — APPROVED** [review]
better

**Review by Rudyrue — CHANGES_REQUESTED** [review]
i think you looked over a line in playstate line 823

**Comment by TheWorldMachinima** [comment]
> i think you looked over a line in playstate line 823

There is nothing in line 823.

**Comment by Rudyrue** [comment]
image

?

**Comment by TheWorldMachinima** [comment]
> image
> 
> ?

Are you sure you're using my fork?

**Comment by Rudyrue** [comment]
that's odd it's not on your fork

ig it's just a problem on my end nvm
i fixed it anyways

**Review by Joalor64 — APPROVED** [review]

**Review by moxie-coder — APPROVED** [review]

**Review by ghost — APPROVED** [review]
bros cooking heat?

**Pull request closed without merging**
