### PR TITLE
Template.hx typo

### PR DESCRIPTION
**Pull request by KELOTOMU**
In Template.hx, the function `countdownTick()` with its parameter "countdown" uses a type of `BaseStage.Countdown` instead of "Countdown" which the base game stages use, making vscode think it's an error.

### CODE REVIEW

**Review by BombasticTomDev — CHANGES_REQUESTED** [review]
Pretty cool, however you could update params in `eventCalled`, since the Template file has them outdated

**Comment by KELOTOMU** [comment]
> Pretty cool, however you could update params in `eventCalled`, since the Template file has them outdated

what were the params that I need to edit/add?

**Comment by BombasticTomDev** [comment]
> > Pretty cool, however you could update params in `eventCalled`, since the Template file has them outdated
> 
> what were the params that I need to edit/add?

`flValue1:Null<Float>` and `flValue2:Null<Float>`

**Comment by KELOTOMU** [comment]
> > > Pretty cool, however you could update params in `eventCalled`, since the Template file has them outdated
> > 
> > 
> > what were the params that I need to edit/add?
> 
> `flValue1:Null<Float>` and `flValue2:Null<Float>`

Didn't do it, cause it already uses the flValue variables stored in triggerEvent function in PlayState.hx, doing this to prevent creating variables over and over again instead of just using one stored in triggerEvent.

**Pull request closed without merging**
