### PR TITLE
Audio Length Fix

### PR DESCRIPTION
**Pull request by Jaduplex**
Simply implementing the fixes mentioned in https://github.com/HaxeFlixel/flixel/issues/2899 here, since the lime .hx file that the fix is for is already mirrored here.

### CODE REVIEW

**Review by charlesisfeline — APPROVED** [review]
eh i'll give points anyway

**Comment by CaptainBaldi** [comment]
I believe this PR concept has been suggested before, but it wasn't merged due to Shadow Mario worrying about bugs.
Instead, I would look into making Pull Requests on these specific libraries to fix this issue internally, and maybe get more educated opinions on issues about it there.

**Review by DetectiveBaldi — APPROVED** [review]

**Comment by Raltyro** [comment]
Wait what did you exactly changed in Sound.hx

**Comment by TheLeerName** [comment]
ayo i already did this but pr was closed bruh

**Review by TheLeerName — APPROVED** [review]

**Comment by CyndaquilDAC** [comment]
> Wait what did you exactly changed in Sound.hx
The changes [here](https://github.com/openfl/openfl/pull/2667).

**Comment by ShadowMario** [comment]
Is this still needed? We are not overriding nearly as much flixel/lime files.

**Comment by CyndaquilDAC** [comment]
> Is this still needed? We are not overriding nearly as much flixel/lime files.

unless the formula has been changed to this, then no. if you aren't overriding the required files anymore then its not really necessary though, since its a flixel issue that hopefully theyll fix themselves. ill close this.

**Pull request closed without merging**
