### PR TITLE
Update hxCodec Libraries

### PR DESCRIPTION
**Pull request by crowplexus**
allows for videos on linux (disabled on purpose) and a handy skip button for them

### CODE REVIEW

**Comment by jigsaw-4277821** [comment]
Buggy height

**Comment by Stilic** [comment]
> Buggy height

don't care + ratio

**Comment by jigsaw-4277821** [comment]
> > Buggy height
> 
> don't care + ratio

You don't care about what will happen to sm if he push that, he will need to fix that himself and probably is better to let it like this

**Comment by Stilic** [comment]
> > > Buggy height
> > 
> > 
> > don't care + ratio
> 
> You don't care about what will happen to sm if he push that, he will need to fix that himself and probably is better to let it like this

just add black bars around original vid for simulate aspect ratio
or just change always ratio to 16:9 bruh

**Comment by BeastlyGhost** [comment]
linux is still broken but it's whatever I'm gonna see what is up with that

**Comment by Gibberditoslumber** [comment]
> linux is still broken but it's whatever I'm gonna see what is up with that

NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by Gibberditoslumber** [comment]
> linux is still broken but it's whatever I'm gonna see what is up with that

um new error:
```bashavereyconley@penguin:~/haxelib/FNF-PsychEngine/FNF-PsychEngine$ lime test windows
source/PlayState.hx:67: characters 8-24 : Type not found : vlc.VideoHandler
source/PlayState.hx:1483: characters 13-25 : Type not found : VideoHandler

**Comment by BeastlyGhost** [comment]
> > linux is still broken but it's whatever I'm gonna see what is up with that
> 
> um new error:
> 
> ```shell
> avereyconley@penguin:~/haxelib/FNF-PsychEngine/FNF-PsychEngine$ lime test linux
> source/PlayState.hx:67: characters 8-24 : Type not found : vlc.VideoHandler
> source/PlayState.hx:1483: characters 13-25 : Type not found : VideoHandler
> ```

install the library first
`haxelib git hxCodec https://github.com/polybiusproxy/hxCodec`

**Comment by BeastlyGhost** [comment]
also quick update: Linux is actually working, however playing videos with it *on psych engine* seems to not work at all

**Comment by Gibberditoslumber** [comment]
> > > linux is still broken but it's whatever I'm gonna see what is up with that
> > 
> > 
> > um new error:
> > ```shell
> > avereyconley@penguin:~/haxelib/FNF-PsychEngine/FNF-PsychEngine$ lime test linux
> > source/PlayState.hx:67: characters 8-24 : Type not found : vlc.VideoHandler
> > source/PlayState.hx:1483: characters 13-25 : Type not found : VideoHandler
> > ```
> 
> install the library first `haxelib git hxCodec https://github.com/polybiusproxy/hxCodec`

i did

**Comment by Stilic** [comment]
> > > linux is still broken but it's whatever I'm gonna see what is up with that
> > 
> > 
> > um new error:
> > ```shell
> > avereyconley@penguin:~/haxelib/FNF-PsychEngine/FNF-PsychEngine$ lime test linux
> > source/PlayState.hx:67: characters 8-24 : Type not found : vlc.VideoHandler
> > source/PlayState.hx:1483: characters 13-25 : Type not found : VideoHandler
> > ```
> 
> install the library first `haxelib git hxCodec https://github.com/polybiusproxy/hxCodec`

the best way to install is to do in a cmd `haxelib install hxCodec`, not by using the dev version from git.

**Comment by Stilic** [comment]
> > > > linux is still broken but it's whatever I'm gonna see what is up with that
> > > 
> > > 
> > > um new error:
> > > ```shell
> > > avereyconley@penguin:~/haxelib/FNF-PsychEngine/FNF-PsychEngine$ lime test linux
> > > source/PlayState.hx:67: characters 8-24 : Type not found : vlc.VideoHandler
> > > source/PlayState.hx:1483: characters 13-25 : Type not found : VideoHandler
> > > ```
> > 
> > 
> > install the library first `haxelib git hxCodec https://github.com/polybiusproxy/hxCodec`
> 
> i did

try this if it still don't work:
```
haxelib remove hxCodec
haxelib install hxCodec
```

**Comment by Mastercopper2346** [comment]
Yooooo it hit merged

**Pull request merged**
