### PR TITLE
Stop the errors that people are complaining about (If its still going on)

### PR DESCRIPTION
**Pull request by CrusherNotDrip**
You can use this for now until your actual code is done for ModsMenuState.hx so that way not many duplicates are in issues (I hope this works if it doesnt tell me the problem)

### CODE REVIEW

**Comment by CrusherMods** [comment]
I may of picked the wrong color sorry about that but you can fix it if you want

**Comment by Blockyyy** [comment]
It works!

**Comment by ChargerDoinDaCode** [comment]
Still isn't workin.

**Comment by DaBanana64** [comment]
The error has been fixed on the latest commit.

**Comment by CrusherMods** [comment]
> The error has been fixed on the latest commit.

It has??? alright im shutting it down

**Pull request closed without merging**
