### PR TITLE
Show loaded Songs counter and weeks counter both in freeplaymenu and storymenu

### PR DESCRIPTION
**Pull request by Raltyro**
image

### CODE REVIEW

**Review by rodney528 — APPROVED** [review]
It's kinda dumb but useful at the same time.

**Comment by Raltyro** [comment]
> It's kinda dumb but useful at the same time.

so true

**Review by Wither362 — APPROVED** [review]
It seems useful

**Review by TheKitBoi — APPROVED** [review]

**Review by EyeDaleHim — COMMENTED** [review]
would approve but I think freeplay one needs improvement

**Review by rodney528 — APPROVED** [review]

**Review by rodney528 — APPROVED** [review]

**Pull request closed without merging**
