### PR TITLE
Update MainMenuState.hx

### PR DESCRIPTION
**Pull request by EzraTheTigerFNF**

### CODE REVIEW

**Comment by TheKitBoi** [comment]
Why would you do that

**Comment by ShadowMilky** [comment]
imagine turning normal psych into an undertale fnf mod

yea that’s kinda terrible tbh

**Comment by CrusherNotDrip** [comment]
ew

**Comment by ShadowMario** [comment]
It's okay, this was an accidental PR, mistakes happen

**Pull request closed without merging**
