### PR TITLE
a way to see your keybinds when a song is paused

### PR DESCRIPTION
**Pull request by nahiassis**
you can see your keybinds in the pause menu with this

### CODE REVIEW

**Comment by perngjiafu** [comment]
code or sum shit idk

**Comment by nintendofan44** [comment]
yk this is a pr right?

**Comment by perngjiafu** [comment]
ye

**Comment by perngjiafu** [comment]
idk how to do it tbh

**Comment by ShadowMario** [comment]
...Or you could just have your 4-8 keys in mind. It isn't really that hard unless you suffer from short term memory.

**Comment by cfgexe** [comment]
make it an option

**Pull request closed without merging**
