### PR TITLE
pixel note splashes (UPDATED & IMPROVED)

### PR DESCRIPTION
**Pull request by HiroMizuki**
pixel note splashes are back (again)

now, moved to preload/pixelUI due to some organization and update at the original main repo
and improved colors & pixel size to fit with the notes (a little orange for right and a little more pink for hurt splashes)
enjoy

https://user-images.githubusercontent.com/72695242/145059415-60353942-926d-4036-86d6-506dbb0b7fe8.mp4

### CODE REVIEW

**Comment by Stilic** [comment]
Please merge this, because it is just a need for some people. Also, others engines have already this.

**Review by FuseIsHere813 — APPROVED** [review]

**Comment by tposejank** [comment]
ok ngl they look way too smooth
they should be slower like
### lower framerate.

**Comment by HiroMizuki** [comment]
> ok ngl they look way too smooth they should be slower like
> 
> ### lower framerate.

lmao

**Comment by HiroMizuki** [comment]
added lower framerate and improved some little coding thingies

**Comment by HiroMizuki** [comment]
> added lower framerate and improved some little coding thingies

and added an automatic thing to select the current pixelated splash skin for a song

**Comment by HiroMizuki** [comment]
yep, crash fixed

**Comment by AnkenyJ2** [comment]
HOW DO I DOWNLOAD???????

**Comment by HiroMizuki** [comment]
> HOW DO I DOWNLOAD???????

replace the codes correctly, download the images and place em at the correct folders and then copy and paste the original xmls, but change the names and the image path

**Comment by antoSKRLOL** [comment]
pixel note splash fla???

**Review by PSYCHOVICH229 — APPROVED** [review]

**Pull request closed without merging**
