### PR TITLE
Enhanced Charting

### PR DESCRIPTION
**Pull request by NS-Unfair**
# Summary
Enhanced charting to have the ability to click and drag to add / delete notes. Added convenience key binding (Tab-C) to make placing multiple notes on top of each other easier. Added single key binding for Tab key to allow the adding of a single stacked note (one per click). In addition, Shift-Tab-C will allow for the drag spamming of stacked notes.

# New Features
- [x] Added support for click and dragging to delete or add. Note: when adding notes, it will not put them on top of each other, but instead have them start immediately following the previously placed note.
- [x] Tab-Click will allow the stacking of notes on top of each other.
- [x] Tab-C will enable auto clicking for note stacking. 
- [x] Shift-Tab-C will enable drag spamming of stacked notes. 

# Why I suggest these changes
When making troll mods or high difficulty mods, you sometimes want to stack notes, have notes come exactly one after another, or just make an impossible song as a joke. The Click and drag, Shift-Tab-C, and the Tab key bindings make this an easier effort to do.

# How changes were implemented
I updated ChartingState.hx to support the new features.

### CODE REVIEW

**Comment by NS-Unfair** [comment]
Note, sorry for all the pull requests. This is my very first time making pull requests, and it took me a while to figure out how to do in a way that my changes could be evaluated and accepted easily.

**Comment by prokube** [comment]
DUDE IMAGINE GETTING `good first pull request`ED

**Comment by NS-Unfair** [comment]
I have fixed the stuff. I can't test the code until you guys do your part

**Comment by NS-Unfair** [comment]
@ShadowMario resolved merge conflicts from latest Main changes.

**Comment by brosomethingwrongwithyothing** [comment]
Might need to update for 5.0 when it releases.

**Comment by acap09** [comment]
> Might need to update for 5.0 when it releases.

*clears throat* 0.5

**Comment by MilkyTheMilkBlob** [comment]
image
fix pls

**Pull request closed without merging**
