### PR TITLE
Re-use popupScore sprites instead of constantly destroying and re-adding.

### PR DESCRIPTION
**Pull request by MeguminBOT**
Should improve overall performance of the game, less likely to cause frame stuttering, since the game doesn't constantly have to remove and add the sprites everytime a note is hit. 

There may be a better method to do this and in that case I'm all ears, but this is atleast better than the current way the sprites are handled.

### CODE REVIEW

**Review by moxie-coder — APPROVED** [review]

**Review by ghost — APPROVED** [review]
not bad. just good

**Comment by MemeHovy** [comment]
> not bad. just good

true

**Comment by NeeEoo** [comment]
This wouldnt work since the groups doesnt remember the content the next time you hit a note, you would need to make the groups outside of the function (such as in a field) or in create.

**Comment by MemeHovy** [comment]
> This wouldnt work since the groups doesnt remember the content the next time you hit a note, you would need to make the groups outside of the function (such as in a field) or in create.

hmm, I have to agree with him here, what could be done is saving the content in another group or something

**Comment by BeastlyGhost** [comment]
the group needs a way to know which sprite comes first by sorting the groups with a value that represents the songPosition, e.g:

```hx
class ComboSprite extends FlxSprite {
	public var depth:Float = 0;
	public static inline function sortByDepth(i:Int, a:ComboSprite, b:ComboSprite):Int
		return a.depth > b.depth ? -i : i;
}

// then when creating the sprite, set the depth of the sprite to the song position, like this
rating.depth = -Conductor.songPosition;
```

**Review by rodney528 — APPROVED** [review]

**Comment by ShadowMario** [comment]
Draft has not been updated since December 2023, closing this

**Pull request closed without merging**
