### PR TITLE
Add FreeDesktop metadata for Linux desktop systems

### PR DESCRIPTION
**Pull request by fpiesche**
These are standard support files for Linux desktop applications, following the FreeDesktop standard:

- a `.desktop` file which will work as a launcher for Linux desktops. If this is copied to the correct path, Linux systems will add an icon for PsychEngine to their app launcher menus.
- a version of the icon resized to 512x512, a standard size recommended by the FreeDesktop foundation.
- a file with metadata about PsychEngine that can be displayed to users in package catalogs.

These would generally be useful to anyone wanting to make a packaged, "installable" distribution of PsychEngine, e.g. Linux system distributors. The initial use case would be the [Flatpak distribution](https://github.com/ShadowMario/FNF-PsychEngine/issues/14209) I've put together.

### CODE REVIEW

**Review by ACoolioDude — APPROVED** [review]

**Comment by Stefan2008Git** [comment]
O, it's officially merged, no way

**Comment by Stefan2008Git** [comment]
> O, it's officially merged, no way

image
@fpiesche It's showing on Pop!_OS store, but i don't know it's showing on UbuntuSoftware store

**Comment by fpiesche** [comment]
it's showing on KDE Discover too:
Screenshot_20240316_124045

On Ubuntu apparently there's a separate plugin needed since 20.04, because Ubuntu are trying to push their own Flatpak alternative (snap) instead: https://flathub.org/setup/Ubuntu

**Comment by Stefan2008Git** [comment]
> it's showing on KDE Discover too: Screenshot_20240316_124045
> 
> On Ubuntu apparently there's a separate plugin needed since 20.04, because Ubuntu are trying to push their own Flatpak alternative (snap) instead: https://flathub.org/setup/Ubuntu
> 
> Ubuntu's insistence on pushing snap over not just Flatpak but even their own system packages is a major cause of anger in their user community at the moment, to the point where several Ubuntu-based distributions (eg. Mint or Vanilla) have been working on switching from Ubuntu as their base system to Debian (which Ubuntu itself is based on).

Interesting

**Pull request merged**
