### PR TITLE
include classes which not used in game

### PR DESCRIPTION
**Pull request by TheLeerName**
hscript: 📈

for example u cant `addHaxeLibrary('FlxGlitchEffect', 'flixel.addons.effects.chainable')` if source code not used this class

### CODE REVIEW

**Comment by MemeHovy** [comment]
couldn't you just add them here instead?
Untitled50

**Comment by CaptainBaldi** [comment]
> couldn't you just add them here instead? Untitled50

considering theres probably hundreds of libraries Psych Engine doesn't use its probably more efficient to do this :shrug:

**Comment by MemeHovy** [comment]
I mean, all the macro does as far as I know is just import classes in a more sophisticated way, that hscript I think can use?
but this doesn't seem as far fletched as just adding them into the interpreter

**Comment by TheLeerName** [comment]
for example u cant import FlxBackdrop if source code not used this class

**Comment by MemeHovy** [comment]
> for example u cant `addHaxeLibrary('FlxGlitchEffect', 'flixel.addons.effects.chainable')` if source code not used this class

okay but like, why not just add them to the interpreter? It’d likely be the same thing as what you did

**Comment by TheLeerName** [comment]
> okay but like, why not just add them to the interpreter if you did use source? It’d likely be the same thing as what you did

bro like its hundreds of lines, and some classes can have same name but other package

**Comment by MemeHovy** [comment]
> > okay but like, why not just add them to the interpreter if you did use source? It’d likely be the same thing as what you did
> 
> bro like its hundreds of lines, and some classes can have same name but other package

hmm, I cannot argue with that

**Review by moxie-coder — APPROVED** [review]

**Comment by TheLeerName** [comment]
#12848

**Pull request closed without merging**
