### PR TITLE
Fix GPU Cache and Iteration on Experimental Branch LoadingState.hx

### PR DESCRIPTION
**Pull request by Raltyro**
Self-explanatory

### CODE REVIEW

**Comment by Raltyro** [comment]
image
huh, this is completely unrelated to the pr

**Comment by Raltyro** [comment]
[Video](https://cdn.discordapp.com/attachments/978032775913422859/1202647572041437286/2024-02-01_23-10-24.mp4)

**Review by ghost — APPROVED** [review]
fire

**Comment by Raltyro** [comment]
Hard Reset the commits to the latest commits of experimental branch to avoid clutterness of the commits

**Comment by Raltyro** [comment]
Fixes the iteration and make it actually loads voices, also uses mutex just incase

**Pull request merged**
