### PR TITLE
Add "Gameplay Settings in General" option

### PR DESCRIPTION
**Pull request by MisterRafers**
So, now if you turn any of gameplay settings in freeplay, they will work in story mode too. This option allows to control it.

### CODE REVIEW

**Comment by jmxamongusmodder** [comment]
seems cool i aint gonna use it but its cool!

**Comment by jmxamongusmodder** [comment]
wait it might interfer because your 2 commits behind??

**Comment by MrClogsworthYT** [comment]
> wait it might interfer because your 2 commits behind??

nope he/she isnt editing the files that the 2 commits edit

**Comment by Theoyeah** [comment]
SORRY, but you can alredy do that

**Comment by ShadowMario** [comment]
Broke

**Pull request closed without merging**
