### PR TITLE
URL loading for Psych

### PR DESCRIPTION
**Pull request by volved2**
Made this alternative because our current hscript support doesn't allow `haxe.Http#request();`

**Usage:**
- for loading an image, do: `var spr:FlxSprite = Paths.loadGraphicFromURL(url:String);`. This WILL override a sprites properties, as this returns a brand new FlxSprite with the loaded image.
- for loading a Sparrow spritesheet, do: `spr.frames = Paths.loadSparrowAtlasFromURL(xmlUrl:String, imageUrl:String);`. This will return the Sparrow Atlas frames, ready with the image.
- for loading a files text data off the web, do: `var str:String = Paths.loadFileFromURL(url:String);`. This will return a string of the text data found from the url.

I have also added the possibility to load lua scripts straight from strings rather than files, this allows people to load a lua script straight from the web using `Paths.loadFileFromURL();`

### CODE REVIEW

**Review by TheKitBoi — APPROVED** [review]

**Review by Raltyro — APPROVED** [review]

**Comment by Raltyro** [comment]
what da dog doin
image

**Comment by volved2** [comment]
> what da dog doin image

if i didn't do that i wouldn't be able to load the fuckin scripts from the web now could i?

**Review by rodney528 — APPROVED** [review]

**Review by Starveldt — COMMENTED** [review]
kinda dope, but can you list off a few use cases for this? i don't really see it being used much aside from like storing data in a db

**Comment by Raltyro** [comment]
> > what da dog doin image
> 
> if i didn't do that i wouldn't be able to load the fuckin scripts from the web now could i?

yeah i just saw lmao i didnt fully read the pr yet when i was posting this comment

**Comment by volved2** [comment]
> kinda dope, but can you list off a few use cases for this? i don't really see it being used much aside from like storing data in a db

well the obvious saving disk space in a mod folder, or using image data such as height for something like the Pokemon Mystery Gifts and other timed events, also allows people to updates sprites *and* code for their mods.

**Review by Starveldt — APPROVED** [review]

**Review by GO-Miles — APPROVED** [review]

**Pull request closed without merging**
