### PR TITLE
make input functions automatically make input names uppercase

### PR DESCRIPTION
**Pull request by libauror-a**
self explanatory

### CODE REVIEW

**Review by moxie-coder — COMMENTED** [review]
how much of a difference does this make tho?

**Review by ghost — COMMENTED** [review]
I don't think adding uppercase changes smth

**Review by ghost — APPROVED** [review]
or actually it's looks good mb

**Review by moxie-coder — APPROVED** [review]
mkay

**Review by charlesisfeline — APPROVED** [review]
yes

**Review by Sword352 — APPROVED** [review]

**Review by rodney528 — APPROVED** [review]

**Pull request closed without merging**
