### PR TITLE
Legacy Chart Support (0.5.2h and prior, other engines)

### PR DESCRIPTION
**Pull request by crowplexus**
this change re-adds `lengthInSteps` in order to make legacy charts (0.5.2h and before, including alternative engines) work properly, exports both values `sectionBeats` and `lengthInSteps` upon saving the json file

### CODE REVIEW

**Review by MemeHoovy — APPROVED** [review]

**Review by TheKitBoi — APPROVED** [review]

**Review by ManMaster707 — APPROVED** [review]

**Comment by RedstoneRuler** [comment]
Wow, this is so cool, can't wait for it to not be merged for some arbitrary reason!!

**Review by RedstoneRuler — APPROVED** [review]

**Review by LEVIXDDLMAO — APPROVED** [review]

**Review by Gostar64 — APPROVED** [review]

**Review by aaaproooo — APPROVED** [review]

**Review by rodney528 — APPROVED** [review]
:D

**Review by Raltyro — APPROVED** [review]

**Review by SillyVyxia — APPROVED** [review]
awesome

**Review by Joalor64 — APPROVED** [review]

**Review by TehPuertoRicanSpartan — APPROVED** [review]

**Review by charlesisfeline — APPROVED** [review]

**Comment by Luisinhi010** [comment]
ur fucking chad

**Pull request closed without merging**
