### PR TITLE
Update MainMenuState.hx

### PR DESCRIPTION
**Pull request by NimuFurrySoftUwU**

### CODE REVIEW

**Comment by BeastlyGhost** [comment]
why would you even do that in the first place? this is the base engine

**Comment by BoloVEVO** [comment]
When you don't know how to clone a repository and mod directly the base engine instead. *Fatherless face*

**Comment by BeastlyGhost** [comment]
> When you don't know how to clone a repository and mod directly the base engine instead. _Fatherless face_

:skull:

**Comment by SrtHero278** [comment]
This is a dumb thing.
There's no reason to have a mods menu if there's no mods.

**Pull request closed without merging**
