### PR TITLE
Add softcoded achievements and update SScript to 5.2.0

### PR DESCRIPTION
**Pull request by ghost**
Added softcoded achievements, supports both SScript and PsychLua, added example in modTemplate zip.
Currently undocumented

### CODE REVIEW

**Review by ghost — APPROVED** [review]
sick

**Comment by benok99** [comment]
Isn't it scrapped and was already done but got removed????

**Review by moxie-coder — APPROVED** [review]
awesome

**Review by Joalor64 — APPROVED** [review]

**Review by NexIsDumb — APPROVED** [review]

**Review by TheLeerName — APPROVED** [review]

**Comment by NexIsDumb** [comment]
wtf

**Pull request closed without merging**
