### PR TITLE
rewrite of HScript.hx (fix of runHaxeCode and etc)

### LINKED ISSUE #13012: RunHaxeCode can only run once
### Describe your bug here.

Trying to run more than 1 `runHaxeCode` in a lua file, will not work past 0.6.3 versions.
This is because 0.6.3 initialized HScript and then ran the code, while the newer versions initialize HScript and run the code in the same function. Normally this wouldn't be a problem if the function didn't look like this:
`	public static function initHaxeModuleCode(parent:FunkinLua, code:String)`
`	{`
`		#if (SScript >= "3.0.0")`
`		if(parent.hscript == null)`
`		{`
`			trace('initializing haxe interp for: ${parent.scriptName}');`
`			parent.hscript = new HScript(parent, code);`
`		}`
`		#end`
`	}`
because once it runs `parent.hscript` isn't `null` anymore and then the code will never be able to be ran using `runHaxeCode` in LUA.

### Command Prompt/Terminal logs (if existing)

_No response_

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

### PR DESCRIPTION
**Pull request by TheLeerName**
code in runHaxeCode runs only if you did it one time, if call it again, it ignores code, this pr fixes that problem
resolves #13012, #12954
u need use `public var examplevar = 0;` to use `examplevar` in another calls of runHaxeCode tho

- **addHaxeLibrary can add enums now**
- **rewrited some error messages**

1. for example (new):
```
ERROR ON LOADING - mods/scripts/sdf.hx:2: Unknown variable: pig
ERROR (onCreate) - mods/scripts/sdf.hx:2: Unknown variable: pig
```
2. also "initialized sscript interp successfully" now traces even if onCreate function doesnt exist
3. also error messages from hscript now traces to console

- **rewrited some code in HScript.hx (optimization?!??!?)**
- **added new coolie feature for 2nd argument of runHaxeCode**
1. for example (new feature):
```lua
runHaxeCode("debugPrint(songPercent);", {'game'})
```
2. the same as:
```lua
runHaxeCode("debugPrint(game.songPercent);")
```

### CODE REVIEW

**Review by moxie-coder — APPROVED** [review]

**Comment by TheLeerName** [comment]
fuck you workflows never used you

**Comment by mcagabe19** [comment]
@MemeHovy think two time before approving pls

**Comment by TheLeerName** [comment]
so, we need to wait new update of rewritten classes
u can merge this, but scripts with classes just will not work as earlier (scripts without classes will work tho)

**Review by ghost — APPROVED** [review]
tested works fine

**Comment by MemeHovy** [comment]
> @MemeHovy think two times before approving pls

alright

**Review by rodney528 — APPROVED** [review]

**Review by Meloomazy — APPROVED** [review]

**Review by rodney528 — APPROVED** [review]

**Review by ghost — CHANGES_REQUESTED** [review]
can't you just add ``#if (SScript < "5.0.0")``? fully removing class support is pointless

**Comment by mcagabe19** [comment]
> > can't you just add `#if (SScript < "5.0.0")`? fully removing class support is pointless
> 
> class support doesnt work in 5.0.x and older so

I still use class support in my repo and works great at older version of SScripts

**Comment by TheLeerName** [comment]
i can but everyone uses newest versions of libs, so its will be kinda useless

**Comment by RodneyAnImaginativePerson** [comment]
> i can but everyone uses newest versions of libs, so its will be kinda useless

How so?

**Comment by TheLeerName** [comment]
now it useless cuz SScript is not exists
#13304

**Pull request closed without merging**
