### PR TITLE
MP3 and WAV support.

### PR DESCRIPTION
**Pull request by Joalor64**
Now you can use the .mp3 and .wav file formats for your instrumentals and voices for your songs.
That's all I need to say.

### CODE REVIEW

**Review by charlesisfeline — APPROVED** [review]
pretty useful for those who struggles to convert their songs to ogg files

**Comment by TheRealJake12** [comment]
> pretty useful for those who struggles to convert their songs to ogg files

why would they struggle?? Just get audacity or smth and convert it like that

**Comment by MilkyTheMilkBlob** [comment]
> > pretty useful for those who struggles to convert their songs to ogg files
> 
> why would they struggle?? Just get audacity or smth and convert it like that

ik

**Comment by MilkyTheMilkBlob** [comment]
> > > pretty useful for those who struggles to convert their songs to ogg files
> > 
> > 
> > why would they struggle?? Just get audacity or smth and convert it like that
> 
> ik

i do have audacity so...

**Comment by WeldedFlap** [comment]
> > pretty useful for those who struggles to convert their songs to ogg files
> 
> why would they struggle?? Just get audacity or smth and convert it like that

some people don't have space on their pc or something is preventing them from converting.

**Comment by frantastic24** [comment]
You can convert with an online tool
Stuff like this just bloats the engine and only benefits lazy asses

**Pull request closed without merging**
