### PR TITLE
Mac (Currently Testing)

### PR DESCRIPTION
**Pull request by Gibberditoslumber**

### CODE REVIEW

**Comment by TheKitBoi** [comment]
What’s the point of this

**Comment by Raltyro** [comment]
wot

**Comment by trayfellow** [comment]
dont, the haxelib version also isnt updated yet

**Comment by Gibberditoslumber** [comment]
https://github.com/polybiusproxy/hxCodec/tree/main/include/Mac/lib
this

**Comment by TheKitBoi** [comment]
> https://github.com/polybiusproxy/hxCodec/tree/main/include/Mac/lib this

image

image

Mate you need to think more carefully cus the haxelib install version was not updated

**Comment by Gibberditoslumber** [comment]
O H

**Pull request closed without merging**
