### PR TITLE
Fix the issue about multiple scripts not being able to use the same variables

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by rodney528 — APPROVED** [review]

**Review by MemeHoovy — APPROVED** [review]

**Review by iym1337 — APPROVED** [review]

**Review by TheKitBoi — APPROVED** [review]

**Review by ManMaster707 — APPROVED** [review]

**Comment by TheKitBoi** [comment]
why did u close this

**Comment by ImaginationSuperHero528** [comment]
@TheWorldMachine why did you close this?

**Comment by TheWorldMachine** [comment]
> @TheWorldMachine why did you close this?

> why did u close this

This was useless.

**Comment by TheWorldMachine** [comment]
> @TheWorldMachine why did you close this?



> why did u close this

This was useless.

**Pull request closed without merging**
