### PR TITLE
Input System V3.5 - "Improved Ghost Note Detection"

### PR DESCRIPTION
**Pull request by crowplexus**
old detection method worked nicely but was very prone to errors in charts that have a ton of ghost notes, now inputs do a single thing while ghost notes get deleted when loading the chart in the first place

### CODE REVIEW

**Comment by crowplexus** [comment]
this will be a draft until it's fully tested

**Review by system32unknown — APPROVED** [review]

**Comment by crowplexus** [comment]
last commit was made so if this ever gets merged, it doesn't break any mods that use that preference

**Comment by crowplexus** [comment]
fixed the conflicts already, i'm just testing to see if nothing broke

**Comment by crowplexus** [comment]
> > fixed the conflicts already, i'm just testing to see if nothing broke
> 
> image

i fixed on my end, i have yet to push the commit

**Comment by crowplexus** [comment]
my branch fucked up big time hold on

**Pull request closed without merging**
