### PR TITLE
Crucial Updates

### PR DESCRIPTION
**Pull request by chronicsilly**

### CODE REVIEW

**Comment by CrusherNotDrip** [comment]
Im pretty sure thats alr fixed int he experimental branch

**Comment by usb-port-2** [comment]
> Im pretty sure thats alr fixed int he experimental branch

Ok but it isnt in the main branch so you sshould fix it

**Comment by LarryFrosty** [comment]
> Ok but it isnt in the main branch so you sshould fix it

the experimental branch will get merged to main...

**Comment by Stilic** [comment]
> engine ruined

you're annoying ngl

**Comment by usb-port-2** [comment]
> > engine ruined
> 
> you're annoying ngl

Genuinely what the fuck is your problem dude 😭
Every time I've talked to you you've bitched about one thing or another and now you're going to weeks old prs just to insult me

Go outside or something, please

**Pull request closed without merging**
