### PR TITLE
Custom options for Lua + made it able to compile without mods enabled.

### PR DESCRIPTION
**Pull request by raf13lol**
This does work, I tested it.
This can allow Lua developers to be more creative and also think of some players who might not want their custom addition to the engine, as well as simplifying it if you are an experienced Lua developer and know how to read and write files which give soft-modded Psych Engine custom options (without this pull request).  

How it works:

Set a custom option with 
```lua
setCustomOption(optionName:String, value:Dynamic)
```
and get a custom option with
```lua
getCustomOption(optionName:String)
```
Note: if the option doesn't exist, trying to get it will return a string of "null".

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Approved + Nice formatting

**Comment by RafPlayz69YT** [comment]
> Approved + Nice formatting

Thanks!

**Review by TheKitBoi — APPROVED** [review]

**Comment by MilkyTheMilkBlob** [comment]
image
fix this pls

**Comment by RafPlayz69YT** [comment]
too hard :sob:

**Comment by Lokitot** [comment]
that's a LOT of code

**Pull request closed without merging**
