### PR TITLE
showCombo is broken :skull:

### PR DESCRIPTION
**Pull request by swordcube**

### CODE REVIEW

**Comment by swordcube** [comment]
showCombo hides comboSpr, which literally never gets used

shouldn't it be hiding numScore?? lmao

**Comment by MasterDirector99** [comment]
@ShadowMario
You better merge this pull request

**Review by ZAngryCadet — APPROVED** [review]

**Comment by swordcube** [comment]
literally the first time i've made a pr on something that's used by people

and it's literally one line of code

**Review by MasterDirector99 — APPROVED** [review]

**Review by ghost — APPROVED** [review]
I don't think anybody ever notices this, but they will once this pr get's acccepted.

**Review by lunacynne — APPROVED** [review]

**Comment by BeastlyGhost** [comment]
> showCombo hides comboSpr, which literally never gets used
> 
> shouldn't it be hiding numScore?? lmao

talked about this with him on a voice call, he said it wasn't supposed to hide numScore

**Review by crowplexus — APPROVED** [review]
despite what he said, I will approve this, it's not a bad PR

also gonna test both changes to see if there's anything different with those

**Comment by swordcube** [comment]
> despite what he said, I will approve this, it's not a bad PR

i changed numScore to hide via showRating

**Comment by BeastlyGhost** [comment]
> > despite what he said, I will approve this, it's not a bad PR
> 
> i changed numScore to hide via showRating

sounds good, I think it should be like that since that combo sprite never gets used

**Review by JorosTheModderPH — APPROVED** [review]

**Review by TheKitBoi — APPROVED** [review]

**Review by jayrattt — APPROVED** [review]

**Comment by ShadowMario** [comment]
got fixed

**Pull request closed without merging**
