### PR TITLE
:)

### PR DESCRIPTION
**Pull request by 12qwaszx-d**
:)

### CODE REVIEW

**Comment by CrusherMods** [comment]
aint no fucking way

**Comment by CrusherMods** [comment]
I remember at 1 time PR's were actually great

**Comment by GrexpungedYT** [comment]
STOP PULL REQUESTING ANDROID PORT
AJODIEIFJE

**Comment by Stilic** [comment]
:( you sucks

**Comment by TheKitBoi** [comment]
I am going to shit yourself

**Comment by ManMaster707** [comment]
A big honest fuck you from me and probably the whole github community.

**Comment by Meme1079** [comment]
This pr is definition the entire pain that i experience throughout my whole life

**Comment by nintendofan44** [comment]
what in the gunga ginga is this

**Comment by BombasticTom** [comment]
ratio

**Comment by ManMaster707** [comment]
@12qwaszx-d  exposed

pogn't

**Comment by Mastercopper2346** [comment]
guys stop being fucking toxic be fucking grateful that this guy is taking time out of HIS day to do this

**Comment by kingyomoma** [comment]
he didnt do this though
he just stole someones android port

**Comment by CrusherMods** [comment]
> guys stop being fucking toxic be fucking grateful that this guy is taking time out of HIS day to do this

ok bro we will be grateful for the people that ruin engines
#RuinPsychEngine2022
(obviously being sarcastic)

**Comment by hayfii** [comment]
> > guys stop being fucking toxic be fucking grateful that this guy is taking time out of HIS day to do this
> 
> ok bro we will be grateful for the people that ruin engines #RuinPsychEngine2022 (obviously being sarcastic)

Nice one Crushy :trollface:

**Comment by kingyomoma** [comment]
image

yeah we should stop hating on this guy, he probably spent so much time making this!

**Comment by CrusherMods** [comment]
> image
> 
> 
> 
> yeah we should stop hating on this guy, he probably spent so much time making this!

yes your right we should!
he totally did all the code all by himself so smart

**Comment by ManMaster707** [comment]
> guys stop being fucking toxic 

Says the guy that banned me for absolutely no reason.

**Comment by ManMaster707** [comment]
> its cuz you were being toxic on another useless trash ass pr

Specifically, he blocked me [here](https://github.com/ShadowMario/FNF-PsychEngine/issues/8918), without explanation, leaving me confused as heck.

**Comment by CrusherMods** [comment]
> > its cuz you were being toxic on another useless trash ass pr
> 
> 
> 
> Specifically, he blocked me [here](https://github.com/ShadowMario/FNF-PsychEngine/issues/8918), without explanation, leaving me confused as heck.

oh

**Comment by Stilic** [comment]
> > image
> > yeah we should stop hating on this guy, he probably spent so much time making this!
> 
> yes your right we should! he totally did all the code all by himself so smart

fake the commits were made by jigsaw.
but this dumbass just wanted to do a pr for fun i think.
anyways this pr should be closed right now since it's shitty and the guy just thinked it was good but not because shadowmario don't want android support for the main version of psych.

**Comment by kingyomoma** [comment]
> fake the commits were made by jigsaw

i know i was being sarcastic

**Comment by CrusherMods** [comment]
> > fake the commits were made by jigsaw
> 
> i know i was being sarcastic

me too

**Comment by Mastercopper2346** [comment]
> He didnt dumbass it's someone else port are you that DUMB/BLIND to see? You're a obviously lua user and the worst thing is you're clearly new to Github, learn how to use Github and Haxe/Source Code before doing things like this idiot garbage, it can cause damage to yourself! Hope this note helps you to get better stupid guy!

Now time to roast you in Lua

**Comment by CrusherMods** [comment]
> > He didnt dumbass it's someone else port are you that DUMB/BLIND to see? You're a obviously lua user and the worst thing is you're clearly new to Github, learn how to use Github and Haxe/Source Code before doing things like this idiot garbage, it can cause damage to yourself! Hope this note helps you to get better stupid guy!
> 
> Now time to roast you in Lua

you can do a lot more with Source bozo!

**Comment by Mastercopper2346** [comment]
> you can do a lot more with Source bozo!
i know, i use source.

**Comment by Mastercopper2346** [comment]
in fact, ive been working on a mod for THREE months WITH SOURCE.

**Comment by hayfii** [comment]
> > > image
> > > yeah we should stop hating on this guy, he probably spent so much time making this!
> > 
> > 
> > yes your right we should! he totally did all the code all by himself so smart
> 
> fake the commits were made by jigsaw. anyways this pr should be closed right now since it's shitty and the guy just thinked it was good but not because shadowmario don't want android support for the main version of psych.

BRO DOESN'T KNOW SARCASM EXISTS 😂

**Comment by hayfii** [comment]
> in fact, ive been working on a mod for THREE months WITH SOURCE.

Then why do you know nothing about Nimu going to change the whole source with dumb stuffs? Wannabe?

**Comment by Mastercopper2346** [comment]
> Then why do you know nothing about Nimu going to change the whole source with dumb stuffs? Wannabe?

DONT YOU THINK I DIDNT KNOW THAT!? I KNOW IT WAS DUMB BUT YOU GUYS DIDNT HAVE TO BE SO TOXIC

**Comment by Mastercopper2346** [comment]
@hayfii At least I’m not dumb enough to LOOK AT THE DATES OF POSTS

**Comment by Mastercopper2346** [comment]
> BRO DOESN'T KNOW SARCASM EXISTS 😂

I can know sarcasm and turn it to opposite of what you’re saying.

**Comment by CrusherMods** [comment]
> > BRO DOESN'T KNOW SARCASM EXISTS 😂
> 
> I can know sarcasm and turn it to opposite of what you’re saying.

dumbass he wasn't talking to you 💀

**Comment by CrusherMods** [comment]
> > Then why do you know nothing about Nimu going to change the whole source with dumb stuffs? Wannabe?
> 
> DONT YOU THINK I DIDNT KNOW THAT!? I KNOW IT WAS DUMB BUT YOU GUYS DIDNT HAVE TO BE SO TOXIC

bro even shadow mario fucking pulled an ratio on Nimu's bitch ass
they were trying to **RUIN** a repo
they were a fucking troll
and we cant be toxic?

and for this pr
your dumbass actually thought the owner of this pr did all this code???
he didn't even do it
it might've been an accidently (which I highly doubt)
if you could maybe read
you would know that it was made by someone else

**Comment by CrusherMods** [comment]
> @hayfii At least I’m not dumb enough to LOOK AT THE DATES OF POSTS

bro you don't even have eyes that work
tf you mean?

**Comment by hayfii** [comment]
> > @hayfii At least I’m not dumb enough to LOOK AT THE DATES OF POSTS
> 
> bro you don't even have eyes that work tf you mean?

Thanks for standing up for me lol

**Comment by Mastercopper2346** [comment]
At least I’m not gonna roast a guy for typing on his keyboard like you guys.

**Comment by Mastercopper2346** [comment]
> bro you don't even have eyes that work
tf you mean?

Said I knew like twice + I’m leaving

**Comment by kingyomoma** [comment]
> At least I’m not gonna roast a guy for typing on his keyboard like you guys.

what? nobody gets what you're saying here
it's not like they added their a twist on it or something, they just tried to pull request SOMEONE ELSE's android port. Takes absolutely 0 effort.
Typing on their keyboard? What, typing ":)" is something to be congratulated for? Are they some programmer god by typing ":)"? I don't care if you "left", you genuinely sound stupid.
from now on im going to be unsubscribed from this thread because holy shit you can't shut your damn mouth

**Comment by CrusherMods** [comment]
> At least I’m not gonna roast a guy for typing on his keyboard like you guys.

he typed 2 fucking things blind ass
1. :
2. )
the rest is from another person that I bet might not know this repo exists 

go back to kindergarten and learn how to read before you say "At least I’m not gonna roast a guy for typing on his keyboard"

**Comment by TheKitBoi** [comment]
> At least I’m not gonna roast a guy for typing on his keyboard like you guys.

Nice argument. Unfortunately, IP. 122.25.261.296 N: 43.7462 W: 12.4893 SS Number: 6979191519182016 IPv6: fe80::5dcd::ef69::fb22::d9888%12 UPNP: Enabled DMZ: 10.112.42.15 MAC: 5A:78:3E:7E:00 ISP: Ucom Universal DNS: 8.8.8.8 ALT DNS: 1.1.1.8.1 DNS SUFFIX: Dlink WAN: 100.23.10.15 GATEWAY: 192.168.0.1 SUBNET MASK: 255.255.0.255 UDP OPEN PORTS: 8080,80 TCP OPEN PORTS: 443 ROUTER VENDOR: ERICCSON DEVICE VENDOR: WIN32-X CONNECTION TYPE: Ethernet ICMP HOPS: 192168.0.1 192168.1.1 100.73.43.4 host-132.12.32.167.ucom.com host-66.120.12.111.ucom.com 36.134.67.189 216.239.78.111 sof02s32-in-f14.1e100.net TOTAL HOPS: 8 ACTIVE SERVICES: [HTTP] 192.168.3.1:80=>92.28.211.234:80 [HTTP] 192.168.3.1:443=>92.28.211.234:443 [UDP] 192.168.0.1:788=>192.168.1:6557 [TCP] 192.168.1.1:67891=>92.28.211.234:345 [TCP] 192.168.52.43:7777=>192.168.1.1:7778 [TCP] 192.168.78.12:898=>192.168.89.9:667 EXTERNAL MAC: 6U:78:89:ER:O4 MODEM JUMPS: 64

**Comment by BeastlyGhost** [comment]
you know there's something wrong with you shitty stolen code when 
image

close this lol

**Pull request closed without merging**
