### PR TITLE
Update the "Toaster Gamer" Achievement to need the shaders to be disabled

### PR DESCRIPTION
**Pull request by Fridox-lol**

### CODE REVIEW

**Review by Intancote — APPROVED** [review]
Surprised that this wasn't done already

**Review by CrusherNotDrip — CHANGES_REQUESTED** [review]
why tf is there another 
```haxe
*/
```
???

**Review by CrusherNotDrip — APPROVED** [review]

**Review by Raltyro — APPROVED** [review]
no shaders :sob:

**Review by Starveldt — APPROVED** [review]
the shit fart ass computer

**Review by TheKitBoi — APPROVED** [review]

**Review by Parsellol — APPROVED** [review]

**Review by MemeHoovy — APPROVED** [review]

**Review by rodney528 — APPROVED** [review]

**Review by br4dnblehh — COMMENTED** [review]
Shit computers only lol

**Review by br4dnblehh — APPROVED** [review]

**Pull request closed without merging**
