### PR TITLE
Main Menu Customization via JSON

### PR DESCRIPTION
**Pull request by crowplexus**
this allows for custom backgrounds, positions, and colors on the main menu, if any value on the json is invalid, it will use the default values

also includes new debug keys for the main menu, Debug 2 (on Controls) should open the mods menu, RESET should restart the state **if** the Reload Key is enabled on the json file

example:
```
{	
	"enableReloadKey":true,
	"centerOptions":false,
	"alignToCenter":false,
	"optionX":300,
	"optionY":300,
	"bgX":-80,
	"bgY":0,
	"scaleX":1,
	"scaleY":1,
	"backgroundStatic":"funkay",
	"backgroundConfirm":"funkay",
	"colorOnConfirm": [
		69,
		69,
		69
	],
	"options": [
		"story_mode",
		"freeplay",
		"awards",
		"options"
	],
	"links": [
		["discord", "https://discord.com/app"],
		["twitter", "https://twitter.com"]
	]
}
```

colorOnConfirm uses RGB values, similar to the characters
links are disabled for the time being

https://user-images.githubusercontent.com/45212377/173432708-1fda9a86-74df-4e00-8e8b-605e0ed8f0b0.mp4

### CODE REVIEW

**Review by Joalor64 — APPROVED** [review]
nice

**Review by TheKitBoi — APPROVED** [review]

**Review by EyeDaleHim — APPROVED** [review]
man's already doing 0.6.0

**Review by ghost — APPROVED** [review]
i have only 3 words. Please Add This.

**Review by ghost — APPROVED** [review]
sure uh you know for the popy lua users

**Review by MasterDirector99 — APPROVED** [review]
**I LOVE IT!!!**

**Review by CrusherNotDrip — APPROVED** [review]
nice

**Comment by Dysfunk** [comment]
Why does this remind me of something...

Jokes aside, banger pr

**Review by Dysfunk — APPROVED** [review]

**Review by stilic — APPROVED** [review]
HOLY SHIT IT'S SO COOL!!!!!

**Comment by BeastlyGhost** [comment]
i noticed too many options can break the menu, so I just made it so you can only have 12

**Review by MemeFlavor — APPROVED** [review]
10/10

**Review by Raltyro — APPROVED** [review]
@ShadowMario PLS ACCEPT THIS PR ITS SO FUCKING COOL

**Comment by EyeDaleHim** [comment]
@ShadowMario

**Comment by TheRealJake12** [comment]
is nice.

**Review by GamerZoneMusic — APPROVED** [review]

**Review by DabbinDude316B — APPROVED** [review]
noice

**Comment by TheRealJake12** [comment]
is there a way to modify specific option X and Y?

**Comment by BeastlyGhost** [comment]
> is there a way to modify specific option X and Y?

will add it soon-ish

**Comment by vidyagirl** [comment]
FYI, Null<Int> is just 0 on static targets
Similarly, Null<Float> is 0 on static targets (or NaN on flash)

**Comment by antoSKRLOL** [comment]
COOL!!!!

**Pull request closed without merging**
