### PR TITLE
resync if vocals are offsync

### PR DESCRIPTION
**Pull request by PrincessMtH**
change the if condition for resyncVocals() to actually include a check for whether the vocals are offsync, wild....

### CODE REVIEW

**Comment by Stilic** [comment]
gonna use that for my fe fork

**Review by nahiassis — COMMENTED** [review]
just yes

**Review by nahiassis — APPROVED** [review]
oops
wrong type lol

**Review by Starmapo — APPROVED** [review]

**Review by RagdollClash — APPROVED** [review]
This fixes the issue where vocals can sometimes be desynced from the instrumental and chart

**Review by lunacynne — APPROVED** [review]

**Review by Trayfellow — APPROVED** [review]
real

**Comment by Doritojoey** [comment]
I THOUGHT THIS WAS JUST HAPPENING CUZ MY PC WAS SHIT

**Review by ghost — APPROVED** [review]

**Review by stilic — APPROVED** [review]

**Comment by Stilic** [comment]
@ShadowMario pls merge this.

**Review by Dysfunk — APPROVED** [review]

**Review by GO-Miles — APPROVED** [review]
This fix is neat; I would sometimes have to pause and/or restart the song for the voices to sync before.

**Pull request merged**
