### PR TITLE
Fixing Sustain Notes When The Direction is Changed

### PR DESCRIPTION
**Pull request by bdidk235**
Fixing some stuff, I like changing direction for notes!

### CODE REVIEW

**Comment by HiroMizuki** [comment]
maybe u could show some video so people can see what it does

**Comment by AdrianCD5** [comment]
This is a really good fix, I need this to force the opponent to remain on upscroll and the sustains are buggy with the new note system. Thanks :)

**Comment by bdidk235** [comment]
The sustain arrows are not reducing, I'm trying to fix it.

**Comment by KevinKuntz255** [comment]
would really love this pulled since I'm making this

https://user-images.githubusercontent.com/35108759/151361652-f3e1b63e-7a35-4120-955c-f919a99b4ca0.mp4

**Comment by nintendofan44** [comment]
the sus clip isnt on the center anymore if you didnt notice it yet

**Pull request closed without merging**
