### PR TITLE
Lua Dialogues in anoder platforms fix

### PR DESCRIPTION
**Pull request by MAJigsaw77**

### CODE REVIEW

**Review by stilic — COMMENTED** [review]
WTF. This is a bullshit PR. This should be closed.

**Comment by Stilic** [comment]
Also you look like to be a bullshit PR kid.

**Comment by jigsaw-4277821** [comment]
Dude this really fix that lmao

**Comment by Stilic** [comment]
You are sure? Look at #3413 for see how this should be closed.

**Comment by jigsaw-4277821** [comment]
For an exemple with this on mobile the Lua Dialogues starts working correctly

**Comment by jigsaw-4277821** [comment]
+ you can check your self download the build from checks

**Comment by Starmapo** [comment]
Psych Engine isn't available on mobile anyways, atleast not the official version. If this is for a mobile port repository, there's no reason to add it to the main one.

**Comment by jigsaw-4277821** [comment]
But can be ported to mobile with all futures, look on my GitHub

**Comment by jigsaw-4277821** [comment]
> Psych Engine isn't available on mobile anyways, atleast not the official version. If this is for a mobile port repository, there's no reason to add it to the main one.

**Pull request closed without merging**
