### PR TITLE
A little fix for stress

### PR DESCRIPTION
**Pull request by MaysLastPlay**
fixed a gameover on stress (it was just bf-dead)
i also tried to fix SScript issue (ik, it's gone, type not found: SCall) but idk how to fix this one

### CODE REVIEW

**Review by ACoolioDude — APPROVED** [review]
Cool LOL

**Comment by NexIsDumb** [comment]
no?
couldnt you just change it through the chart editor if stress didnt have the bf holding gf gameover?
shadowmario added gameover characters on charts for a reason

**Review by NexIsDumb — CHANGES_REQUESTED** [review]
no?
couldnt you just change it through the chart editor if stress didnt have the bf holding gf gameover?
shadowmario added gameover characters on charts for a reason

**Comment by MaysLastPlay10** [comment]
> no? couldnt you just change it through the chart editor if stress didnt have the bf holding gf gameover? shadowmario added gameover characters on charts for a reason

Hmm, then why he add pixel gameover on senpai's week? This gameover was on 0.6.3 (and og game) and for unknown reasons got deleted on 0.7+, so I just added that back

**Comment by NexIsDumb** [comment]
> > no? couldnt you just change it through the chart editor if stress didnt have the bf holding gf gameover? shadowmario added gameover characters on charts for a reason
> 
> Hmm, then why he add pixel gameover on senpai's week? This gameover was on 0.6.3 (and og game) and for unknown reasons got deleted on 0.7+, so I just added that back

it was not for unknown reason, check the chart editor in the data tab, you'll see what I mean

**Comment by NexIsDumb** [comment]
plus softcoding is better than hardcoding in the source, thats why he did it through the chart editor

**Pull request closed without merging**
