### PR TITLE
Yeah

### PR DESCRIPTION
**Pull request by ghost**
Yeah

### CODE REVIEW

**Comment by ManMaster707** [comment]
Oh come on, another one?
Android won't ever be supported officially, so please close this.

**Comment by EyeDaleHim** [comment]
All you did was steal someone else's code

**Comment by TheKitBoi** [comment]
if github were to add a button feature that enables or disable the forking other peoples work

**Comment by 8bitjake** [comment]
oh my god not this again

**Comment by Meme1079** [comment]
image

**Comment by MilkyTheMilkBlob** [comment]
NOOOOOOOO NOT AGAIN

**Comment by MilkyTheMilkBlob** [comment]
image
but thank god at least it has conflicts that arent resolved

**Comment by MilkyTheMilkBlob** [comment]
.

**Comment by Mastercopper2346** [comment]
I’d rather you copy paste all the code my guy

**Comment by CrusherMods** [comment]
oh fucks naw

**Comment by antoSKRLOL** [comment]
bruhhhhh

**Comment by Raltyro** [comment]
this mf be fucking smoking high when they pulled up this pr

**Comment by MilkyTheMilkBlob** [comment]
this guys like "duh, i wanna merge an android port to psych"
and then they did



why

**Comment by MilkyTheMilkBlob** [comment]
image
they made a github account and did this
and thats it

**Comment by MilkyTheMilkBlob** [comment]
image
@Funkeon, this is for your own good

**### DO IT.**

**Comment by ManMaster707** [comment]
> image they made a github account and did this and thats it

judging from this it seems that he's a literal troll, so at this point let's just ignore him, @ShadowMario will do the duty.

**Comment by Wither362** [comment]
This pull request should be named `Yeah, more *shit*`

**Comment by TheKitBoi** [comment]
> This pull request should be named `Yeah, more *shit*`

image

Wish Granted

**Comment by Raltyro** [comment]
SHADOWMARIO PLEASE CLOSE THIS PR OMFG

**Review by rodney528 — COMMENTED** [review]
Wtf dude

**Comment by silvashp** [comment]
little kiddies PR'ing android to original psych engine (brainless)

**Comment by pasta870** [comment]
RDT_20220410_1203215328520486665721702

**Review by rodney528 — COMMENTED** [review]
Pineapple

**Review by rodney528 — COMMENTED** [review]
@ShadowMario please close this Pull Request. Also @jigsaw-4277821 please notice what's going on.

**Comment by jigsaw-4277821** [comment]
> @ShadowMario please close this Pull Request. Also @jigsaw-4277821 please notice what's going on.

A stupid guy pull request all the commits I done on my repo

**Comment by ManMaster707** [comment]
> A stupid guy pull request all the commits I done on my repo

Not only this guy, recently there's been a LOT of people/children doing a pr with your stuff.

**Review by rodney528 — COMMENTED** [review]
oh boy

**Review by rodney528 — APPROVED** [review]

**Comment by CrusherMods** [comment]
> image @Funkeon, this is for your own good
> 
> ### DO IT.

YOOO THEY DID IT

**Review by rodney528 — CHANGES_REQUESTED** [review]
Take down this stupid "Yeah" pull request.

**Review by rodney528 — COMMENTED** [review]
Pineapple

**Comment by CrusherMods** [comment]
> Take down this stupid "Yeah" pull request.

they deleted their account so they kinda cant

**Comment by MilkyTheMilkBlob** [comment]
> Take down this stupid "Yeah" pull request.

they already deleted their account so only @ShadowMario can close this

**Comment by MilkyTheMilkBlob** [comment]
> > A stupid guy pull request all the commits I done on my repo
> Not only this guy, recently there's been a LOT of people/children doing a pr with your stuff.

yea, i agree
its like some hacker hacking random github accounts to do a pull request with the android port

**Review by rodney528 — COMMENTED** [review]
Pineapple

**Review by rodney528 — COMMENTED** [review]
Pineapple

**Review by MemeHoovy — COMMENTED** [review]
poptart

**Comment by MAJigsaw77** [comment]
@ShadowMario close this please

**Comment by ImaginationSuperHero528** [comment]
> @ShadowMario close this please 

I think his notifications are on silent or some shit.

**Comment by CrusherMods** [comment]
> I think his notifications are on silent or some shit.

yeah he does
therefore pinging him does absolutely nothing at all

**Comment by ShadowMilky** [comment]
oh finally
its closed

**Pull request closed without merging**
