### PR TITLE
Less RAM usage by optimizing spritesheets

### PR DESCRIPTION
**Pull request by ACrazyTown**
All this PR does is trim the big transparent parts of spritesheets Animate CC likes to add. They might seem useless, but when loading the game, they also get loaded taking up extra memory.

In theory it should also improve loading speeds, but I haven't tested that.

RAM usage before and after:
| State      | Usage Before | Usage After |
| ----------- | ----------- | ----------- |
| Title Screen     | 118.5MB       | 82.1MB |
| Main Menu | 200MB | 109.3MB |
| Story Mode | 200MB | 102.7MB |
| Week 1    | 513MB        | 458.9MB |
| Week 2 | 850.9MB | 594.3MB |
| Week 3     | 540.2MB       | 464.4MB |
| Week 4 | 550MB | 390MB |
| Week 5 | 964MB | 707.5MB |
| Week 6 | 192MB | 189.6MB |
| Week 7   | 568MB      | 438.8MB |

Keep in mind, these values may not be 100% correct on all computers, this is just how it was on my PC.

### CODE REVIEW

**Comment by trayfellow** [comment]
finally

**Review by Trayfellow — APPROVED** [review]

**Review by ManMaster707 — APPROVED** [review]

**Review by EyeDaleHim — APPROVED** [review]
Eh, RAM is not the usual thing to focus for performance in some cases, but sure.

**Review by xRaRxTeos — APPROVED** [review]

**Review by MemeFlavor — APPROVED** [review]

**Comment by ACrazyTown** [comment]
> Eh, RAM is not the usual thing to focus for performance in some cases, but sure.

Might still improve performance on weaker PCs with less available RAM

**Review by Raltyro — CHANGES_REQUESTED** [review]
?
image

**Review by Raltyro — APPROVED** [review]

**Comment by ACrazyTown** [comment]
> ? image

I couldn't get the game to build without that, hxCodec renamed `MP4Handler` to `VideoHandler` on it's Git/Haxelib repo

**Review by TheKitBoi — APPROVED** [review]

**Comment by BeastlyGhost** [comment]
> > ? image
> 
> I couldn't get the game to build without that, hxCodec renamed `MP4Handler` to `VideoHandler` on it's Git/Haxelib repo

image
trust me the Haxelib version was not updated

**Review by BombasticTom — APPROVED** [review]
amazing pull

**Comment by ACrazyTown** [comment]
> > > ? image
> > 
> > 
> > I couldn't get the game to build without that, hxCodec renamed `MP4Handler` to `VideoHandler` on it's Git/Haxelib repo
> 
> image trust me the Haxelib version was not updated

Oh my bad, turns out I was running the git version instead of haxelib 😅, I'll push a commit rn to fix this

**Review by DM-kun — APPROVED** [review]

**Comment by RowanSkie** [comment]
You know, now that I see this PR, I had this whole tangent once in the subreddit on an app called PNGGauntlet, which shrinks PNGs and compresses them with minimal to no losses.

Might be a 50-70% decrease in space usage, but it's probably not part of the main PR.

~~considering that Starbound, and Terraria have done and used that to save what is effectively gigabytes of texture spaces with said tool, haha.~~

**Review by xRaRxTeos — APPROVED** [review]

**Comment by xChillax** [comment]
> You know, now that I see this PR, I had this whole tangent once in the subreddit on an app called PNGGauntlet, which shrinks PNGs and compresses them with minimal to no losses.

For the lazy:
https://pnggauntlet.com/

Also, It's actually a LOSSLESS method, meaning no quality is lost. All it does is strip unnecessary data like unused colors and other information that usually gets printed on the images by image editors or exporters.

I actually intended to make a PR about it doing both methods (trimming and cleaning the PNGs) but I guess at least one part of it is done. lol

Also if this was added to this PR, which personally, it should be, all the author would need to do is just rename the title afterward.

> In theory it should also improve loading speeds, but I haven't tested that.

It does improve loading times, as mind you, the game has to load, read and interpret the image before being able to show it, so the less big your files are, the faster it will load them.
A good example is how 3 MB images after being trimmed and processed through PNGauntlet instead of having a little freeze cause no freeze at all.

By making the images smaller you not only improve performance (on PCs that don't have a lot of RAM) but you also reduce the loading times or random stutters while loading assets (as long as they are small enough, big ones will still cause some degree of freezes but it will be reduced regardless).

**Comment by ACrazyTown** [comment]
> Fix?

Should be good to go now! Also tried using PNGGauntlet as @xChillax suggested, although it hasn't made a big difference in RAM usage as far as I can tell.

Also, I can't change Tankman's spritesheet due to merge conflicts, but if you want to use the compressed and trimmed version you can get it from [here](https://github.com/ACrazyTown/FNF-PsychEngine/blob/41ed819d4a3812b51fef9b16f4b97a54ef18a3be/assets/shared/images/characters/tankmanCaptain.png)

**Comment by Lokitot** [comment]
xml of the spritesheets???

**Comment by ACrazyTown** [comment]
> xml of the spritesheets???

?

**Comment by ACrazyTown** [comment]
> bro when i put the spritesheets the sprite starts doing frauuhhubtbbtbbrb, you need to post the xml files

No? I have the latest build of Psych and it works fine. Please give more info and if possible provide a screenshot or video

**Comment by Lokitot** [comment]
> man im using soul engine 💀💀

**Comment by ACrazyTown** [comment]
> > man im using soul engine 💀💀

I cant help you then. This PR was made with Psych and works on Psych, for other engines, figure it out yourself

**Comment by Lokitot** [comment]
> > > man im using soul engine 💀💀
> 
> I cant help you then. This PR was made with Psych and works on Psych, for other engines, figure it out yourself

alr, i'll try to find a solution, thanks for the help btw

**Comment by ActualMandM** [comment]
Was this done manually or did you use a program to automate the trimming?

**Comment by ACrazyTown** [comment]
> Was this done manually or did you use a program to automate the trimming?

It was done manually, at the time I was unaware of a few programs that can do it automatically

**Pull request merged**
