### PR TITLE
Multi-sheet Characters

### PR DESCRIPTION
**Pull request by dombomb64**
This adds a new field to the character editor that lets you reference other sprite sheets for certain animations. One of the things this is useful for is if your character is too big (or just has fully animated voicelines) and is forced to use multiple sprite sheets (unless you downgraded to Adobe Animate 2018 just for texture atlases for some reason).

Note: While I was already deep into programming this, I had the thought that there could be a way to store all the frames in the frames variable at once, but I didn't want to sacrifice my progress, so if this doesn't work well enough for whatever reason, that could be attempted.

Demo video:

https://github.com/ShadowMario/FNF-PsychEngine/assets/49823019/4eb3f712-33c1-46c3-97af-8b7184b50757

### CODE REVIEW

**Review by ghost — APPROVED** [review]
I feel like this needs a more in-depth explanation of what it does necessarily, while the example video is good, it doesn't really replace proper descriptions

**Comment by dombomb64** [comment]
> I feel like this needs a more in-depth explanation of what it does necessarily, while the example video is good, it doesn't really replace proper descriptions

So, basically, I added a new text field in the “Animations” tab that changes the sprite sheet that that animation uses to the one specified. One of the things this is useful for is if your character is too big (or just has fully animated voicelines) and needs to use multiple sprite sheets. Something of note is that, in gameplay, all of the sprite sheets the character uses get loaded at once, so you don’t need to precache the extra ones.

**Comment by Rom4chek** [comment]
good for sprites that have long dialogue animation

**Review by moxie-coder — APPROVED** [review]

**Review by jimmyjamescool — APPROVED** [review]
Needed this

**Review by charlesisfeline — APPROVED** [review]
this is pretty necessary for characters that have long dialogue animation like some mods do

**Review by DarkWeBareBears69 — APPROVED** [review]
I added this on my engine fork. Great feature, dude!

**Review by ManMaster707 — APPROVED** [review]

**Review by PSYCHOVICH229 — APPROVED** [review]

**Comment by antoSKRLOL** [comment]
I tried it in my custom build of psych engine and noticed that when running animations it tends to crash
but apart from that it is super useful to optimize, you can add as many animations as you want without overloading the spriteSheet

**Comment by 4ntonySKR** [comment]
i did a test of this and it gave this result, lmao

https://github.com/ShadowMario/FNF-PsychEngine/assets/103867370/d3e6bd24-a793-4450-80d5-cd823cc1a77b

**Comment by KookerFoxYT** [comment]
also shouldnt this be rebased to the experimental branch because i cant like use this in my v0.7b build without merge conflicts sjsifjkrfjg9thiy

**Comment by dombomb64** [comment]
> also shouldnt this be rebased to the experimental branch because i cant like use this in my v0.7b build without merge conflicts sjsifjkrfjg9thiy

I just tried to add it to the experimental branch, but it won't compile. I keep getting errors about hxCodec, which appears to have had some sort of significant overhaul about four days ago, so I think the changes might not have been taken into consideration here yet. And yes, I've read the list of library versions.

**Comment by NexIsDumb** [comment]
> > also shouldnt this be rebased to the experimental branch because i cant like use this in my v0.7b build without merge conflicts sjsifjkrfjg9thiy
> 
> 
> 
> I just tried to add it to the experimental branch, but it won't compile. I keep getting errors about hxCodec, which appears to have had some sort of significant overhaul about four days ago, so I think the changes might not have been taken into consideration here yet. And yes, I've read the list of library versions.

I just made a PR about those errors #12629
The api was totally different what the heck
Would be better to use 2.6.1 but if you want, if and once shadow merge that PR, you can rebase it to experimental

**Pull request closed without merging**
