### PR TITLE
Now y'all can shut up about Lua

### PR DESCRIPTION
**Pull request by moxie-coder**

### CODE REVIEW

**Comment by Rom4chek** [comment]
rude but true

**Review by roma-perec-bp — APPROVED** [review]

**Comment by Stilic** [comment]
useless/joke pr, should be closed.

**Comment by MemeHovy** [comment]
> useless/joke pr, should be closed.

the only reason I did this was to fix an issue if people did not switch their forks of linc_luajit

**Comment by MemeHovy** [comment]
on second thoughts, I'll close this because I made it out of annoyance from the issues

**Comment by MemeHovy** [comment]
but I hope something could be done to prevent them if people don't switch forks

**Comment by BombasticTomDev** [comment]
> > useless/joke pr, should be closed.
> 
> the only reason I did this was to fix an issue if people did not switch their forks of linc_luajit

its not an issue it's haxelib being haxelib, you had to specify that you want to download from the master branch, the command would go like this:

`haxelib git linc_luajit https://github.com/superpowers04/linc_luajit master`

**Comment by MemeHovy** [comment]
> > > useless/joke pr, should be closed.
> > 
> > 
> > the only reason I did this was to fix an issue if people did not switch their forks of linc_luajit
> 
> its not an issue it's haxelib being haxelib, you had to specify that you want to download from the master branch, the command would go like this:
> 
> `haxelib git linc_luajit https://github.com/superpowers04/linc_luajit master`

good to know

**Pull request closed without merging**
