### PR TITLE
set the instrumental and the vocals volume to 0.85 in freeplay

### PR DESCRIPTION
**Pull request by nahiassis**
the volume at 0.7 may sound bad in some songs at freeplay so i turned it up

### CODE REVIEW

**Comment by jmxamongusmodder** [comment]
no. just no. thats too loud.

**Comment by MayoALT** [comment]
just up the volume of the vocals in the song editing program

**Comment by nintendofan44** [comment]
> just up the volume of the vocals in the song editing program

thats not the best way to do it

**Comment by jmxamongusmodder** [comment]
this is better

**Comment by Dysfunk** [comment]
> just up the volume of the vocals in the song editing program

or literally do it in the chart editor

**Comment by mayo78** [comment]
> > just up the volume of the vocals in the song editing program
> 
> thats not the best way to do it

yes it is :trollface:

**Comment by nintendofan44** [comment]
> > > just up the volume of the vocals in the song editing program
> > 
> > 
> > thats not the best way to do it
> 
> yes it is :trollface:

its not becouse if someone is with their volume on the maximum their ears are going to explode
so its better to do it on the game

**Comment by Doritojoey** [comment]
This is useless

**Comment by nintendofan44** [comment]
i get it

**Pull request closed without merging**
