### PR TITLE
add state lua shit

### PR DESCRIPTION
**Pull request by stilic**
funny shit i did on my phone

NOT TESTED ALSO!!!

### CODE REVIEW

**Comment by jmxamongusmodder** [comment]
ill test it.

**Comment by Itz-NOT-Miles** [comment]
While I'm at school, is this properly implemented for `loadAndSwitchState();`?

**Review by Itz-NOT-Miles — APPROVED** [review]
nvm, was looking at an older commit.

**Comment by Cherif107** [comment]
zooom

**Review by Blossomical — APPROVED** [review]

**Review by Raltyro — APPROVED** [review]

**Pull request closed without merging**
