### PR TITLE
Button to Reset Achievements

### PR DESCRIPTION
**Pull request by crowplexus**
grêmio.

### CODE REVIEW

**Comment by Mastercopper2346** [comment]
OMG YESSSS

**Review by DabbinDude316B — APPROVED** [review]

**Comment by Mastercopper2346** [comment]
This needs to be merged

**Review by TheKitBoi — APPROVED** [review]

**Review by DM-kun — APPROVED** [review]
finally

**Comment by antoSKRLOL** [comment]
add this to my modification, I hope you don't mind hehe

**Pull request closed without merging**
