### PR TITLE
Open a URL with lua

### PR DESCRIPTION
**Pull request by MAJigsaw77**
I think the title says all

### CODE REVIEW

**Comment by DudeItsJonnycat** [comment]
what does it actually do?

**Comment by Gui-iago** [comment]
> what does it actually do?

do you know the "CoolUtil.browserLoad" feature on source? yeah that makes it so it can be accessed using lua scripts

**Comment by DudeItsJonnycat** [comment]
oh shiii

**Comment by DudeItsJonnycat** [comment]
how to I approve 
?

**Comment by DudeItsJonnycat** [comment]
cause im new to GitHub stuff

**Comment by Gui-iago** [comment]
> cause im new to GitHub stuff

image
click here, then search for the "Review Changes" button and review it

**Review by crowplexus — APPROVED** [review]
I just tested it for a bit, and it works

**Review by ghost — APPROVED** [review]

**Comment by DudeItsJonnycat** [comment]
thank you @Gui-iago

**Comment by cherryiguess** [comment]
I don't think this should be merged in my opinion, it can be used for malicious links like IP grabbers

**Comment by DudeItsJonnycat** [comment]
> I don't think this should be merged in my opinion, it can be used for malicious links like IP grabbers

that is true

**Review by GamerZoneMusic — APPROVED** [review]
WE NEED THIS

**Review by MasterDirector99 — APPROVED** [review]
**YES!!!**

**Review by lunacynne — CHANGES_REQUESTED** [review]
i think there should be a whitelist for sites that lua can send you to, because in this state it can be easily used for malicious purposes

arg 1 could be the site name like "youtube" or "imgur" or something
and arg 2 could be the video or image parameter

the function would check if the site you put is in the whitelist and if it is then it assembles the link based on the arguments and sends you to it

something like `openUrl("youtube", "BPSwU1ApmZ0")` would send you to `https://youtu.be/BPSwU1ApmZ0`

**Comment by cyn-8** [comment]
i also think a debounce should be added if possible so people cant put it in onUpdate or something and open like 60 videos in 1 second

**Comment by Steviegt6** [comment]
> I don't think this should be merged in my opinion, it can be used for malicious links like IP grabbers

Who cares if someone has your IP? At least provide a more malicious example.

**Comment by frantastic24** [comment]
> At least provide a more malicious example.

You could get rickrolled

**Comment by PoleyMagik** [comment]
I'm not exactly sure with this commit, I feel like a browser could really easily be used to open malicious js code.

**Comment by SonicProYT** [comment]
that could link the player to some malicious JS code or something ig

**Review by coolfren — COMMENTED** [review]
1. What purpose does this serve?
2. Security risk as people can just redirect you to iploggers or some bouncer scripts that will memleak your browser

**Review by zephyr-zeph — COMMENTED** [review]
you can already do this with lua, using os.execute("start (link here)")

**Comment by cyn-8** [comment]
> you can already do this with lua, using os.execute("start (link here)")

os commands have been disabled

**Comment by letranger213** [comment]
> > you can already do this with lua, using os.execute("start (link here)")
> 
> os commands have been disabled

use 0.5

**Review by megasssdev — APPROVED** [review]

**Comment by Lokitot** [comment]
lua script?

**Pull request closed without merging**
