### PR TITLE
discord rpc improvements

### PR DESCRIPTION
**Pull request by richTrash21**
Main changes:

* creates only one thread

* thread now updates each second instead of half a second

* added ability to change large image key

* reflectable presence (for retrieving and setting presence info in scripts)

### CODE REVIEW

**Comment by PurSnake** [comment]
Usefully

**Review by ACoolioDude — APPROVED** [review]
Peak improvements

**Comment by Stefan2008Git** [comment]
WHAT THE FUCK!!?? IT'S OFFICIALLY MERGED?

**Comment by Redar13** [comment]
no way

**Comment by Stefan2008Git** [comment]
> no way

Boys, we got Shadow Mario cooked

**Pull request merged**
