### PR TITLE
Implement Pixel Splashes (without XML)

### PR DESCRIPTION
**Pull request by DM-kun**
(this is just #8999 but I had to reopen it cause i renamed the branch)
This PR adds Pixel Notesplashes that are actually pixels AND they don't use an XML like the Pixel Notes
Here is a little showcase:

https://user-images.githubusercontent.com/86197998/185785608-25d897c2-df12-485b-b13f-4369d7cd3744.mp4

Original Pixel Splashes by me, Improved version by [xChillax](https://github.com/xChillax)
Pixel Hurt Splashes by [xChillax](https://github.com/xChillax)

### CODE REVIEW

**Review by Raltyro — APPROVED** [review]
cool

**Review by MemeHoovy — APPROVED** [review]

**Review by TheKitBoi — APPROVED** [review]

**Review by Jotaro-Gaming — APPROVED** [review]
i didnt see youre code but idc if its messy if it works it works

**Review by Parsellol — APPROVED** [review]
awesome

**Comment by ImaginationSuperHero528** [comment]
:D

**Review by rodney528 — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by iym1337 — APPROVED** [review]

**Review by Gostar64 — APPROVED** [review]

**Pull request closed without merging**
