### PR TITLE
Updat I liscene

### PR DESCRIPTION
**Pull request by TheKillerA1**

### CODE REVIEW

**Comment by Playertrip777** [comment]
Why did you "update" the license?

**Comment by LilDrippyMyFnf** [comment]
> Why did you "update" the license?

idk

**Review by MemeHoovy — CHANGES_REQUESTED** [review]
omg, will you just kindly fuck off already?

**Comment by TheKillerA1** [comment]
> omg, will you just kindly fuck off already?

1816A31D-B846-444D-ADBD-DF38026ABA35

**Review by kingyomoma — COMMENTED** [review]
so cool!!!!!!!

**Comment by MemeHoovy** [comment]
> this you?

LEAKER 1

**Comment by kingyomoma** [comment]
no

**Review by TheKitBoi — COMMENTED** [review]
C3672C1F-38DC-42F9-A14E-33A90E352781

**Comment by Itz-Miles** [comment]
@TheKillerA1 Although I think everyone reacted too violently on the first offence, your behavior is frustrating anyone who is looking for updates. Consider your account reported; this repository just isn't the place for these kinds of PRs, satire or not.

**Comment by ShadowMario** [comment]
Charming PR, however i'm writing slurs about you right now

**Pull request closed without merging**
