### PR TITLE
Faster playback rates

### PR DESCRIPTION
**Pull request by Starmapo**
Adds the unused gameplay modifier that changes the song's playback rate, up to 2.5x speed. It uses `FlxG.timeScale` so basically everything will automatically be sped up, including timers, tweens, and animations, without having to do it manually.
Slower playback rates are _possible_ but they cause audio errors near the end of the song so I opted to remove them for now.

Would've included a video but there's an upload size limit.

### CODE REVIEW

**Review by crowplexus — APPROVED** [review]
i present to you https://8mb.video

**Review by Raltyro — APPROVED** [review]
CHIPMUNKS

**Review by dummmmdum — APPROVED** [review]

**Review by BalancedLight — APPROVED** [review]
now this is epic

**Comment by KadeDev** [comment]
> so basically everything will automatically be sped up, including timers, tweens, and animations, without having to do it manually.

idk man. I think a better version of this would be using OpenAL like shadow is already doing and then just increasing/decreasing the bpm and make everything based on the bpm.

Speeding up everything sounds like a terrible idea that'll cause a lot of shit to break/look jank.

**Pull request closed without merging**
