### PR TITLE
Right click to select a note in chart editor

### PR DESCRIPTION
**Pull request by FearmongerWade**
Very useful! Ctrl + Left click is eh

### CODE REVIEW

**Review by libauror-a — APPROVED** [review]

**Review by TehPuertoRicanSpartan — APPROVED** [review]

**Review by charlesisfeline — APPROVED** [review]
m

**Review by BlueColorsin — APPROVED** [review]

**Comment by BlueColorsin** [comment]
please shadow mario..,
PLEASEEEE

**Review by melodiekit — APPROVED** [review]
caption-1-1

**Pull request closed without merging**
