### PR TITLE
Multi-Sheet Characters (Experimental Branch)

### PR DESCRIPTION
**Pull request by dombomb64**
This is my pull request #12517, but on the actual correct branch this time.

###### Copy-pasted from the previous iteration:

This adds a new field to the character editor that lets you reference other sprite sheets for certain animations. One of the things this is useful for is if your character is too big (or just has fully animated voicelines) and is forced to use multiple sprite sheets (unless you downgraded to Adobe Animate 2018 just for texture atlases for some reason).

Demo video:

https://github.com/ShadowMario/FNF-PsychEngine/assets/49823019/4eb3f712-33c1-46c3-97af-8b7184b50757

### CODE REVIEW

**Review by moxie-coder — APPROVED** [review]

**Comment by ender69funk** [comment]
Gud

**Review by jimmyjamescool — APPROVED** [review]
I dipped my balls in ketchup

**Comment by dombomb64** [comment]
> I dipped my balls in ketchup

```
⠀⠀⠀⠀⠀⠀⠀⠄⡉⠀⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀Good job!
⠀⠀⠀⠀⠀⠀⢀⢂⠀⡁⢢⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⢀⠰⡈⠥⢉⠌⠒⠦⡁⢂⠀⣀⣀⠀⠀⠀⠀⠀⠀
⠐⡌⢂⠐⠤⢌⠠⠁⠄⠑⡂⠘⠁⠈⠀⠁⠶⣄⠀⠀
⡣⢐⠈⠄⠀⠀⠈⠑⢌⠢⡁⠐⣈⠀⠀⠠⠄⡈⢆⡀
⢢⠁⠆⡘⠀⢆⠁⠄⠂⠥⠐⠂⠾⠃⠀⢭⢷⠀⠢⡄
⠀⢉⠒⠤⡁⡀⢉⠦⢍⠢⠉⣆⠠⠁⠌⡠⢁⢆⠓⡌
⠀⠀⠈⠐⠑⠘⢂⠣⢊⠔⡡⢘⣧⣉⢐⣰⢃⠎⡱⠈
⠀⠀⠀⠀⠀⠀⠀⠁⠊⢀⠐⡁⠲⢿⡿⢃⢎⡘⠁⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⢈⡑⢢⠜⠈⠂⠀⠀⠀
```

**Comment by TheLeerName** [comment]
u dont need init maps like this
just `var coolmap:Map<String, String> = [];`

**Pull request closed without merging**
