### PR TITLE
Pixel icons are now pixel perfect (non-stretched)

### PR DESCRIPTION
**Pull request by doggogit**
Small change to the pixel icons, credit to @MaybeMaru for noticing this

### CODE REVIEW

**Comment by crowplexus** [comment]
THANK FUCKING GOD

**Comment by MaybeMaru** [comment]
you welcome lmao

**Review by NexIsDumb — APPROVED** [review]
fire

**Review by J-Orell — APPROVED** [review]
Yes

**Review by lunacynne — APPROVED** [review]

**Comment by HaydenGamingBack** [comment]
LEGEND

**Comment by doggogit** [comment]
Will re-open this.

**Pull request closed without merging**
