### PR TITLE
TitleState Rewrite

### PR DESCRIPTION
**Pull request by CCobaltDev**
- Removed black background images (except the one for title secrets)
- Better organization
- Moved all the variables to the top
- Small optimizations
- Added `createImage()` and `deleteImages()` for adding images to TitleState easily
- Small Edits to Main.hx

### CODE REVIEW

**Comment by trayfellow** [comment]
Yummers!

**Comment by CobaltBar** [comment]
I just realized a massive issue

I forgot to update some of the stuff for the title easter eggs so thats broken

currently fixing

**Comment by CobaltBar** [comment]
yeah the title easter eggs are completely broken 1 moment

**Review by DetectiveBaldi — APPROVED** [review]
pretty nice

**Comment by CobaltBar** [comment]
Fixed secrets

**Review by Sword352 — APPROVED** [review]
That's good, but maybe keep the old title json fields for compatibility, otherwise that would be breaking changes

**Pull request closed without merging**
