### PR TITLE
the better ways easier

### PR DESCRIPTION
**Pull request by afeefflox**
bruh you don't need two Animation Indices loop and non loop just made into one bruh

### CODE REVIEW

**Comment by ManMaster707** [comment]
While I understand where you're coming from, I think you should keep the AddAnimationByIndicesLoop function for backwards compatibility with older mods.

**Comment by Raltyro** [comment]
tis wont work cuz linc luajit doesnt supports 6 or more arguments, they just will be nil

**Review by rodney528 — CHANGES_REQUESTED** [review]
> this wont work cuz linc luajit doesnt supports 6 or more arguments, these will just become null

What raltyro said.

**Comment by ShadowMario** [comment]
bro didn't test his own commit...

**Pull request closed without merging**
