### PR TITLE
Press ESC in Titlescreen will Close Game

### PR DESCRIPTION
**Pull request by aaaproooo**
IDK is it useful or not But It works :)

### CODE REVIEW

**Comment by APRO716** [comment]
I forgot something wait pls

**Comment by BeastlyGhost** [comment]
also pretty useless as you can press alt+f4 anyways

**Comment by MemeHoovy** [comment]
> also pretty useless as you can press alt+f4 anyways

agreed

**Comment by APRO716** [comment]
sorry

> also pretty useless as you can press alt+f4 anyways
i mean just an alternative way thank you

**Comment by APRO716** [comment]
oh I just want it as an alternative way btw thank you

**Comment by Raltyro** [comment]
itg noway

**Pull request closed without merging**
