### PR TITLE
fix 4.3.0 haxe version

### PR DESCRIPTION
**Pull request by JonnycatMeow**
https://github.com/HaxeFlixel/flixel/issues/2780#event-9073694321 thanks for @Geokureli for the fix

### CODE REVIEW

**Review by moxie-coder — APPROVED** [review]

**Comment by Stefan2008Git** [comment]
Interesting

**Review by ACoolioDude — APPROVED** [review]

**Review by RandomUserOnInternet — APPROVED** [review]

**Review by talopakola — APPROVED** [review]

**Comment by Geokureli** [comment]
@JonnycatMeow why was this closed?

**Comment by JonnycatMeow** [comment]
@Geokureli i deleted my psych engine fork and so it closed the pull request

**Comment by JonnycatMeow** [comment]
i will reopen

**Pull request closed without merging**
