### PR TITLE
Make note color changing more precise

### PR DESCRIPTION
**Pull request by RagdollClash**
While the current method of changing the note color is sufficient enough, it doesn't allow you to get the precise color that you want. If you're trying to go for a single color setup, it's very hard to get them all to match.

This PR rectifies this by tackling note colors in a different fashion. Instead of using ColorSwap to change the HSV of the current note assets, we separate the 3 colors of the note into each of the RGB channels then use a color mask shader to change the color much more precisely. This means we can now directly use RGB values for changing the note colors.

https://user-images.githubusercontent.com/15317421/215308992-d5e2b8b4-b048-49ee-b8bd-41688755619a.mp4

https://user-images.githubusercontent.com/15317421/215309013-1e7f75e6-1315-41a4-bedc-842c45b7db60.mp4

It is possible to modify all 3 parts of the note color, but I chose to keep it simple since I don't know how to easily integrate it into Psych's menus.

This doesn't apply to note and splash skins set by the songs themselves, since otherwise it would break compatibility.

### CODE REVIEW

**Comment by ActualMandM** [comment]
Setting back to draft for now since it bugs out if the chart defines splashSkin as ""

**Comment by BeastlyGabi** [comment]
begging for this to get merged, good stuff

**Comment by BeastlyGabi** [comment]
although, one criticism I could give is that I'd probably keep the HSB support, something like "TAB to switch color modes" kind of deal could mitigate the issue, as note colors were made specifically for people who have colorblindness issues, but came off as a really great tool for everyone

**Review by DetectiveBaldi — APPROVED** [review]
damn this is really good

**Review by TheKitBoi — APPROVED** [review]

**Review by Joalor64 — APPROVED** [review]

**Review by Luisinhi010 — APPROVED** [review]
good stuff

**Review by Burgerballs — APPROVED** [review]
Really silly!!!!

**Comment by antoSKRLOL** [comment]
👍

**Review by Crimson-is-stupid — APPROVED** [review]

**Review by Grape-Boy — APPROVED** [review]

**Comment by BeastlyGabi** [comment]
yo would you mind if i used this for a project? i will make sure to give proper credit and such

**Comment by ActualMandM** [comment]
@BeastlyGabi Sure, go ahead!

**Review by NexIsDumb — APPROVED** [review]

**Comment by ActualMandM** [comment]
PR made obsolete by 4f1817fb637a358d224147607e95cba1ebd649f6 in the experimental branch, closing.

**Pull request closed without merging**
