### PR TITLE
add pixel note splashes

### PR DESCRIPTION
**Pull request by HiroMizuki**
this PR will add a feature that doesn't exist in the original fnf, but kinda makes sense to make it: **pixelated note splashes**

yea, it is a little thing, but idk, some people would like it

there is a video below to show what it does, check it out

https://user-images.githubusercontent.com/72695242/142067000-d76570f5-2ede-4f49-beba-e9bd8e312b5d.mp4

and yeah, i coded it to hurt notes too, in some case of someone making a chart with these notes

i created it by a issue i've seen today. Here it is #1072

### CODE REVIEW

**Review by FuseIsHere813 — APPROVED** [review]
very pog

the note splashes for pixel didn't exist on here till i saw this :pogchamp:

**Comment by HiroOfc** [comment]
> very pog
> 
> the note splashes for pixel didn't exist on here till i saw this :pogchamp:

ya bro :poggers:

**Comment by ShadowMario** [comment]
Are those based on Week 7's? I hope not.

**Comment by HiroOfc** [comment]
> Are those based on Week 7's? I hope not.

no, week 7's update doesn't have pixel note splashes too

**Comment by Mokona5901** [comment]
Thanks @HiroOfc

**Comment by HiroOfc** [comment]
> Thanks @HiroOfc

u're welcome dude

**Comment by ShadowMario** [comment]
> > Are those based on Week 7's? I hope not.
> 
> no, week 7's update doesn't have pixel note splashes too

I'm asking if it's based on Week 7's note splash textures, not asking if it's from Week 7

**Comment by HiroOfc** [comment]
> > > Are those based on Week 7's? I hope not.
> > 
> > 
> > no, week 7's update doesn't have pixel note splashes too
> 
> I'm asking if it's based on Week 7's note splash textures, not asking if it's from Week 7

oh, srry lol
nah, i used the Psych Engine's splash texture as base

**Comment by DMMaster636** [comment]
I decided to test it and uh... well, look at it yourself 
image

**Comment by CrusherMods** [comment]
> I decided to test it and uh... well, look at it yourself image

If your talking about the enemy note splash then in the video shown its supposed to go to bf notes only

**Comment by DMMaster636** [comment]
> > I decided to test it and uh... well, look at it yourself image
> 
> If your talking about the enemy note splash then in the video shown its supposed to go to bf notes only

That's not it... I mean why are the pixel notes suddenly so small?

**Comment by HiroOfc** [comment]
> > > I decided to test it and uh... well, look at it yourself image
> > 
> > 
> > If your talking about the enemy note splash then in the video shown its supposed to go to bf notes only
> 
> That's not it... I mean why are the pixel notes suddenly so small?

bruh, it's not the PR's fault, i've already seen it, check #1037

**Comment by DMMaster636** [comment]
> > > > I decided to test it and uh... well, look at it yourself image
> > > 
> > > 
> > > If your talking about the enemy note splash then in the video shown its supposed to go to bf notes only
> > 
> > 
> > That's not it... I mean why are the pixel notes suddenly so small?
> 
> bruh, it's not the PR's fault, i've already seen it, check #1037

oh, alright, sorry.

**Comment by HiroOfc** [comment]
> > > > > I decided to test it and uh... well, look at it yourself image
> > > > 
> > > > 
> > > > If your talking about the enemy note splash then in the video shown its supposed to go to bf notes only
> > > 
> > > 
> > > That's not it... I mean why are the pixel notes suddenly so small?
> > 
> > 
> > bruh, it's not the PR's fault, i've already seen it, check #1037
> 
> oh, alright, sorry.

it's ok lol

**Comment by DMMaster636** [comment]
> > > > > > I decided to test it and uh... well, look at it yourself image
> > > > > 
> > > > > 
> > > > > If your talking about the enemy note splash then in the video shown its supposed to go to bf notes only
> > > > 
> > > > 
> > > > That's not it... I mean why are the pixel notes suddenly so small?
> > > 
> > > 
> > > bruh, it's not the PR's fault, i've already seen it, check #1037
> > 
> > 
> > oh, alright, sorry.
> 
> it's ok lol

Btw, I hope it's ok if I use your pixel notesplash for my fork. I even made an icon and put you in the credits of it.

**Comment by HiroOfc** [comment]
> > > > > > > I decided to test it and uh... well, look at it yourself image
> > > > > > 
> > > > > > 
> > > > > > If your talking about the enemy note splash then in the video shown its supposed to go to bf notes only
> > > > > 
> > > > > 
> > > > > That's not it... I mean why are the pixel notes suddenly so small?
> > > > 
> > > > 
> > > > bruh, it's not the PR's fault, i've already seen it, check #1037
> > > 
> > > 
> > > oh, alright, sorry.
> > 
> > 
> > it's ok lol
> 
> Btw, I hope it's ok if I use your pixel notesplash for my fork. I even made an icon and put you in the credits of it.

well, for me it's ok lol

**Comment by DMMaster636** [comment]
> > > > > > > > I decided to test it and uh... well, look at it yourself image
> > > > > > > 
> > > > > > > 
> > > > > > > If your talking about the enemy note splash then in the video shown its supposed to go to bf notes only
> > > > > > 
> > > > > > 
> > > > > > That's not it... I mean why are the pixel notes suddenly so small?
> > > > > 
> > > > > 
> > > > > bruh, it's not the PR's fault, i've already seen it, check #1037
> > > > 
> > > > 
> > > > oh, alright, sorry.
> > > 
> > > 
> > > it's ok lol
> > 
> > 
> > Btw, I hope it's ok if I use your pixel notesplash for my fork. I even made an icon and put you in the credits of it.
> 
> well, for me it's ok lol

thanks, also damn, that's a lot of quotes

**Comment by HiroOfc** [comment]
> > > > > > > > > I decided to test it and uh... well, look at it yourself image
> > > > > > > > 
> > > > > > > > 
> > > > > > > > If your talking about the enemy note splash then in the video shown its supposed to go to bf notes only
> > > > > > > 
> > > > > > > 
> > > > > > > That's not it... I mean why are the pixel notes suddenly so small?
> > > > > > 
> > > > > > 
> > > > > > bruh, it's not the PR's fault, i've already seen it, check #1037
> > > > > 
> > > > > 
> > > > > oh, alright, sorry.
> > > > 
> > > > 
> > > > it's ok lol
> > > 
> > > 
> > > Btw, I hope it's ok if I use your pixel notesplash for my fork. I even made an icon and put you in the credits of it.
> > 
> > 
> > well, for me it's ok lol
> 
> thanks, also damn, that's a lot of quotes

yea l m a o

**Comment by HiroOfc** [comment]
forgot about deez, sorry

**Comment by DMMaster636** [comment]
> forgot about deez, sorry

yay, it's compatible again :D

**Review by HiroMizuki — COMMENTED** [review]
confirmed: yea, it is now compatible

**Comment by HiroOfc** [comment]
TEMPORARILY CLOSED!!
i accidentally deleted some week files and i'll close this for a while

**Pull request closed without merging**
