### PR TITLE
bpmTxt updating when needed

### PR DESCRIPTION
**Pull request by Burgerballs**

### CODE REVIEW

**Comment by tposejank** [comment]
image
man this still gonna update every frame + no affect to performance

**Comment by Burgerballs** [comment]
> image man this still gonna update every frame + no affect to performance

That is because the bpmtxt needs to update every frame when the song is playing, or else it wont show the curbeats and stuff

**Comment by tposejank** [comment]
> > image man this still gonna update every frame + no affect to performance
> 
> That is because the bpmtxt needs to update every frame when the song is playing, or else it wont show the curbeats and stuff

then wtf is this for

**Comment by Burgerballs** [comment]
So it doesn't update when the information stays the same. Such as when the song is paused or if you are using the UI tabs.

**Pull request closed without merging**
