### PR TITLE
Better Lua Note Hit Detection Done!!!

### PR DESCRIPTION
**Pull request by crispyi2**
Eeeepic Lua note hit detection

### CODE REVIEW

**Comment by Mokona5901** [comment]
Funny isSus variable but there isn't sick note score ?

**Comment by crispyi2** [comment]
> Funny isSus variable but there isn't sick note score ? Or i'm blind maybe

Could you maybe give my the code you are refering to? I dont remember changing/adding anything about the sick rating

**Comment by crispyi2** [comment]
> > Funny isSus variable but there isn't sick note score ? Or i'm blind maybe
> 
> Could you maybe give my the code you are refering to? I dont remember changing/adding anything about the sick rating

Nevermind found out what you ment. It's been fixed :)

**Comment by ShadowMario** [comment]
Would probably have to rewrite this once i redo the accuracy system.

**Pull request closed without merging**
