### PR TITLE
Instead of making HUD invisible in cutscenes, tween the alpha to make it look nicer

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by TheKitBoi** [comment]
there's literally a function that can tween this shit
doTweenAlpha('Name', 'camHUD', 0, 0.8, 'linear');

**Comment by TahirRollingArch** [comment]
You can't use lua in cutscenes are you dumb?

**Comment by TheKitBoi** [comment]
> You can't use lua in cutscenes are you dumb?

you mean videos or dialogue

**Comment by TahirRollingArch** [comment]
I am talking about week 6 and 7's cutscene.

**Comment by TheKitBoi** [comment]
> I am talking about week 6 and 7's cutscene.

well it has to be canon from the week 7 official website if they want it tweened they can add it them selves

**Comment by EyeDaleHim** [comment]
Unnecessary PR.

**Pull request closed without merging**
