### PR TITLE
littl fix and littl optimization

### PR DESCRIPTION
**Pull request by k0ffinz**
template.hx doesnt give error in one particular line now + a bit of silly tiny code optimization

### CODE REVIEW

**Review by moxie-coder — APPROVED** [review]

**Comment by BeastlyGhost** [comment]
btw ternary operators get turned into normal if else statements when compiled

**Comment by Ralsin** [comment]
> doesn't do nothing BUT compromise the readability of the code

Depends on the person reading it and the code itself.
Also it's actually easier to read, you can even google it and you will get "makes the code cleaner and **more readable**".

**Review by Raltyro — APPROVED** [review]

**Review by rodney528 — APPROVED** [review]

**Comment by ShadowMario** [comment]
Probably not needed anymore(?)

**Pull request closed without merging**
