### PR TITLE
Installation steps for Ubuntu distros.

### PR DESCRIPTION
**Pull request by ghost**
Since I don't always remember how to compile FNF on Ubuntu I decided to add all the steps for Ubuntu systems.

Why Ubuntu? Cuz I use it lol.

### CODE REVIEW

**Comment by SrtHero278** [comment]
psych engine doesn't really instructions on how to build it.
you're making something that only ubuntu users can use.

**Comment by coolfren** [comment]
you should rename it to "debian" based distros as ubuntu is based off debian

**Comment by SimoneStarace** [comment]
> psych engine doesn't really instructions on how to build it.

That's why I wrote how to build it on distros based on Ubuntu. 
I think that open source projects should have a section dedicated on how to build the project.

> you're making something that only ubuntu users can use.

Because I only use Linux lol. 
Anyone who uses Windows or MacOS can basically make a pull request explaining how to compile the game on the respective OS. IMO it could be useful for non Linux users.

**Comment by SimoneStarace** [comment]
> you should rename it to "debian" based distros as ubuntu is based off debian

While you're right about Ubuntu being a derivative of Debian, the instructions for compile the engine are different in few cases. It might be better making a section dedicated to Debian distros.

**Comment by Playertrip777** [comment]
There is already download instruction for Linux at the Haxe download website.

**Comment by SimoneStarace** [comment]
> There is already download instruction for Linux at the Haxe download website.

True, but I wanted to replicate the instructions in the file, so I don't have to go in the website.

**Comment by Playertrip777** [comment]
So you're too lazy to google download haxe linux?

**Comment by SimoneStarace** [comment]
> So you're too lazy to google download haxe linux?

Kinda lol.

**Pull request closed without merging**
