### PR TITLE
Lua Utilities for working with Regular Expressions/Regex

### PR DESCRIPTION
**Pull request by stephencomputer**
### Why?

Regex is super useful for parsing complex strings without much boilerplate, 
splitting strings at a match, and more.

That's why I'm requesting to put it in psych.

### How?

Under the hood it uses the Haxe EReg class: https://api.haxe.org/EReg.html
This class is part of the Haxe standard library, which means no haxelib downloads are required.

### CODE REVIEW

**Review by moxie-coder — APPROVED** [review]

**Comment by BeastlyGabi** [comment]
you should probably push these changes to https://github.com/ShadowMario/FNF-PsychEngine/tree/experimental instead

**Comment by stevecodergh** [comment]
@BeastlyGabi alright, never knew that existed

**Comment by stevecodergh** [comment]
done

**Comment by stevecodergh** [comment]
damn it

**Comment by stevecodergh** [comment]
there we go!

**Comment by Magnumsrt** [comment]
@ShadowMario merge for a cookie :)

**Comment by MemeHovy** [comment]
> @ShadowMario merge for a cookie :)

he has his notifications off, and mentioning him will only get you banned

**Comment by Magnumsrt** [comment]
> > @ShadowMario merge for a cookie :)
> 
> he has his notifications off, and mentioning him will only get you banned quicker(?)

oh alright, sorry!

**Comment by MemeHovy** [comment]
it's alright

**Comment by Stilic** [comment]
useless pr since lua already has regex utils

**Comment by MemeHovy** [comment]
> useless pr since lua already has regex utils

oh, I looked it up and turns out it does, so yeah I'm taking my approval back

**Comment by MemeHovy** [comment]
not to mention, you could possibly use runHaxeCode to import EReg or something like that

**Comment by Magnumsrt** [comment]
> useless pr since lua already has regex utils

it has _pattern matching_ which I already knew and it's pretty weak, actual regex can do a lot more.

**Comment by Magnumsrt** [comment]
> > useless pr since lua already has regex utils
> 
> oh, well I looked it up and turns out it does, so yeah I'm taking my approval back

it has pattern matching which I already knew and it's pretty weak, actual regex can do a lot more.

**Comment by KookerFoxYT** [comment]
> useless pr since lua already has regex utils

while i could agree
one problem is that lua's own regex utilities are reasonably inadequate

**Pull request closed without merging**
