### PR TITLE
Update hxCodec Libraries

### PR DESCRIPTION
**Pull request by crowplexus**
this allows for videos on linux and a handy skip button for them (linux is disabled for the time being)

### CODE REVIEW

**Review by EyeDaleHim — APPROVED** [review]
I like this a lot

**Comment by jigsaw-4277821** [comment]
If I remember correctly the height is bugged on hxCodec so this is a bad addition

**Review by stilic — COMMENTED** [review]
Why these files are still here?

**Comment by BeastlyGhost** [comment]
> Why these files are still here?

because the game won't compile without them, that's why shadowmario copied them to the source folder in the first place

**Comment by Stilic** [comment]
They are already included in the Haxelib package. We just need to install it.

Now, I recommand you to remove these files and to add a note inside the README.

**Comment by BeastlyGhost** [comment]
> They are already included in the Haxelib package. We just need to install it.
> 
> Now, I recommand you to remove these files and to add a note inside the README (and also to install HxCodec using Haxelib if it isn't done already).

won't do, I want to have the files there to make double sure this will work, I did test compiling without them and I just don't want to have new issues regardling compiling issues because the vlc folder doesn't exist, if it works, then it works, leave it as is

**Comment by Stilic** [comment]
> > They are already included in the Haxelib package. We just need to install it.
> > Now, I recommand you to remove these files and to add a note inside the README (and also to install HxCodec using Haxelib if it isn't done already).
> 
> won't do, I want to have the files there to make double sure this will work, I did test compiling without them and I just don't want to have new issues regardling compiling because the vlc folder doesn't exist, if it works, then it works, leave it as is

Sorry but I tried back before my PR for add hxCodec was closed with the Haxelib and it perfectly worked.
So, seriously, remove these files please.

**Comment by BeastlyGhost** [comment]
> You all know then the height is glitched in hxCodec right?

I know, it's not my job to fix it though, and even then if poly ever fixes it, no PR needs to be made

**Comment by Stilic** [comment]
> You all know then the height is glitched in hxCodec right?

fix it then lol

**Comment by jigsaw-4277821** [comment]
> 

I tryed almost a month and nothing

**Comment by jigsaw-4277821** [comment]
@BeastlyGhost  did

**Comment by BeastlyGhost** [comment]
made another one just to wrap it up on one commit

**Pull request closed without merging**
