### PR TITLE
A main menu

### PR DESCRIPTION
**Pull request by HeptatonicScale**

### CODE REVIEW

**Comment by cabfile** [comment]
what the fuck

**Comment by Stefan2008Git** [comment]
THE FUCK IS THIS? THE OLDEST PE VERSION COMMITS FROM OLDER MAJIGSAW77 PORT?

**Comment by CharlesCatYT** [comment]
ah shit here we go again

**Comment by CobaltBar** [comment]
Tf

**Comment by idkwhattonamethisimnevergoingtousethis** [comment]
What

**Comment by system32unknown** [comment]
image

**Pull request closed without merging**
