### PR TITLE
Adding more things to psych engine

### PR DESCRIPTION
**Pull request by DabbinDude316B**

### CODE REVIEW

**Review by DillyzThe1 — COMMENTED** [review]
Honestly, I don't see the point.

Lua versions:
- `addHealth(amount)`
- `setHealth(amount)`
- `doTweenAlpha(tag,char,0,1.0,'easeInOut')`
- just setting the color for everyone and adding a white sprite behind (no i'm not writing it for you)

<i>NOTE: If I got the functions wrong, I don't care.</i>
<i> Just look for them.</i>


<i>Also, your programming is redundant by itself.</i>

**Comment by Mastercopper2346** [comment]
Im going to add more events over time, not just these!

**Comment by Mastercopper2346** [comment]
plus, this is SOURCE. not lua!

**Comment by DillyzThe1** [comment]
i mean, yeah, i'm obviously aware that you're doing basic haxeflixel by itself.
i read and understood the changes and commented on how it was also weird how you just pasted an flxtween a ton instead of just making a character variable to tween

i just want to know what the point is when health modifiers are not something you typically need as an event when not needed for an oddly specific part of a song that turns into a literal printer (at that point just use lua)

the idea of the silhouette was pretty cool tho

**Comment by EyeDaleHim** [comment]
Trash PR, those are not good events.

**Comment by Mastercopper2346** [comment]
1. Pls stop being toxic
2. It’s a draft, I’m going too add more stuff

**Comment by frantastic24** [comment]
you could at least list what you plan to add because as it is, this is pretty useless

**Review by rodney528 — COMMENTED** [review]
This... is not needed.

**Comment by Stilic** [comment]
> 1. Pls stop being toxic
> 2. It’s a draft, I’m going too add more stuff

YOU are toxic. all the prs that you did are each time shitty prs.

**Comment by ImaginationSuperHero528** [comment]
Yeah, dude stop trying to merge these.

**Comment by Raltyro** [comment]
geez

**Comment by DillyzThe1** [comment]
alright, this pull request honestly looks more useful now
like i could see this actually getting used by some people

4 things i want changed though:
- on the animation.play() function, make sure to add an argument for "Forced:Bool" that checks if value2.toLoweCase() is true, t, 1, or yes
- change "Screen Effect" to "Silhouette" (and maybe make it tween?)
- change the programming in the alpha tween to work by going through characters in an arrya and making a tween for them by using shorter code, also solving the fact that you called variable "boyfriend" by "alpha", which causes a null object reference and an alpha tween error
- consider using the modchart sprite system for the images for better usage of sprite placement and organization

if you do not know how to change any of this but may want to, i could try to make a pr to fix it & i'd test everything out before submitting the pr on my own pc

**Comment by DillyzThe1** [comment]
oh, and sorry for being rude earlier.

**Comment by EyeDaleHim** [comment]
Trash PR even more because of the forced crash game event, remove it, it will make the game malicious in a way.

**Comment by DillyzThe1** [comment]
malicious?! how?!?!
it's literally just a built in exit function in haxeflixel that's present in various forms across ANY programming language that causes no harm to any computer
also you can already do it from lua anyway

ofc, i'm not saying it's good or bad as something like an event, i'm just asking how it's "malicious" to close the game window

**Comment by EyeDaleHim** [comment]
> malicious?! how?!?! it's literally just a built in exit function in haxeflixel that's present in various forms across ANY programming language that causes no harm to any computer also you can already do it from lua anyway
> 
> ofc, i'm not saying it's good or bad as something like an event, i'm just asking how it's "malicious" to close the game window

So you're saying forcefully exiting the application from itself is not malicious? It's very invasive to just forcefully close the game window.

**Comment by DillyzThe1** [comment]
i never stated my opinion on weither or not is was a good change
anyway yes im pretty sure closing a window isn't a "malicious command", but can be annoying and possibly unwanted for a sudden unexpected close that isn't asked for or reasonable

i will agree that the accessability of it being there as a built in event in unwanted mid-song mechanics is where its a step too far

**Comment by lemz1** [comment]
the image doesnt even appear because it hasnt been added. Also all of the events are useless because you can do them in lua.

**Comment by doinkers** [comment]
> > malicious?! how?!?! it's literally just a built in exit function in haxeflixel that's present in various forms across ANY programming language that causes no harm to any computer also you can already do it from lua anyway
> > ofc, i'm not saying it's good or bad as something like an event, i'm just asking how it's "malicious" to close the game window
> 
> So you're saying forcefully exiting the application from itself is not malicious? It's very invasive to just forcefully close the game window.
> 
> Plus, a script is fine for exiting the game windows, but having it as an event even on base psych can be too far.

I'm confused. How is a program closing itself in any way malicious?

**Comment by EyeDaleHim** [comment]
> > > malicious?! how?!?! it's literally just a built in exit function in haxeflixel that's present in various forms across ANY programming language that causes no harm to any computer also you can already do it from lua anyway
> > > ofc, i'm not saying it's good or bad as something like an event, i'm just asking how it's "malicious" to close the game window
> > 
> > 
> > So you're saying forcefully exiting the application from itself is not malicious? It's very invasive to just forcefully close the game window.
> > Plus, a script is fine for exiting the game windows, but having it as an event even on base psych can be too far.
> 
> I'm confused. How is a program closing itself in any way malicious?

If you're making a "Close Game" button, that's fine, but it's dangerous to have it as an event.

**Comment by Mastercopper2346** [comment]
rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr

**Comment by thecosmicgamer29** [comment]
smh what a bad pr

**Comment by kingyomoma** [comment]
this was almost 2 months ago

**Comment by Lokitot** [comment]
missing ; in " var char:String == 'all'; "

**Comment by DabbinDude316B** [comment]
Why I here 💀

**Comment by Lokitot** [comment]
> Why U here 💀

no, Why U here 😱

**Pull request closed without merging**
