### PR TITLE
scoretxt never updates unless you did hit/miss a note

### PR DESCRIPTION
**Pull request by crowplexus**
can prevent memory leaking due to that text being updated every frame

example video:

https://user-images.githubusercontent.com/45212377/176214243-31123860-2a89-4d38-8b10-a8c4e8b4a57d.mp4

### CODE REVIEW

**Comment by trayfellow** [comment]
waletr., whit e

**Review by Trayfellow — APPROVED** [review]

**Comment by BeastlyGhost** [comment]
> waletr., whit e

https://user-images.githubusercontent.com/45212377/176217100-e89192b3-15dc-4dce-af3e-bf89bea87f9d.mp4

!!!

**Comment by BeastlyGhost** [comment]
> Hwalter hwite... Also wouldn't updating score under `recalculateRating()` also work? I have it like that on a personal build and I'm wondering if your way would be better instead

hmmm you're right, gonna test this

**Review by stilic — APPROVED** [review]

**Review by TheKitBoi — APPROVED** [review]

**Review by BombasticTom — APPROVED** [review]
@ShadowMario approve!!!!

**Comment by BeastlyGhost** [comment]
oh yeah, for custom score shits, you need to use `onRecalculateRating`

example:

```
function onRecalculateRating()
    if ratingFC == '' then -- if the FC is nothing
        setProperty('scoreTxt.text',
        'Score: ' .. score ..
        ' • Misses: ' .. misses ..
        ' • Accuracy: ' ..round(rating * 100, 2).. '%')
    else
        setProperty('scoreTxt.text',
        'Score: ' .. score ..
        ' • Misses: ' .. misses ..
        ' • Accuracy: ' ..round(rating * 100, 2)..
        '% [' ..ratingFC..']')
    end
end
```

**Review by GO-Miles — APPROVED** [review]
Jesse, we need to approve this PR.

**Comment by BombasticTom** [comment]
right now

**Pull request merged**
