### PR TITLE
Add updated vocals and instrumentals from Base Game to Psych Engine

### PR DESCRIPTION
**Pull request by BombasticTomDev**
This pull request adds all the new separated Vocal tracks, and updated Instrumentals from the new 0.3.0 prototype update of Friday Night Funkin'.

### CODE REVIEW

**Review by ACoolioDude — APPROVED** [review]

**Comment by ShadowMario** [comment]
image
I'm not adding erect songs in

**Comment by RodneyAnImaginativePerson** [comment]
> image
> I'm not adding erect songs in

BOOOOOOOOOOOO

**Comment by BombasticTomDev** [comment]
OHH. I just realized what happened. I forgot to remove the Base Game `dadbattle` folder. The difference is that Psych Engine's Dadbattle folder is `dad-battle`. The erect remix in Fresh was an oversight.

**Comment by Gearybeer** [comment]
Damn, no more erect.

**Pull request merged**
