### PR TITLE
Character Editor Black Background + Weekend 1 + Finish It! plz + Extra Keys

### PR DESCRIPTION
**Pull request by KadeMeme2024**
So Theres Alot Of Things Going On In The Character Editor (Only The Character Editor Ignore The Others) Heres The Problem The Editor Has a Random Large Black Box Infront Of The In-game Hud, Someone Already Have a Solution, Also Please Add Weekend 1 And All The Other Weeks And Finish It, i Just Cant Wait Till' It Comes Out, Just Finish a Few In The Source And Fuala, i Saw The 1.0b Build! [For The Character Editor Or Just Copy My Character Editor From My Deluxe Version :) plz](https://github.com/ShadowMario/FNF-PsychEngine/pull/14495#issuecomment-2117432754), And Also Can You Please Add Extra Keys In a Different Psych Update, Why Different Update? i Just Cant Wait Till' The Update Comes out (You Dont Have Too If You Want)

### CODE REVIEW

**Comment by LarryFrosty** [comment]
Dawg what

**Comment by brusakas** [comment]
what tf is bro doing here talking about extra keys lmao 💀

**Comment by CobaltBar** [comment]
:skull:

**Comment by Sword352** [comment]
psych engine prs in a nutshell

**Pull request closed without merging**
