### PR TITLE
Add an optional third value

### PR DESCRIPTION
**Pull request by ghost**
This PR adds an optional third value to event notes since some people can need an extra value.
For now only "Change Scroll Speed" event uses an extra value which is an optional ease.

Example video here:

https://user-images.githubusercontent.com/106805332/193344326-14ba8e01-439a-4bff-8ab0-5f3f64517bf1.mp4

For using value 3 in softcoded events with Lua, just put this at the start:
```setTheNeedOfValue3(true);```

### CODE REVIEW

**Review by rodney528 — APPROVED** [review]

**Review by MemeHoovy — APPROVED** [review]

**Comment by MemeHoovy** [comment]
so epic

**Review by TheKitBoi — APPROVED** [review]

**Review by Parsellol — APPROVED** [review]

**Comment by LilDrippyMyFnf** [comment]
Great idea

**Review by DaRealDotZ — APPROVED** [review]

**Comment by ImaginationSuperHero528** [comment]
Why did you close this?

**Comment by MemeHoovy** [comment]
> Why did you close this?

his account got deleted

**Comment by ShadowMilky** [comment]
yea, at least i merged it to my mod, shame that i cant credit for said pr

**Review by jmxamongusmodder — COMMENTED** [review]
gud

**Comment by TheKitBoi** [comment]
> gud

This crap is closed why review it

**Pull request closed without merging**
