### PR TITLE
gameplay modifiers

### PR DESCRIPTION
**Pull request by nebulazorua**
idk bunch of gameplay modifiers

### CODE REVIEW

**Review by michaelforev — APPROVED** [review]
very amazing

**Review by HeliProGamer — APPROVED** [review]
That's what psych engine needs, more gameplay modifiers!

**Review by TheKitBoi — APPROVED** [review]

**Review by mayo78 — APPROVED** [review]

**Review by Raltyro — APPROVED** [review]

**Comment by CesarGpe** [comment]
cool

**Review by ThatOneSillyGuyDon — APPROVED** [review]
very epic.

**Comment by nebulazorua** [comment]
so apparently no fail is practice mode
fuck

**Comment by nebulazorua** [comment]
and it is gone

**Review by EndorrrH — COMMENTED** [review]
cool

**Pull request closed without merging**
