### PR TITLE
made a simple thing that may prevent event crashes

### PR DESCRIPTION
**Pull request by nahiassis**

### CODE REVIEW

**Comment by nintendofan44** [comment]
nvm it doesnt prevent crashes
but its cool and can say to the user if an event doesn't exist

**Comment by Stilic** [comment]
> nvm it doesnt prevent crashes but its cool and can say to the user if an event doesn't exist

you should open a dialogue box instead of tracing shit in the console

**Comment by nintendofan44** [comment]
i will do that later or use luatrace

**Comment by BombasticTom** [comment]
LOL

**Pull request closed without merging**
