### PR TITLE
added an import checker

### PR DESCRIPTION
**Pull request by Blossomical**
checks for imports
```hx
var code:String = "
     import flixel.FlxSprite;
     import flixel.text.FlxText;
     
     var abc:String = 'hello import flixel;'; // does not check for imports here since its inside a string
";
trace(getImports(code)) // output: flixel.FlxSprite, flixel.text.FlxText
// after removing all imports using regex:
trace(code) // output: var abc:String = "hello import flixel;";
```

### CODE REVIEW

**Review by DetectiveBaldi — APPROVED** [review]
pretty neat

**Comment by jimmyjamescool** [comment]
im eating jolly ranchers from my ass

**Review by jimmyjamescool — APPROVED** [review]

**Review by libauror-a — APPROVED** [review]
my balls itch

**Comment by Cherif107** [comment]
oh my god i did not mean to close this

**Comment by ThePlank** [comment]
oops mb 😊

**Pull request closed without merging**
