### PR TITLE
Additional functions of FlxColor to hscript

### PR DESCRIPTION
**Pull request by TheLeerName**
say hello to `FlxColor.interpolate()` 👋👋👋

### CODE REVIEW

**Review by ghost — APPROVED** [review]
acceptable

**Review by moxie-coder — APPROVED** [review]

**Review by rodney528 — APPROVED** [review]

**Review by rodney528 — APPROVED** [review]

**Comment by ShadowMario** [comment]
Question, why was it turned into a instance?

**Comment by TheLeerName** [comment]
> Question, why was it turned into a instance?

its better than make it all statics

**Comment by TheLeerName** [comment]
#13323

**Pull request closed without merging**
