### PR TITLE
Add things to lua that would just make me happier lol

### PR DESCRIPTION
**Pull request by KlavierGayming**
Adds an hscript function, which will execute Haxe code when the function is ran. There's some classes defined already.
Adds a getRandomInt and getRandomBool because math.random SUCKS.

### CODE REVIEW

**Comment by THOBY555** [comment]
Just Do Notes Tweens And You Will Make Friday Night Fever XD

**Comment by KlavierGayming** [comment]
what?
this adds some actually i think useful stuff. but idk.

**Comment by nintendofan44** [comment]
would be nice if you explained how those work

**Comment by KlavierGayming** [comment]
getRandomInt will return a number between min and max and getRandomBool Will return a bool depending on the Chance you put in to get a true

**Comment by KlavierGayming** [comment]
hscript() Just runs haxe code that you put inside of the code argument

**Comment by KlavierGayming** [comment]
call Method calls a method

**Comment by nintendofan44** [comment]
> hscript() Just runs haxe code that you put inside of the code argument

like bopeebo rumble?
the modchart for that is on a .hx file

**Comment by KlavierGayming** [comment]
Kind of. you'll need to make loads of modificiations but it will work.

**Comment by Steviegt6** [comment]
> > hscript() Just runs haxe code that you put inside of the code argument
> 
> like bopeebo rumble? the modchart for that is on a .hx file

I believe 4mbr0s3 uses Haxe hotloading, so basically yes. Last I checked, his engine provides an actual modding API and will load separate modules, basically abstracting stuff away and adding hooks for maximum compatibility between mods.

**Comment by ShadowMario** [comment]
> getRandomInt will return a number between min and max and getRandomBool Will return a bool depending on the Chance you put in to get a true

This already exists, it's called math.random

**Comment by KlavierGayming** [comment]
I literally said in the pr description
"Because math.random SUCKS."
It can only generate a new random number every second so you would need to do something Like
'''lua
math.random and math.random and math.random and math.random and math.random and math.random and math.random(1, 2)
'''

**Comment by KlavierGayming** [comment]
i like how you dont even look at the stuff i added, you just see that i added a random number generator and you close it.
We have pretty much no way to do randomBool thats other than 50% on lua!
and we cant call external functions! i added both those things.

**Comment by KlavierGayming** [comment]
ok i got a bit mad there, just gonna make the random int generator in lua...

**Comment by KlavierGayming** [comment]
i made it, if anyone else doesnt like math.random here it is..
contains float, int and bool functions

```lua
local MODULUS = getPropertyFromClass('FlxMath', 'MAX_VALUE_INT');
local internalSeed = 1;
local MULTIPLIER = 48271.0

function generate()
    return internalSeed = (internalSeed * MULTIPLIER) % MODULUS
end

function int(Min, Max)
    if Min == 0 and Max == MODULUS then
        return math.floor(generate());
    elseif Min == Max then
        return Min;
    else
        if Min > Max then
            Min = Min + Max
            Max = Min - Max
            Min = Min - Max
        end

        local result = 0
        
        result = math.floor(Min + generate() / MODULUS * (Max - Min + 1))

        return result;
    end
end

function float(Min, Max)
    if Min == 0 and Max == 1 then
        return generate() / MODULUS;
    elseif Min == Max then
        return Min;
    else
        if Min > Max then
            Min = Min + Max
            Max = Min - Max
            Min = Min - Max
        end

        local result = 0
        
        result = Min + generate() / MODULUS * (Max - Min + 1)

        return result;
    end
end

function bool(chance)
    return float(0, 100) < chance;
end
```

**Comment by KlavierGayming** [comment]
i tried copying FlxRandom's algorithm for randomizing

**Comment by BobbyDrawz** [comment]
> hscript() Just runs haxe code that you put inside of the code argument

uhh you know there's runHaxeCode()?

**Comment by Rudyrue** [comment]
> uhh you know there's runHaxeCode()?
this pr is from 2021

**Comment by BobbyDrawz** [comment]
> > uhh you know there's runHaxeCode()?
> 
> this pr is from 2021 runHaxeCode wasn't added until like a year later

ty for info

**Pull request closed without merging**
