### PR TITLE
So i think deleting -D 32bits will fix the 0.6.3 32Bits Problem

### PR DESCRIPTION
**Pull request by SoLuzid**
So i think deleting -D 32bits will fix the 0.6.3 32Bits Problem

### CODE REVIEW

**Review by MemeHoovy — CHANGES_REQUESTED** [review]
you made many more changes though

**Comment by CaptainBaldi** [comment]
image
how does this solve 32bits being broken

**Comment by ElPro7777** [comment]
i used my fork XD

> you made many more changes though



> image how does this solve 32bits being broken

**Comment by MemeHoovy** [comment]
> and idk how to delete other commits

make a new fork without those stupid commits by making a new branch

**Review by MemeHoovy — CHANGES_REQUESTED** [review]
make a new branch without those stupid commits

**Comment by ElPro7777** [comment]
> make a new branch without those stupid commits

HEY >:( Dont say that are stupid commits (i am making a Psych engine Epic Gamer Edition aka Pro Engine)

**Comment by MemeHoovy** [comment]
well don't include non related commits next time you make a PR

**Comment by CaptainBaldi** [comment]
> > make a new branch without those stupid commits
> 
> HEY >:( Dont say that are stupid commits (i am making a Psych engine Epic Gamer Edition aka Pro Engine)

1. that name is ass
image
2. these commits make it look like ur fork isnt going to be good 
im betting those rtx sprites are stolen
and changing gf's position isnt at all needed

**Comment by ElPro7777** [comment]
They ARE NOT STOLEN

> > > make a new branch without those stupid commits
> > 
> > 
> > HEY >:( Dont say that are stupid commits (i am making a Psych engine Epic Gamer Edition aka Pro Engine)
> 
> 1. that name is ass
>    image
> 2. these commits make it look like ur fork isnt going to be good
>    im betting those rtx sprites are stolen
>    and changing gf's position isnt at all needed
> 
> so they're right when they say your commits are stupid

I  made them with Hoken's tutorial

**Comment by ElPro7777** [comment]
> > > make a new branch without those stupid commits
> > 
> > 
> > HEY >:( Dont say that are stupid commits (i am making a Psych engine Epic Gamer Edition aka Pro Engine)
> 
> bro is probably gonna steal w.i code.

That Was The WORST JOKE I EVER HEARD, i forked w.i because i was testing the json (hash) feature

**Comment by ElPro7777** [comment]
its cool feature

**Pull request closed without merging**
