### PR TITLE
Readme Changes

### PR DESCRIPTION
**Pull request by govinda777**

### CODE REVIEW

**Comment by Vortex2Oblivion** [comment]
what

**Comment by Rudyrue** [comment]
chatgpt ah pr

**Comment by Rudyrue** [comment]
oh wait nvm their entire account is just chatgpt lmfao

**Comment by crowplexus** [comment]
muito bom cara parabéns

**Comment by Stefan2008Git** [comment]
GhatGPT ahhhh readme file

**Comment by ShadowMario** [comment]
Dude who the fuck are you why are you here you retard

**Pull request closed without merging**
