### PR TITLE
Text Box In Credits Menu

### PR DESCRIPTION
**Pull request by MAJigsaw77**
I mean it looks cool with it, just look
Screenshot (118)

### CODE REVIEW

**Comment by jigsaw-4277821** [comment]
Don't look at the back background it's.for my mod

**Comment by CrusherMods** [comment]
that actually looks kinda nice ngl

**Review by HiroMizuki — APPROVED** [review]
maybe

**Comment by jmxamongusmodder** [comment]
looks cool ill use it for my mod!

**Comment by MrClogsworthYT** [comment]
ill steal dis for my engine

**Comment by jigsaw-4277821** [comment]
:(

**Comment by MrClogsworthYT** [comment]
> :(

this is the world of being open source

**Comment by XtraXD1** [comment]
I could steal the idea, but make it myself. :))

**Comment by XtraXD1** [comment]
jk, i wont do so.
i wont include it after all, but good detail. :)

**Comment by jmxamongusmodder** [comment]
hey thx for the code i copyed it over to achivements menu state and it looks soo cool! i may add it to all the options states and everything!

**Comment by XtraXD1** [comment]
~~Garcello, agachate y conocelo.~~
~~(Garcello, crouch and meet it.)~~

**Review by steviegt6 — APPROVED** [review]
Code-wise, looks good.

**Comment by MaxlionButMyNameIsTakenSoThisIsmyName** [comment]
Definetly looks cleaner and could help for white/gray background colours.

**Comment by doggogit** [comment]
This is a small addition, but it can help with backgrounds that have bright colors.

Added this to a mod's repository, credited you, as well as linked the original pull request.

(If you have any problems with this, you can contact me about it and I'll be more than happy to take it down)

**Comment by Gui-iago** [comment]
he made one himself, I think you can close this

**Review by crowplexus — APPROVED** [review]
it looks neat though

**Review by TheKitBoi — APPROVED** [review]

**Review by megasssdev — APPROVED** [review]

**Comment by jigsaw-4277821** [comment]
Is already in it, so

**Pull request closed without merging**
