### PR TITLE
Fix note tails being a little too long

### LINKED ISSUE #1493: Hold notes are way too long
### Describe your bug here.

Psych engine build
image
Non-psych engine build
image
These notes have the exact same hold times, which are often seem to be longer than they are programmed to be. I chart using an external program, so if these issues do not occur in psych engine's editor, then sorry about that. However, when porting songs from different engines to psych engine, hold notes become a lot longer, meaning you have less time to comfortably switch between notes.

I do not know if this is a visual bug or if it actually requires that the notes be held longer. The fix is to interpret all notes in a chart as being ever-so-slightly shorter than they are.

Example where a problem could rise:
image

Notice that I have a very small time window between lifting up <- and pressing down.

### Command Prompt/Terminal logs (if existing)

```bash
-
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No source code changes.

### PR DESCRIPTION
**Pull request by stilic**
(Kinda) fixes #1493.

### CODE REVIEW

**Review by MemeHoovy — APPROVED** [review]

**Review by DabbinDude316B — APPROVED** [review]
Finally I won’t lose my 0 misses streak to a goofy ahh sustain note

**Review by DetectiveBaldi — APPROVED** [review]
this is the one thing this engine needed but also the one thing no one bothered to do
props to you

**Review by Luisinhi010 — APPROVED** [review]

**Review by Luisinhi010 — APPROVED** [review]

**Comment by Luisinhi010** [comment]
shadow mario te dou 50 reais se tu aprovar esse pr

**Review by TheKitBoi — APPROVED** [review]

**Review by TheRealJake12 — APPROVED** [review]

**Review by aaaproooo — APPROVED** [review]

**Comment by TheRealJake12** [comment]
the one weird ass left note in fresh is still too long but ig I shall cope

**Pull request closed without merging**
