### PR TITLE
Source Code

### PR DESCRIPTION
**Pull request by StefanBETA**
Hello Saw,I Just Wanna Want To Compile Source Code On Android,But I Cant,Are You Deactivated Or Someting?

### CODE REVIEW

**Comment by TheRealJake12** [comment]
what... is this?

**Comment by HaxLua** [comment]
god please no

**Comment by ManMaster707** [comment]
You CAN'T compile source code on android, now don't become a second @nimudevUwU and close this, please

**Comment by hayfii** [comment]
> You CAN'T compile source code on android, now don't become a second @NimuDevUwU and close this, please

You can but you need the Android build + It's also complicated

**Comment by HiroMizuki** [comment]
why are you pulling psych engine android repo to the main original psych?

**Comment by ManMaster707** [comment]
> You can but you need the Android build + It's also complicated

ok, fair enough, but then explain why did he do all of this here?
He could have just done it on the android build's prs

**Comment by PrismLight** [comment]
AGAIN?
FUCK PR'S!

**Comment by HiroMizuki** [comment]
> > You can but you need the Android build + It's also complicated
> 
> ok, fair enough, but then explain why did he do all of this here? He could have just done it on the android build's prs

the only reason is cuz the PR's author wants mobile support, but it's not needed
and pulling this to the android build's repo would change nothing actually

**Comment by ManMaster707** [comment]
> the only reason is cuz the PR's author wants mobile support, but it's not needed
and pulling this to the android build's repo would change nothing actually

Oh, thank you for making clear everything that I wanted to say from the beginning:
**This is useless.**

**Comment by BeastlyGhost** [comment]
wrong repository man, close this

**Comment by zacksgamerz** [comment]
Wrong repository, and wrong way to request an issue. This isnt jigsaw's source code, and pullrequests is for contributors to help out on the development of the code, make an issue instead on jigsaw's source code.

**Comment by silvashp** [comment]
idiots!

**Comment by TheKitBoi** [comment]
no wonder why some pull request are 20% of the time just stupid and not spread drama

**Comment by Mastercopper2346** [comment]
GUYS STOP BEING TOXIC AND ACTUALLYSSUPPORT THIS GUY FOR TRYING

**Comment by Mastercopper2346** [comment]
im going to block everyone toxic.

**Comment by frantastic24** [comment]
Cope harder

**Comment by PrismLight** [comment]
> GUYS STOP BEING TOXIC AND ACTUALLY SUPPORT THIS GUY FOR TRYING

Dumbass he didn't try. That isn't even his build it's some random guys that he stole.

> im going to block everyone toxic.

Thanks now I can go back into the basement.

**Pull request closed without merging**
