### PR TITLE
Controller support (not really sure if it gives the right results)

### PR DESCRIPTION
**Pull request by tposejank**
I'm using a PS3 controller, I had this idea, I put a bunch of stuff in a new Menu, and it seems pretty good.
It might not give the right inputs, but It does what it's supposed to.

### CODE REVIEW

**Review by cfgexe — APPROVED** [review]
WOw this is cool

**Comment by Gui-iago** [comment]
at least with my xbox series X controller, it doesn't give the rights results, for example, if I move the left stick to any direction, it can either bind it as "B", "Y" or "X", when in-game, I need to press those exact buttons (instead of moving the left stick) in order to do said action

**Comment by cfgexe** [comment]
we need to add a thing to options menu where it asks you if you have a xbox or playstation controller and then modifies the results

**Comment by tposejank** [comment]
> we need to add a thing to options menu where it asks you if you have a xbox or playstation controller and then modifies the results
> 

i was planning on doing that but
i thought would someone even care to use this
i mean, like this you would only see it on the menu.

**Comment by cfgexe** [comment]
we could use save data and determine if this is the first time ran with a controller and ask then?

**Comment by cfgexe** [comment]
bruh

**Pull request closed without merging**
