### PR TITLE
Replace Title Text with fewer frames

### PR DESCRIPTION
**Pull request by Raltyro**
this pr makes it so that title text doesnt need huge image anymore for animation
now it changes color

(also works with older asset for titleEnter)

### CODE REVIEW

**Review by DM-kun — APPROVED** [review]

**Review by ghost — APPROVED** [review]
YO THIS IS AWESOME

**Comment by Mastercopper2346** [comment]
I approve

**Review by DabbinDude316B — APPROVED** [review]

**Review by TheKitBoi — APPROVED** [review]

**Review by CrusherNotDrip — APPROVED** [review]
fucking epic

**Review by Fridox-lol — APPROVED** [review]
now it's easier to edit it

**Review by raf13lol — APPROVED** [review]
yuh fire

**Pull request merged**
