### PR TITLE
Added sampler2D input support to FlxRuntimeShader

### PR DESCRIPTION
**Pull request by UncertainProd**
FlxRuntimeShader currently doesn't seem to have a method to set sampler2D inputs on the run-time shaders. This pr adds support for sampler2D inputs as well. It also adds a corresponding lua function to set/manipulate these inputs as well.
Usage in lua:
```lua
initLuaShader('your-shader-name')
setSpriteShader('your-sprite', 'your-shader-name')
setShaderSampler2D('your-sprite', 'my_tex_input', 'path-to-image-to-use-as-sampler2d')
```

In the shader:
```glsl
uniform sampler2D my_tex_input;
void main()
{
    // stuff you wanna do with the texture input
}
```

### CODE REVIEW

**Review by MemeHoovy — APPROVED** [review]

**Review by iym1337 — APPROVED** [review]

**Review by TheKitBoi — APPROVED** [review]

**Review by system32unknown — APPROVED** [review]

**Review by EliteMasterEric — APPROVED** [review]
I have a similar change in an update to my FlxRuntimeShader PR, but that also has changes that require an update to OpenFL so this looks good to me.

The only real difference is that you called it sampler2D and I called it BitmapData

**Review by Luisinhi010 — APPROVED** [review]

**Review by Raltyro — APPROVED** [review]
🙏 🙏 🙏

**Review by lunacynne — APPROVED** [review]

**Comment by ItsyourboyJonnycat** [comment]
please merge @ShadowMario

**Comment by TheKitBoi** [comment]
He has notifications off

**Comment by ItsyourboyJonnycat** [comment]
damn

**Pull request merged**
