### PR TITLE
Fixed crash on pause menu

### PR DESCRIPTION
**Pull request by dtwotwo**
I noticed that when changing the difficulty in a pause, if the chart was not found, then the game just crashed.
I fixed this problem and now the game writes that the chart was not found without crashes.

### Before:

https://github.com/ShadowMario/FNF-PsychEngine/assets/97068888/f94c4a05-9e32-4464-ad55-0de5f76bf2f9

### After:

https://github.com/ShadowMario/FNF-PsychEngine/assets/97068888/ee5738f6-70e2-4640-bb33-31f6bfe4fca6

### CODE REVIEW

**Review by moxie-coder — APPROVED** [review]

**Review by DarkWeBareBears69 — APPROVED** [review]
Yo! I really want this on the next version!

**Review by jimmyjamescool — APPROVED** [review]

**Comment by jimmyjamescool** [comment]
Hey wait does this also work in the chart editor when opening a json with an invalid difficulty

**Comment by Danya20072019** [comment]
> Эй, подождите, это также работает в редакторе диаграмм при открытии json с недопустимой сложностью?

it looks like it was in the latest version

**Comment by Danya20072019** [comment]
> Hey wait does this also work in the chart editor when opening a json with an invalid difficulty
it looks like it was in the latest version

**Comment by CaptainBaldi** [comment]
this problem is caused by really simple human error, and the crash handler also tells you which file is missing, this isn't needed

**Comment by ShadowMario** [comment]
I'm only human after all
anim

**Comment by jimmyjamescool** [comment]
Don’t put the blame on me
3F86A022-08A5-4B9E-8EAF-7467DB9EAF9B

**Pull request merged**
