### PR TITLE
Basic Video Sprites in Lua and Source

### PR DESCRIPTION
**Pull request by BendyGaming0**
Still needs to be tested but BGSprites and ModchartSprites can be attached to video bitmaps and display the bitmap onto the sprite

still needs pause, resume, loops, volume and audio support as well as not breaking the music

### CODE REVIEW

**Comment by BendyGaming0** [comment]
whoops, looks like there isn't a music problem, i was looking at something else and got mixed up.

**Review by GamerZoneMusic — APPROVED** [review]
I didn't test but I think it is very cool!

**Comment by BendyGaming0** [comment]
the compiler doesn't like how im doing this so ill do it another way

**Comment by BendyGaming0** [comment]
the Windows build has passed, Linux and Mac however are complaining over nothing.

**Review by TheKitBoi — COMMENTED** [review]
The latest commit failed the compile on win, mac and linux, just a reminder for the pull requester

**Comment by Jrmcwicked** [comment]
OMG WHAT I WAS LOOKING FOR THIS EVERYWHERE THANK YOU

**Comment by BendyGaming0** [comment]
I'm going to close this pull, it's too buggy and I don't really have the focus for this. plus this is really only gonna be used in very specific cases where there is source code modification

**Pull request closed without merging**
