### PR TITLE
Cleaned up code & removed useless shit

### PR DESCRIPTION
**Pull request by MemeHoovy**
title says all, also tried to add flxanimate support but that didn't work so fuck that shit

### CODE REVIEW

**Comment by Stilic** [comment]
it doesn't build at all on mac and linux

**Comment by MemeHoovy** [comment]
> it doesn't build at all on mac and linux

🤷🏻‍♂️

**Comment by Stilic** [comment]
> > it doesn't build at all on mac and linux
> 
> 🤷🏻‍♂️ it should work fine on both, I didn't take out anything that could possibly break both

oh sorry didn't noticed the reason was that haxelib server got fucked up at build time

**Comment by MemeHoovy** [comment]
> > > it doesn't build at all on mac and linux
> > 
> > 
> > 🤷🏻‍♂️ it should work fine on both, I didn't take out anything that could possibly break both
> 
> oh sorry didn't noticed the reason was that haxelib server got fucked up at build time

it's fine

**Review by APRO716 — APPROVED** [review]

**Comment by MaybeMaru** [comment]
dont take blah blah blah coolswag away from me
put it back

**Comment by MemeHoovy** [comment]
> dont take blah blah blah coolswag away from me
> 
> put it back

No

**Review by CoolingTool — APPROVED** [review]

**Pull request closed without merging**
