### PR TITLE
CHARACTER EDITOR UI TEXT ZOOM FIX

### PR DESCRIPTION
**Pull request by bbpanzu**
This fixes the god forsaken bug where if you zoom in or out, all input texts become unusable

### CODE REVIEW

**Comment by Unholywanderer** [comment]
holy shit bb pants zoo

**Review by iym1337 — APPROVED** [review]

**Review by MemeHoovy — APPROVED** [review]

**Review by DillyzThe1 — APPROVED** [review]
I'm not sure what's going on over there in FunkinLua.hx, but this is  overall a good change.

**Review by Raltyro — APPROVED** [review]

**Review by TheKitBoi — APPROVED** [review]

**Review by Parsellol — APPROVED** [review]

**Review by DaRealDotZ — APPROVED** [review]

**Review by JorosTheModderPH — APPROVED** [review]

**Review by Trayfellow — APPROVED** [review]
shadow... merge this... now..
image

**Review by ManMaster707 — APPROVED** [review]

**Comment by IlayTheGithub2nd1234** [comment]
holy shit, it's bbpanzu! 😲

**Comment by thefatos** [comment]
finally this has been annoying me for who knows how much

**Review by aaaproooo — APPROVED** [review]

**Review by lunacynne — APPROVED** [review]

**Pull request closed without merging**
