### PR TITLE
Automated VersionShit (i guess) (Experimental Branch)

### PR DESCRIPTION
**Pull request by hackx2**
yeah!

### CODE REVIEW

**Review by moxie-coder — APPROVED** [review]
you could've switched branches on the other PR

**Comment by Hackx2** [comment]
> you could've switched branches on the other PR

Can't since it would create conflicts

**Comment by MemeHovy** [comment]
okay, yeah nvm I just saw

**Comment by MemeHovy** [comment]
(also you can solve the conflicts yourself y'know?)

**Comment by MemeHovy** [comment]
okay

**Review by FunkoDev — APPROVED** [review]

**Review by ACoolioDude — APPROVED** [review]

**Review by charlesisfeline — APPROVED** [review]

**Review by rodney528 — APPROVED** [review]

**Review by rodney528 — APPROVED** [review]

**Comment by Hackx2** [comment]
i never deleted the repo 😭

**Comment by Hackx2** [comment]
😭😭😭

**Review by rodney528 — APPROVED** [review]
:P

**Pull request closed without merging**
