### PR TITLE
GameJolt Support

### PR DESCRIPTION
**Pull request by GamerPablito**
Since Indie Cross existed, everyone wants to make mods to be compatible with GameJolt.
So I thought: "Why don't give it a shot and implement a custom client for it by myself?"

I know everyone wants this, so I think it would be a good idea to implement it into PE.

### CODE REVIEW

**Comment by DabbinDude316B** [comment]
Ye, I’ll add this to my mod for credit

**Comment by DabbinDude316B** [comment]
I’ve been wondering how to do it since _aflac_.

**Comment by GamerPablito** [comment]
@DabbinDude316B Remember, this is a draft, is not finished yet, but I'm glad you liked the idea

**Comment by MemeHoovy** [comment]
ShadowMario wants this engine to be kept as close to the vanilla engine as possible though

**Comment by GamerPablito** [comment]
Oh, ok, there's no problem at all :)

**Pull request closed without merging**
