### PR TITLE
Kill

### PR DESCRIPTION
**Pull request by Yasemen-karakaya**
Hwjekfmf

### CODE REVIEW

**Comment by impostor5875** [comment]
why exactly are you trying to pull request some random person's psych android port that isn't even yours

**Comment by TheKitBoi** [comment]
Imagine a child created a account from github and fork the someone android port and pull request it to psych engine

**Comment by SonicProYT** [comment]
why pull request an android port of psych to psych engine
**WHY**

**Comment by Keoiki** [comment]
fatherless behavior

**Comment by PrismLight** [comment]
This is more useless than #3232

**Comment by DEMOLITIONDON96** [comment]
perish.

**Comment by DewDrags** [comment]
what types of kills?

**Comment by PrismLight** [comment]
YES A BUILD FAILED!

**Comment by Joalor64GH** [comment]
this pr is worse than mine

**Comment by fireredfan7** [comment]
(Inhale) SECURITY ALEART!!!!! @ShadowMario

**Comment by fireredfan7** [comment]
Ayo come look at this. @jigsaw-4277821

**Comment by jmxamongusmodder** [comment]
> > > This is more useless than #3232
> > 
> > 
> > Psych engine but better. OMG
> 
> i made that people still hate it :C

it was my first attempt on a chrome book ok dont judge me.

**Comment by fireredfan7** [comment]
> > > > This is more useless than #3232
> > > 
> > > 
> > > Psych engine but better. OMG
> > 
> > 
> > i made that people still hate it :C
> 
> it was my first attempt on a chrome book ok dont judge me.

So judged.

**Comment by PrismLight** [comment]
> > > > This is more useless than #3232
> > > 
> > > 
> > > Psych engine but better. OMG
> > 
> > 
> > i made that people still hate it :C
> 
> it was my first attempt on a chrome book ok dont judge me.

You are @FurryColtin?

**Comment by ShadowMario** [comment]
Stealing code/assets is bad, very icky, no good.

**Comment by PrismLight** [comment]
Shadow forgot to lock this pr.

**Comment by MilkyTheMilkBlob** [comment]
> Stealing code/assets is bad, very icky, no good.

agreed, i mean this pr just merges the android port to here
but we dont want that since android ports arent good officially

**Pull request closed without merging**
