### PR TITLE
Added ability to skip cutscenes in week 7

### PR DESCRIPTION
**Pull request by AltronMaxX**

### CODE REVIEW

**Comment by xChillax** [comment]
Press Enter to skip the cutscene, basically.
Surprised it wasn't a thing already.

**Comment by StefanBETA2008** [comment]
I Don't Understand, But Okay

**Review by MemeHoovy — APPROVED** [review]

**Review by MemeHoovy — COMMENTED** [review]
I forgot to approve this long ago :|

**Comment by StefanBETA2008** [comment]
> I forgot to approve this long ago :|

Me Too •_•

**Pull request closed without merging**
