### PR TITLE
Added a setting to load custom arrow skins

### PR DESCRIPTION
**Pull request by Apearson75**
**Custom Arrow Skins Settings**

I added a setting into options that allows you to switch between different arrow skins.

This is it in the options:
image

I'm not good at making menus in haxeflixel.
But this is what the menu looks like:

image
_The centre text changes when the up and down arrows are pressed._

This is what they look like in game:
image

### CODE REVIEW

**Comment by DEMOLITIONDON96** [comment]
yoooo, this is nice, been hoping someone would do this eventually, cause my version ended up breaking, can i use this for my build?

**Review by GO-Miles — APPROVED** [review]
I've been working on custom note skins on completed achievements, but this does most of the work for me.

**Comment by Itz-Miles** [comment]
Second thought: small suggestion. Either A, (merge this substate with note colors) or B. (add a preview of the selected noteskin)

**Comment by Phoneguytech75** [comment]
> can i use this for my build?

sure

**Comment by Phoneguytech75** [comment]
> Second thought: small suggestion. Either A, (merge this substate with note colors) or B. (add a preview of the selected noteskin)

Those are some good ideas. I'll try to add them with some bug fixes.

**Comment by Itz-Miles** [comment]
What are some of the reported bugs? Are they small ones an average joe could iron out?

**Comment by DEMOLITIONDON96** [comment]
it seems to crash for me when i try playing, probably cause of mayo's CPU skin code i have, but, idk

**Comment by Phoneguytech75** [comment]
> What are some of the reported bugs? Are they small ones an average joe could iron out?

I figured out that adding custom skins into the folder and loading them didn't work.

I'm thinking on moving the skins folder to the mods folder.

**Comment by Phoneguytech75** [comment]
> it seems to crash for me when i try playing, probably cause of mayo's CPU skin code i have, but, idk

I fixed it in the latest commit. It should work now.

**Comment by Theoyeah** [comment]
YEEEEEEEEESSSSSSSSSS

**Comment by Theoyeah** [comment]
FUNKIN YEEEEEEEEEEESSSSSSS

**Comment by Meme1079** [comment]
Cool

**Comment by Theoyeah** [comment]
Bruh in the menu you can't scroll for the noteskins, you're locked with the defaults

**Comment by nebulazorua** [comment]
cant you just use the mods system for noteskins tho

**Comment by Theoyeah** [comment]
nan
it wont work too

**Comment by Phoneguytech75** [comment]
> Bruh in the menu you can't scroll for the noteskins, you're locked with the defaults

you can use the up and down arrows to scroll through them. there is already two skins inside of mods/images/noteSkins

**Comment by Theoyeah** [comment]
> you can use the up and down arrows to scroll through them. there is already two skins inside of mods/images/noteSkins

OHHHH THATS WHY IT WONT LET ME AHH

**Review by JorosTheModderPH — APPROVED** [review]

**Review by Theoyeah — APPROVED** [review]

**Comment by silvashp** [comment]
i tried importing custom noteskins, but when i do so none of the songs load, just an endless black screen.

**Review by iym1337 — APPROVED** [review]
nice

**Review by Raltyro — APPROVED** [review]

**Comment by DEMOLITIONDON96** [comment]
looks like it crashes or won't load when using custom notetypes, for i just tested the hurt notes with this

**Review by HeliProGamer — APPROVED** [review]

**Comment by Theoyeah** [comment]
> looks like it crashes or won't load when using custom notetypes, for i just tested the hurt notes with this

image
For me tho it works, even with instakill note

**Comment by DEMOLITIONDON96** [comment]
> > looks like it crashes or won't load when using custom notetypes, for i just tested the hurt notes with this
> 
> image For me tho it works, even with instakill note

Huh, weird, maybe it’s just me lol

**Comment by Theoyeah** [comment]
@Phoneguytech75  you sould add something that centers the the text so it make it look better

**Comment by Theoyeah** [comment]
> > @Phoneguytech75  you sould add something that centers the the text so it make it look better
> 
> Do you mean the text in the setting?

No, the big text
image

**Review by Theoyeah — APPROVED** [review]

**Comment by Theoyeah** [comment]
@Phoneguytech75  There a big bug with hurts notes where the skin wont load

**Comment by Theoyeah** [comment]
but i found a way to fix it but it uses the mods folder

**Comment by JorosTheModderPH** [comment]
There's a bug that can't load the texture of Hurt Note.Is there anyway to fix it?

**Comment by Phoneguytech75** [comment]
> There's a bug that can't load the texture of Hurt Note.Is there anyway to fix it?

idk i just reset my pc so i'll look into it after i download haxe

**Comment by Theoyeah** [comment]
> > There's a bug that can't load the texture of Hurt Note.Is there anyway to fix it?
> 
> idk i just reset my pc so i'll look into it after i download haxe

I confirm that hurt note's texture is not showing

**Comment by JorosTheModderPH** [comment]
I think the issue is the anti-aliasing. I think it's because when you try to disable or enable the anti-aliasing in the graphics options, it shows blank.

**Comment by JorosTheModderPH** [comment]
Well, I guess I will just use Lua for custom notetypes.

**Comment by Phoneguytech75** [comment]
> I confirm that hurt note's texture is not showing

I do remember playing the bf phantasm mod and the hurt notes were just regular notes but smaller. Idk why. I also don't feel like working on this pull request as well. I'll think about closing it in a few hours

**Comment by Phoneguytech75** [comment]
Yeah I'm just gonna close this now.

**Comment by Theoyeah** [comment]
R.I.P

**Pull request closed without merging**
