### PR TITLE
Fix Charting Waveform for Mono, and Stereo Sound

### PR DESCRIPTION
**Pull request by Raltyro**
^
and also make waveform instrumental and voices at the same time possible
Debunked from my closed issue request

Before
https://user-images.githubusercontent.com/78720179/167110760-2cfdf60e-4a59-4a68-9a5c-3a1802f0fb4e.mp4

After
https://cdn.discordapp.com/attachments/860848418687680543/972076633286672384/2022-05-06_16-50-56.mp4
https://cdn.discordapp.com/attachments/860848418687680543/972076633974513694/2022-05-06_16-48-00.mp4

(THX TO GEDEHARI FOR THE ORIGINAL WAVEFORM CODES)

### CODE REVIEW

**Review by BombasticTom — APPROVED** [review]
damnnn didn't even know it was broken

**Review by ghost — APPROVED** [review]
good fix i dont even know how you found it out

**Review by lunacynne — APPROVED** [review]

**Comment by ShadowMario** [comment]
Was approved by sqirra (formerly gederahi)

**Comment by gedehari** [comment]
whos gedehari

**Pull request merged**
