### PR TITLE
I updaet pack.josn

### PR DESCRIPTION
**Pull request by TheKillerA1**

### CODE REVIEW

**Comment by LilDrippyMyFnf** [comment]
> _ No description provided. _

your so bad at spelling

**Comment by LilDrippyMyFnf** [comment]
> > > _ No description provided. _
> > 
> > 
> > your so bad at spelling
> 
> Hwat th fcuk dyou mae n

imagine not spelling right

**Comment by TheKillerA1** [comment]
> go to fucking hell

Dude, your here shitting on a bait pr. 
Get a life, Touch grass, Stop watching anime every minute, And stop being high every second of your life. 
Don’t blame me, Anybody with more than quarter of a brain can see through the irony I’ve set up.

**Comment by LilDrippyMyFnf** [comment]
> > go to fucking hell
> 
> Dude, your here shitting on a bait pr. Get a life, Touch grass, Stop watching anime every minute, And stop being high every second of your life. Don’t blame me, Anybody with more than quarter of a brain can see through the irony I’ve set up.

like you gotta brain

**Comment by LilDrippyMyFnf** [comment]
> > > go to fucking hell
> > 
> > 
> > Dude, your here shitting on a bait pr. Get a life, Touch grass, Stop watching anime every minute, And stop being high every second of your life. Don’t blame me, Anybody with more than quarter of a brain can see through the irony I’ve set up.
> 
> like you gotta brain

cuz you can't spell right

**Comment by TheKillerA1** [comment]
> > > go to fucking hell
> > 
> > 
> > Dude, your here shitting on a bait pr. Get a life, Touch grass, Stop watching anime every minute, And stop being high every second of your life. Don’t blame me, Anybody with more than quarter of a brain can see through the irony I’ve set up.
> 
> like you gotta brain

Partners in trolling

**Comment by MemeHoovy** [comment]
I fucking hate you

**Comment by TheKillerA1** [comment]
> I fucking hate you

Thank you very much

**Comment by LilDrippyMyFnf** [comment]
> > I fucking hate you
> 
> Thank you very much

cry about it nigga

**Comment by TheKillerA1** [comment]
> > > I fucking hate you
> > 
> > 
> > Thank you very much
> 
> cry about it nigga

Mf expected we can see his skin color through Unicode 💀💀💀💀💀💀

**Comment by LilDrippyMyFnf** [comment]
> > > > I fucking hate you
> > > 
> > > 
> > > Thank you very much
> > 
> > 
> > cry about it nigga
> 
> Mf expected we can see his skin color through Unicode 💀💀💀💀💀💀

yeah,sure,bitch


bad spelling self

**Comment by LilDrippyMyFnf** [comment]
did you even go to school to spell right?

i don't think you did

**Comment by TheKillerA1** [comment]
> > > > > I fucking hate you
> > > > 
> > > > 
> > > > Thank you very much
> > > 
> > > 
> > > cry about it nigga
> > 
> > 
> > Mf expected we can see his skin color through Unicode 💀💀💀💀💀💀
> 
> yeah,sure,bitch
> 
> bad spelling self

**ahem ahem ah ahem *dies of lung cancer* **
Irony

**Comment by LilDrippyMyFnf** [comment]
> > > > > > I fucking hate you
> > > > > 
> > > > > 
> > > > > Thank you very much
> > > > 
> > > > 
> > > > cry about it nigga
> > > 
> > > 
> > > Mf expected we can see his skin color through Unicode 💀💀💀💀💀💀
> > 
> > 
> > yeah,sure,bitch
> > bad spelling self
> 
> **ahem ahem ah ahem _dies of lung cancer_ ** Irony

too late....blocked you!!! XDD

**Comment by TheKillerA1** [comment]
> > > > > > > I fucking hate you
> > > > > > 
> > > > > > 
> > > > > > Thank you very much
> > > > > 
> > > > > 
> > > > > cry about it nigga
> > > > 
> > > > 
> > > > Mf expected we can see his skin color through Unicode 💀💀💀💀💀💀
> > > 
> > > 
> > > yeah,sure,bitch
> > > bad spelling self
> > 
> > 
> > **ahem ahem ah ahem _dies of lung cancer_ ** Irony
> 
> too late....blocked you!!! XDD

Low quality bait

**Comment by MemeHoovy** [comment]
homophobic racist piece of shit

**Comment by LilDrippyMyFnf** [comment]
> > > > > > > > I fucking hate you
> > > > > > > 
> > > > > > > 
> > > > > > > Thank you very much
> > > > > > 
> > > > > > 
> > > > > > cry about it nigga
> > > > > 
> > > > > 
> > > > > Mf expected we can see his skin color through Unicode 💀💀💀💀💀💀
> > > > 
> > > > 
> > > > yeah,sure,bitch
> > > > bad spelling self
> > > 
> > > 
> > > **ahem ahem ah ahem _dies of lung cancer_ ** Irony
> > 
> > 
> > too late....blocked you!!! XDD
> 
> Low quality bait

like i can understand that?????

bitch,you need to change yo goddamn ways or else some mf kid go bust he hell out of you

**Comment by TheKillerA1** [comment]
> homophobic racist piece of shit

Anime 4channer who's middle name is “Reddit”

**Comment by TheKillerA1** [comment]
> > > > > > > > > I fucking hate you
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Thank you very much
> > > > > > > 
> > > > > > > 
> > > > > > > cry about it nigga
> > > > > > 
> > > > > > 
> > > > > > Mf expected we can see his skin color through Unicode 💀💀💀💀💀💀
> > > > > 
> > > > > 
> > > > > yeah,sure,bitch
> > > > > bad spelling self
> > > > 
> > > > 
> > > > **ahem ahem ah ahem _dies of lung cancer_ ** Irony
> > > 
> > > 
> > > too late....blocked you!!! XDD
> > 
> > 
> > Low quality bait
> 
> like i can understand that?????
> 
> bitch,you need to change yo goddamn ways or else some mf kid go bust he hell out of you

Like who?? This was just made to pass time. Thanks for your reactions btw 😎😎😎😎😎😎😎

**Comment by LEVIXDDLMAO** [comment]
> > homophobic racist piece of shit
> 
> Anime 4channer who's middle name is “Reddit”

dude shut the fuck up talk shit about me all you want idfc  just stop being  a fucking dick wad and get a fucking life,

**Comment by TheKillerA1** [comment]
> > > homophobic racist piece of shit
> > 
> > 
> > Anime 4channer who's middle name is “Reddit”
> 
> dude shut the fuck up talk shit about me all you want idfc just stop being a fucking dick wad and get a fucking life,

Oh no “he” got his alt account out!1!11!!1!!!1!1!1!1!
“SHIBER ME TINBEEES AAAA AAGAH”

**Comment by LilDrippyMyFnf** [comment]
> > > > > > > > > > I fucking hate you
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Thank you very much
> > > > > > > > 
> > > > > > > > 
> > > > > > > > cry about it nigga
> > > > > > > 
> > > > > > > 
> > > > > > > Mf expected we can see his skin color through Unicode 💀💀💀💀💀💀
> > > > > > 
> > > > > > 
> > > > > > yeah,sure,bitch
> > > > > > bad spelling self
> > > > > 
> > > > > 
> > > > > **ahem ahem ah ahem _dies of lung cancer_ ** Irony
> > > > 
> > > > 
> > > > too late....blocked you!!! XDD
> > > 
> > > 
> > > Low quality bait
> > 
> > 
> > like i can understand that?????
> > bitch,you need to change yo goddamn ways or else some mf kid go bust he hell out of you
> 
> Like who?? This was just made to pass time. Thanks for your reactions btw 😎😎😎😎😎😎😎

XDDD STUPID AASSSSSSSS

**Comment by TheKillerA1** [comment]
> 

???

**Comment by LEVIXDDLMAO** [comment]
> > > > homophobic racist piece of shit
> > > 
> > > 
> > > Anime 4channer who's middle name is “Reddit”
> > 
> > 
> > dude shut the fuck up talk shit about me all you want idfc just stop being a fucking dick wad and get a fucking life,
> 
> Oh no “he” got his alt account out!1!11!!1!!!1!1!1!1! “SHIBER ME TINBEEES AAAA AAGAH”

alt? Nah im whole diff person you fucking dumbass, a fucking baby is smarter then you

**Comment by LilDrippyMyFnf** [comment]
> > > > > homophobic racist piece of shit
> > > > 
> > > > 
> > > > Anime 4channer who's middle name is “Reddit”
> > > 
> > > 
> > > dude shut the fuck up talk shit about me all you want idfc just stop being a fucking dick wad and get a fucking life,
> > 
> > 
> > Oh no “he” got his alt account out!1!11!!1!!!1!1!1!1! “SHIBER ME TINBEEES AAAA AAGAH”
> 
> alt? Nah im whole diff person you fucking dumbass, a fucking baby is smarter then you

no cap

**Comment by LilDrippyMyFnf** [comment]
> > 
> 
> ???

exatly,can't understand cuz you only got 1 eye that just got busted

**Comment by TheKillerA1** [comment]
> > > > > homophobic racist piece of shit
> > > > 
> > > > 
> > > > Anime 4channer who's middle name is “Reddit”
> > > 
> > > 
> > > dude shut the fuck up talk shit about me all you want idfc just stop being a fucking dick wad and get a fucking life,
> > 
> > 
> > Oh no “he” got his alt account out!1!11!!1!!!1!1!1!1! “SHIBER ME TINBEEES AAAA AAGAH”
> 
> alt? Nah im whole diff person you fucking dumbass, a fucking baby is smarter then you

Bozo replied to another person acting like they were him 💀💀💀

**Comment by TheKillerA1** [comment]
> > > > > > homophobic racist piece of shit
> > > > > 
> > > > > 
> > > > > Anime 4channer who's middle name is “Reddit”
> > > > 
> > > > 
> > > > dude shut the fuck up talk shit about me all you want idfc just stop being a fucking dick wad and get a fucking life,
> > > 
> > > 
> > > Oh no “he” got his alt account out!1!11!!1!!!1!1!1!1! “SHIBER ME TINBEEES AAAA AAGAH”
> > 
> > 
> > alt? Nah im whole diff person you fucking dumbass, a fucking baby is smarter then you
> 
> Bozo replied to another person and begun acting like they were him 💀💀💀

**Comment by LEVIXDDLMAO** [comment]
> > > > > > homophobic racist piece of shit
> > > > > 
> > > > > 
> > > > > Anime 4channer who's middle name is “Reddit”
> > > > 
> > > > 
> > > > dude shut the fuck up talk shit about me all you want idfc just stop being a fucking dick wad and get a fucking life,
> > > 
> > > 
> > > Oh no “he” got his alt account out!1!11!!1!!!1!1!1!1! “SHIBER ME TINBEEES AAAA AAGAH”
> > 
> > 
> > alt? Nah im whole diff person you fucking dumbass, a fucking baby is smarter then you
> 
> Bozo replied to another person acting like they were him 💀💀💀

dude your fucking dumb, i wasnt trying to be him im a whole diff person dumbass

**Comment by TheKillerA1** [comment]
> > > > > > > homophobic racist piece of shit
> > > > > > 
> > > > > > 
> > > > > > Anime 4channer who's middle name is “Reddit”
> > > > > 
> > > > > 
> > > > > dude shut the fuck up talk shit about me all you want idfc just stop being a fucking dick wad and get a fucking life,
> > > > 
> > > > 
> > > > Oh no “he” got his alt account out!1!11!!1!!!1!1!1!1! “SHIBER ME TINBEEES AAAA AAGAH”
> > > 
> > > 
> > > alt? Nah im whole diff person you fucking dumbass, a fucking baby is smarter then you
> > 
> > 
> > Bozo replied to another person acting like they were him 💀💀💀
> 
> dude your fucking dumb, i wasnt trying to be him im a whole diff person dumbass

You def sounded like it

**Comment by MemeHoovy** [comment]
you need to shut the fuck up

**Comment by LilDrippyMyFnf** [comment]
> > > > > > > > homophobic racist piece of shit
> > > > > > > 
> > > > > > > 
> > > > > > > Anime 4channer who's middle name is “Reddit”
> > > > > > 
> > > > > > 
> > > > > > dude shut the fuck up talk shit about me all you want idfc just stop being a fucking dick wad and get a fucking life,
> > > > > 
> > > > > 
> > > > > Oh no “he” got his alt account out!1!11!!1!!!1!1!1!1! “SHIBER ME TINBEEES AAAA AAGAH”
> > > > 
> > > > 
> > > > alt? Nah im whole diff person you fucking dumbass, a fucking baby is smarter then you
> > > 
> > > 
> > > Bozo replied to another person acting like they were him 💀💀💀
> > 
> > 
> > dude your fucking dumb, i wasnt trying to be him im a whole diff person dumbass
> 
> You def sounded like it

you are def CUZ YOU AINT GOT NONE EARS

**Comment by LEVIXDDLMAO** [comment]
> > > > > > > > homophobic racist piece of shit
> > > > > > > 
> > > > > > > 
> > > > > > > Anime 4channer who's middle name is “Reddit”
> > > > > > 
> > > > > > 
> > > > > > dude shut the fuck up talk shit about me all you want idfc just stop being a fucking dick wad and get a fucking life,
> > > > > 
> > > > > 
> > > > > Oh no “he” got his alt account out!1!11!!1!!!1!1!1!1! “SHIBER ME TINBEEES AAAA AAGAH”
> > > > 
> > > > 
> > > > alt? Nah im whole diff person you fucking dumbass, a fucking baby is smarter then you
> > > 
> > > 
> > > Bozo replied to another person acting like they were him 💀💀💀
> > 
> > 
> > dude your fucking dumb, i wasnt trying to be him im a whole diff person dumbass
> 
> You def sounded like it

dude this is why you only joined an 1 ago so you can start shit like this fucking dumbass

**Comment by TheKillerA1** [comment]
> > > > > > > > > homophobic racist piece of shit
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Anime 4channer who's middle name is “Reddit”
> > > > > > > 
> > > > > > > 
> > > > > > > dude shut the fuck up talk shit about me all you want idfc just stop being a fucking dick wad and get a fucking life,
> > > > > > 
> > > > > > 
> > > > > > Oh no “he” got his alt account out!1!11!!1!!!1!1!1!1! “SHIBER ME TINBEEES AAAA AAGAH”
> > > > > 
> > > > > 
> > > > > alt? Nah im whole diff person you fucking dumbass, a fucking baby is smarter then you
> > > > 
> > > > 
> > > > Bozo replied to another person acting like they were him 💀💀💀
> > > 
> > > 
> > > dude your fucking dumb, i wasnt trying to be him im a whole diff person dumbass
> > 
> > 
> > You def sounded like it
> 
> you are def CUZ YOU AINT GOT NONE EARS

3A502794-09FF-4BC6-81D4-311234D5B31E

**Comment by LEVIXDDLMAO** [comment]
says nothing about you dumbass

**Comment by TheKillerA1** [comment]
> > > > > > > > > homophobic racist piece of shit
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Anime 4channer who's middle name is “Reddit”
> > > > > > > 
> > > > > > > 
> > > > > > > dude shut the fuck up talk shit about me all you want idfc just stop being a fucking dick wad and get a fucking life,
> > > > > > 
> > > > > > 
> > > > > > Oh no “he” got his alt account out!1!11!!1!!!1!1!1!1! “SHIBER ME TINBEEES AAAA AAGAH”
> > > > > 
> > > > > 
> > > > > alt? Nah im whole diff person you fucking dumbass, a fucking baby is smarter then you
> > > > 
> > > > 
> > > > Bozo replied to another person acting like they were him 💀💀💀
> > > 
> > > 
> > > dude your fucking dumb, i wasnt trying to be him im a whole diff person dumbass
> > 
> > 
> > You def sounded like it
> 
> dude this is why you only joined an 1 ago so you can start shit like this fucking dumbass

1 what?!?!? Learn how to use time measurements dumbass

**Comment by LilDrippyMyFnf** [comment]
> > > > > > > > > > homophobic racist piece of shit
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Anime 4channer who's middle name is “Reddit”
> > > > > > > > 
> > > > > > > > 
> > > > > > > > dude shut the fuck up talk shit about me all you want idfc just stop being a fucking dick wad and get a fucking life,
> > > > > > > 
> > > > > > > 
> > > > > > > Oh no “he” got his alt account out!1!11!!1!!!1!1!1!1! “SHIBER ME TINBEEES AAAA AAGAH”
> > > > > > 
> > > > > > 
> > > > > > alt? Nah im whole diff person you fucking dumbass, a fucking baby is smarter then you
> > > > > 
> > > > > 
> > > > > Bozo replied to another person acting like they were him 💀💀💀
> > > > 
> > > > 
> > > > dude your fucking dumb, i wasnt trying to be him im a whole diff person dumbass
> > > 
> > > 
> > > You def sounded like it
> > 
> > 
> > you are def CUZ YOU AINT GOT NONE EARS
> 
> 3A502794-09FF-4BC6-81D4-311234D5B31E

YOU REALLY HAVE TO GET A SCREENSHOT?

**Comment by LEVIXDDLMAO** [comment]
> > > > > > > > > > > homophobic racist piece of shit
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > Anime 4channer who's middle name is “Reddit”
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > dude shut the fuck up talk shit about me all you want idfc just stop being a fucking dick wad and get a fucking life,
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Oh no “he” got his alt account out!1!11!!1!!!1!1!1!1! “SHIBER ME TINBEEES AAAA AAGAH”
> > > > > > > 
> > > > > > > 
> > > > > > > alt? Nah im whole diff person you fucking dumbass, a fucking baby is smarter then you
> > > > > > 
> > > > > > 
> > > > > > Bozo replied to another person acting like they were him 💀💀💀
> > > > > 
> > > > > 
> > > > > dude your fucking dumb, i wasnt trying to be him im a whole diff person dumbass
> > > > 
> > > > 
> > > > You def sounded like it
> > > 
> > > 
> > > you are def CUZ YOU AINT GOT NONE EARS
> > 
> > 
> > 3A502794-09FF-4BC6-81D4-311234D5B31E
> 
> YOU REALLY HAVE TO GET A SCREENSHOT?

XDD HOMIE NEEDS HELP HOMIE HAD TO FUCKING SCREEN SHOT

**Comment by TheKillerA1** [comment]
> 

39AD4493-3C04-4402-874B-79345607529C
Pissing you off :trollface:

**Comment by LilDrippyMyFnf** [comment]
> > > > > > > > > > > > homophobic racist piece of shit
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > Anime 4channer who's middle name is “Reddit”
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > dude shut the fuck up talk shit about me all you want idfc just stop being a fucking dick wad and get a fucking life,
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Oh no “he” got his alt account out!1!11!!1!!!1!1!1!1! “SHIBER ME TINBEEES AAAA AAGAH”
> > > > > > > > 
> > > > > > > > 
> > > > > > > > alt? Nah im whole diff person you fucking dumbass, a fucking baby is smarter then you
> > > > > > > 
> > > > > > > 
> > > > > > > Bozo replied to another person acting like they were him 💀💀💀
> > > > > > 
> > > > > > 
> > > > > > dude your fucking dumb, i wasnt trying to be him im a whole diff person dumbass
> > > > > 
> > > > > 
> > > > > You def sounded like it
> > > > 
> > > > 
> > > > you are def CUZ YOU AINT GOT NONE EARS
> > > 
> > > 
> > > 3A502794-09FF-4BC6-81D4-311234D5B31E
> > 
> > 
> > YOU REALLY HAVE TO GET A SCREENSHOT?
> 
> XDD HOMIE NEEDS HELP HOMIE HAD TO FUCKING SCREEN SHOT

XDDD

**Comment by LEVIXDDLMAO** [comment]
> > 
> 
> 39AD4493-3C04-4402-874B-79345607529C Pissing you off :trollface:

Piss me off? Im not pissed its just your a fucking no friends and no bitches and no father ass kid so stfu

**Comment by LilDrippyMyFnf** [comment]
> > 
> 
> 39AD4493-3C04-4402-874B-79345607529C Pissing you off :trollface:

when you have to show us everything in the fucking diconarty

**Comment by LEVIXDDLMAO** [comment]
> > > 
> > 
> > 
> > 39AD4493-3C04-4402-874B-79345607529C Pissing you off :trollface:
> 
> when you have to show us everything in the fucking diconarty

homie is broke to but a real one so he goes on wikipeadia

**Comment by TheKillerA1** [comment]
> > 39AD4493-3C04-4402-874B-79345607529C Pissing you off :trollface:
> 
> when you have to show us everything in the fucking diconarty

48C4E3C4-4A4C-474F-881F-8B5E45D4816B

+ dictionary*

**Comment by LilDrippyMyFnf** [comment]
> > > 39AD4493-3C04-4402-874B-79345607529C Pissing you off :trollface:
> > 
> > 
> > when you have to show us everything in the fucking diconarty
> 
> 48C4E3C4-4A4C-474F-881F-8B5E45D4816B
> 
> * dictionary*

get a career

**Comment by TheKillerA1** [comment]
> > 39AD4493-3C04-4402-874B-79345607529C Pissing you off :trollface:
> 
> Piss me off? Im not pissed its just your a fucking no friends and no bitches and no father ass kid so stfu

“Bozo + ratoi + didnt ask!1!1!1!1!11!”
Dude nice self roast

**Comment by LEVIXDDLMAO** [comment]
> > > 39AD4493-3C04-4402-874B-79345607529C Pissing you off :trollface:
> > 
> > 
> > Piss me off? Im not pissed its just your a fucking no friends and no bitches and no father ass kid so stfu
> 
> “Bozo + ratoi + didnt ask!1!1!1!1!11!” Dude nice self roast

oh shit i think your talking about yourself so yeah go get a fucking life

**Comment by TheKillerA1** [comment]
> > > > 39AD4493-3C04-4402-874B-79345607529C Pissing you off :trollface:
> > > 
> > > 
> > > Piss me off? Im not pissed its just your a fucking no friends and no bitches and no father ass kid so stfu
> > 
> > 
> > “Bozo + ratoi + didnt ask!1!1!1!1!11!” Dude nice self roast
> 
> oh shit i think your talking about yourself so yeah go get a fucking life

Hey wait a fucking minute this ain’t twitter

**Comment by LilDrippyMyFnf** [comment]
> > > 39AD4493-3C04-4402-874B-79345607529C Pissing you off :trollface:
> > 
> > 
> > Piss me off? Im not pissed its just your a fucking no friends and no bitches and no father ass kid so stfu
> 
> hi,i'm TheKillerA1,i have no friends or family,i'm so trash at everything,i suck,i should be dead,i am dead

**Comment by MemeHoovy** [comment]
I fucking hate you

**Comment by LilDrippyMyFnf** [comment]
read it

**Comment by TheKillerA1** [comment]
> > > 39AD4493-3C04-4402-874B-79345607529C Pissing you off :trollface:
> > 
> > 
> > Piss me off? Im not pissed its just your a fucking no friends and no bitches and no father ass kid so stfu
> 
> hi,i'm TheKillerA1,i have no friends or family,i'm so trash at everything,i suck,i should be dead,i am dead

I’m the same guy behind the screen as jimmy lmao
6E8E6E8F-29EC-42BB-A4BA-BE8E87008294

**Comment by LilDrippyMyFnf** [comment]
> > > > 39AD4493-3C04-4402-874B-79345607529C Pissing you off :trollface:
> > > 
> > > 
> > > Piss me off? Im not pissed its just your a fucking no friends and no bitches and no father ass kid so stfu
> > 
> > 
> > hi,i'm TheKillerA1,i have no friends or family,i'm so trash at everything,i suck,i should be dead,i am dead
> 
> I’m the same guy behind the screen as jimmy lmao 6E8E6E8F-29EC-42BB-A4BA-BE8E87008294

witch yo bad drawing skills

**Comment by TheKillerA1** [comment]
> > > > > 39AD4493-3C04-4402-874B-79345607529C Pissing you off :trollface:
> > > > 
> > > > 
> > > > Piss me off? Im not pissed its just your a fucking no friends and no bitches and no father ass kid so stfu
> > > 
> > > 
> > > hi,i'm TheKillerA1,i have no friends or family,i'm so trash at everything,i suck,i should be dead,i am dead
> > 
> > 
> > I’m the same guy behind the screen as jimmy lmao 6E8E6E8F-29EC-42BB-A4BA-BE8E87008294
> 
> witch yo bad drawing skills

Watch*

**Comment by LilDrippyMyFnf** [comment]
> > > > > > 39AD4493-3C04-4402-874B-79345607529C Pissing you off :trollface:
> > > > > 
> > > > > 
> > > > > Piss me off? Im not pissed its just your a fucking no friends and no bitches and no father ass kid so stfu
> > > > 
> > > > 
> > > > hi,i'm TheKillerA1,i have no friends or family,i'm so trash at everything,i suck,i should be dead,i am dead
> > > 
> > > 
> > > I’m the same guy behind the screen as jimmy lmao 6E8E6E8F-29EC-42BB-A4BA-BE8E87008294
> > 
> > 
> > witch yo bad drawing skills
> 
> i'm the killer a1 and im a sore loser

you sure are

**Comment by MemeHoovy** [comment]
fuck you

**Comment by TheKillerA1** [comment]
> fuck you

Throwing random messages at me like throwing darts

**Comment by LilDrippyMyFnf** [comment]
> > fuck you
> 
> Throwing random messages at me like throwing darts

you can't even play darts assy

**Comment by TheKillerA1** [comment]
> > > fuck you
> > 
> > 
> > Throwing random messages at me like throwing darts
> 
> you can't even play darts assy

Neither can you, stalemate.

**Comment by LilDrippyMyFnf** [comment]
> > > > fuck you
> > > 
> > > 
> > > Throwing random messages at me like throwing darts
> > 
> > 
> > you can't even play darts assy
> 
> Neither can you, stalemate.

i can,unlike you with no home

**Comment by TheKillerA1** [comment]
> > > > > fuck you
> > > > 
> > > > 
> > > > Throwing random messages at me like throwing darts
> > > 
> > > 
> > > you can't even play darts assy
> > 
> > 
> > Neither can you, stalemate.
> 
> i can,unlike you with no home

How did you know…
How did you know exactly how to do a self roast?? Pretty impressive ngl

**Comment by MemeHoovy** [comment]
you fucking suck

**Comment by LilDrippyMyFnf** [comment]
> > > > > > fuck you
> > > > > 
> > > > > 
> > > > > Throwing random messages at me like throwing darts
> > > > 
> > > > 
> > > > you can't even play darts assy
> > > 
> > > 
> > > Neither can you, stalemate.
> > 
> > 
> > i can,unlike you with no home
> 
> How did you know… How did you know exactly how to do a self roast?? Pretty impressive ngl

reverse card nigga

**Comment by TheKillerA1** [comment]
> you fucking suck

You sound like that one kid behind you in class saying racial slurs at you every 3 minutes

**Comment by LilDrippyMyFnf** [comment]
> > you fucking suck
> 
> You sound like that one kid behind you in class saying racial slurs at you every 3 minutes

says the guy with no voice

**Comment by TheKillerA1** [comment]
> > > you fucking suck
> > 
> > 
> > You sound like that one kid behind you in class saying racial slurs at you every 3 minutes
> 
> says the guy with no voice

Uh… whar? 💀

**Comment by LilDrippyMyFnf** [comment]
> > > > you fucking suck
> > > 
> > > 
> > > You sound like that one kid behind you in class saying racial slurs at you every 3 minutes
> > 
> > 
> > says the guy with no voice
> 
> Uh… whar? 💀

sorry,you can't hear me?

**Comment by TheKillerA1** [comment]
> > > > > you fucking suck
> > > > 
> > > > 
> > > > You sound like that one kid behind you in class saying racial slurs at you every 3 minutes
> > > 
> > > 
> > > says the guy with no voice
> > 
> > 
> > Uh… whar? 💀
> 
> sorry,you can't hear me?

Oh sorry, that annoying bitch MemeHoovy keeps throwing random insults at me. Sorry bro

**Comment by LilDrippyMyFnf** [comment]
> > > > > > you fucking suck
> > > > > 
> > > > > 
> > > > > You sound like that one kid behind you in class saying racial slurs at you every 3 minutes
> > > > 
> > > > 
> > > > says the guy with no voice
> > > 
> > > 
> > > Uh… whar? 💀
> > 
> > 
> > sorry,you can't hear me?
> 
> Oh sorry, that annoying bitch MemeHoovy keeps throwing random insults at me. Sorry bro
download

i think i found u

**Comment by TheKillerA1** [comment]
> > > > > > > you fucking suck
> > > > > > 
> > > > > > 
> > > > > > You sound like that one kid behind you in class saying racial slurs at you every 3 minutes
> > > > > 
> > > > > 
> > > > > says the guy with no voice
> > > > 
> > > > 
> > > > Uh… whar? 💀
> > > 
> > > 
> > > sorry,you can't hear me?
> > 
> > 
> > Oh sorry, that annoying bitch MemeHoovy keeps throwing random insults at me. Sorry bro
> > download
> 
> i think i found u

Bros leaking his own baby pictures 💀💀

**Comment by LilDrippyMyFnf** [comment]
> > > > > > > > you fucking suck
> > > > > > > 
> > > > > > > 
> > > > > > > You sound like that one kid behind you in class saying racial slurs at you every 3 minutes
> > > > > > 
> > > > > > 
> > > > > > says the guy with no voice
> > > > > 
> > > > > 
> > > > > Uh… whar? 💀
> > > > 
> > > > 
> > > > sorry,you can't hear me?
> > > 
> > > 
> > > Oh sorry, that annoying bitch MemeHoovy keeps throwing random insults at me. Sorry bro
> > > download
> > 
> > 
> > i think i found u
> 
> Bros leaking his own baby pictures 💀💀
here you are againimage

**Comment by TheKillerA1** [comment]
> > > > > > > > you fucking suck
> > > > > > > 
> > > > > > > 
> > > > > > > You sound like that one kid behind you in class saying racial slurs at you every 3 minutes
> > > > > > 
> > > > > > 
> > > > > > says the guy with no voice
> > > > > 
> > > > > 
> > > > > Uh… whar? 💀
> > > > 
> > > > 
> > > > sorry,you can't hear me?
> > > 
> > > 
> > > Oh sorry, that annoying bitch MemeHoovy keeps throwing random insults at me. Sorry bro
> > > download
> > 
> > 
> > i think i found u
> 
> Bros leaking his own baby pictures 💀💀 here you are againimage

Walter white leaked photo

**Comment by TheKillerA1** [comment]
In summary, fuck you MemeHoovy you self absorbed karma farming Reddit & 4chan whore.
Your the one who needs to fucking die

**Comment by Intancote** [comment]
What did I just walk in on?????????

**Comment by MemeHoovy** [comment]
> In summary, fuck you MemeHoovy you self absorbed karma farming Reddit & 4chan whore. Your the one who needs to fucking die

_your_ the one who needs to fucking die, you homophobic racist piece of garbage

**Comment by TheKillerA1** [comment]
> > In summary, fuck you MemeHoovy you self absorbed karma farming Reddit & 4chan whore. Your the one who needs to fucking die
> 
> _your_ the one who needs to fucking die, you homophobic racist piece of garbage
“MOMPOHBIC RASICT GARABG!11!1!1”

**Comment by Swapper1** [comment]
Seriously, what is going on here?

**Comment by MemeHoovy** [comment]
> > > In summary, fuck you MemeHoovy you self absorbed karma farming Reddit & 4chan whore. Your the one who needs to fucking die
> > 
> > 
> > _your_ the one who needs to fucking die, you homophobic racist piece of garbage
> > “MOMPOHBIC RASICT GARABG!11!1!1”
> 
> * you're

fuck you

**Comment by TheKillerA1** [comment]
> > > > In summary, fuck you MemeHoovy you self absorbed karma farming Reddit & 4chan whore. Your the one who needs to fucking die
> > > 
> > > 
> > > _your_ the one who needs to fucking die, you homophobic racist piece of garbage
> > > “MOMPOHBIC RASICT GARABG!11!1!1”
> > 
> > 
> > 
> > * you're
> 
> fuck you

This you? 
45E5BFDD-C74C-4627-A408-5F2BADAA5EB8

**Comment by TheKillerA1** [comment]
> > > > > In summary, fuck you MemeHoovy you self absorbed karma farming Reddit & 4chan whore. Your the one who needs to fucking die
> > > > 
> > > > 
> > > > _your_ the one who needs to fucking die, you homophobic racist piece of garbage
> > > > “MOMPOHBIC RASICT GARABG!11!1!1”
> > > 
> > > 
> > > 
> > > * you're
> > 
> > 
> > fuck you
> 
> This you? 45E5BFDD-C74C-4627-A408-5F2BADAA5EB8

Fuck that rhymed

**Comment by MemeHoovy** [comment]
🖕🖕

**Comment by TheKillerA1** [comment]
> 🖕🖕

396E4938-EBE9-4CAB-8CCC-60C56296AB8F

**Comment by Swapper1** [comment]
Omg, @ShadowMario please CLOSE this

**Comment by TheKillerA1** [comment]
> Omg, @ShadowMario please CLOSE this

He’s on do not disturb 24/7, Never checks pings. Basically talking to a wall.

**Comment by CaptainBaldi** [comment]
on god twitter has come to psych engine pull requests

**Comment by lemz1** [comment]
I find it so funny how all of you guys are getting trolled by TheKillerA1. You guys are literally taking the bait.

**Comment by LilDrippyMyFnf** [comment]
> I find it so funny how all of you guys are getting trolled by TheKillerA1. You guys are literally taking the bait.

sure

**Comment by TheKillerA1** [comment]
> > I find it so funny how all of you guys are getting trolled by TheKillerA1. You guys are literally taking the bait.
> 
> sure

**R  A  T  I  O**

**Comment by ShadowMario** [comment]
> > Omg, @ShadowMario please CLOSE this
> 
> He’s on do not disturb 24/7, Never checks pings. Basically talking to a wall.

TRUEEEE LMAO

**Pull request closed without merging**
