### PR TITLE
"shader coords fix" Update in Main.hx

### PR DESCRIPTION
**Pull request by Jamextreme140**
replaced deprecated code (cam._filters to cam.filters)

### CODE REVIEW

**Comment by NexIsDumb** [comment]
duplicate of #13422

**Comment by Jamextreme140** [comment]
> duplicate of #13422

Oh, I didn't see it on the experimental branch. Thanks

**Comment by NexIsDumb** [comment]
np

**Comment by system32unknown** [comment]
Can you reopen your pr?

**Comment by Jamextreme140** [comment]
> Can you reopen your pr?

https://github.com/ShadowMario/FNF-PsychEngine/pull/13806

**Pull request closed without merging**
