### PR TITLE
README Rewrite

### PR DESCRIPTION
**Pull request by ghost**
This Pull Request aims to completely rewrite the *entirety* of Psych Engine's GitHub README.

It contains:
* a table of contents (easier to navigate for those who want to see a specific part of the README);
* a *full* building/game compile guide (so people don't have to hop from page to page and can just copy paste the things they need from the guide);
* rewritten sections (most notably the credits and special credits sections cause I went into the pull requests for the GitHub repo and saw what each member commited and rewrote it);
* new images, as well as an update to the old ones.

Miscellaneous stuff:
* removed the 2 images from ``/docs/img`` since they're stored directly into the README (via drag-and-drop into the GitHub README editor and Discord links);
* [updated some website code ninjamuffin pushed to the base game's repository](https://github.com/ninjamuffin99/Funkin/commit/4a976ca3a12175f772988f747200a7d2bc4e6711).

If anything in this README needs a change or if the building guide is out-of-date/incorrect, **please leave a review under this PR and I'll 100% look into it**.

### CODE REVIEW

**Review by CrusherNotDrip — APPROVED** [review]

**Review by MemeHoovy — APPROVED** [review]

**Comment by TheRealJake12** [comment]
👍🏻

**Review by TheKitBoi — APPROVED** [review]

**Review by Parsellol — APPROVED** [review]

**Review by GO-Miles — APPROVED** [review]
approving this so shadowMario doesn't close

**Review by J-Orell — APPROVED** [review]
Neat

**Review by MemeHoovy — APPROVED** [review]

**Comment by MemeHoovy** [comment]
oops, accidentally approved twice

**Comment by Mastercopper2346** [comment]
> approving this so shadowMario doesn't close

That won’t do anything.

**Review by Intancote — APPROVED** [review]

**Review by Raltyro — APPROVED** [review]

**Comment by Itz-Miles** [comment]
> > approving this so shadowMario doesn't close
> 
> That won’t do anything.

*Not* approving it won't do anything. I think it's useful to know how to compile non-release versions psych engine without peering into workflows.

**Comment by totallynotdoggogit** [comment]
> > > approving this so shadowMario doesn't close
> > 
> > 
> > That won’t do anything.
> 
> _Not_ approving it won't do anything. I think it's useful to know how to compile non-release versions psych engine without peering into workflows.

It is a standard Friday Night Funkin' compile guide, but, it is nice not having to hop from page to page or from repository to repository just to find a guide.

For instance, the Windows 11 section and Visual Studio 2022 sections are documented *nowhere*, since everyone uses Visual Studio 2019 and Windows 10. I only found an alternative by searching in the ``Issues`` tab in the original Funkin' repo, so I thought it'd be nice and useful to those who use those tools and document it.

**Comment by Raltyro** [comment]
wait isnt it better if the link to the contributors actually redirect you to this instead of to the pull requests
https://github.com/ShadowMario/FNF-PsychEngine/graphs/contributors

**Comment by totallynotdoggogit** [comment]
> wait isnt it better if the link to the contributors actually redirect you to this instead of to the pull requests https://github.com/ShadowMario/FNF-PsychEngine/graphs/contributors

Good idea! Will do that now.

**Review by notmagniill — APPROVED** [review]
very cool

**Comment by Magniill** [comment]
this was wrote with good grammar. **fantastic!!!**

**Review by MemeFlavor — APPROVED** [review]
Amazing pr

**Comment by RedstoneRuler** [comment]
Amazing

**Comment by totallynotdoggogit** [comment]
Gonna be updating the compile guide tomorrow. :)

**Review by TheKitBoi — APPROVED** [review]

**Comment by LilMewo** [comment]
i approv

**Comment by totallynotdoggogit** [comment]
Marking this as draft as I need to change some stuff around.

**Comment by Justudude321** [comment]
I hope someone made a copy of this

**Comment by MemeHoovy** [comment]
> I hope someone made a copy of this

just look through the commits

**Pull request closed without merging**
