### PR TITLE
gfNote Variable

### PR DESCRIPTION
**Pull request by rodney528**
Basically, grab if a note press is from a gfNote.

### CODE REVIEW

**Review by MemeHoovy — APPROVED** [review]

**Review by TheKitBoi — APPROVED** [review]

**Comment by frantastic24** [comment]
What is the point of this
You can just use the note type

**Comment by BeastlyGhost** [comment]
this accomplishes like nothing at all, that's why the Notetype variable is set on luas anyways

**Comment by ImaginationSuperHero528** [comment]
> What is the point of this
> You can just use the note type

Bro you can set multiple notes with this var so no.

**Comment by ImaginationSuperHero528** [comment]
> this accomplishes like nothing at all, that's why the Notetype variable is set on luas anyways

Could elaborate on the "that's why the Notetype variable is set on luas anyways" part?

**Comment by BeastlyGhost** [comment]
> Could elaborate on the "that's why the Notetype variable is set on luas anyways" part?

gfNotes are notetypes too, one could simply use that in order to locally make a `gfNote` variable on a lua script, or just use the noteType variable itself

**Comment by Stilic** [comment]
sorry but it's literally useless

**Comment by ShadowMilky** [comment]
this is useless cuz you can just use the notetype

**Comment by ImaginationSuperHero528** [comment]
> this is useless cuz you can just use the notetype

This is to grab the var that is the key component of the "GF Sing" note.

**Comment by frantastic24** [comment]
there already is a var, it's called note type
again, this is useless

**Comment by ImaginationSuperHero528** [comment]
So... this is actual garbage.

**Comment by ImaginationSuperHero528** [comment]
So... this is actual garbage.

**Comment by rodney528** [comment]
Ah, the good ol days. When I was a **fucking idiot**.

**Pull request closed without merging**
