### PR TITLE
No deprecation warnings

### PR DESCRIPTION
**Pull request by MemeHoovy**

### CODE REVIEW

**Review by Itz-Miles — APPROVED** [review]
wow!

**Review by TheKitBoi — APPROVED** [review]

**Review by TheWorldMachine — APPROVED** [review]

**Review by Grape-Boy — APPROVED** [review]
✨ Revolutionary! ✨

**Comment by BoloVEVO** [comment]
Epic

**Review by BoloVEVO — APPROVED** [review]

**Review by cyn-8 — APPROVED** [review]

**Comment by MemeHoovy** [comment]
> tottaly not stolen from a another suicide mouse mod :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface:

sshhh

**Comment by MemeHoovy** [comment]
> > > tottaly not stolen from a another suicide mouse mod :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface:
> > 
> > 
> > shhh
> 
> maybe it's from Wednesday idiftely,.,.,..,..,.,

maybe🤔

**Comment by MemeHoovy** [comment]
> > > > > tottaly not stolen from a another suicide mouse mod :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface:
> > > > 
> > > > 
> > > > shhh
> > > 
> > > 
> > > maybe it's from Wednesday idiftely,.,.,..,..,.,
> > 
> > 
> > maybe🤔
> 
> nah, it is!!!!1111 [bozo](https://github.com/lunarcleint/Wednesdays-Infidelity/blob/master/Project.xml#L96)

bruh💀

**Comment by LEVIXDDLMAO** [comment]
dope

**Comment by MemeHoovy** [comment]
> dope

thx

**Pull request closed without merging**
