### PR TITLE
MASSIVE performance improvements

### PR DESCRIPTION
**Pull request by glintfishGH**
I've noticed a lot of areas in the engine which are badly written / optimized. This PR should help fix most of the issues with performance. A lot of touch ups have been added and code has become easier to read, but the workflow for both source and LUA users should remain the same.

### CODE REVIEW

**Comment by glintfishGH** [comment]
This has been in the works for a while now, so any comments or suggestions would be appreciated!

**Comment by NexIsDumb** [comment]
bro ur coding master

**Comment by UmbratheUmbreon** [comment]
Dude it compiles so fast now you're a coding master.

**Comment by glintfishGH** [comment]
> Dude it compiles so fast now you're a coding master.

Thank you! I've been super hard at work on this.

**Comment by NexIsDumb** [comment]
> Bro has not heard of long comments

he didnt do all that manually, theres a command in vsc allowing you to comment multiple lines like that with no effort lmfao

**Comment by glintfishGH** [comment]
> Bro has not heard of long comments

couldn't really be assed to do /* */ around the entire class, and it's funnier this way I think

**Comment by CharlesCatYT** [comment]
> > > Bro has not heard of long comments
> > 
> > 
> > couldn't really be assed to do /* */ around the entire class, and it's funnier this way I think
> 
> Also commenting out random stuff doesn't make things run better

well in fact he commented just about everything (excluding imports ofc)



at least he didnt comment the project.xml lolololol-

**Comment by NexIsDumb** [comment]
> > Also commenting out random stuff doesn't make things run better
> 
> well in fact he commented just about everything (excluding imports & project.xml ofc)
> 
> 
> at least he didnt comment the project.xml lolololol-

bet (please)

**Comment by TheRealJake12** [comment]
wait this entire pr is just // ?

**Comment by Vortex2Oblivion** [comment]
> wait this entire pr is just // ?

Yes

**Comment by CharlesCatYT** [comment]
> wait this entire pr is just // ?

_gunpoint_ always have been

**Comment by ShadowMario** [comment]
The joke gets funnier and funnier when you repeat it a hundred times

**Pull request closed without merging**
