### PR TITLE
Split Voice Files

### PR DESCRIPTION
**Pull request by Jaduplex**
Split the voices files for every song with separated voices in the song stems.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
holy shit

**Comment by NexIsDumb** [comment]
Tbh with the default game things I think its better keeping them as they were before
Cause if theres a mod that overrides the voices, youd basically break it

**Comment by CyndaquilDAC** [comment]
> Tbh with the default game voices I think its better keeping them as they were before Cause if theres a mod that overrides the voices, youd basically break it

This same change is being done officially in the basegame update, and these would probably be swapped to the official ones after that. If anything, this would give people more time to prepare for that.

**Comment by NexIsDumb** [comment]
> > Tbh with the default game voices I think its better keeping them as they were before Cause if theres a mod that overrides the voices, youd basically break it
> 
> This same change is being done officially in the basegame update, and these would probably be swapped to the official ones after that. If anything, this would give people more time to prepare for that.

Oh its being done there too? Where did you find that info

**Comment by CyndaquilDAC** [comment]
> > > Tbh with the default game voices I think its better keeping them as they were before Cause if theres a mod that overrides the voices, youd basically break it
> > 
> > 
> > This same change is being done officially in the basegame update, and these would probably be swapped to the official ones after that. If anything, this would give people more time to prepare for that.
> 
> Oh its being done there too? Where did you find that info

Been confirmed several times on Twitch and such.

**Review by Vortex2Oblivion — APPROVED** [review]

**Review by NexIsDumb — APPROVED** [review]

**Review by charlesisfeline — APPROVED** [review]
everyone gangsta until someone installs an older mod that replaces these songs

but other that that, cool

**Comment by CyndaquilDAC** [comment]
> everyone gangsta until someone installs an older mod that replaces these songs
> 
> but other that that, cool

there should probably be a system in place that places mods with one voices file in higher priority, even when the base engine has split files which would normally be obviously superior

**Comment by CharlesCatYT** [comment]
> there should probably be a system in place that places mods with one voices file in higher priority, even when the base engine has split files which would normally be obviously superior

agreed

**Comment by thefnfcoder** [comment]
With the new update having to split vocals. will the merged version (the Voices.ogg) still be able to work?

**Comment by CharlesCatYT** [comment]
> With the new update having to split vocals. will the merged version (the Voices.ogg) still be able to work?

iirc, yeah

**Pull request merged**
