### PR TITLE
Add ‘remove health’ to lua

### PR DESCRIPTION
**Pull request by DabbinDude316B**
So your health drain scripts are so much easier

### CODE REVIEW

**Comment by frantastic24** [comment]
addHealth already does this

**Comment by SrtHero278** [comment]
yea you can just do `addHealth(negativeValue)`

**Comment by ImaginationSuperHero528** [comment]
🤦🏻

**Comment by frantastic24** [comment]
This PR is useless
Also stop opening PRs that do nothing but very few insignificant changes

**Comment by VMan-2002** [comment]
literally `addHealth(-0.05)`

**Comment by Mastercopper2346** [comment]
> This PR is useless
Also stop opening PRs that do nothing but very few insignificant changes

ok but #9677 was good

**Comment by Mastercopper2346** [comment]
Plus I have other features that I can make prs on that I’m not doing

**Comment by ImaginationSuperHero528** [comment]
> > This PR is useless
> Also stop opening PRs that do nothing but very few insignificant changes
> 
> ok but #9677 was good

No it's not.

**Comment by ShadowMario** [comment]
> > This PR is useless
> > Also stop opening PRs that do nothing but very few insignificant changes
> 
> ok but #9677 was good

No, it sucked ass

**Comment by ImaginationSuperHero528** [comment]
See he agrees!

**Pull request closed without merging**
