### PR TITLE
Trim ig

### PR DESCRIPTION
**Pull request by rodney528**
This probably doesn't work.

### CODE REVIEW

**Comment by MemeHoovy** [comment]
it doesn't work

**Comment by frantastic24** [comment]
there's a trim function right below??? and at least test before opening a pr

**Comment by ImaginationSuperHero528** [comment]
> there's a trim function right below??? and at least test before opening a pr

Yeah... I'ma just...

**Comment by ImaginationSuperHero528** [comment]
Nvm I can't draft on mobile.

**Comment by frantastic24** [comment]
Why draft and not close, this is useless

**Comment by ImaginationSuperHero528** [comment]
> Why draft and not close, this is useless

Fair

**Comment by rodney528** [comment]
This could've been good... if I wasn't an idiot back then lmao.

**Pull request closed without merging**
