### PR TITLE
Update HealthIcon.hx

### PR DESCRIPTION
**Pull request by ghost**
sorry, I didn't know how to edit it for my own use

### CODE REVIEW

**Comment by SonicProYT** [comment]
NO
WHY DO YOU NEED WINNING ICONS FOR PSYCH ENGINE
SHADOWMARIO DOESNT LIKE THAT

**Comment by ActualMandM** [comment]
due to how health icons are coded in psych, winning icons breaks every single health icon that exists (unless it has been adjusted for winning icons)

**Comment by frantastic24** [comment]
🤡🤡🤡

**Comment by cherryiguess** [comment]
use winning icons for your own mod + you broke the health icon image system
image

**Comment by SrtHero278** [comment]
image

**Comment by SonicProYT** [comment]
i wish shadowmario closed this

cuz this breaks the icons

**Comment by SonicProYT** [comment]
and also width / 3
not 2

**Comment by supajimmy** [comment]
> NO WHY DO YOU NEED WINNING ICONS FOR PSYCH ENGINE SHADOWMARIO DOESNT LIKE THAT

Haha psych engine winning icons go berrr
https://gamebanana.com/tools/8553

**Comment by DragShot** [comment]
Is it really so hard for you guys to add winning icons without breaking the existing ones? I thought there was a method to find the width of an image somewhere.

**Pull request closed without merging**
