### PR TITLE
Added setOnLuas

### PR DESCRIPTION
**Pull request by rodney528**
Like the title says I added setOnLuas... cause why not?

### CODE REVIEW

**Review by iym1337 — CHANGES_REQUESTED** [review]
shouldn't `scriptVar` be dynamic?

**Comment by ImaginationSuperHero528** [comment]
> shouldn't `scriptVar` be dynamic?

true...

**Review by lunacynne — APPROVED** [review]

**Comment by ImaginationSuperHero528** [comment]
Wtf

**Comment by ImaginationSuperHero528** [comment]
Ig this is just how it is now.

**Comment by RodneyAnImaginativePerson** [comment]
:D

**Pull request closed without merging**
