### PR TITLE
Rainbow(Chroma) fps option

### PR DESCRIPTION
**Pull request by lemz1**
Hi,
I added an option for rainbow fps. With rainbow fps I mean, that the fps have a chroma effect, for example green to red to blue...
It isn't really a crazy thing but maybe some people want this little feature.

I hope no one breaks the chain

### CODE REVIEW

**Comment by tposejank** [comment]
no

**Comment by CrusherMods** [comment]
no

**Comment by magnumsrtisswag** [comment]
no

**Comment by MasterDirector99** [comment]
no

**Comment by Gui-iago** [comment]
no

**Comment by pakieFNF** [comment]
yes :trollface:

**Comment by CrusherMods** [comment]
> yes :trollface:

NOOO YOU RUINED THE no'S BROOOOOO

**Comment by lemz1** [comment]
> yes :trollface:

NOOO YOU RUINED THE no'S BROOOOOO

**Comment by tposejank** [comment]
> yes :trollface:

NOOO YOU RUINED THE no'S BROOOOOO

**Comment by megakeh** [comment]
> yes :trollface:

NOOO YOU RUINED THE no'S BROOOOOO

**Pull request closed without merging**
