### PR TITLE
Dialogue Enhancements

### PR DESCRIPTION
**Pull request by DevScyu**
Changelog:
```diff
+ Allow dialogue files to be executed without source changes per song
+ Allow dialogue background music to be configured in the dialogue json and via the dialogue editor
+ Adds new dialogueEND support to allow dialogue to be played when a song ends
```

I have tested this to be compatible with 0.4.2.

image

Inside of your `mods/data/SONG` folder:
`dialogue.json` for dialogue when song starts
`dialogueEND.json` for dialogue when song ends

Closes #578

### CODE REVIEW

**Review by FuseIsHere813 — COMMENTED** [review]
This looks pretty good, but some Lua stuff are unnecessary as Shadow states.

What am i referencing to is the "setOnLuas" part in line 36 and 68 on GameOverSubState.

**Comment by DevScyu** [comment]
> This looks pretty good, but some Lua stuff are unnecessary as Shadow states.
> 
> What am i referencing to is the "setOnLuas" part in line 36 and 68 on GameOverSubState.

When i was looking at the code, if setOnLuas was not called the variable was not updated, so would this mean, if i do not update it back to false that it would stay in the true state for the lua scripts?

**Comment by FuseIsHere813** [comment]
> > This looks pretty good, but some Lua stuff are unnecessary as Shadow states.
> > What am i referencing to is the "setOnLuas" part in line 36 and 68 on GameOverSubState.
> 
> When i was looking at the code, if setOnLuas was not called the variable was not updated, so would this mean, if i do not update it back to false that it would stay in the true state for the lua scripts?

Maybe.

**Comment by DevScyu** [comment]
> Many of these changes for the Lua related stuff are unnecessary, you don't have to setOnLuas when quitting PlayState because Lua scripts stop running there.

@ShadowMario 
When i was looking at the code, if setOnLuas was not called the variable was not updated, so would this mean, if i do not update it back to false that it would stay in the true state for the lua scripts?

**Comment by GrexpungedYT** [comment]
oh oh
resolve them
081B8D92-FD17-436C-A4CE-CB3C2B63CAB3

**Comment by frantastic24** [comment]
> resolve them

My brother in Christ this is 6 months old

**Comment by frantastic24** [comment]
Why are you bringing up conflicts then

**Comment by BombasticTom** [comment]
this is hella old

**Comment by Gibberditoslumber** [comment]
True

**Pull request closed without merging**
