### PR TITLE
Native camera shaders functions

### PR DESCRIPTION
**Pull request by Sword352**
After a lot of requests its finally here (should work but still need testing)

### Added functions
- `addShaderToCam(cam:String, shader:String)` adds the specified shader to the specified camera
- `removeCamShader(cam:String, shader:String)` removes the specified shader from the specified camera
- `clearCamShaders(cam:String)` removes all the shaders from a camera

### CODE REVIEW

**Comment by Unholywanderer** [comment]
frday night fuckin

**Comment by Sword352** [comment]
Hold up actions failing brb lol!!!

**Comment by ThePlank** [comment]
image
ok but why ping me

**Comment by Sword352** [comment]
> image ok but why ping me

You asked for it i think idk

**Comment by Sword352** [comment]
Fixed

**Comment by ThePlank** [comment]
> > image ok but why ping me
> 
> You asked for it i think idk

no?

**Comment by Sword352** [comment]
> no?
damn but can u delete your messages its taking too much place here smh

**Review by DetectiveBaldi — APPROVED** [review]
where the `FlxG.game.setFilters()` :rage:

**Comment by Sword352** [comment]
> where the `FlxG.game.setFilters()` 😡

Good question
Im gonna implement those cuz why not actually

**Comment by CaptainBaldi** [comment]
yummy :yum:

**Comment by Sword352** [comment]
Woopsie doopsie did a mistake again should be good now

**Comment by Sword352** [comment]
# Note to add in the wiki:

"If we add shaders to the game via `addShaderToGame`, make sure to call `removeGameShader` when the `destroy` function is called, otherwise the shader will remain in game!"

We can do that automatically but I won't add it, to keep consistency with shaders added via source ig

**Comment by Sword352** [comment]
Ok should be working fine for real now it just needs testing but i highly doubt it has a problem 🙏🙏🙏

**Review by moxie-coder — APPROVED** [review]

**Review by Justine101213k — APPROVED** [review]

**Review by NexIsDumb — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by jimmyjamescool** [comment]
Mmmmm feed me more of those `FlxG.game.setFilters()` 😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋

**Review by jimmyjamescool — APPROVED** [review]

**Review by Intancote — APPROVED** [review]

**Review by Raltyro — APPROVED** [review]

**Comment by cyn0x8** [comment]
some functions need to be added (or modified) so that we can edit shader uniforms like we can with sprites, since customizable or animated shaders need uniforms to function properly

there should also be a way to specify which shader youre editing uniforms in to avoid the variable names overlapping

also also... if im not wrong, if you use the same shader twice the first one will be replaced within storedfilters (maybe a tag can be used instead?? it would work well with the idea in the previous paragraph)

**Comment by Sword352** [comment]
> some functions need to be added (or modified) so that we can edit shader uniforms like we can with sprites, since customizable or animated shaders need uniforms to function properly
> 
> there should also be a way to specify which shader youre editing uniforms in to avoid the variable names overlapping
> 
> also also... if im not wrong, if you use the same shader twice the first one will be replaced within storedfilters (maybe a tag can be used instead?? it would work well with the idea in the previous paragraph)

Right
I just got an idea to avoid that problem lemme do some modifications

**Comment by Sword352** [comment]
Shouldve used tag instead of index but whatever

**Comment by Sword352** [comment]
Damn there is some problems with the workflows

**Review by rodney528 — APPROVED** [review]

**Review by rodney528 — APPROVED** [review]

**Comment by MemeHovy** [comment]
dude the PR is closed

**Review by rodney528 — APPROVED** [review]

**Pull request closed without merging**
