### PR TITLE
Update MainMenuState.hx

### PR DESCRIPTION
**Pull request by VLkkkkkk**

### CODE REVIEW

**Comment by TheKitBoi** [comment]
you removed the donate option

**Comment by KutikiPlayz** [comment]
no

**Comment by ManMaster707** [comment]
Wot

**Comment by Paracosm-Daemon** [comment]
what's the purpose of this?
you removed donations, awards, and forced the mods menu.

**Comment by MemeHoovy** [comment]
what the hell is the point of this?
🤦🏻‍♂️

**Comment by CrusherMods** [comment]
bitch what

**Comment by Raltyro** [comment]
your evil :(

**Comment by ShadowMilky** [comment]
this guy removed the donate button

**Comment by ShadowMilky** [comment]
what an fatherless act

**Comment by Eventretta** [comment]
oh no cringe

**Comment by ShadowMilky** [comment]
how come this isnt closed

**Comment by ShadowMilky** [comment]
this just removed the donate button

**Review by ghost — APPROVED** [review]
Bad Request. Why You Deleted The Freaking Story Mode, Donate, Awards And ModsMenu?

**Comment by MemeHoovy** [comment]
> Bad Request. Why You Deleted The Freaking Story Mode, Donate, Awards And ModsMenu?

why did you approve?

**Comment by StefanBETA2008** [comment]
> > Bad Request. Why You Deleted The Freaking Story Mode, Donate, Awards And ModsMenu?
> 
> why did you approve?

Accidentally. Sorry

**Comment by ShadowMilky** [comment]
still waiting for shadow mario to close this since 
this just removed the story mode donate and awards menu

**Pull request closed without merging**
