### PR TITLE
Audio and Visual Caching Overhaul

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by tposejank — APPROVED** [review]
@ShadowMario @bbpanzu the j

**Comment by Yoshubs** [comment]
Pros:

- Better memory management!
- Best of both worlds
- Returns assets instead of paths when using paths.hx
- Buttery smooth when restarting and going into chart editor
- Doesn't lag much with Lua

Cons:
- Paths.hx no longer returns the actual path unless you're using getPath (very easy to circumvent in most cases)
- not 100% tested with mod support
- Removes the persistent caching option because this does that but without destroying your computer

**Comment by tposejank** [comment]
when this finishes doing the action imma see how my shit pc can handle psych then

**Comment by gaminbottomtext** [comment]
Ok, this is cool.

**Review by haya3218 — APPROVED** [review]
Vouch :)

**Pull request merged**
