### PR TITLE
Softcoded achievements

### PR DESCRIPTION
**Pull request by ghost**
This PR is a rewrite of a shitty PR I made before, #10861.
If you are using the old PR for your mods, please switch to this one.
Also, this is going to be a draft for a while because it may have bugs I don't know about. 

Changes:

- Json files with **global** in it must have a lua file.
- Added **song**, more information below.
- Achievement lua script will ignore of your return attempts, please don't try to return anything with them.
- ***giveAchievement*** works with any function now (https://github.com/ShadowMario/FNF-PsychEngine/pull/10861#issuecomment-1356893529), and only achievement scripts can run it.
- Softcoded achievements will work only on current mod folder, and preload folder.
- ***giveAchievement*** will return useful logs, use ***debugPrint*** to see the logs.
- No miss week achievements are supported for real now.

### UPDATED DESCRIPTION:
To make softcoded achievements, you'll need a .json and .lua file.
Here's an example.

So this is an example .json file: 
```json
{
	"name": "Road to Ten Million",
	"desc": "Gain 10 Million scores in total.",
	"save_tag": "ten_million",
	"hidden": false,
	"clearAchievements": true,
        "week_nomiss": null,
        "lua_code": null,
	"global": null,
	"index": -1,
        "song": ""
}
```
And there is the .lua file (optional, you can just put the code to **lua_code**).
```lua
function onUpdate(elapsed) 
  if getProperty("songScore") >= 10000000 then
    giveAchievement("ten_million")
   -- will return "Unlocked Achievement ten_million" if this achievement is not unlocked
   -- if it is already unlocked, it will return "Achievement ten_million is already unlocked!"
   -- if the achievement does not exist, it will return "Achievement ten_million does not exist"
  end
end
```

### JSON
Mandatory variables:
(ALL OF THE VARIABLES HERE ARE IGNORED IF ***global*** IS NOT NULL!)
- **name** is obviously the name of the achievement.
- **desc** is the description of your achievement.
- **save_tag** is the save tag of the achievement, also the file name of the achievement icon.
- **hidden** is the visibility of your achievement. Remains invisible until it's unlocked if true.
- If **index** is null or -1, gets added to end of the achievements.
- If **song** is not null, your achievement will be only be unlockable in that specific song.

Optional variables:

### **WARNING**: Using these optional variables is dangerous and using these can cause unstability. Use carefully.
**clearAchievements** clears all of the achievements if true. **SHOULD BE USED ONLY ONCE IN A MODPACK.**
**global** is the most dangerous one. If you want to set **global**, remember all of the other variables will get ignored.
If **global** is not null, it replaces the WHOLE achievements. So a .json file with **global** should be like this:
```json
{
	"name": "",
	"desc": "",
	"save_tag": "",
	"hidden": false,
	"clearAchievements": false,
	"index": null,
        "song": null,
        "global":  [
            ["Road to Ten Million", "Gain 10 Million scores in total.", "ten_million", false],
            ["Road to a Billion", "Gain 1 Billion scores in total.", "one_billion", false]
        ]
}
```
This way, achievements gets replaced with **global**. First element is name, second is description.
Third is the save tag and icon file name, fourth is the invisibility until unlocked.
### JUST LIKE **clearAchievements**, **global** SHOULD BE ONLY USED ONCE IN A MODPACK.

**week_nomiss** is the week name, just put the file name of the week to it to make a "No miss" achievement.
**week_nomiss should always end with "nomiss"!  For example, if your week name is "week8" and you want
to make a beating week with no misses achievement, just write "week8_nomiss" to week_nomiss!**

**lua_code** is the code of the achievement. If you do not want to create a lua file, just put your code in it! **lua_code** is ignored if ***global*** is set.

### LUA
Lua is nothing special, though there are differences.
Just use **giveAchievement(*Achievement's save tag*)** to unlock the achievement.
If achievement is already unlocked or achievements doesn't exist or the lua script is not an achievement script,
**giveAchievement** is ignored.

### Example Images
Using **clearAchievements**:
image

Without using **clearAchievements**:
image

With **index** being 0:
image

With using **global**:
image

### CODE REVIEW

**Review by TheKitBoi — APPROVED** [review]

**Review by charlesisfeline — APPROVED** [review]

**Review by DM-kun — APPROVED** [review]

**Review by Joalor64 — APPROVED** [review]

**Review by aaaproooo — APPROVED** [review]

**Review by Luisinhi010 — APPROVED** [review]

**Review by crowplexus — APPROVED** [review]
this should probably be renamed to "Softcoded Achivements" as a general term, works perfectly out of the box

**Review by DisIsNOt — APPROVED** [review]

**Comment by Joalor64GH** [comment]
I should ask. How does `lua_code` work?

**Comment by TheWorldMachinima** [comment]
> I should ask. How does `lua_code` work?

What do you mean?

**Comment by Joalor64GH** [comment]
Like, are we supposed to add the name of the script or do something else??

**Comment by TheWorldMachinima** [comment]
> Like, are we supposed to add the name of the script or do something else??

Put the code to *lua-code*, if you don't want to create a file for it.

**Pull request closed without merging**
