### PR TITLE
Make compiling with haxe 4.1.5 impossible

### PR DESCRIPTION
**Pull request by MemeHoovy**
I took that from Hope engine, they're underrated as hell.
https://github.com/skuqre/Hope-Engine

And also made it so you couldn't compile if your not using the git version of Linc_luajit (Use nebs fork for the love of god people, can't you fucking read instructions?)
https://github.com/ShadowMario/FNF-PsychEngine/blob/fe5104c1cf927e990e43a82009854f8258cc282b/README.md#L9

### CODE REVIEW

**Review by APRO716 — APPROVED** [review]

**Review by Itz-Miles — APPROVED** [review]

**Review by NotNimu — APPROVED** [review]

**Comment by MemeHoovy** [comment]
> I don't like this feature at all; A Chrome OS (which is a type of Linux if you are on one with the support) user is forced to use Haxe 4.1.5.

can't you use haxe 4.2.5 on chrome os?

**Comment by MemeHoovy** [comment]
let me do something rq

**Comment by coolfren** [comment]
> Sudo Apt Install haxe only installs 4.1.5

lol get the [haxe ppa](https://launchpad.net/~haxe/+archive/ubuntu/releases)

**Review by TheKitBoi — APPROVED** [review]

**Review by XS09-dev — APPROVED** [review]

**Comment by XS09-dev** [comment]
I only approve it because well we need it. But I feel like it's worthless against a expert programmer, I think you should make it a separate .hx file and then add it onto the .gitignore just so it's harder to access and get rid of if even possible to access.

**Comment by MemeHoovy** [comment]
> I only approve it because well we need it. But I feel like it's worthless against a expert programmer, I think you should make it a separate .hx file and then add it onto the .gitignore just so it's harder to access and get rid of if even possible to access.

nah

**Comment by XS09-dev** [comment]
> > I only approve it because well we need it. But I feel like it's worthless against a expert programmer, I think you should make it a separate .hx file and then add it onto the .gitignore just so it's harder to access and get rid of if even possible to access.
> 
> nah, works fine the way it is

Eh. What do I know? Pretty much 0 about .xml files. So yea probs is.

**Pull request closed without merging**
