### PR TITLE
Fix addLuaScript script adding twice

### PR DESCRIPTION
**Pull request by mosusg**
simple one line change that I think should fix

### CODE REVIEW

**Comment by TheConcealedCow** [comment]
yippee

**Review by DetectiveBaldi — APPROVED** [review]
yummy

**Review by moxie-coder — APPROVED** [review]
slay

**Review by MemeFlavor — APPROVED** [review]

**Comment by TheConcealedCow** [comment]
shadowmario fixed this in a recent push, so yeah this pr is useless now

**Pull request closed without merging**
