### PR TITLE
Add Memory Peak Counter

### PR DESCRIPTION
**Pull request by crowplexus**
adds an extra bit of information on the fpsVar by showing how many memory megabytes the game used in total

looks like:
image

also makes it so you can hide the fps and the counter individually

### CODE REVIEW

**Comment by trayfellow** [comment]
i already did this

https://github.com/ShadowMario/FNF-PsychEngine/pull/9333

**Comment by REALHaydenGaming** [comment]
There was already a mem peak counter

**Comment by BeastlyGhost** [comment]
> There was already a mem peak counter

the difference between this and the other one is something minor, you can hide them indvidually

https://user-images.githubusercontent.com/45212377/177898124-921aa578-d361-4cfb-a5c4-01a8886cbe6e.mp4

was kinda annoying that the fps counter option also got rid of the memory one, so I added that as an option along with it having a memory peak counter

**Review by JuniorNovoa1 — APPROVED** [review]
yes very cool

**Review by Raltyro — APPROVED** [review]

**Review by TheKitBoi — APPROVED** [review]

**Review by iym1337 — APPROVED** [review]

**Review by Starveldt — APPROVED** [review]

**Review by Trayfellow — APPROVED** [review]

**Review by MemeHoovy — APPROVED** [review]

**Review by Parsellol — APPROVED** [review]

**Review by DaRealDotZ — APPROVED** [review]

**Comment by REALHaydenGaming** [comment]
Oh uh, adding that as an option ig

**Review by Intancote — APPROVED** [review]

**Pull request closed without merging**
