### PR TITLE
Poison note (new example note?)

### PR DESCRIPTION
**Pull request by DabbinDude316B**

### CODE REVIEW

**Review by Raltyro — CHANGES_REQUESTED** [review]
should do 0.1 * elapsed instead of 0.00025 smh

**Comment by DaRealDotZ** [comment]
why

**Comment by Mastercopper2346** [comment]
Error: `source/PlayState.hx:3995: characters 26-33  :  Unknown identifier : elapsed`

and I DID check for spelling errors

**Comment by Mastercopper2346** [comment]
Putting update. in front does this: `source/PlayState.hx:3995: characters 33-40 : (elapsed : Float) -> Void had no field elapsed`

Bruh.

**Comment by Mastercopper2346** [comment]
It’s not like lua, it automatically does stuff that source doesn’t.

**Pull request closed without merging**
