### PR TITLE
compile the game yourself

### PR DESCRIPTION
**Pull request by cursedUs64-git**
yea do it

### CODE REVIEW

**Comment by TheKitBoi** [comment]
Are you trying to pull request someone’s engine

**Comment by cursedUs64-git** [comment]
psyde engine is mine

**Comment by cursedUs64-git** [comment]
karv dev and me created the engine

**Comment by TheKitBoi** [comment]
No one’s gonna approve it and it’s should be closed in 5 to 10 days

**Comment by cursedUs64-git** [comment]
Bro, the engine is mine, if you want proof....

https://github.com/cursedUs64-git/PsydeEngine-FNF

Im gonna close it (maybe)

**Comment by TheKitBoi** [comment]
> Bro, the engine is mine, if you want proof....
> 
> https://github.com/cursedUs64-git/PsydeEngine-FNF
> 
> Im gonna close it (maybe)

That's literally a fork

**Comment by cursedUs64-git** [comment]
yeah, but i used psych to make the engine, OK?

**Comment by CrusherNotDrip** [comment]
> yeah, but i used psych to make the engine, OK?

but still psych forks shouldn't be put inside psych engine
and there might be errors too but idk

**Pull request closed without merging**
