### PR TITLE
fix week 6 strum frame rates

### PR DESCRIPTION
**Pull request by somefnfplayerlol**
why not?

### CODE REVIEW

**Comment by Luisinhi010** [comment]
wait, it was really supposed to be 12 frames?

**Comment by MemeHoovy** [comment]
> wait, it was really supposed to be 12 frames per sec?

yes? judging by the pressed framerate

**Review by MemeHoovy — APPROVED** [review]

**Review by Luisinhi010 — APPROVED** [review]

**Comment by somefnfplayerlol** [comment]
the animation would be 2x the original speed if framerate was 24

**Comment by somefnfplayerlol** [comment]
closed because i made a unrelated commit lol

**Pull request closed without merging**
