### PR TITLE
Installation files

### PR DESCRIPTION
**Pull request by DeadSyntaxdev**
Basically you open the folder than click on the files and it installs all the stuff you need for this engine besides Haxe itself.

### CODE REVIEW

**Comment by Itz-Miles** [comment]
Now THIS is pretty cool, but is there a way to make sure these commands are run in the intended order? I dunno what'd happen if  someone doesn't happen to open the README, which hasn't been changed in this PR.

**Review by GO-Miles — APPROVED** [review]

**Comment by XS09-dev** [comment]
> Now THIS is pretty cool, but is there a way to make sure these commands are run in the intended order? I dunno what'd happen if someone doesn't happen to open the README, which hasn't been changed in this PR.

I'll most likely number them with the name

**Comment by XS09-dev** [comment]
> Now THIS is pretty cool, but is there a way to make sure these commands are run in the intended order? I dunno what'd happen if someone doesn't happen to open the README, which hasn't been changed in this PR.

Ok I numbered them. 1), 2), and 3)

**Review by GO-Miles — APPROVED** [review]
Seems very user friendly, especially compared to copy-pasting commands into cmd.

**Comment by XS09-dev** [comment]
> Referen



> Seems very user friendly, especially compared to copy-pasting commands into cmd.

That was what I was thinking when putting it together. "it's way easier to use than copy and pasting each individual commands"

**Pull request closed without merging**
