### PR TITLE
Create data

### PR DESCRIPTION
**Pull request by K4NEK1N**

### CODE REVIEW

**Comment by MemeHovy** [comment]
https://user-images.githubusercontent.com/124418090/220232513-b923be12-461d-4b8b-8963-f723af9d233c.mp4

**Comment by Rom4chek** [comment]
This is future of psych engine

**Comment by CaptainBaldi** [comment]
revolutionary

**Review by ummmbra — APPROVED** [review]

**Comment by RandomUserOnInternet** [comment]
Best PR Ever 😱

**Comment by NexIsDumb** [comment]
Changed my life

**Pull request closed without merging**
