### PR TITLE
this will fix lua dialoge for other platform

### PR DESCRIPTION
**Pull request by ghost**
also this is not a shit pr this actually fixes the lua dialoge

### CODE REVIEW

**Comment by tposejank** [comment]
No

**Comment by ThatDisabledKid** [comment]
why no

**Comment by ThatDisabledKid** [comment]
?

**Comment by Stilic** [comment]
> ?

From a guy of the Psych Engine Discord:

> Me when only helps with psych builds only on unsupported mobile builds and breaks compatibility with some luas therefore misconveniencing builds that are actually supported

**Comment by Stilic** [comment]
so no

**Comment by ThatDisabledKid** [comment]
bro this is a good pr

**Comment by ThatDisabledKid** [comment]
it is not gonna break other things

**Comment by ThatDisabledKid** [comment]
this is fix the dialogue for the Lua script for other platforms

**Comment by ThatDisabledKid** [comment]
trust me I have tried it out

**Comment by Dysfunk** [comment]
💀

**Comment by ThatDisabledKid** [comment]
I have tho

**Comment by Dysfunk** [comment]
None of the supported platforms need this

**Comment by PoleyMagik** [comment]
> also this is not a shit pr this actually fixes the lua dialoge

Sorry but this pr sucks. It may fix mobile, but it should be considered that mobile isn't an officially supported platform. This commit would be way more fit for a custom fork, because at the end of the day this is code that worsens the supported platforms' code just to fix android, which is not supported.

**Comment by DudeItsJonnycat** [comment]
bro I have  tried this on my Mac it works on Mac

**Comment by DudeItsJonnycat** [comment]
IT WORKS

**Comment by tposejank** [comment]
> IT WORKS

don't care + didn't ask + ratio + kys

**Comment by DudeItsJonnycat** [comment]
> > IT WORKS
> 
> don't care + didn't ask + ratio + kys

wtf is kys

**Comment by Steviegt6** [comment]
> > > IT WORKS
> > 
> > 
> > don't care + didn't ask + ratio + kys
> 
> wtf is kys

Keep yourself safe.

**Comment by Steviegt6** [comment]
> > > > > IT WORKS
> > > > 
> > > > 
> > > > don't care + didn't ask + ratio + kys
> > > 
> > > 
> > > wtf is kys
> > 
> > 
> > Keep yourself safe.
> 
> i don't understand these new slang words anymore

1. I lied.
2. It's an abbreviation, not a "slang word".
3. https://google.com/

**Comment by DudeItsJonnycat** [comment]
bro why you guys gotta hate on other platforms?

**Comment by Gui-iago** [comment]
1- Lua already works on Mac without your "fix"
2- Android is not officially supported
3- this is unnecessary

period.

**Comment by Dysfunk** [comment]
> 1- Lua already works on Mac without your "fix" 2- Android is not officially supported 3- this is unnecessary
> 
> period.

An extra thing to add is that it might break compatibility with a lot of mods, which isn't very, good at all

**Comment by fireredfan7** [comment]
> 1- Lua already works on Mac without your "fix" 2- Android is not officially supported 3- this is unnecessary
> 
> period.

No it doesn't.

**Comment by JuniorNovoa1** [comment]
> 1- Lua already works on Mac without your "fix" 2- Android is not officially supported 3- this is unnecessary
> 
> period.

1. He meant dialogue not pausing and the song continuing while the dialogue is on-screen fucking dumbass.

2. Android is supported just needs a little fixing.

3. This is necessary since Psych Engine is a "modding" engine

**Comment by JuniorNovoa1** [comment]
> > 1- Lua already works on Mac without your "fix" 2- Android is not officially supported 3- this is unnecessary
> > period.
> 
> An extra thing to add is that it might break compatibility with a lot of mods, which isn't very good at all

No, it doesn't I have tried on the latest version and everything works on Windows, macOS, Linux, HTML5 with no building errors at all 🤡

**Comment by Gui-iago** [comment]
>     2. Android is supported just needs a little fixing.

I meant officially supported, if yall want that "fix", then fork the god damn engine yourselves and stop trying to merge shit that can potentially break current features

**Comment by JuniorNovoa1** [comment]
> > ```
> > 2. Android is supported just needs a little fixing.
> > ```
> 
> I meant **officially** supported, if yall want that "fix", then fork the god damn engine yourselves and stop trying to merge shit that can potentially break current features

THEY DON'T LMAO CHECK UR FACTS BEFORE U GET UR HEAD IN UR ASS

**Comment by Gui-iago** [comment]
> > > ```
> > > 2. Android is supported just needs a little fixing.
> > > ```
> > 
> > 
> > I meant **officially** supported, if yall want that "fix", then fork the god damn engine yourselves and stop trying to merge shit that can potentially break current features
> 
> THEY DON'T LMAO CHECK UR FACTS BEFORE U GET UR HEAD IN UR ASS

wdym "they don't"?, I tested on all three platforms, lua works as intended

**Comment by Gui-iago** [comment]
and before you come up and say "blah you don't even own a mac", virtual machines exist, and I don't use windows as my daily OS

**Comment by JuniorNovoa1** [comment]
> > > > ```
> > > > 2. Android is supported just needs a little fixing.
> > > > ```
> > > 
> > > 
> > > I meant **officially** supported, if yall want that "fix", then fork the god damn engine yourselves and stop trying to merge shit that can potentially break current features
> > 
> > 
> > THEY DON'T LMAO CHECK UR FACTS BEFORE U GET UR HEAD IN UR ASS
> 
> wdym "they don't"?, I tested on all three platforms, lua works as intended

You are so stupid, THIS IS FOR LUA DIALOGUE FIX NOT NORMAL FUCKING LUA

**Comment by Gui-iago** [comment]
> 
> You are so stupid, THIS IS FOR LUA DIALOGUE FIX NOT NORMAL FUCKING LUA

can you actually read older comments?
image

**Comment by Gui-iago** [comment]
it's not about fixing one single function, it's about breaking thousands of other functions

**Comment by JuniorNovoa1** [comment]
> it's not about fixing one single function, it's about breaking thousands of other functions

it fucking doesn't lmao

**Comment by Gui-iago** [comment]
> > it's not about fixing one single function, it's about breaking thousands of other functions
> 
> it fucking doesn't lmao

ok then fork the engine and import the changes this PR made on your own build, if you are going to be agressive like that on a github repository, then I might as well just don't reply to you lol

**Comment by Gui-iago** [comment]
or better yet if we are talking about being aggressive, get a windows pc kid

**Comment by PoleyMagik** [comment]
why are you all fighting this is a github pull request not twitter dot com

**Comment by Gui-iago** [comment]
> why are you all fighting this is a github pull request not twitter dot com

I just wanna see how mad will this person get if I say actual facts

**Comment by JuniorNovoa1** [comment]
> or better yet if we are talking about being aggressive, get a windows pc kid

omg yes im gonna pull out cash out of the ground thank u!!!!!!!

**Comment by JuniorNovoa1** [comment]
> > why are you all fighting this is a github pull request not twitter dot com
> 
> I just wanna see how mad will this person get if I say actual facts

what facts that u can't agree that ur wrong?

**Comment by PoleyMagik** [comment]
The idea with this commit is to fix text stuff from lua, correct? If I recall correctly, Mac (a supported platform) did have a bug with dialogue (I think it was about the game just not pausing during the dialogue??). Does this fix this? Was it already fixed? Sorry if I sound out of the loop, I can't test the mac build myself.

**Comment by Gui-iago** [comment]
> The idea with this commit is to fix text stuff from lua, correct? If I recall correctly, Mac (a supported platform) did have a bug with dialogue (I think it was about the game just not pausing during the dialogue??). Does this fix this? Was it already fixed? Sorry if I sound out of the loop, I can't test the mac build myself.

was it broken in the first place? it works fine on mine without the fix

**Comment by Gui-iago** [comment]
> > > why are you all fighting this is a github pull request not twitter dot com
> > 
> > 
> > I just wanna see how mad will this person get if I say actual facts
> 
> what facts that u can't agree that ur wrong?

image
period.
stop trying to be a superhero on the internet

**Comment by JuniorNovoa1** [comment]
> The idea with this commit is to fix text stuff from lua, correct? If I recall correctly, Mac (a supported platform) did have a bug with dialogue (I think it was about the game just not pausing during the dialogue??). Does this fix this? Was it already fixed? Sorry if I sound out of the loop, I can't test the mac build myself.

Well dialogue in general, Yes this fixes it, No it wasn't fixed

**Comment by JuniorNovoa1** [comment]
> > > > why are you all fighting this is a github pull request not twitter dot com
> > > 
> > > 
> > > I just wanna see how mad will this person get if I say actual facts
> > 
> > 
> > what facts that u can't agree that ur wrong?
> 
> image period. stop trying to be a superhero on the internet

I'm not trying to be the hero, I'm trying to be the one with braincells

**Comment by PoleyMagik** [comment]
> The idea with this commit is to fix text stuff from lua, correct? If I recall correctly, Mac (a supported platform) did have a bug with dialogue (I think it was about the game just not pausing during the dialogue??). Does this fix this? Was it already fixed? Sorry if I sound out of the loop, I can't test the mac build myself.

I recalled correctly https://github.com/ShadowMario/FNF-PsychEngine/issues/4453

**Comment by Gui-iago** [comment]
> 
> I'm not trying to be the hero, I'm trying to be the one with braincells
so just fork the engine and implement the changes yourself, there's no reason whatsoever for this to be merged, specially because ShadowMario at the current time is fixing bugs, he's not merging PRs and he probably already fixed issues with MacOS Lua

**Comment by JuniorNovoa1** [comment]
> > The idea with this commit is to fix text stuff from lua, correct? If I recall correctly, Mac (a supported platform) did have a bug with dialogue (I think it was about the game just not pausing during the dialogue??). Does this fix this? Was it already fixed? Sorry if I sound out of the loop, I can't test the mac build myself.
> 
> was it broken in the first place? it works fine on mine without the fix

So ur telling me your dialogue plays without the song starting?

**Comment by JuniorNovoa1** [comment]
> > The idea with this commit is to fix text stuff from lua, correct? If I recall correctly, Mac (a supported platform) did have a bug with dialogue (I think it was about the game just not pausing during the dialogue??). Does this fix this? Was it already fixed? Sorry if I sound out of the loop, I can't test the mac build myself.
> 
> I recalled correctly #4453
> 
> If this commit fixes this issue then this should absolutely pass.

then ig it's passing

**Comment by Gui-iago** [comment]
> > > The idea with this commit is to fix text stuff from lua, correct? If I recall correctly, Mac (a supported platform) did have a bug with dialogue (I think it was about the game just not pausing during the dialogue??). Does this fix this? Was it already fixed? Sorry if I sound out of the loop, I can't test the mac build myself.
> > 
> > 
> > was it broken in the first place? it works fine on mine without the fix
> 
> So ur telling me your dialogue plays without the song starting?

it plays at the exact moment it starts, blocks my inputs until the dialogue box is closed, starts the countdown and then the song

basically works as expected

**Comment by Dysfunk** [comment]
💀

**Comment by JuniorNovoa1** [comment]
> > I'm not trying to be the hero, I'm trying to be the one with braincells
> 
> so just fork the engine and implement the changes yourself, there's no reason whatsoever for this to be merged, specially because ShadowMario at the current time is fixing bugs, he's not merging PRs and he probably already fixed issues with MacOS Lua

so this bug fix doesn't deserve to be merged?

**Comment by Gui-iago** [comment]
> > > I'm not trying to be the hero, I'm trying to be the one with braincells
> > 
> > 
> > so just fork the engine and implement the changes yourself, there's no reason whatsoever for this to be merged, specially because ShadowMario at the current time is fixing bugs, he's not merging PRs and he probably already fixed issues with MacOS Lua
> 
> so this bug fix doesn't deserve to be merged?

it's basically pointless if he already fixed it

**Comment by JuniorNovoa1** [comment]
> > > > I'm not trying to be the hero, I'm trying to be the one with braincells
> > > 
> > > 
> > > so just fork the engine and implement the changes yourself, there's no reason whatsoever for this to be merged, specially because ShadowMario at the current time is fixing bugs, he's not merging PRs and he probably already fixed issues with MacOS Lua
> > 
> > 
> > so this bug fix doesn't deserve to be merged?
> 
> it's basically pointless if he already fixed it

So dialogue works perfectly on mac?

**Comment by Gui-iago** [comment]
> > > > > I'm not trying to be the hero, I'm trying to be the one with braincells
> > > > 
> > > > 
> > > > so just fork the engine and implement the changes yourself, there's no reason whatsoever for this to be merged, specially because ShadowMario at the current time is fixing bugs, he's not merging PRs and he probably already fixed issues with MacOS Lua
> > > 
> > > 
> > > so this bug fix doesn't deserve to be merged?
> > 
> > 
> > it's basically pointless if he already fixed it
> 
> So dialogue works perfectly on mac?

on private builds, yes, on the current github build, probably no
I've never got into this problem

**Comment by JuniorNovoa1** [comment]
> > > > > > I'm not trying to be the hero, I'm trying to be the one with braincells
> > > > > 
> > > > > 
> > > > > so just fork the engine and implement the changes yourself, there's no reason whatsoever for this to be merged, specially because ShadowMario at the current time is fixing bugs, he's not merging PRs and he probably already fixed issues with MacOS Lua
> > > > 
> > > > 
> > > > so this bug fix doesn't deserve to be merged?
> > > 
> > > 
> > > it's basically pointless if he already fixed it
> > 
> > 
> > So dialogue works perfectly on mac?
> 
> on private builds, yes, on the current github build, probably no I've never got into this problem

that's the point

**Comment by Dysfunk** [comment]
action builds are kinda poopy, its better to build it from the source code

**Comment by JuniorNovoa1** [comment]
> action builds are kinda poopy, its better to build it from the source code

ikr then most of the time they give u errors

**Comment by Gui-iago** [comment]
> 
> that's the point

then why merge it if at this time it's probably already fixed and ShadowMario is probably gonna merge it soon along with other changes?

**Comment by JuniorNovoa1** [comment]
> > that's the point
> 
> then why merge it if at this time it's probably already fixed and ShadowMario is probably gonna merge it soon along with other changes?

it's not fixed, I'm on mac this is a current bug as of rn

**Comment by JuniorNovoa1** [comment]
> > that's the point
> 
> then why merge it if at this time it's probably already fixed and ShadowMario is probably gonna merge it soon along with other changes?

we can wait then.

**Comment by Gui-iago** [comment]
> 
> we can wait then.

my point still stands, forking the engine and implementing the PR changes is still a viable solution for fixing it temporarily at least

**Comment by JuniorNovoa1** [comment]
> > we can wait then.
> 
> my point still stands, forking the engine and implementing the PR changes is still a viable solution for fixing it temporarily at least

never said it wasn't I've just been sayin' this is for other platforms and not FUCKING WINDOWS

**Comment by Gui-iago** [comment]
> 

yeah I don't use windows, I actually use linux instead, dialogue works here
I tested on several windows machines, they also work there
and on my MacOS Virtual Machine (and a real macbook i tested psych), it also works perfectly fine

the thing is, I compiled those builds myself, don't know if the builds from the actions tab are even doing anything major to the compiling process

**Comment by JuniorNovoa1** [comment]
> > never said it wasn't I've just been sayin' this is for other platforms and not FUCKING WINDOWS
> 
> yeah I don't use windows, I actually use linux instead, dialogue works here I tested on several windows machines, they also work there and on my MacOS Virtual Machine (and a real macbook i tested psych), it also works perfectly fine
> 
> the thing is, I compiled those builds myself, don't know if the builds from the actions tab are even doing anything major to the compiling process

OH SHIT I JUST REALIZED UHHHHH what version is ur macbook running

**Comment by Gui-iago** [comment]
> > > never said it wasn't I've just been sayin' this is for other platforms and not FUCKING WINDOWS
> > 
> > 
> > yeah I don't use windows, I actually use linux instead, dialogue works here I tested on several windows machines, they also work there and on my MacOS Virtual Machine (and a real macbook i tested psych), it also works perfectly fine
> > the thing is, I compiled those builds myself, don't know if the builds from the actions tab are even doing anything major to the compiling process
> 
> OH SHIT I JUST REALIZED UHHHHH what version is ur macbook running

MacOS Big Sur (both the macbook and the Virtual Machine)

**Comment by JuniorNovoa1** [comment]
> > > > never said it wasn't I've just been sayin' this is for other platforms and not FUCKING WINDOWS
> > > 
> > > 
> > > yeah I don't use windows, I actually use linux instead, dialogue works here I tested on several windows machines, they also work there and on my MacOS Virtual Machine (and a real macbook i tested psych), it also works perfectly fine
> > > the thing is, I compiled those builds myself, don't know if the builds from the actions tab are even doing anything major to the compiling process
> > 
> > 
> > OH SHIT I JUST REALIZED UHHHHH what version is ur macbook running
> 
> MacOS Big Sur (both the macbook and the Virtual Machine)

okkkkkkk I get it so new software updates and new macs have FUCKED dialogue since new code and software I'm so sorry i never knew this was like this

**Comment by kaysancoder** [comment]
Twitter be like:

**Comment by ShadowMario** [comment]
I won't break Lua for adding compatibility to a build i don't support.

If you want to fix dialogues so much on other builds, set "inCutscene" to true.

**Comment by ACardboardBox1** [comment]
> > 1- Lua already works on Mac without your "fix" 2- Android is not officially supported 3- this is unnecessary
> > period.
> 
>     1. He meant dialogue not pausing and the song continuing while the dialogue is on-screen fucking dumbass.
> 
>     2. Android is supported just needs a little fixing.
> 
>     3. This is necessary since Psych Engine is a "modding" engine
> 
> 
> PERIOD BITCH.


period bitch will not help your statement lmao

**Pull request closed without merging**
