### PR TITLE
Read please

### PR DESCRIPTION
**Pull request by ghost**
twitlonger.com/show/n_1ss997k

adressing about some silly drama (also I made like 8/10th of the shitpost troll pr's here)

I recommend showing haydengaming and the rest of the damsels on psychenginediscussions because there’s something they really will want to read in there

i just want the trolls to stop
                                - jimmy

### CODE REVIEW

**Comment by NexIsDumb** [comment]
why are you guys uploading this kind of stuff as PRs

**Comment by MemeHovy** [comment]
> why are you guys uploading this kind of stuff as PRs and moreover drama

cuz they're trolls

**Comment by MemeHovy** [comment]
it's what they do

**Comment by NexIsDumb** [comment]
💀

https://user-images.githubusercontent.com/87421482/230493610-a3db530a-7a3a-4171-aaf0-53070474a7d2.mov

**Pull request closed without merging**
