### PR TITLE
License Change

### PR DESCRIPTION
**Pull request by xiaochenhao576**
I found that the license just copy and forgot to **change something**(it was the [yyyy] [name of copyright owner]),so i did it lol,also,it was created at 2y ago,so [yyyy] will be 2021

### CODE REVIEW

**Comment by NexIsDumb** [comment]
i dunno if itd be wise to edit it, but i think at thia point its better to copyright ninjamuffin for the original fnf idk

**Comment by EyeDaleHim** [comment]
i don't think you should do this, i think it's better that shadow mario does this himself instead of a random PR.

**Comment by NexIsDumb** [comment]
> i don't think you should do this, i think it's better that shadow mario does this himself instead of a random PR.

indeed

**Comment by ShadowMario** [comment]
I do not own Friday Night Funkin', I think it's more reasonable to credit the Funkin' Team, however I understand absolutely zero things of copyright laws, so I will just leave it blank as I don't care enough.

**Pull request closed without merging**
