### PR TITLE
WHAT THE FUCK SHADOW MARIO

### PR DESCRIPTION
**Pull request by Votexz**
WHY THIS SHIT DON'T WORK??
I DOWNLOAD ALL LIBRARIES!
Снимок экрана 2023-05-03 211011

WHY THIS

### CODE REVIEW

**Comment by KookerFoxYT** [comment]
shouldnt this be just an issue and not a pr

**Comment by MemeHovy** [comment]
> shouldnt this be just an issue and not a pr

agreed

**Comment by jimmyjamescool** [comment]
A7C0514B-DB2B-4792-80C5-195D2DD125D7
💀

**Comment by BeastlyGabi** [comment]
downgrade haxe to 4.2.5

**Comment by KookerFoxYT** [comment]
> downgrade haxe to 4.2.5

or downgrade your flixel to the one before haxe 4.3.0

**Comment by NexIsDumb** [comment]
> > downgrade haxe to 4.2.5
> 
> or downgrade your flixel to the one before haxe 4.3.0

and flixel-addons

plus why is this a PR and not an issue bruh

**Comment by NexIsDumb** [comment]
@stikiPorter use the new hmm from #12366

**Comment by WickedYT** [comment]
just downgrade haxe to 4.2.5 and then like download hmm and run it. not that big of a deal

**Comment by catte-cloud** [comment]
cry about it

**Comment by NexIsDumb** [comment]
why is this still here god

**Comment by NexIsDumb** [comment]
> i am still waiting to get this closed
> 
> maybe when shadowmario does another commit, he might 

i doubt but i hope

**Comment by KookerFoxYT** [comment]
> > i am still waiting to get this closed
> > maybe when shadowmario does another commit, he might
> 
> i doubt but i hope too

same

**Comment by KookerFoxYT** [comment]
he made a commit recently but did not close this pr
huh

**Comment by NexIsDumb** [comment]
> he made a commit recently but did not close this pr
> 
> huh

Bruh

**Comment by J0nathan550** [comment]
Downgrade will work with 4.2.5 and here is the hmm.json that you should install, I collect all stuff to get it work, waste fucking few hours to get it done

```json
{
  "dependencies": [
    {
      "name": "lime",
      "type": "haxelib",
      "version": "8.0.1"
    },
    {
      "name": "openfl",
      "type": "haxelib",
      "version": null
    },
    {
      "name": "flixel",
      "type": "haxelib",
      "version": "5.2.2"
    },
    {
      "name": "flixel-addons",
      "type": "haxelib",
      "version": null
    },
    {
      "name": "flixel-tools",
      "type": "haxelib",
      "version": null
    },
    {
      "name": "flixel-ui",
      "type": "haxelib",
      "version": null
    },
    {
      "name": "hxcpp",
      "type": "haxelib",
      "version": null
    },
    {
      "name": "tjson",
      "type": "haxelib",
      "version": null
    },
    {
      "name": "hxjsonast",
      "type": "haxelib",
      "version": null
    },
    {
      "name": "hxCodec",
      "type": "haxelib",
      "version": "2.6.1"
    },
    {
      "name": "hscript",
      "type": "haxelib",
      "version": null
    },
    {
      "name": "hxcpp-debug-server",
      "type": "haxelib",
      "version": null
    },
    {
      "name": "discord_rpc",
      "type": "git",
      "dir": null,
      "ref": "master",
      "url": "https://github.com/Aidan63/linc_discord-rpc"
    },
    {
      "name": "hscript-ex",
      "type": "git",
      "dir": null,
      "ref": "master",
      "url": "https://github.com/ianharrigan/hscript-ex"
    },
    {
      "name": "linc_luajit",
      "type": "git",
      "dir": null,
      "ref": "master",
      "url": "https://github.com/nebulazorua/linc_luajit"
    }
  ]
}
```
Let me know if is there any issues

**Pull request closed without merging**
