### PR TITLE
Delete GitarooPause.hx

### PR DESCRIPTION
**Pull request by Jotaro-Gaming**
simple it isnt used
also saves about 2.22KB not really a large number but its something

### CODE REVIEW

**Comment by Steviegt6** [comment]
It *is* used.

**Comment by MrClogsworthYT** [comment]
> It _is_ used, just in the vanilla game. Preferably should be kept for easy merging.

and this _isnt_ the vanilla game

**Comment by Steviegt6** [comment]
> > It _is_ used, just in the vanilla game. Preferably should be kept for easy merging.
> 
> and this _isnt_ the vanilla game

Read the latter half of my message, and stop trying to get useless commits into this repository.

**Comment by MrClogsworthYT** [comment]
> > > It _is_ used, just in the vanilla game. Preferably should be kept for easy merging.
> > 
> > 
> > and this _isnt_ the vanilla game
> 
> Read the latter half of my message, and stop trying to get useless commits into this repository.

ok

**Pull request closed without merging**
