### PR TITLE
typo

### PR DESCRIPTION
**Pull request by ghost**
wth is this typo 💀
@ShadowMario you should migrate this

### CODE REVIEW

**Review by moxie-coder — APPROVED** [review]

**Comment by Akhia11** [comment]
*gets rejected by shadow mario*

**Comment by ShadowMario** [comment]
Don't ping me, i have notifications turned off and i can't see it

**Comment by Akhia11** [comment]
Holy shuhuhtigdush

**Comment by mcagabe19** [comment]
> Don't ping me, i have notifications turned off and i can't see it

@MemeHovy told me already but oki

**Pull request merged**
