### PR TITLE
Update credits

### PR DESCRIPTION
**Pull request by superpowers04**
* Change my twitter to my bio(I don't use twitter that often)
* Adjust my credit reason a bit (thank for the credits btw)

### CODE REVIEW

**Review by moxie-coder — APPROVED** [review]
👍🏻

**Comment by Raltyro** [comment]
This does not solve miscredited contributors (gabriela, etc.) /hj

**Review by NexIsDumb — APPROVED** [review]
At this point I'd suggest adding smth to update the credits without everytime making a pr, maybe like checking an online file, similar to what the game does for checking updates

**Comment by NexIsDumb** [comment]
> At this point I'd suggest adding smth to update the credits without everytime making a pr, maybe like checking an online file, similar to what the game does for checking updates

The problem is that every credited person should be aware and okay with this and create the actual file, sooo

Or maybe shadowmario creating an online doc where he adds the credited ppl as editors, idk

**Pull request closed without merging**
