### PR TITLE
rewrite most of MainMenuState

### PR DESCRIPTION
**Pull request by Rudyrue**
makes some variables final
sets active to false on the bg and text objects cuz they don't need to be updated every frame
reworks how curselected is handled which now makes adding mouse support easier

also fixed the cam lerp bug that i caused because psych does cam lerp weirdly

also also yea i could've used setFormat for the text shur up.......

### CODE REVIEW

**Review by DetectiveBaldi — APPROVED** [review]
this has reminded me that i should use finals more in the main menu im making

**Review by richTrash21 — APPROVED** [review]
FlxMath.wrap()????? so based
ezgif-2-db4f8e0187

**Comment by Rudyrue** [comment]
oh my GOD i hate github so fucking much

**Comment by Rudyrue** [comment]
welp that's stuck in this pr now

**Pull request closed without merging**
