### PR TITLE
Little improvements

### LINKED ISSUE #1237: Optimization Mode for really shit PC's
### What feature do you want to get added on the base engine?

I would like an optimization mode to get added to Psych Engine, which removes backgrounds and characters entirely.

This could have the potential to help with performance on comically bad PC's...like mine and also focus.

If not optimization atleast some overlay below the arrows?, Low quality being on and anti-aliasing being off don't help with performance a whole lot.

I don't have anything else to say here

### PR DESCRIPTION
**Pull request by stilic**
- Add "Max Optimization" option (closes #1237).
- Make the start transition of notes at start of a song selected from freeplay also happen to the first song of a story playlist.
- **For Visual Studio Code**: add a new file for make tests of code easier to run.

### CODE REVIEW

**Comment by Stilic** [comment]
@ShadowMario Can you take a look at this please?

**Comment by ShadowMario** [comment]
Most of these stuff have been fixed already

**Comment by Stilic** [comment]
> Most of these stuff have been fixed already

Yes but this PR adds three things:

> * Add "Max Optimization" option (closes [Optimization Mode for really shit PC's #1237](https://github.com/ShadowMario/FNF-PsychEngine/issues/1237)).
> * Make the start transition of notes at start of a song selected from freeplay also happen to the first song of a story playlist.
> * **For Visual Studio Code**: add a new file for make tests of code easier to run.

**Comment by Stilic** [comment]
@ShadowMario Can you merge my PR?

**Comment by Stilic** [comment]
I don't understand why this PR is not merged for now. (I really don't want to ping again ShadowMario to bother him)

**Pull request closed without merging**
