### PR TITLE
Audio Options

### PR DESCRIPTION
**Pull request by Burgerballs**
Allows you to change the volume of the sound effects used in gameplay (eg; Philly trains, limo cars, miss sounds, etc)

This PR also sorts all the catagories alphabetically, and renames 'Graphics' to 'Graphics And Audio'
[Video](https://files.catbox.moe/7xirf2.mp4)

### CODE REVIEW

**Comment by CharlesCatYT** [comment]
what cuz the game's volume tray isnt enough?

well at least this helps for doing ost videos
but we have a music player so

**Comment by Burgerballs** [comment]
> what cuz the game's volume tray isnt enough?
> 
> well at least this helps for doing ost videos but we have a music player so

the volume tray applies to all audio, these options separate the sfx and music.

**Comment by Fearester2008** [comment]
I guess that this option is need in game

**Comment by Gearybeer** [comment]
I can see the usefulness. Turning down the train sound effects in week 4, gunshots in weekend 1, I can see the use here

**Comment by ShadowMario** [comment]
Feels kinda useless

**Pull request closed without merging**
