### PR TITLE
BPMs in chart editor are no longer capped at 339

### PR DESCRIPTION
**Pull request by Jaduplex**
removed completely arbitrary limitation. now you can make songs up to 1000 bpm which is way more than youd ever need so enjoy

### CODE REVIEW

**Comment by tposejank** [comment]
no

**Review by Jotaro-Gaming — APPROVED** [review]
Some songs exceed even 500 bpm this will 100% help for them

**Review by HiroMizuki — APPROVED** [review]
i rlly would like it cuz i've already seen songs with an extremely high BPM

**Comment by XtraXD1** [comment]
Better cap it at a maximum of 999. :]

**Comment by HiroMizuki** [comment]
> Better cap it at a maximum of 999. :]

not rlly, there's songs with 1000 BPM, and it's better leave this cap with 1000 as well

**Review by ghost — APPROVED** [review]
yes i can FINALLY chart kalampokiphobia

**Review by stilic — APPROVED** [review]

**Comment by tposejank** [comment]
not offensive i like this but shadow mario would probably never merge this because he thinks its ridicule to chart a song over 339 bpm
plus you can edit it from the chart JSON anyway

**Comment by MrClogsworthYT** [comment]
> not offensive i like this but shadow mario would probably never merge this because he thinks its ridicule to chart a song over 339 bpm plus you can edit it from the chart JSON anyway

tbh this engine focuses on modding so uh i think he will still merge (:

**Comment by ActualMandM** [comment]
for the record, base FNF also caps it at 339

https://github.com/ninjamuffin99/Funkin/blob/f94dece4a40d977c8a501b55ed9b9b3ee4344e13/source/ChartingState.hx#L222

**Comment by HiroMizuki** [comment]
> > not offensive i like this but shadow mario would probably never merge this because he thinks its ridicule to chart a song over 339 bpm plus you can edit it from the chart JSON anyway
> 
> tbh this engine focuses on modding so uh i think he will still merge (:

i don't think he will, but maybe some people can use this

**Comment by tposejank** [comment]
> > not offensive i like this but shadow mario would probably never merge this because he thinks its ridicule to chart a song over 339 bpm plus you can edit it from the chart JSON anyway
> 
> tbh this engine focuses on modding so uh i think he will still merge (:

nope

**Comment by ActualMandM** [comment]
forgot to check for this earlier, but the change bpm stepper goes up to 999 in both base FNF and in psych

https://github.com/ninjamuffin99/Funkin/blob/f94dece4a40d977c8a501b55ed9b9b3ee4344e13/source/ChartingState.hx#L277

https://github.com/ShadowMario/FNF-PsychEngine/blob/96b294b7d93c15f16aea39d2c64c37219b8ce1b6/source/editors/ChartingState.hx#L659

**Comment by SonicProYT** [comment]
> > not offensive i like this but shadow mario would probably never merge this because he thinks its ridicule to chart a song over 339 bpm plus you can edit it from the chart JSON anyway
> 
> tbh this engine focuses on modding so uh i think he will still merge (:

i dont think shadow mario will merge at  all

**Comment by Wither362** [comment]
> not offensive i like this but shadow mario would probably never merge this because he thinks its ridicule to chart a song over 339 bpm
> plus you can edit it from the chart JSON anyway

But I wanted to make a song with more than **_340_** bpm :(

**Comment by HiroMizuki** [comment]
> finnaly, songs with 69420 bpm can be charted..not that there is any lol

the max at the PR is 999

**Comment by HiroMizuki** [comment]
but u can use it for cap as long as u want, i would change it just to chart 2021, by Camellia

**Comment by the-funky-lad** [comment]
use change bpm

**Comment by sonicfan888** [comment]
Bruh
You can just chart it by using Half BPM of [bpm amount]
In this case
Kalampokiphobia has 522 BPM
So you can do 522 : 2 = 261
You can chart it using half BPM and i believe this is what they did on that one Bambi's Hellscape mod

**Comment by sonicfan888** [comment]
But whatever

**Pull request closed without merging**
