### PR TITLE
Try this, Mac users. :)

### PR DESCRIPTION
**Pull request by fireredfan7**
This is a crucial fix for the Mac build.

### CODE REVIEW

**Comment by fireredfan7** [comment]
This is a crucial fix for the Mac build.

**Comment by tposejank** [comment]
Extra thanks to @gaminbottomtext

**Comment by gaminbottomtext** [comment]
?

**Comment by fireredfan7** [comment]
Many thanks, ShadowMario.

**Comment by gaminbottomtext** [comment]
ok

**Pull request merged**
