### PR TITLE
Allow custom FlxCameras to be used on `LuaUtils.cameraFromString`

### PR DESCRIPTION
**Pull request by melodiekit**
Allow custom FlxCameras to be used so long as they are in the `variables` map

### CODE REVIEW

**Comment by DetectiveBaldi** [comment]
I would probably move this functionality into the `LuaUtils.cameraFromString` function itself, firstly check the PlayState cameras, and then check the `variables` map

**Comment by LarryFrosty** [comment]
> I would probably move this functionality into the `LuaUtils.cameraFromString` function itself, firstly check the PlayState cameras, and then check the `variables` map

Something like this?

```haxe
public static function cameraFromString(cam:String):FlxCamera {
	switch(cam.toLowerCase()) {
		case 'camgame' | 'game': return PlayState.instance.camGame;
		case 'camhud' | 'hud': return PlayState.instance.camHUD;
		case 'camother' | 'other': return PlayState.instance.camOther;
		}
		var camera:Dynamic = PlayState.instance.variables.get(cam);
		if (camera == null || !Std.isOfType(camera, FlxCamera)) camera = PlayState.instance.camGame;
		return camera;
}
```

**Comment by DetectiveBaldi** [comment]
> > I would probably move this functionality into the `LuaUtils.cameraFromString` function itself, firstly check the PlayState cameras, and then check the `variables` map
> 
> Something like this?
> 
> ```hx
> public static function cameraFromString(cam:String):FlxCamera {
>     switch(cam.toLowerCase()) {
>         case 'camgame' | 'game': return PlayState.instance.camGame;
>         case 'camhud' | 'hud': return PlayState.instance.camHUD;
>         case 'camother' | 'other': return PlayState.instance.camOther;
>     }
>     var camera:Dynamic = PlayState.instance.variables.get(cam);
>     if (camera == null || !Std.isOfType(camera, FlxCamera)) camera = PlayState.instance.camGame;
>     return camera;
> }
> ```

yea, looks good

**Review by DetectiveBaldi — APPROVED** [review]

**Review by rodney528 — APPROVED** [review]

**Comment by LarryFrosty** [comment]
#15088

**Pull request closed without merging**
