### PR TITLE
Fix crashes with Character Editor when using Forbidden Windows names.

### PR DESCRIPTION
**Pull request by MemeHoovy**
Fix crash when using forbidden Windows
names in the Character Editor, referencing this issue: #9902 
If this gets closed then so be it.

### CODE REVIEW

**Review by TheKitBoi — APPROVED** [review]

**Comment by kingyomoma** [comment]
arrays exist

**Comment by kingyomoma** [comment]
you could do something along the lines of this
```haxe
if (sender == healthIconInputText) {
    var forbidden:Array<String> = ['AUX', 'CON', 'PRN', 'NUL']
    for (i in 1...9) {
        forbidden.push('COM$i')
        forbidden.push('LPT$i')
    }

    for (donot in forbidden) {
        if (sender.text == donot) return;
    }
}
```

**Comment by MemeHoovy** [comment]
> you could do something along the lines of this
> 
> ```hx
> if (sender == healthIconInputText) {
>     var forbidden:Array<String> = ['AUX', 'CON', 'PRN', 'NUL'];
>     for (i in 1...9) {
>         forbidden.push('COM$i');
>         forbidden.push('LPT$i');
>     }
> 
>     for (donot in forbidden) {
>         if (sender.text == donot) return;
>     }
> }
> ```

Ok thanks.

**Review by CrusherMods — APPROVED** [review]

**Review by Raltyro — APPROVED** [review]

**Review by Stilic — APPROVED** [review]

**Review by Intancote — APPROVED** [review]

**Review by JorosTheModderPH — APPROVED** [review]

**Comment by MemeHoovy** [comment]
I think it's clear that shadow mario won't merge this, if you wanna use this for your own mods go ahead

**Comment by MemeHoovy** [comment]
I won't delete the branch just in case

**Pull request closed without merging**
