### PR TITLE
Tiny little fix that fixes html5 build errors

### PR DESCRIPTION
**Pull request by UncertainProd**
Yeah, barely anyone builds for html5 but this should fix some of the build errors for html5 (as of v0.6.2)
(specifically these errors that popped up)
```cmd
source/FunkinLua.hx:3061: characters 23-28 : Type not found : State
source/CoolUtil.hx:18: lines 18-141 : ... Defined in this class
source/PlayState.hx:3752: characters 40-68 : Class<FunkinLua> has no field getPropertyLoopThingWhatever
source/PlayState.hx:4895: characters 8-12 : FunkinLua has no field call
source/PlayState.hx:4896: characters 8-12 : FunkinLua has no field stop
```
Basically added a few conditional compilation flags that stop llua.State from being checked for html5

### CODE REVIEW

**Review by TheKitBoi — APPROVED** [review]

**Review by DaRealDotZ — APPROVED** [review]

**Review by Parsellol — APPROVED** [review]

**Review by MemeHoovy — APPROVED** [review]

**Review by CrusherNotDrip — APPROVED** [review]
im on html5 and github actions until my main computer comes back alive

**Review by ghost — APPROVED** [review]

**Review by Raltyro — APPROVED** [review]

**Review by Intancote — APPROVED** [review]

**Comment by ethpsa09** [comment]
This works! Im a noob at github so idk how to approve but this worked for me :)

**Comment by tylerandari12** [comment]
Can confirm this works...

**Review by ghost — APPROVED** [review]
!!!

**Pull request closed without merging**
