### PR TITLE
fix -null on using chart editor on boot up

### PR DESCRIPTION
**Pull request by raf13lol**
this makes it so if it gets a null difficulty (which it usually does on boot-up and not loading any songs), it will just not have a file suffix

### CODE REVIEW

**Review by SillyVyxia — APPROVED** [review]

**Review by TheKitBoi — APPROVED** [review]

**Review by Mokona59 — APPROVED** [review]

**Comment by brujfnf** [comment]
hi raf 😁

**Comment by RafPlayz69YT** [comment]
hi

**Comment by ThePlank** [comment]
hi raf 😁

**Comment by RafPlayz69YT** [comment]
hi

**Pull request closed without merging**
