### PR TITLE
restore bf-old easter egg

### LINKED ISSUE #3571: Pressing 9 doesn't make the bf icon switch old bf icon
### What is your question?

so i idk if its a bug or you just took it out? an if so why did you take it out?

### PR DESCRIPTION
**Pull request by Jotaro-Gaming**
how dare you guys remove it

### CODE REVIEW

**Comment by HiroMizuki** [comment]
image

**Comment by Gui-iago** [comment]
it's useless

**Comment by Hunter13n** [comment]
🤔

**Comment by MrClogsworthYT** [comment]
> image

if its useless by bbpanzu logic then why isnt that rare easter egg of gameover not removed?

**Comment by MrClogsworthYT** [comment]
> it's useless

so?

**Comment by MrClogsworthYT** [comment]
by your logic the game is useless lmfao

**Comment by Gui-iago** [comment]
> by your logic the game is useless lmfao

just leave that on your own builds, nor SM or bbpanzu want this on the engine

**Comment by DaBanana64** [comment]
> by your logic the game is useless lmfao

By that logic, your logic that makes the game useless is useless.

**Comment by Gui-iago** [comment]
"damn I can't press 9 to change bf's icon, engine ruined :cry: :cry:"
seriously, it's just an easter egg, not a game changer, just keep it on private forks of PE instead of merging it on the official repository, if the devs don't want it, then there's no reason to do it

**Comment by HiroMizuki** [comment]
> by your logic the game is useless lmfao

ok and

**Comment by HiroMizuki** [comment]
and this code doesn't work, i tried it out right now LOL

**Pull request closed without merging**
