### PR TITLE
Add support for 5,6,7,8 and 9 key charts

### LINKED ISSUE #12: more keys support (5k, 6k, etc etc)
( for reference - https://gamebanana.com/mods/311713 or https://github.com/TheZoroForce240/FNF-with-extra-keys )

would it be possible to port this into the chart editor? i know Shaggy and this other mod and stuff are made with kade engine, but maybe it is possible to redo the code on Psych Engine?

### PR DESCRIPTION
**Pull request by DevScyu**
As the title says this PR adds support for 5,6,7,8 and 9 key charts, and the ability to chart them via the chart editor.

All regular note functions can be applied to the extra keys such as modifying the hue sat and brightness via the note options, and custom key binds for each of the modes.

Pixel note assets and splash note assets kindly created by RiverOaken

This took around 25 hours to implement, test and get working properly.

Fixes #514 
Fixes #474 
Fixes #12

### CODE REVIEW

**Comment by FuseIsHere813** [comment]
I will use this, but I wouldn't merge it if I were you. Because ShadowMario may not want more keys in the engine.

**Comment by DevScyu** [comment]
> I will use this, but I wouldn't merge it if I were you. Because ShadowMario may not want more keys in the engine.

I am not able to merge, only @ShadowMario is able to.

I am making this PR so that they are able to merge it in if they want to. I saw them say before they wouldn't add it since it would take too much effort to add with all of the additions made by Psych. I have tried to make it as compatible with Psych as possible, such as working via mods folder and json files etc etc

**Comment by FuseIsHere813** [comment]
Ohh, i guess this explains why. Thanks for the explanation!

**Comment by ShadowMario** [comment]
I already said i don't want to implement it into the master branch, feel free to do your own branch but i don't want it.

**Comment by DevScyu** [comment]
> I already said i don't want to implement it into the master branch, feel free to do your own branch but i don't want it.

Fair enough. I saw this message and thought you were just too busy to focus on it.

> Would probably be too annoying to code and make compatible with the changes already in.

**Pull request closed without merging**
