### PR TITLE
Fixed Mp4 video handler error

### PR DESCRIPTION
**Pull request by JonnycatMeow**

### CODE REVIEW

**Review by Raltyro — COMMENTED** [review]
Someone (BeatlyGhost) already did this, it's currently in draft because haxelib for hxCodec isn't updated yet
https://github.com/ShadowMario/FNF-PsychEngine/pull/9112

**Comment by trayfellow** [comment]
this is cause the current version of hxcodec psych uses is the haxelib version, if you want to compile psych engine make sure ur using the haxelib version instead of the git version of hxcodec, we should wait hxcodec to update first then this can be changed

**Comment by BeastlyGhost** [comment]
this error doesn't need to be fixed, as Psych Engine uses the stable branch of hxCodec

image
the stable branch uses MP4Handler, which is basically the old version of VideoHandler, simply install from stable rather than from the git branch with `haxelib install hxCodec`

**Review by EyeDaleHim — CHANGES_REQUESTED** [review]
Question, are you on 0.6.2?

**Comment by ItsyourboyJonnycat** [comment]
i think so

**Pull request closed without merging**
