### PR TITLE
lua/mod changes

### PR DESCRIPTION
**Pull request by nebulazorua**
lets you manipulate individual notes w/ lua api, and also adds a new function "onSpawnNote", which is called when a note is spawned.

if you want to, for example, hide note 6 to 12 in the chart, you could do something like
```lua
function onSpawnNote(index, direction, noteType, isSustainNote, id)
    if(id>=5 and id<=11)then
        setProperty("note"..id..".copyAlpha", false)
        setProperty("note"..id..".alpha", 0)
    end
end
```

also adds `addAnimation` which works the same as haxeflixel's sprite.animation.add, and you can now specify the gridX and gridY in loadgraphic

### CODE REVIEW

**Comment by Stilic** [comment]
no way andromeda x psych??? (i was joking)

**Review by stilic — APPROVED** [review]

**Review by Raltyro — APPROVED** [review]

**Review by Blossomical — APPROVED** [review]
gotta appreciate the hard work

**Comment by mayo78** [comment]
could you set the note's camera with this? cause that would be cool

**Comment by nebulazorua** [comment]
> could you set the note's camera with this? cause that would be cool

yes you can

**Review by mayo78 — APPROVED** [review]

**Review by HeliProGamer — APPROVED** [review]

**Comment by nebulazorua** [comment]
made it so getPropertyFromGroup can now be used on other things so you can like
`getPropertyFromGroup('note1.tail', 0, 'ID')` to get the 1st sustain attached to the 2nd note in the chart's ID, for example

**Review by TheKitBoi — APPROVED** [review]

**Review by GO-Miles — APPROVED** [review]

**Comment by nebulazorua** [comment]
@ShadowMario i beg pls merge

**Review by GamerZoneMusic — APPROVED** [review]

**Review by DM-kun — APPROVED** [review]

**Review by ghost — APPROVED** [review]
APPROVED APPROVED I NEED THIS SO BAD

**Review by Apearson75 — APPROVED** [review]

**Comment by Phoneguytech75** [comment]
This is very cool

**Review by iym1337 — APPROVED** [review]

**Comment by nebulazorua** [comment]
:pensive:

**Comment by Itz-NOT-Miles** [comment]
(slightly off topic) @nebulazorua I want the camera to follow a specific note, are there any source counterparts I can use to do this?

**Comment by nebulazorua** [comment]
Updated one over at https://github.com/ShadowMario/FNF-PsychEngine/pull/8890

**Pull request closed without merging**
