### PR TITLE
rewrite BUILDING.md

### PR DESCRIPTION
**Pull request by Rudyrue**
rewrites BUILDING.md to be more concise and informative

### CODE REVIEW

**Review by crowplexus — APPROVED** [review]
erm what the ribbit?

**Comment by Stefan2008Git** [comment]
You can install normally ``g++`` on Fedora Linux. It will install automatically all packages for g++ when you accept the installation

**Comment by Rudyrue** [comment]
> You can install normally ``g++`` on Fedora Linux. It will install automatically all packages for g++ when you accept the installation 

i don't use linux
super was the one that made those instructions

but thanks i guess lmao

**Comment by Stefan2008Git** [comment]
> > You can install normally `g++` on Fedora Linux. It will install automatically all packages for g++ when you accept the installation
> 
> i don't use linux super was the one that made those instructions
> 
> but thanks i guess lmao

Yw

**Review by ACoolioDude — APPROVED** [review]

**Comment by Stefan2008Git** [comment]
> > > You can install normally `g++` on Fedora Linux. It will install automatically all packages for g++ when you accept the installation
> > 
> > 
> > i don't use linux super was the one that made those instructions
> > but thanks i guess lmao
> 
> Yw

O, i forgot that Fedora Linux doesn't support libvlc  and libvlccore since Fedora Linux is a different Linux Distro with different package manager, so you are able to compile normally game without libvlc stuff, but you just need a g++ for that.

**Pull request closed without merging**
