### PR TITLE
This might be necessary.

### PR DESCRIPTION
**Pull request by MeowcaTheoRange**
This will help somewhat to combat the gargantuan amount of stage editor requests out there.

### CODE REVIEW

**Comment by DeceptedPar** [comment]
I'm pretty sure Shadow said they weren't gonna do winning icons, that could change in the future though.

**Comment by MeowcaTheoRange** [comment]
> I'm pretty sure Shadow said they weren't gonna do winning icons, that could change in the future though.

Yes, this is what shouldn't be *suggested*. This is still open to changes in things, like if ShadowMario/the team is considering adding winning icons.

**Comment by ShadowMario** [comment]
This is actually pretty clever, and also funny lmao.

**Comment by MeowcaTheoRange** [comment]
Holy fuck this change was amazing. It gives me stuff to look at when I'm super bored and want something to laugh at.
I love the `i swear to god` tag it's the best thank you

**Pull request merged**
