### PR TITLE
Fixed an error in StoryMenuState

### PR DESCRIPTION
**Pull request by flashintv**
`image is FlxGraphic` changed to `Std.is(image, FlxGraphic)`

### CODE REVIEW

**Comment by flashintv** [comment]
Creating this pull request, because I seen a lot of people coming and posting about: `Expected )`

**Comment by flashintv** [comment]
> change `Std.is` to `Std.isOfType`

both of them are the same, but the other one is just depricated but sure

**Comment by ShadowMario** [comment]
Update your Haxe.

**Comment by flashintv** [comment]
> Update your Haxe.
caption

No legacy support

**Pull request closed without merging**
