### PR TITLE
make icons in freeplay centered properly

### PR DESCRIPTION
**Pull request by Rudyrue**
icons in freeplay are off center
this fixes that

# without fix

# with fix

icons are also both 300x150

this might also be a shit way of fixing it but im sure someone will make a better method down the road lmao

### CODE REVIEW

**Comment by Unholywanderer** [comment]
what if instead i snapped you into 2 pieces like a kit kat bar

**Comment by Rudyrue** [comment]
nerd emoji's you

**Comment by richTrash21** [comment]
mid😔

**Comment by Rudyrue** [comment]
ok bro

**Pull request closed without merging**
