### PR TITLE
Fix crash on story mode weeks 6 and 7

### PR DESCRIPTION
**Pull request by RedstoneRuler**
This fixes a null object reference crash on story mode. Pretty simple.

### CODE REVIEW

**Review by TheKitBoi — APPROVED** [review]

**Comment by MemeHoovy** [comment]
What did you do? you replaced the whole playstate

**Comment by TheKitBoi** [comment]
I’m taking my approval back

**Comment by MemeHoovy** [comment]
> I’m taking my approval back

I wish you could

**Comment by RedstoneRuler** [comment]
Yeah, I have no idea why it thinks I replaced the entirety of PlayState, I only edited a few lines. I'm gonna try to fix that.

**Pull request closed without merging**
