### PR TITLE
No more BPM Capping.

### PR DESCRIPTION
**Pull request by Joalor64**
This is kind of a duplicate of #3572, but better. Now the max BPM in the chart editor is 10000. 
(This is my first time making pull requests, okay?)

### CODE REVIEW

**Comment by PrismLight** [comment]
jsfdjnfsdjk;adfphoiusdgr7deywatquwrekkkkkkkkkkkkkkdhfn4wj;oiph35fyurjmks,l;
The hardest song.

**Comment by Joalor64GH** [comment]
imagine somebody made that an actual mod lol that would be funny i think

**Comment by PrismLight** [comment]
> imagine somebody made that an actual mod lol that would be funny i think

Ik. But why 10k nobody even needs that.

**Comment by Joalor64GH** [comment]
i know it's a bit too much

**Comment by BombasticTom** [comment]
> > imagine somebody made that an actual mod lol that would be funny i think
> 
> Ik. But why 10k nobody even needs that.

you forgot about dave and bambi porters, right?

**Review by lunacynne — APPROVED** [review]

**Comment by Wither362** [comment]
Wait, I tested this at it crashed, this isn’t good for low pcs, instead of 10000 use 1000 bpm

**Review by Wither362 — CHANGES_REQUESTED** [review]
I approve this, but I have tested this, and for low pcs isn’t good, better if the max bpm is 1000 instead of 10000

**Comment by Joalor64GH** [comment]
you're right

**Pull request closed without merging**
