### PR TITLE
Better health system.

### PR DESCRIPTION
**Pull request by ghost**
Reduces health value checks down to a single line, using FlxMath.bound, also accounts for practice mode when the health hits/is at 0.

### CODE REVIEW

**Review by richTrash21 — CHANGES_REQUESTED** [review]
I suggest using Math.min(), since health <= 0 is always gameover.
Ex:
```haxe
health = Math.min(health, (healthBar.bounds.max != null ? healthBar.bounds.max : 2));
```
Also it will be a good idea to add a setter for the health and move bound code there, so that hp would be bounded only when it's value changed.
Ex:
```haxe
public var health(default, set):Float = 1.0;

function set_health(HP:Float):Float
{
    if (health == HP)
        return HP; // hp hasn't changed = just return it

    // bounds HP to the lower bound
    health = Math.min(HP, (healthBar.bounds.max != null ? healthBar.bounds.max : 2));
    doDeathCheck(); // just a convinience
    return health; // returns bounded health
}
```

**Comment by Blue2359** [comment]
> `I suggest using Math.min(), since health <= 0 is always gameover. Ex:`
My fix also accounted for practice mode, since you can't die when it's enabled, and the icons just start going offscreen when the `health` is below 0.

**Comment by richTrash21** [comment]
> My fix also accounted for practice mode, since you can't die when it's enabled, and the icons just start going offscreen when the `health` is below 0.

Ohhh yeah, forgot about this. My bad

**Comment by ShadowMario** [comment]
Health is supposed to get negative

**Pull request closed without merging**
