### PR TITLE
Include all Flixel classes without DCE

### PR DESCRIPTION
**Pull request by ThomasDarkson**
This PR makes it so game includes all unused Flixel classes without DCE
Includes 252 classes

### CODE REVIEW

**Comment by PurSnake** [comment]
Macro: just exists

**Comment by Vortex2Oblivion** [comment]
Couldn't you just use a macro?
Also why do we need this?

**Comment by Sword352** [comment]
I don't like how that's being done. I would rather just use macro than pushing lots of classes into an unused array at runtime.
See https://api.haxe.org/haxe/macro/Compiler.html#include

**Comment by ActualMandM** [comment]
#12953 does this same thing but in a much better manner

**Pull request closed without merging**
