### PR TITLE
[WIP] More intro text funies

### PR DESCRIPTION
**Pull request by tailsicweneedtocook**
Adding about 2000+

Don’t close as I’m still makin this
Also do txt compressors exist

### CODE REVIEW

**Comment by TheKitBoi** [comment]
> Also do txt compressors exist

Yes https://github.com/SamirPaul1/txt-compressor

**Comment by tailsicweneedtocook** [comment]
> > Also do txt compressors exist
> 
> Yes https://github.com/SamirPaul1/txt-compressor

thanks bro

**Comment by CaptainBaldi** [comment]
people are coming up with the most wack pr's these days

**Comment by tailsicweneedtocook** [comment]
> people are coming up with the most wack pr's these days

I’m still gonna finish it

**Pull request closed without merging**
