### PR TITLE
fix ghostChar not scaling with player

### PR DESCRIPTION
**Pull request by DM-kun**
a very simple and small fix for the character editor, which makes the ghost char finally scale with the player
image

### CODE REVIEW

**Review by CrusherNotDrip — APPROVED** [review]

**Comment by Grape-Boy** [comment]
good

**Review by DeadSyntaxdev — APPROVED** [review]

**Review by BombasticTom — APPROVED** [review]

**Review by Raltyro — APPROVED** [review]

**Comment by Grape-Boy** [comment]
why was this closed

**Comment by BombasticTom** [comment]
he fucked up something #8561

**Comment by DMMaster636** [comment]
> why was this closed

Yeah, I managed to fuck my entire fork thanks to github being weird for me sometimes
Well, at last I re-opened it #8561

**Pull request closed without merging**
