### PR TITLE
Dialogue fix for Mac

### PR DESCRIPTION
**Pull request by fireredfan7**
A smarter version of another pr that should not have been closed.

### CODE REVIEW

**Comment by fireredfan7** [comment]
Thanks @beeanie

**Comment by beeanie** [comment]
your welcome

**Comment by beeanie** [comment]
instead of #if mac instead make it #if macro

**Comment by beeanie** [comment]
please

**Comment by fireredfan7** [comment]
idk what that does

**Comment by fireredfan7** [comment]
> instead of #if mac instead make it #if macro

I don’t know what that does.

**Comment by beeanie** [comment]
its bascially mac but its macro

**Comment by beeanie** [comment]
actually it dosn't work i just tested it

**Comment by fireredfan7** [comment]
> actually it dosn't work i just tested it

Mac or macro?

**Comment by beeanie** [comment]
let me test it agian

**Comment by beeanie** [comment]
actually nevermind

**Comment by beeanie** [comment]
it works

**Review by ghost — APPROVED** [review]
i approve

**Comment by fireredfan7** [comment]
When I tested it, I think it didn’t work for the very first time but it worked every other time.

**Review by ghost — COMMENTED** [review]
i think it should be #if macos  instead of #if mac

**Comment by fireredfan7** [comment]
aw

**Pull request closed without merging**
