### PR TITLE
lane underlay

### PR DESCRIPTION
**Pull request by nahiassis**

### CODE REVIEW

**Comment by MayoALT** [comment]
can you explain what this does

**Comment by nintendofan44** [comment]
its a background kind of thing behind the strum line.

In the Visuals and UI section of the options menu
you can set the transparency for it

from 0 to 1

like:

0
0.1
0.2
0.3
0.4
0.5

and so on

**Comment by nintendofan44** [comment]
@ShadowMario

**Comment by nintendofan44** [comment]
no problem lol

**Comment by CrusherMods** [comment]
Can I use this??? ill credit you in the build

**Comment by nintendofan44** [comment]
ye

**Comment by DEV-idiotXD** [comment]
Imma use this to ive needed this for so long im used to just focusing on notes not the bg somethime the bg can get distracting

**Comment by nintendofan44** [comment]
> Imma use this to ive needed this for so long im used to just focusing on notes not the bg somethime the bg can get distracting

true lol

**Comment by DEV-idiotXD** [comment]
how do i use this

**Comment by nintendofan44** [comment]
you go to the options and change the transparency there

**Comment by nintendofan44** [comment]
in the visual and ui section

**Comment by DEV-idiotXD** [comment]
> in the visual and ui section

no im meaning which files are edited cuz i wanna port this to a mod im making (ill credit you)

**Comment by nintendofan44** [comment]
ClientPrefs.hx
PlayState.hx
EditorPlaystate.hx
VisualUISubState.hx

**Comment by DEV-idiotXD** [comment]
> ClientPrefs.hx PlayState.hx EditorPlaystate.hx VisualUISubState.hx

thx can u send me a icon of u? ill put u in credits

**Comment by DEV-idiotXD** [comment]
nvm it just broke the build lol

**Comment by nintendofan44** [comment]
> nvm it just broke the build lol

i think you are using an old build

**Comment by nintendofan44** [comment]
bc it broke only for you

**Comment by Gui-iago** [comment]
I know this is already closed, but there's a bug with both dialogues and the chart editor

Chart Editor's Playtest looks like this no matter if MScroll is on or not
image

Dialogue Looks like this
image

the underlay on both instances are on the exact same position, is there any fix for that?

**Pull request closed without merging**
