### PR TITLE
Gameplay Modifier: Mirror Mode

### PR DESCRIPTION
**Pull request by BoloVEVO**
Flip chart notes horizontally as seen in many rythm games.

https://user-images.githubusercontent.com/88955176/168459633-f899972f-15b4-47ba-86bb-287e68c570ed.mp4

### CODE REVIEW

**Review by stilic — APPROVED** [review]

**Review by TheKitBoi — APPROVED** [review]

**Review by ManMaster707 — APPROVED** [review]
Cool!

**Review by JorosTheModderPH — APPROVED** [review]
Nice, can I use this code in my build?

**Comment by BoloVEVO** [comment]
> Nice, can I use this code in my build?

Yeah no problem.

**Comment by JorosTheModderPH** [comment]
> > Nice, can I use this code in my build?
> 
> Yeah no problem.

Thanks!

**Comment by Junicko** [comment]
Very cool! Can I use this in my mod?

**Review by BombasticTom — APPROVED** [review]
shadowmario should make a modifier substate at this point

**Review by megasssdev — APPROVED** [review]

**Comment by BeastlyGhost** [comment]
> shadowmario should make a modifier substate at this point

Gameplay Changers is quite literally that

**Pull request closed without merging**
