### PR TITLE
More finalizations (Flxanimate & new setup method)

### PR DESCRIPTION
**Pull request by NexIsDumb**
Both finalizes #13543 and #13257

Why am I deleting the installer once it finishes downloading? Speaks for itself lmfao; it's literally useless keep it there once the installation was completed

### CODE REVIEW

**Comment by NexIsDumb** [comment]
oh wait shadow has a fork, then hol up

**Comment by NexIsDumb** [comment]
there
also dw it fails just because in this pr theres not the #13543 fix
so ye this pr must be merged with that pr aswell

**Review by DetectiveBaldi — APPROVED** [review]
b

**Comment by crowplexus** [comment]
https://github.com/NexIsDumb/FNF-PsychEngine/pull/2

**Comment by NexIsDumb** [comment]
okay, so now its not needed to merge the other pr aswell but just use this

**Review by BlueColorsin — APPROVED** [review]

**Comment by NexIsDumb** [comment]
okay time to add in this pr some commits to make everything compatible with normal flxanimate
i'll start doing it in a bit

**Comment by NexIsDumb** [comment]
@Geokureli
do you actually want us to use original Flxanimate?
cause more than an override in the source its a fork
just for understanding, what do you say

**Comment by Geokureli** [comment]
Im not sure i dont use FlxAnimate, you might wanna ask cheems, instead

**Comment by NexIsDumb** [comment]
> Im not sure i dont use FlxAnimate, you might wanna ask cheems, instead

oh yeah fair enough

**Comment by Cheemsandfriends** [comment]
> do you actually want us to use original Flxanimate?

Idk what exactly is inside that FlxAnimate fork (something about `loadAtlasEx` I saw on the server), but like George said, it's heaps better to use a fork that everyone can maintain than modifying a single file that permanently sets it to a specific version till the overshadow's gone.

I'd say that if it's something that can benefit both psych engineers and the flixelers, then he can dm me anytime to tell me his suggestion, or put an issue on github and i'll add another feature for the already long list of features of 4.0.0, but I can see why it wouldnt work if the changes are made for the engine ¯\\\_(ツ)_/¯.

**Comment by NexIsDumb** [comment]
> Idk what exactly is inside that FlxAnimate fork (something about `loadAtlasEx` I saw on the server), but like George said, it's heaps better to use a fork that everyone can maintain than modifying a single file that permanently sets it to a specific version till the overshadow's gone.
> 
> I'd say that if it's something that can benefit both psych engineers and the flixelers, then he can dm me anytime to tell me his suggestion, or put an issue on github and i'll add another feature for the already long list of features of 4.0.0, but I can see why it wouldnt work if the changes are made for the engine ¯\_(ツ)_/¯.

yup I totally agree with you, thats why I asked 
also he wrote what he was trying to do in the fork description:

image

**Pull request merged**
