### PR TITLE
secure lua + module support

### PR DESCRIPTION
**Pull request by lunacynne**
improvement of pr #6716
credits: @superpowers04 @cyn-8 @DragShot

- removes only the abusable builtin functions
- reimplements `require` for use of modules while blocking requiring luajit extensions like `ffi`
  - searches in the folder of the running script, `mods/libs`, and `mods/modfolder/libs` if the script runs from a modfolder
  - because modfolders are dynamic, a script in `mods` cannot search in a modfolder, and a script in a modfolder cannot search in other modfolders

### CODE REVIEW

**Comment by DragShot** [comment]
> calling require will only work in global scope
Make sure the line `set('require', false);` has been removed from he constructor of `FunkinLua`. It is present atm and for this patch to work correctly it has to be removed.

**Comment by cyn-8** [comment]
> > calling require will only work in global scope
> 
> Make sure the line `set('require', false);` has been removed from he constructor of `FunkinLua`. It is present atm and for this patch to work correctly that line has to go.

okk ill do that now

**Comment by Stilic** [comment]
Please can you keep the IO module? _It is no removed actually and nobody have any problem with that I think._

**Comment by cyn-8** [comment]
> Please can you keep the IO module? _It is no removed actually and nobody have any problem with that I think._

i dont want to include `io` because it can easily write over existing files
and create/execute malicious ones
and do command line stuff
etc
image

**Comment by Stilic** [comment]
> > Please can you keep the IO module? _It is no removed actually and nobody have any problem with that I think._
> 
> i dont want to include `io` because it can easily write over existing files and create/execute malicious ones and do command line stuff etc image

At least see if you can recreate a safe alternative of it?

**Comment by nebulazorua** [comment]
might try my hand at breaking out of the sandbox later

**Comment by DragShot** [comment]
> At least, can you recreate a safe alternative of it?

We got a `getTextFromFile()` callback so far, so maybe a `putTextIntoFile()` one wouldn't do bad. As long as they keep the reach of file access inside the mod folders it should be OK, and they could be even easier to use than the `io` streams.

**Comment by Stilic** [comment]
Yeah I forget that! This is a good idea!

**Comment by BombasticTom** [comment]
legend

**Comment by DragShot** [comment]
@cyn-8 Uhh... is this supposed to be here in `FunkinLua.hx`?
```
80.  root = splice_path(1) [[ .. 'libs/?.lua;' ]]
81.  path_script = root .. 'libs/?.lua;' .. root .. 'libs/?/init.lua;'
```
Because I think not.

**Comment by cyn-8** [comment]
> @cyn-8 Uhh... is this supposed to be here in `FunkinLua.hx`?
> ```
> 80.  root = splice_path(1) [[ .. 'libs/?.lua;' ]]
> 81.  path_script = root .. 'libs/?.lua;' .. root .. 'libs/?/init.lua;'
> ```
> Because I think not.

im not sure, really; it was part of the original code
ill try removing it and see if anything happens

**Comment by cyn-8** [comment]
> > > Please can you keep the IO module? _It is no removed actually and nobody have any problem with that I think._
> > 
> > i dont want to include `io` because it can easily write over existing files and create/execute malicious ones and do command line stuff etc image
> 
> At least, can you recreate a safe alternative of it?

maybe in a separate pr i can make a haxe lua function thing for that

**Comment by DragShot** [comment]
> im not sure, really; it was part of the original code ill try removing it and see if anything happens

Hmm... it's probably a mistake on my end, because I do see it in my copy as well. I mean, `'libs/?.lua;'` is being appended in line 81 so there's no point in doing it in line 80, it would end up being pasted twice. Please remove that part.

**Comment by DragShot** [comment]
Uh... why?

imagen

That `match()` is needed to weed out the filename from the path. Without that, search inside **data/mysong** (or whenever the calling script is) will break, leaving only the lib folders.

**Comment by BombasticTom** [comment]
this looks funkin nuts

**Review by BombasticTom — APPROVED** [review]
These would be really useful if approved.

**Review by stilic — APPROVED** [review]

**Review by BombasticTom — APPROVED** [review]
good luck

**Comment by DragShot** [comment]
Nice!

**Review by Raltyro — APPROVED** [review]
awesome :D

**Comment by BombasticTom** [comment]
when is this gonna get approved, this pull request is just too powerful! it would be really useful to not copy-paste the same functions in different scripts

**Comment by BombasticTom** [comment]
plus the fact that you could add custom libs

**Comment by cyn-8** [comment]
no need for module support as the new commits basically implement the same functionality
making a new pr for secure lua on its own

**Pull request closed without merging**
