### PR TITLE
i made the source better

### PR DESCRIPTION
**Pull request by kitty-girl**

### CODE REVIEW

**Comment by WizardMantis441** [comment]
very cool

**Comment by swordcube** [comment]
very cool

**Comment by kittstone** [comment]
very cool

**Comment by kingyomoma** [comment]
????

**Comment by Leather128** [comment]
very cool

**Comment by RafaelGiacom** [comment]
> ???? there's no way this is getting merged

what do you mean it's so much better now

**Comment by TheWorldMachine** [comment]
You like men

**Comment by Leather128** [comment]
> ???? there's no way this is getting merged

what do you mean it's so much better now

**Comment by kittstone** [comment]
> ???? there's no way this is getting merged

what do you mean it's so much better now

**Comment by swordcube** [comment]
> ???? there's no way this is getting merged

what do you mean it's so much better now

**Comment by kingyomoma** [comment]
> ???? there's no way this is getting merged

what do you mean it's so much better now

**Comment by swordcube** [comment]
> > ???? there's no way this is getting merged
> 
> what do you mean it's so much better now

the code is very much alot cleaner

**Comment by Leather128** [comment]
> > ???? there's no way this is getting merged
> 
> what do you mean it's so much better now

the code is very much alot cleaner

**Comment by swordcube** [comment]
> > > ???? there's no way this is getting merged
> > 
> > 
> > what do you mean it's so much better now
> 
> the code is very much alot cleaner

and more alot optimized

**Comment by swordcube** [comment]
and also like very like cool like and like very like awesome like

**Review by Leather128 — APPROVED** [review]
seems very optimized

**Review by swordcube — APPROVED** [review]
this is very fast code and funkinlua will no longer be 3000+ lines long

**Review by WizardMantis441 — APPROVED** [review]
very cool

**Review by fluffabun15 — APPROVED** [review]
i Love this!

**Comment by Leather128** [comment]
> Totally not stolen yoshi engine stuff

ikr

**Comment by swordcube** [comment]
ikr

**Comment by kittstone** [comment]
> > Totally not stolen yoshi engine stuff
> 
> FUN FACT OF TA DAY......: The entire code is only yoshi engine!!!!!!

no its not...

**Comment by RafaelGiacom** [comment]
> > Totally not stolen yoshi engine stuff
> 
> FUN FACT OF TA DAY......: The entire code is only yoshi engine!!!!!!

no its not...

**Comment by Leather128** [comment]
> > Totally not stolen yoshi engine stuff
> 
> FUN FACT OF TA DAY......: The entire code is only yoshi engine!!!!!!

no its not...

**Comment by WizardMantis441** [comment]
it says psych engine...

**Comment by RafaelGiacom** [comment]
> > > > Totally not stolen yoshi engine stuff
> > > 
> > > 
> > > FUN FACT OF TA DAY......: The entire code is only yoshi engine!!!!!!
> > 
> > 
> > no its not...
> 
> Then why does project.xml say so?

nah man you seeing things

**Comment by Leather128** [comment]
> > > > Totally not stolen yoshi engine stuff
> > > 
> > > 
> > > FUN FACT OF TA DAY......: The entire code is only yoshi engine!!!!!!
> > 
> > 
> > no its not...
> 
> Then why does project.xml say so?

nah man you seeing things

**Comment by RafaelGiacom** [comment]
> > > > > > Totally not stolen yoshi engine stuff
> > > > > 
> > > > > 
> > > > > FUN FACT OF TA DAY......: The entire code is only yoshi engine!!!!!!
> > > > 
> > > > 
> > > > no its not...
> > > 
> > > 
> > > Then why does project.xml say so?
> > 
> > 
> > nah man you seeing things
> 
> bro seriously, why did you make a shitty pr

wdym i made the source so much better bro

**Comment by Leather128** [comment]
> > > > > > Totally not stolen yoshi engine stuff
> > > > > 
> > > > > 
> > > > > FUN FACT OF TA DAY......: The entire code is only yoshi engine!!!!!!
> > > > 
> > > > 
> > > > no its not...
> > > 
> > > 
> > > Then why does project.xml say so?
> > 
> > 
> > nah man you seeing things
> 
> bro seriously, why did you make a shitty pr

raf made the source so much better tho bro

**Comment by kittstone** [comment]
> wdym i made the source so much better bro

wdym i made the source so much better bro

**Comment by WizardMantis441** [comment]
my name is yoshi engine and i support this message :thumbs_up:

**Comment by WizardMantis441** [comment]
wow rude :(

**Comment by WizardMantis441** [comment]
HAHAHAHAHHAHAHballsHAHHAHAHA !!!!!

**Comment by Leather128** [comment]
> > wow rude :(
> 
> HAHHAHAHAHWHAKFJefhQEF I WILL TAKE THAT SHITTY CODE OVER, THAN CALL IT A DAY :trollface: /j

rehehehehehehehehehhehehehehehehehehehheyeheehehhehehehehehehehehehehehehehehehehehehehehe

**Comment by WizardMantis441** [comment]
my name is leather engine and i approve of this engine 👍

**Comment by Leather128** [comment]
> > > > wow rude :(
> > > 
> > > 
> > > HAHHAHAHAHWHAKFJefhQEF I WILL TAKE THAT SHITTY CODE OVER, THAN CALL IT A DAY :trollface: /j
> > 
> > 
> > rehehehehehehehehehhehehehehehehehehehheyeheehehhehehehehehehehehehehehehehehehehehehehehe
> 
> your engine leather, it soooooooo muchhhhhh bettttterrrrrr

incorrect response. termination required.

**Comment by WizardMantis441** [comment]
**BURN IN A FIRE!!!!!! KILL YOURSELF!!!! I HAVE OBTAINED THE PSYCH ENGINE MASCOTS IP.......**

**Comment by Leather128** [comment]
> **BURN IN A FIRE!!!!!! KILL YOURSELF!!!! I HAVE OBTAINED THE YOSHI ENGINE MASCOTS IP.......**

not when you say it like that

**Comment by WizardMantis441** [comment]
On My Way!

**Comment by Leather128** [comment]
> > > **BURN IN A FIRE!!!!!! KILL YOURSELF!!!! I HAVE OBTAINED THE YOSHI ENGINE MASCOTS IP.......**
> > 
> > 
> > not when you say it like that
> 
> 118.13.44.163, he is in deez nut's island.......

ok

**Comment by WizardMantis441** [comment]
hold on let me contact him
*ring ring* Hello? Mister BBPanzu? Yes can I talk to Shadow Mario? Thank you! *blushes cutely*

**Comment by RafaelGiacom** [comment]
he's actually reviewing the changes rn

**Comment by Leather128** [comment]
> hold on let me contact him _ring ring_ Hello? Mister BBPanzu? Yes can I talk to Shadow Mario? Thank you! _blushes cutely_

me irl

**Comment by WizardMantis441** [comment]
my name is shadow mario engine and i approve of this message :thumbs_up:

**Comment by Leather128** [comment]
> > > hold on let me contact him _ring ring_ Hello? Mister BBPanzu? Yes can I talk to Shadow Mario? Thank you! _blushes cutely_
> > 
> > 
> > me irl
> 
> leather, let me steal code from your engine, Mr einstein....

how about you get good instead and steal code from yoshi engine since it's better than my engine :sunglasses:

**Comment by WizardMantis441** [comment]
ratio

**Comment by Leather128** [comment]
> > > > > hold on let me contact him _ring ring_ Hello? Mister BBPanzu? Yes can I talk to Shadow Mario? Thank you! _blushes cutely_
> > > > 
> > > > 
> > > > me irl
> > > 
> > > 
> > > leather, let me steal code from your engine, Mr einstein....
> > 
> > 
> > how about you get good instead and steal code from yoshi engine since it's better than my engine sunglasses
> 
> _**kys**_

not when you say it

**Comment by WizardMantis441** [comment]
ratio

**Comment by RafaelGiacom** [comment]
ratio

**Comment by FoxelTheFennic** [comment]
wtf is going on 😭😭😭

**Comment by Leather128** [comment]
> wtf is going on sobsobsob

real life

**Comment by WizardMantis441** [comment]
> > > > > > > hold on let me contact him _ring ring_ Hello? Mister BBPanzu? Yes can I talk to Shadow Mario? Thank you! _blushes cutely_
> > > > > > 
> > > > > > 
> > > > > > me irl
> > > > > 
> > > > > 
> > > > > leather, let me steal code from your engine, Mr einstein....
> > > > 
> > > > 
> > > > how about you get good instead and steal code from yoshi engine since it's better than my engine sunglasses
> > > 
> > > 
> > > _**kys**_
> > 
> > 
> > not when you say it
> 
> _**burn in a fire**_ _**I will steal code no matter what ......**_

ratio

**Comment by Leather128** [comment]
> > > > > > > hold on let me contact him _ring ring_ Hello? Mister BBPanzu? Yes can I talk to Shadow Mario? Thank you! _blushes cutely_
> > > > > > 
> > > > > > 
> > > > > > me irl
> > > > > 
> > > > > 
> > > > > leather, let me steal code from your engine, Mr einstein....
> > > > 
> > > > 
> > > > how about you get good instead and steal code from yoshi engine since it's better than my engine sunglasses
> > > 
> > > 
> > > _**kys**_
> > 
> > 
> > not when you say it
> 
> _**burn in a fire**_ _**I will steal code no matter what ......**_

not when you say it like that i won't

**Comment by WizardMantis441** [comment]
no we made the source code better

**Comment by kittstone** [comment]
> > wtf is going on 😭😭😭
> 
> idk, somebody went fuckin high

you know who else went fuckin high?

**Comment by swordcube** [comment]
The FitnessGram™ Pacer Test is a multistage aerobic capacity test that progressively gets more difficult as it continues. The 20 meter pacer test will begin in 30 seconds. Line up at the start. The running speed starts slowly, but gets faster each minute after you hear this signal. [beep] A single lap should be completed each time you hear this sound. [ding] Remember to run in a straight line, and run as long as possible. The second time you fail to complete a lap before the sound, your test is over. The test will begin on the word start. On your mark, get ready, start.

**Comment by ShadowMario** [comment]
That's not even funny at this point.

**Pull request closed without merging**
