### PR TITLE
Delete Modding.md

### PR DESCRIPTION
**Pull request by DabbinDude316B**

### CODE REVIEW

**Review by MemeHoovy — APPROVED** [review]
outdated shit

**Comment by BeastlyGhost** [comment]
alright, so real talk, rather that straight up deleting it, why not make it useful? you could give brief explanations as to how *psych*'s mod system works or anything similar

**Comment by MemeHoovy** [comment]
> 

that is honestly a better idea

**Comment by BeastlyGhost** [comment]
could be something like this

```
# BRIEF OVERVIEW OF THE MODS SYSTEM!

Psych Engine aims to make Modding easier and modular for every newbie coder and user
it's core features introduce

* a Achievements System to engage on Replayability of the main weeks
* New Gameplay Features and Song Events that further enhance the main game's experience
* Quality of Life improvements, such as a full options menu, customizable note colors, and more!
* a Mods Menu, where mods can be enabled, disabled and sorted through
* In-game Editors to make modding much easier, including a revamped Chart Editor
* a Powerful and easy to learn Lua Scripting System
* a equally powerful, in-lua hscript implementation
```

**Comment by Parsellol** [comment]
> alright, so real talk, rather that straight up deleting it, why not make it useful? you could give brief explanations as to how _psych_'s mod system works or anything similar

agreed

**Pull request closed without merging**
