### PR TITLE
Add a prompt on credits menu to prevent malicious links, and make titlescreen transitioning faster.

### PR DESCRIPTION
**Pull request by stephencomputer**
### **Summary Of This Pull Request**
Add a prompt on the credits menu showing users the link they are about to visit and the option to opt out if the link looks suspicious. I have also tinkered with the timer in the titlestate to make the transition from titlestate to mainmenu/outdated extremely fast.

### **Why You Should Merge**
Pretty self explanatory, to prevent users with malicious intent on precompiled builds from using the credits menu for malicious purposes, like giving IP grabbers. Also makes titlescreen transitioning very fast.

### CODE REVIEW

**Comment by CrusherMods** [comment]
Now I cant Rick Roll :(

**Comment by DEV-idiotXD** [comment]
anti rickroll gg

**Comment by Stilic** [comment]
security moment

**Comment by DEV-idiotXD** [comment]
why didya close it?

**Comment by ImaginationSuperHero528** [comment]
> ### **Summary Of This Pull Request**
> Add a prompt on the credits menu showing users the link they are about to visit and the option to opt out if the link looks suspicious. I have also tinkered with the timer in the titlestate to make the transition from titlestate to mainmenu/outdated extremely fast.
> 
> ### **Why You Should Merge**
> Pretty self explanatory, to prevent users with malicious intent on precompiled builds from using the credits menu for malicious purposes, like giving IP grabbers. Also makes titlescreen transitioning very fast.

Why did you close it?

**Comment by Steviegt6** [comment]
This is inherently flawed, since anyone with a "precompiled build" could just remove this anyway.

**Comment by magnumsrtisswag** [comment]
> > ### **Summary Of This Pull Request**
> > Add a prompt on the credits menu showing users the link they are about to visit and the option to opt out if the link looks suspicious. I have also tinkered with the timer in the titlestate to make the transition from titlestate to mainmenu/outdated extremely fast.
> > ### **Why You Should Merge**
> > Pretty self explanatory, to prevent users with malicious intent on precompiled builds from using the credits menu for malicious purposes, like giving IP grabbers. Also makes titlescreen transitioning very fast.
> 
> Why did you close it?

LMFAO SORRY IT WAS AN ACCIDENT

**Comment by magnumsrtisswag** [comment]
hey guys ill reopen it after the next update

**Comment by MrClogsworthYT** [comment]
> ### **Summary Of This Pull Request**
> Add a prompt on the credits menu showing users the link they are about to visit and the option to opt out if the link looks suspicious. I have also tinkered with the timer in the titlestate to make the transition from titlestate to mainmenu/outdated extremely fast.
> 
> ### **Why You Should Merge**
> Pretty self explanatory, to prevent users with malicious intent on precompiled builds from using the credits menu for malicious purposes, like giving IP grabbers. Also makes titlescreen transitioning very fast.

would be cool if you make it a substate or have a a half transperent black background when it shows up for the next update

**Pull request closed without merging**
