### PR TITLE
Fully fix sustain clipping

### PR DESCRIPTION
**Pull request by NeeEoo**
This fully fixes the problem and is a better fix than #12168

### CODE REVIEW

**Review by moxie-coder — APPROVED** [review]

**Review by NexIsDumb — APPROVED** [review]

**Review by charlesisfeline — APPROVED** [review]

**Review by aaaproooo — APPROVED** [review]

**Comment by KoharuXenon** [comment]
im pretty sure removing the ciprect height/width changing and just moving it is faster than fixing the reference to the frame

**Comment by NeeEoo** [comment]
> im pretty sure removing the ciprect height/width changing and just moving it is faster than fixing the reference to the frame

Uhhh thats because i overwrote it, the original set_clipRect does it too, i just removed the .round() from the clipRect thingy

**Comment by KoharuXenon** [comment]
> 

what original set_clipRect

**Comment by NeeEoo** [comment]
> what original set_clipRect

```hx
function set_clipRect(rect:FlxRect):FlxRect
{
	if (rect != null)
		clipRect = rect.round();
	else
		clipRect = null;

	if (frames != null)
		frame = frames.frames[animation.frameIndex];

	return rect;
}
```

here https://github.com/HaxeFlixel/flixel/blob/dev/flixel/FlxSprite.hx#L1512-L1523

**Comment by KoharuXenon** [comment]
> > what original set_clipRect
> 
> ```hx
> function set_clipRect(rect:FlxRect):FlxRect
> {
> 	if (rect != null)
> 		clipRect = rect.round();
> 	else
> 		clipRect = null;
> 
> 	if (frames != null)
> 		frame = frames.frames[animation.frameIndex];
> 
> 	return rect;
> }
> ```
> 
> here https://github.com/HaxeFlixel/flixel/blob/dev/flixel/FlxSprite.hx#L1512-L1523

i stand corrected, but cliprect height do be movin doe, and my code do be making it look cool (bro didnt have to crush my hopes and dreams)

**Pull request merged**
