### PR TITLE
Note specific scroll speeds

### PR DESCRIPTION
**Pull request by KutikiPlayz**
Allows you to make specific note types use a different scroll speed than the chart.
Pretty cool shit I think.

### CODE REVIEW

**Comment by DEMOLITIONDON96** [comment]
I saw your discussion post earlier, and yeah, it’s good, but, I don’t think ShadowMario will actually merge this, sadly, so, if anything, it’s likely we’re just gonna have to use the code on a separate repo if we want to use it

**Comment by KutikiPlayz** [comment]
> I saw your discussion post earlier, and yeah, it’s good, but, I don’t think ShadowMario will actually merge this, sadly, so, if anything, it’s likely we’re just gonna have to use the code on a separate repo if we want to use it

probably not but at least people can see the code now so they can add it

**Comment by DEMOLITIONDON96** [comment]
Yeah, you got a point there

**Review by ghost — APPROVED** [review]
This is what the Dave and Bambi fans have always wanted.

**Review by lilynx2509 — APPROVED** [review]

**Comment by KutikiPlayz** [comment]
shit
fuck
totally didn't accidentally merge shit from my other shit into this

**Pull request closed without merging**
