### PR TITLE
Add Spores, Remove base game assets

### PR DESCRIPTION
**Pull request by blatantist**

### CODE REVIEW

**Comment by Zyflx** [comment]
Why are you making a pull request that removes all of the base game assets and adds in what im going to assume is your mod

Pull requests are not supposed to be used for adding mods.
Pull requests are supposed to be used to improve the engine not delete shit from it and add things that do not affect the engine in any way.

**Comment by CaptainBaldi** [comment]
> Why are you making a pull request that removes all of the base game assets and adds in what im going to assume is your mod
> 
> Pull requests are not supposed to be used for adding mods. Pull requests are supposed to be used to improve the engine not delete shit from it and add things that do not affect the engine in any way.

I believe this is probably an accidental PR

**Comment by Zyflx** [comment]
> > Why are you making a pull request that removes all of the base game assets and adds in what im going to assume is your mod
> > Pull requests are not supposed to be used for adding mods. Pull requests are supposed to be used to improve the engine not delete shit from it and add things that do not affect the engine in any way.
> 
> I believe this is probably an accidental PR
upon double checking i think this is an accidental pr my bad

**Comment by KookerFoxYT** [comment]
kid named "Close pull request"

**Comment by CaptainBaldi** [comment]
> > i dunno what you guys are talking about this should be merged right now!!!!!
> 
> ITS AN ACCIDENTAL PR ARE YOU JOKING

dude calm down they were also joking

**Comment by ThePlank** [comment]
best pr in psyhcaehw aehb gine ‼️ ‼️ ‼️ ‼️ 🇧🇩 🎍 bangabng a n jiaji hiofhwoi hiJOP #(Y(* YT$(*EH*(HIikl w ajditert naiwj ite
shoidl  eb alvistio be maricgied into baise gamine:bangbang:

**Comment by KookerFoxYT** [comment]
> best pr in psyhcaehw aehb gine ‼️ ‼️ ‼️ ‼️ 🇧🇩 🎍 bangabng a n jiaji hiofhwoi hiJOP #(Y(* YT$(_EH_(HIikl w ajditert naiwj ite shoidl eb alvistio be maricgied into baise gamine‼️

its an accidental pr

**Comment by KookerFoxYT** [comment]
yes ik you were joking

**Comment by NexIsDumb** [comment]
what the fuck is going on!!!1!
https://user-images.githubusercontent.com/87421482/229444482-f563cb2b-6f7d-431e-83ad-d94e0168d796.mp4

**Comment by MemeHovy** [comment]
> what the fuck is going on!!!1!

some guy being an idiot made a dumb pr

**Comment by NexIsDumb** [comment]
> > what the fuck is going on!!!1!
> 
> some guy being an idiot made a dumb pr 

I saw but
why the hek isnt this pr already closed LMFAO

**Comment by MemeHovy** [comment]
> > > what the fuck is going on!!!1!
> > 
> > 
> > some guy being an idiot made a dumb pr
> 
> I saw but why the hek isnt this pr already closed LMFAO

cuz they either didn't bother to close it or shadowmario hasn't noticed it yet

**Comment by Blatantist** [comment]
damn i really caused chaos here didnt I...

**Comment by megasssdev** [comment]
NO THIS IS SUCH A GOOD PR DONT CLOSE IT NOOOOOOOOOO

**Pull request closed without merging**
