### PR TITLE
New Menu BG.

### PR DESCRIPTION
**Pull request by Joalor64**
I simply just used the background for the charter from @gedehari's Izzy Engine and then used a recolor tool online for the different menu bgs.
(Still my first time making pull requests.)
(Also, ignore the other commit. That was for another pull request.)
(Also, sorry if menuDesat.png is a little too dark.)

### CODE REVIEW

**Comment by SrtHero278** [comment]
this might not get merged since Shadow wants to keep this Engine as vanilla as possible.

**Comment by Joalor64GH** [comment]
oh wait your right

**Comment by XperiorTR** [comment]
you can add this through the mods folder because assets from the mod folder override vanilla files

**Comment by Joalor64GH** [comment]
ohh okay

**Comment by Lokitot** [comment]
you should add this an option, like dark mode

**Comment by Joalor64GH** [comment]
why did i not think of that?

**Comment by Lokitot** [comment]
> why did i not think of that?

idk homie

**Pull request closed without merging**
