### PR TITLE
Add way to set lua text border styles

### PR DESCRIPTION
**Pull request by Unholywanderer**
idk i didnt test it lol
would be cool though

nvm i tested it now i think its fine

### CODE REVIEW

**Review by rodney528 — APPROVED** [review]

**Comment by Unholywanderer** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/assets/96925902/08f72b70-ed12-4582-8563-2101434eaff0


lets you set funny lua text border styles as well as use decimal border sizes without setProperty or something
image

**Comment by CobaltBar** [comment]
lol

lmao even

**Review by rodney528 — APPROVED** [review]
Rodney Approved 👍

**Review by melodiekit — APPROVED** [review]
true

**Pull request merged**
