### PR TITLE
egg

### PR DESCRIPTION
**Pull request by tailsicweneedtocook**
EB9A92E7-CA70-4BB6-8DCB-AD6BE95110F4

### CODE REVIEW

**Comment by DaRealDotZ** [comment]
I agree

**Review by MemeHoovy — CHANGES_REQUESTED** [review]
...no

**Comment by antoSKRLOL** [comment]
egg

**Comment by tailsicweneedtocook** [comment]
> ...no


https://user-images.githubusercontent.com/116702642/198414879-657c5d53-487d-47c6-ba1b-ab4aa690f93b.mp4

**Comment by Raltyro** [comment]
lolwhy

**Comment by TheKitBoi** [comment]
> ...no

what are you doing with ur life

**Comment by MemeHoovy** [comment]
> > ...no
> 
>  First.of.all.Your.Jordan.s.are.Fake-.onlinevideoconverter.com.mp4

35969c0ea5e9b6edd19596c4617130a7 (2)

**Comment by tailsicweneedtocook** [comment]
> > > ...no
> > 
> > 
> > First.of.all.Your.Jordan.s.are.Fake-.onlinevideoconverter.com.mp4
> 
> 35969c0ea5e9b6edd19596c4617130a7 (2)

E21AC348-B867-4E62-8F3C-5C84F18482BC

**Comment by TheKitBoi** [comment]
> just close this bruh

He ain’t gonna do it 
so we have to wait for shadow Mario to do the move

**Comment by tailsicweneedtocook** [comment]
> > just close this bruh
> 
> He ain’t gonna do it so we have to wait for shadowmario to do the move

We do a little

**Pull request closed without merging**
