### PR TITLE
android :)

### PR DESCRIPTION
**Pull request by ghost**
:)

### CODE REVIEW

**Comment by TheKitBoi** [comment]
Why do you keep on sending bullshit

**Comment by Rudyrue** [comment]
no fuck off

**Comment by Gavman69** [comment]
your mother hung herself

**Comment by TehPuertoRicanSpartan** [comment]
do this at your own repo

**Comment by ShadowMilky** [comment]
why the heck does a random ass person want the engine to be android-only
like why

**Pull request closed without merging**
