### PR TITLE
Hold Note Scroll Direction Bug: FIXED!!

### PR DESCRIPTION
**Pull request by jayrattt**
_yes, this probably contains commits from #7219, my other pull request
however, i undid them in this one, so pretend they aren't there_

i noticed that hold notes look weird when their scroll direction is changed, so i tried to fix that

https://user-images.githubusercontent.com/75950907/168700859-7be8a6f9-35af-4137-9f74-1f1a638bc042.mp4

(ignore wide bf in the example video)

i _may_ update this pr later to fix some other shit but idk

### CODE REVIEW

**Comment by BeastlyGhost** [comment]
you should probably just create a new branch for that, it's really confusing to have two PRs in one when the main purpose of this one is to fix Holds Direction

**Review by stilic — APPROVED** [review]

**Comment by DEMOLITIONDON96** [comment]
been looking for something like this, thx!

**Review by ThatOneSillyGuyDon — APPROVED** [review]

**Review by Raltyro — APPROVED** [review]

**Review by BombasticTom — APPROVED** [review]

**Review by lunacynne — APPROVED** [review]

**Review by ghost — APPROVED** [review]
At least it definitely looks better!

**Review by JorosTheModderPH — APPROVED** [review]

**Comment by ImaginationSuperHero528** [comment]
Finally someone fixing it via the source code!

**Review by rodney528 — APPROVED** [review]
Idk what's with `.gitignore` but I approve!

**Review by rodney528 — APPROVED** [review]

**Comment by ImaginationSuperHero528** [comment]
@8bitjake does it look better then the example video or is it the same?

**Comment by ImaginationSuperHero528** [comment]
Just wondering

**Comment by 8bitjake** [comment]
@ImaginationSuperHero528 looks the same, planning on fixing an upscroll bug since im dumb and only tested on downscroll :skull:

**Comment by 8bitjake** [comment]
@ImaginationSuperHero528 looks the same, planning on fixing an upscroll bug since im dumb and only tested on downscroll :skull:

**Comment by ImaginationSuperHero528** [comment]
Ya know making it a wip is a thing right?

**Pull request closed without merging**
