### PR TITLE
softcoded noteskins and splashes

### PR DESCRIPTION
**Pull request by DM-kun**
Like the title says, this pr plans to make it possible for noteskins and splashes to be added in the options (which is probably also planned)

will def take some time as i'm not too experienced in coding

### CODE REVIEW

**Comment by DMMaster636** [comment]
After testing some more and trying to somehow optimize it, i myself couldn't find a solution
SM, if you merge this, then please check the code and try to optimize it!!! I tried my best

**Comment by BeastlyGabi** [comment]
looks neat, although I'd keep the default options ("Default" for Noteskins, "Psych" for Note Splashes) hardcoded since you weren't really supposed to be able to remove them

**Comment by DMMaster636** [comment]
> looks neat, although I'd keep the default options ("Default" for Noteskins, "Psych" for Note Splashes) hardcoded since you weren't really supposed to be able to remove them

Yeah, I'll prolly do that, but I'm currently driving to the airport, cus I'm going on vacation with my family
I'll do it on my phone once we're there

**Comment by DMMaster636** [comment]
Well, custom splashes and noteskins are real now, so I'll close this

**Pull request closed without merging**
