### PR TITLE
Create 1

### PR DESCRIPTION
**Pull request by Ladhisshdk**

### CODE REVIEW

**Comment by MemeHovy** [comment]
no

**Comment by NexIsDumb** [comment]
https://user-images.githubusercontent.com/87421482/230681226-f00a522f-4b95-462c-948d-03f36dc9693e.MOV

**Review by libauror-a — APPROVED** [review]
Great addition!

**Comment by NexIsDumb** [comment]
> Great addition!

image

**Comment by MemeHovy** [comment]
@Ladhisshdk 
mario-gun-nose (1)

**Comment by ThePlank** [comment]
holy shit i just checked this guys repo (there are more commits but sharex stupid
image

**Comment by NexIsDumb** [comment]
> holy shit i just checked this guys repo (there are more commits but sharex stupid
> 
> image
> 
> 

Bro💀

**Comment by DaRealDotZ** [comment]
This is such a Create 1 moment

**Pull request closed without merging**
