### PR TITLE
In Game Mod Downloader/Installer Via Gamebanana Mod ID

### PR DESCRIPTION
**Pull request by stephencomputer**
***THE INSTALLER WILL DOWNLOAD THE TOP AVAILABLE DOWNLOAD ON THE MOD PAGE (First Array Entry), I **_STRONGLY RECOMMEND_** LETTING PEOPLE KNOW THIS IF YOU DECIDE TO MERGE***
It's what the title says! It can download mods from gamebanana.com via their mod id. It is kind of limited, having only support for .zip files. It can filter through files and will stop you from downloading mods that aren't psych engine compatible (e.g not having the pack.json file in the folder). This does require a stable internet connection. And only works on windows, in which I have implemented conditional complication blocks. Thanks for your consideration. (_No gamejolt support for obvious reasons_)

### CODE REVIEW

**Comment by XS09-dev** [comment]
Hey. Can I use this and the stage editor in a psych fork? I will credit you.

**Review by Raltyro — APPROVED** [review]
yo wtf this is awesome

**Review by Apearson75 — APPROVED** [review]

**Comment by Phoneguytech75** [comment]
I was planning on making a program to do this. But adding the functionality into the engine is very cool.
I'm gonna use this in my source code.
I'll credit you.

**Review by CrusherNotDrip — APPROVED** [review]
very cool and useful!

**Review by MikeGames573 — APPROVED** [review]

**Review by TheKitBoi — APPROVED** [review]

**Review by MasterDirector99 — APPROVED** [review]

**Review by stilic — APPROVED** [review]

**Review by DeadSyntaxdev — APPROVED** [review]

**Comment by supajimmy** [comment]
Yooo this is so cool :DDD

**Review by HeliProGamer — APPROVED** [review]

**Comment by TheLeerName** [comment]
you can add support of other pack formats via 7z.exe cmd commands
ans it cool i give this idea for my in-game downloader <3

**Comment by Steviegt6** [comment]
> you can add support of other pack formats via 7z.exe cmd commands and it cool i give this idea for my in-game downloader <3

Man wants to use a 7z executable in a cross-OS game. 💀

**Comment by TheLeerName** [comment]
> Man wants to use a 7z executable in a cross-OS game. 💀

7-zip supports mac and linux

**Comment by magnumsrtisswag** [comment]
> > Man wants to use a 7z executable in a cross-OS game. 💀
> 
> 7-zip supports mac and linux (console version, which need)

But the user would have to download it themselves, which means I'm not adding it.

**Comment by TheLeerName** [comment]
> But the user would have to download it themselves, which means I'm not adding it.

just add in psych engine repo 7z and download it from here via url request :)
7z is only about 500 kb

**Comment by Phoneguytech75** [comment]
> > > Man wants to use a 7z executable in a cross-OS game. 💀
> > 
> > 7-zip supports mac and linux (console version, which need)
> 
> But the user would have to download it themselves, which means I'm not adding it.

If you did want to commit to this you could use the lzma sdk that is on the 7zip website and make a haxelib package. But that seems too much.

**Review by JuniorNovoa1 — APPROVED** [review]
very poggers

**Comment by Stilic** [comment]
@magnumsrtisswag why you closed this pr?

**Comment by Raltyro** [comment]
why was this closed?

**Pull request closed without merging**
