### PR TITLE
fix build errors on haxe 4.3.0 +

### PR DESCRIPTION
**Pull request by Vortex2Oblivion**

### CODE REVIEW

**Comment by BeastlyGhost** [comment]
ironically it failed here, HOWEVER its not your fault in the slightest, apparently `Std` (a Standard haxe library) is just broken

**Comment by Vortex2Oblivion** [comment]
> ironically it failed here, HOWEVER its not your fault in the slightest, apparently `Std` (a Standard haxe library) is just broken

ye ik 
wonder why it just dies in the actions builds tho

**Comment by BeastlyGhost** [comment]
> ye ik wonder why it just dies in the actions builds tho

I assume the signature for actions expired to some extent since it says that it failed to check signature in the error

**Comment by Vortex2Oblivion** [comment]
Closing because of #13243

**Pull request closed without merging**
