### PR TITLE
Add support for FeralInteractive Gamemode on Linux

### PR DESCRIPTION
**Pull request by nubz4lif**
first pull request woooooooooo
adds support for [FeralInteractive/gamemode](https://github.com/FeralInteractive/gamemode) on linux

there might be a more organized place to put gamemode_client.h but for now this works

### CODE REVIEW

**Review by ghost — APPROVED** [review]
sick

**Review by charlesisfeline — APPROVED** [review]
I don't really use Linux but yea cool

I'm not sure if it improves performance at any level, but I checked out the original game mode and yep maybe it does at some level

**Review by moxie-coder — APPROVED** [review]

**Comment by CrowPlexus** [comment]
I'd say create a folder called "linux" and put the externs there

**Comment by Noobz4Life** [comment]
apparently it doesn't compile if you don't have gamemode installed (despite me testing for that exact scenario before making the pull request?????????)

looking into it now

**Review by NexIsDumb — APPROVED** [review]
you cooked

**Pull request merged**
