### PR TITLE
Rework CreditsState/HealthIcon + Add missing contributors

### PR DESCRIPTION
**Pull request by Raltyro**
Draft...

### CODE REVIEW

**Review by MemeHoovy — APPROVED** [review]

**Review by lunacynne — APPROVED** [review]

**Review by DM-kun — APPROVED** [review]

**Review by TheKitBoi — APPROVED** [review]

**Review by Luisinhi010 — APPROVED** [review]

**Review by aaaproooo — APPROVED** [review]

**Comment by Luisinhi010** [comment]
very chad.

**Review by JorosTheModderPH — APPROVED** [review]

**Review by UncertainProd — APPROVED** [review]

**Comment by UncertainProd** [comment]
Ayy thanks!

**Comment by Raltyro** [comment]
forgot to put this here, im converting this to draft to make a few changes to pr such as automatically defaults unloaded icons to unknown icon and make icons be able to pixelated, and stuffs

**Comment by DMMaster636** [comment]
> forgot to put this here, im converting this to draft to make a few changes to pr such as automatically defaults unloaded icons to unknown icon and make icons be able to pixelated, and stuffs

based
this would close my issue #10959

**Review by Gostar64 — APPROVED** [review]

**Review by ACrazyTown — APPROVED** [review]
Just noticed this, thank you :)

**Comment by Raltyro** [comment]
I will be remaking ACrazyTown, and Gabrelia Icons, and make UncertainProd icon next week.
this week have been a tiring week for me, be hesistant!

**Comment by Luisinhi010** [comment]
there's a problem in CreditsState.hx btw :kek:

**Pull request closed without merging**
