### PR TITLE
DVD Logo feature.

### PR DESCRIPTION
**Pull request by Joalor64**
Basically, this just adds a bouncing DVD logo thing.
I know very well this is useless, but I also think it would be nice if this was added.

https://user-images.githubusercontent.com/99079926/179623108-204db28a-a22c-4c2e-91c0-f4f3be9a08c1.mp4

### CODE REVIEW

**Comment by Unholywanderer** [comment]
wha

**Comment by Itz-Miles** [comment]
Maybe replace that with a color-tweening Funkin' logo, and add it to the bottom of the menu if easter eggs are enabled.

**Comment by Joalor64GH** [comment]
Sure, I'll work on that.

**Comment by Paracosm-Daemon** [comment]
i don't see the point of this... this probably belongs in your own mod's repo instead of psych engine's sc

**Comment by MilkyTheMilkBlob** [comment]
i think it could be along with the gf easter eggs

**Comment by EyeDaleHim** [comment]
This is literally something probably only YOU will use. Will not be accepted.

**Comment by Parsellol** [comment]
awesome but this probably wont get merged lol

**Comment by magnumsrt** [comment]
FZkAArHXkAAbwip
@Joalor64GH yo you got a shoutout

**Comment by Joalor64GH** [comment]
omg cool

**Pull request closed without merging**
