### PR TITLE
Non-stretched pixel icons

### PR DESCRIPTION
**Pull request by doggogit**
Reopening of #14060

Pixel icons aren't stretched anymore, courtesy of @MaybeMaru

### CODE REVIEW

**Comment by Circuitella** [comment]
Wait they were stretched? damm this is crazy

**Comment by doggogit** [comment]
> Wait they were stretched? damm this is crazy

Yeah, I never knew about it either, up until a few months ago

**Comment by MaybeMaru** [comment]
We've been living a lie

**Comment by Stefan2008Git** [comment]
Is that a same pull required who did the different guy?

**Comment by doggogit** [comment]
> Is that a same pull required who did the different guy?

I don't get what you're saying, I just re-opened my own PR.

**Comment by Stefan2008Git** [comment]
> > Is that a same pull required who did the different guy?
> 
> I don't get what you're saying, I just re-opened my own PR.

Nevermind. I already saw and it was you :(

**Comment by doggogit** [comment]
> Nevermind. I already saw and it was you :(

It's okay 👍

**Pull request closed without merging**
