### PR TITLE
Goan and text box in awards menu state

### PR DESCRIPTION
**Pull request by jmxamongusmodder**
Hola the title says it all. goan is a game over character. and the box behind text is optinal. soon ill fix the text color but yeah!!
anoldversionxD

### CODE REVIEW

**Comment by tposejank** [comment]
What is this

**Comment by SrtHero278** [comment]
DO NOT MERGE THIS.
There is already a way to edit the gameover characters.
Not to mention, you are making ENTIRE SCRIPTS TO EXPLAIN THESE COMMANDS WHICH IS SOMETHING NONE OF THE OTHER ONES HAVE.
Just use this.
```
function onCreate()
	setPropertyFromClass('GameOverSubstate', 'characterName', 'bf'); --Character json file for the death animation
	setPropertyFromClass('GameOverSubstate', 'deathSoundName', 'fnf_loss_sfx'); --put in mods/sounds/
	setPropertyFromClass('GameOverSubstate', 'loopSoundName', 'gameOver'); --put in mods/music/
	setPropertyFromClass('GameOverSubstate', 'endSoundName', 'gameOverEnd'); --put in mods/music/
end
```

**Comment by Stilic** [comment]
NO
@ShadowMario pls close this

**Comment by jmxamongusmodder** [comment]
uhhh bruh i didnt know im stupid but the text box in awards is cool right?

**Comment by jmxamongusmodder** [comment]
also ima just close this its dumb and useless and im such an idiot im stupid i dont deserve to live. I AM AN IDIOT OK

**Comment by jmxamongusmodder** [comment]
im stupid

**Comment by jmxamongusmodder** [comment]
im stupid

**Comment by jmxamongusmodder** [comment]
> DO NOT MERGE THIS. There is already a way to edit the gameover characters. Not to mention, you are making ENTIRE SCRIPTS TO EXPLAIN THESE COMMANDS WHICH IS SOMETHING NONE OF THE OTHER ONES HAVE. Just use this.
> 
> ```
> function onCreate()
> 	setPropertyFromClass('GameOverSubstate', 'characterName', 'bf'); --Character json file for the death animation
> 	setPropertyFromClass('GameOverSubstate', 'deathSoundName', 'fnf_loss_sfx'); --put in mods/sounds/
> 	setPropertyFromClass('GameOverSubstate', 'loopSoundName', 'gameOver'); --put in mods/music/
> 	setPropertyFromClass('GameOverSubstate', 'endSoundName', 'gameOverEnd'); --put in mods/music/
> end
> ```

im stupid i didnt know please no hate me

**Comment by fireredfan7** [comment]
> me

How old are you?

**Pull request closed without merging**
