### PR TITLE
PlayState camPos optimization

### PR DESCRIPTION
**Pull request by Sword352**
Just a little pr that gets a recycled point for camPos and recycles camPos after being used.

### CODE REVIEW

**Review by moxie-coder — APPROVED** [review]
banger man

**Comment by Sword352** [comment]
ikr, however i thought that camFollow was an FlxPoint iirc? Dunno why it's back to FlxObject

**Comment by MemeHovy** [comment]
> ikr, however i thought that camFollow was an FlxPoint iirc? Dunno why it's back to FlxObject

pretty sure it was always a flxobject I think?

**Comment by Sword352** [comment]
> > ikr, however i thought that camFollow was an FlxPoint iirc? Dunno why it's back to FlxObject
> 
> pretty sure it was always a flxobject I think?

perhaps, i have an older version of 0.7 that i use for a mod with camFollow as an FlxPoint, but i dont think i modified it msyelf as an FlxPoint

**Comment by MemeHovy** [comment]
> > > ikr, however i thought that camFollow was an FlxPoint iirc? Dunno why it's back to FlxObject
> > 
> > 
> > pretty sure it was always a flxobject I think?
> 
> perhaps, i have an older version of 0.7 that i use for a mod with camFollow as an FlxPoint, but i dont think i modified it msyelf as an FlxPoint

I just looked at the vanilla source code, and it’s a flxobject

**Comment by MemeHovy** [comment]
4D9506EC-91EA-446C-BAB3-EF16DAFED8AC

**Comment by Sword352** [comment]
alr thx for clarification

**Comment by MemeHovy** [comment]
> alr thx for clarification

np bud

**Review by DetectiveBaldi — APPROVED** [review]
noice

**Review by charlesisfeline — APPROVED** [review]

**Review by NexIsDumb — APPROVED** [review]

**Comment by Sword352** [comment]
Closing this in favor of a new pr

**Pull request closed without merging**
