### PR TITLE
Custom UIs per Stage

### PR DESCRIPTION
**Pull request by crowplexus**
## Overview
This allows you to give each stage JSON a different UI style, no longer limiting developers to just normal and pixel, you can now make your own custom UI styles by changing a single string on your stage file

## How to
go into your Mods directory and create a new folder, the folder needs to be named after your stage UI parameter, with the "UI" suffix

example: my stage file has the `stageUI` parameter as "ourple"
now, I can just create a folder named "ourpleUI" and drop my custom assets there

**[THIS INFORMATION BELOW DOES NOT APPLY TO UIS NAMED AS "PIXEL", AS I KEPT THEM AS THEY WERE BEFORE FOR COMPATIBILITY REASONS!!!]**

the assets themselves must be named as they are on the "shared" folder, for example, the "sick" rating is named "sick.png", the "ready" sprite is named "ready.png", thus your custom assets should follow this name scheme

### CODE REVIEW

**Comment by BeastlyGhost** [comment]
this is currently very untested i will take the time to do so later

**Review by moxie-coder — APPROVED** [review]
interesting, and unique

**Comment by BeastlyGhost** [comment]
hopefully fixed pixel "go" on the countdown
why is it named "date-pixel" dude I'm gonna PISS MYSELF

**Comment by Stefan2008Git** [comment]
> ## Overview
> 
> This allows you to give each stage JSON a different UI style, no longer limiting developers to just normal and pixel, you can now make your own custom UI styles by changing a single string on your stage file
> ## How to
> 
> go into your Mods directory and create a new folder, the folder needs to be named after your stage UI parameter, with the "UI" suffix
> 
> example: my stage file has the `stageUI` parameter as "ourple" now, I can just create a folder named "ourpleUI" and drop my custom assets there
> 
> **[THIS INFORMATION BELOW DOES NOT APPLY TO UIS NAMED AS "PIXEL", AS I KEPT THEM AS THEY WERE BEFORE FOR COMPATIBILITY REASONS!!!]**
> 
> the assets themselves must be named as they are on the "shared" folder, for example, the "sick" rating is named "sick.png", the "ready" sprite is named "ready.png", thus your custom assets should follow this name scheme

O. Awesome. Now i can use easily

**Review by ACoolioDude — APPROVED** [review]

**Comment by Stefan2008Git** [comment]
> interesting, and unique

OFC, yeah

**Pull request merged**
