### PR TITLE
Updated Stage Editor (NOT A REPOST, READ THE DESCRIPTION)

### PR DESCRIPTION
**Pull request by stephencomputer**
THIS IS NOT A REPOST, I LOST ACCESS TO MY OLD REPO AND HAD TO MAKE A NEW ONE!!!

I made a ton of improvements to the stage editor, including, but not limited to: Visually adjust gf, bf, and opponent's positions, draggable layers via mouse click and hold, working load stage button (can only load .json files, but you could still export the loaded data to a lua, so it is not a big deal) , flipX and flipY options for both json layers AND lua, placeholders when there is no already made layers, and, you can now cycle through the current selected layer via a numeric stepper.

This is easily one of the most customizable editors in the engine.

You are free to use this in your **forks only**.

Here is a showcase of what it is capable of:

https://user-images.githubusercontent.com/90519370/156928008-08898855-a79b-49c6-8eff-b8183e7f2de0.mp4

### CODE REVIEW

**Comment by lemz1** [comment]
shish kebab

**Comment by beeanie** [comment]
bro if you have obs in your share screen go to your obs. Then go to your settings. after you go to your settings then go to recording and set your video file to mkv thats why its laggy. @magnumsrtisswag

**Comment by HiroMizuki** [comment]
epic

**Review by HiroMizuki — APPROVED** [review]

**Comment by magnumsrtisswag** [comment]
@ShadowMario ready for merge, highly recommend doin' this before 0.5.2, i have made it compatible with the latest stage .json updates.

**Comment by 3ukn** [comment]
swag

**Comment by frantastic24** [comment]
> highly recommend doin' this before 0.5.2

F

**Comment by XS09-dev** [comment]
> @ShadowMario ready for merge, highly recommend doin' this before 0.5.2, i have made it compatible with the latest stage .json updates.

Nope I tested it, it needs to be fixed.

**Comment by magnumsrtisswag** [comment]
> > @ShadowMario ready for merge, highly recommend doin' this before 0.5.2, i have made it compatible with the latest stage .json updates.
> 
> Nope I tested it, it needs to be fixed.

can you tell me WHAT needs to be fixed?

**Comment by magnumsrtisswag** [comment]
something might be wrong

**Comment by XS09-dev** [comment]
> > > @ShadowMario ready for merge, highly recommend doin' this before 0.5.2, i have made it compatible with the latest stage .json updates.
> > 
> > 
> > Nope I tested it, it needs to be fixed.
> 
> can you tell me WHAT needs to be fixed?

Whenever I try to load a stage in it doesn't load in

**Comment by XS09-dev** [comment]
> something might be wrong

@magnumsrtisswag  I fixed it. Turns out something was wrong with the one I download idk why that happened it works now.

**Comment by XS09-dev** [comment]
@magnumsrtisswag  I fixed the problem it turns out my pc had a problem with opening the file. Fixed it now tho

**Comment by magnumsrtisswag** [comment]
> @magnumsrtisswag I fixed the problem it turns out my pc had a problem with opening the file. Fixed it now tho

alright

**Comment by XS09-dev** [comment]
> > @magnumsrtisswag I fixed the problem it turns out my pc had a problem with opening the file. Fixed it now tho
> 
> alright

Antivirus false positive am I right?

**Review by DeadSyntaxdev — CHANGES_REQUESTED** [review]
Please add this. It works really good.

**Review by HeliProGamer — APPROVED** [review]
This can take time but it will surelly be merged!

**Comment by DaBanana64** [comment]
I think this is pretty good but in my opinion it's really not ready to be merged. This might be a pretty useful editor but it has it's own flaws.

For starters, the descriptions just makes it impossible to press the buttons on the toolbox and I have to zoom in the stage in order to do my stuff on the toolbox. I'm thinking moving them down would make it much, MUCH, easier to press the buttons on the toolbox.

Another issue I have encountered is, whenever I select **Save Lua** it saves as a .json instead of .lua....? Not sure if it's supposed to be saved as .json or .lua but it seems weird to me.

These are the issues I had with the editor when I was testing it. Again this is **NOT** meant to trash your work. I think this editor is near as perfect, but I think it needs the criticism it deserves. So I hope you take these criticisms and make it better!

**Comment by magnumsrtisswag** [comment]
> I think this is pretty good but in my opinion it's really not ready to be merged. This might be a pretty useful editor but it has it's own flaws.
> 
> For starters, the descriptions just makes it impossible to press the buttons on the toolbox and I have to zoom in the stage in order to do my stuff on the toolbox. I'm thinking moving them down would make it much, MUCH, easier to press the buttons on the toolbox.
> 
> Another issue I have encountered is, whenever I select **Save Lua** it saves as a .json instead of .lua....? Not sure if it's supposed to be saved as .json or .lua but it seems weird to me.
> 
> These are the issues I had with the editor when I was testing it. Again this is **NOT** meant to trash your work. I think this editor is near as perfect, but I think it needs the criticism it deserves. So I hope you take these criticisms and make it better!

No, I understand. The reason the lua saves as a json is because you are clicking the orange lua button, which saves the lua config needed for the game to load the .lua file and translate that into a stage. I would save them both with one button but that saves them both as the same type. I will get to lowering the description text right now tho. Thanks

**Review by megasssdev — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by Fridox-lol** [comment]
add animated sprites pls

**Comment by multicuentadereespaldo** [comment]
I like!!! I'm going to use it in my version of psych engine!!!!!! (OBVIOUSLY WITH CREDITS OMG YOU ARE THE BEST)

I leave you my channel, so you can be aware of whether I upload it or not!!!!!
https://www.youtube.com/channel/UCZ3mS-8La6tM6XzQTKqxLcw

**Comment by CasualCypress** [comment]
is there a way to download these files with manualy changing them lol

**Comment by AverageDaveLover65** [comment]
hi @magnumsrt, can you dm me via discord and give the stage editor in dms? would be appreciated.
AverageDaveLover#7718

**Comment by Gurudevsing** [comment]
i don't have stage editor in psych engine help me out

**Pull request closed without merging**
