### PR TITLE
Chart save pop-up now automatically goes to song data directory

### PR DESCRIPTION
**Pull request by Snirozu**

### CODE REVIEW

**Review by MemeHoovy — APPROVED** [review]

**Comment by MemeHoovy** [comment]
amazing

**Review by DetectiveBaldi — APPROVED** [review]
shadow mario i beg you PLEASE merge this

**Comment by Raltyro** [comment]
can yoy make this toggleable please?

**Review by TheKitBoi — APPROVED** [review]

**Review by DisIsNOt — APPROVED** [review]
Holy moly

**Review by JorosTheModderPH — APPROVED** [review]

**Review by Gostar64 — APPROVED** [review]

**Review by Intancote — APPROVED** [review]

**Pull request closed without merging**
