### PR TITLE
makeGraphic on attachedsprite

### PR DESCRIPTION
**Pull request by nahiassis**
this allows you to make an **_'attached'_** sprite without it having to be an image

### CODE REVIEW

**Comment by nintendofan44** [comment]
ay @ShadowMario

**Comment by ImaginationSuperHero528** [comment]
What do you mean?

**Comment by nintendofan44** [comment]
this makes you able to make a square for example without using an image file

**Comment by nintendofan44** [comment]
i tried to do that without this and it gave me an error
so basically i copied and pasted this function here from the flxsprite code

**Comment by trayfellow** [comment]
> this makes you able to make a square for example without using an image file

image

wdym you can do that already unless im missing something else here

**Comment by frantastic24** [comment]
This isn't for Lua

**Review by HiroMizuki — APPROVED** [review]
useful

**Comment by ShadowMario** [comment]
You can already do that though???
Screenshot_2
Screenshot_3

**Comment by nintendofan44** [comment]
i think that was a bug for me
haxe is weird sometimes

**Pull request closed without merging**
