### PR TITLE
Player Offsets for Json Character

### PR DESCRIPTION
**Pull request by CasualCypress**
!!! THIS IS NOT MY CODE, ALL CREDIT GO TO BLANTADOS !!!

### CODE REVIEW

**Review by CasualCypress — COMMENTED** [review]
m

**Comment by Stilic** [comment]
no

**Review by rodney528 — COMMENTED** [review]
Cool and really needed! But idk if @ShadowMario will allow it plus are you that's all the changes you'll need?

**Comment by Stilic** [comment]
> Cool and really needed! But idk if @ShadowMario will allow it plus are you that's all the changes you'll need?

he will not merge this because he wants to keep the engine as "vanilla" as possible.
keep this to your forks bruh

**Comment by xChillax** [comment]
Shouldn't this be a bool for characters instead? that way it can be toggled instead of being forced to all mods (and possibly breaking some). Hence not forcing this "non-vanilla" look on everything.

**Comment by Lokitot** [comment]
source/editors/CharacterEditorState.hx:673: lines 673-680 : Object requires field playerOffsets
source/editors/CharacterEditorState.hx:673: lines 673-680 : ... For optional function argument 'OnClick'

**Comment by RodneyAnImaginativePerson** [comment]
> > Cool and really needed! But idk if @ShadowMario will allow it plus are you that's all the changes you'll need?
> 
> he will not merge this because he wants to keep the engine as "vanilla" as possible.
> keep this to your forks bruh

0.7 is calling

**Pull request closed without merging**
