### PR TITLE
rewrite title state

### PR DESCRIPTION
**Pull request by Rudyrue**
rewrites the title state to load faster and be easier to read in half the lines
also touches up Main.hx a bit

idk if the stuff i removed in Main will cause issues but it seems to run fine on other projects and it seems to run fine here so

also yea the psych secret characters are removed
mainly because openfl was being an ass and did NOT wanna use the files so i just commented out the code entirely until i can find a solution for later

### CODE REVIEW

**Review by richTrash21 — APPROVED** [review]

**Review by BlueColorsin — APPROVED** [review]

**Review by system32unknown — APPROVED** [review]

**Review by Vortex2Oblivion — APPROVED** [review]

**Review by BlueColorsin — APPROVED** [review]

**Review by charlesisfeline — APPROVED** [review]

**Review by charlesisfeline — APPROVED** [review]

**Comment by Rudyrue** [comment]
ok i give up lmfao
after spending like an hour trying to add secret characters this shit just does not wanna work with openfl nor lime

**Comment by KarimAkra** [comment]
there is no "secrets" library?

**Comment by Rudyrue** [comment]
> after spending like an hour trying to add secret characters this shit just does not wanna work with openfl nor lime

**Comment by Rudyrue** [comment]
also this pr is so out of date i might close it lmfao

**Comment by Rudyrue** [comment]
fuck

**Pull request closed without merging**
