### PR TITLE
Yeah, repaired easter egg

### PR DESCRIPTION
**Pull request by Wither362**
Well, I activated the Easter egg, and now I can’t disable it, so I make this to restore the easter egg, and return it to the normal screen

### CODE REVIEW

**Comment by frantastic24** [comment]
Easter eggs aren't broken, you disable them by typing the code again
This PR is useless

**Review by TheKitBoi — CHANGES_REQUESTED** [review]
run it back

**Comment by Wither362** [comment]
I mean, I typed bb, and now I can’t get gf back, but with this, it will reset the Easter egg, not disabling it

**Comment by frantastic24** [comment]
You type bbpanzu not bb, close this already

**Comment by frantastic24** [comment]
TitleState.hx line 469
image

**Pull request closed without merging**
