### PR TITLE
Stupid dumb shit that bothered me

### PR DESCRIPTION
**Pull request by Unholywanderer**
0 impact on gameplay, still bothered me

oh boy my first pull request for psych
I sure hope this extremely simple and stupid pull request gets merged :-)

### CODE REVIEW

**Review by TheKitBoi — APPROVED** [review]

**Review by Raltyro — APPROVED** [review]
ong

**Comment by Unholywanderer** [comment]
yea

**Comment by Unholywanderer** [comment]
stupid shit,  as I said

**Review by rodney528 — APPROVED** [review]
My ocd approves

**Review by MemeHoovy — APPROVED** [review]

**Comment by DillyzThe1** [comment]
After reviewing the minor edits done to the source code, this actually seems like a pretty good change that wouldn't really affect too much.
If there's anthing I'd suggest, it'd be to change the hitsound text to something much more grammatically correct or straightfoward.
(Such as "The notes will indicate timing with a sound in the editor.")

**Review by Intancote — APPROVED** [review]

**Comment by Unholywanderer** [comment]
bruh moment

**Review by rodney528 — APPROVED** [review]

**Pull request closed without merging**
