### PR TITLE
adding note shaders

### PR DESCRIPTION
**Pull request by ghost**
this is the fixed version of the note shader

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by nebulazorua** [comment]
atleast credit me lmao

**Comment by beeanie** [comment]
sorry lol

**Review by HiroMizuki — APPROVED** [review]
idk what exactly is that but ok LMAO

**Comment by ShadowMario** [comment]
Bruh really snatching stuff without crediting originally 💀💀💀💀💀💀

**Pull request closed without merging**
