### PR TITLE
Latin Alphabet Support

### PR DESCRIPTION
**Pull request by crowplexus**
Repost of my previous Latin Alphabet Support PR
hopefully this one wraps everything up in those 3 commits only

this is not meant to be merged since ShadowMario probably has a better solution, but you guys can merge this with your forks!

make sure to credit me and @HiroMizuki (who made the designs) if you merge this with your fork

### CODE REVIEW

**Review by BombasticTom — APPROVED** [review]

**Review by HiroMizuki — APPROVED** [review]

**Review by stilic — APPROVED** [review]

**Review by lunacynne — APPROVED** [review]

**Comment by Swapper1** [comment]
I just realized that the letter 'ā ē ī ō ø œ ū ŵ ÿ' and 'ŷ', as well as the bold text of 'ä å æ è ë ì î ï ò ö ø œ ù û ü ý þ ð ẞ § µ', are missing. Because when I test it, the letters won't show up.

**Comment by BeastlyGhost** [comment]
closed this because shadowmario has a better solution for it, you guys can still use it and make your own fixes for it, I won't delete the branch itself

**Comment by MilkyTheMilkBlob** [comment]
why did you delete the branch

**Comment by BeastlyGhost** [comment]
I didn't delete it

**Comment by BeastlyGhost** [comment]
https://github.com/BeastlyGhost/FNF-PsychEngine/tree/latin-alphabet

**Comment by ShadowMilky** [comment]
> https://github.com/BeastlyGhost/FNF-PsychEngine/tree/latin-alphabet

it says 404 not found

**Comment by BeastlyGhost** [comment]
shadow is rewriting alphabet himself, expect official latin alphabet support soon

**Pull request closed without merging**
