### PR TITLE
Flash movie support

### PR DESCRIPTION
**Pull request by Joalor64**
This simply adds support for .swf movies and such.
Probably should've added an example, but whatever.

### CODE REVIEW

**Review by charlesisfeline — APPROVED** [review]

**Comment by RiachuC4D** [comment]
OHH THIS IS SO CRAZY

i hope they add it

**Comment by TheKitBoi** [comment]
> This simply adds support for .swf movies and such.

This needs lua functions

**Review by MemeHoovy — APPROVED** [review]
Needs Lua functions, but ok

**Comment by Joalor64GH** [comment]
For those of you who say that this needs lua functions, I don't know how to do that. But, if you do know how to do it, please let me know.

**Comment by ShadowMario** [comment]
This has near zero use cases, adding this to the engine would just be unnecessary bloating.

**Comment by ShadowMilky** [comment]
too bad i already merged it to my fork :troll:

**Comment by TheKitBoi** [comment]
> too bad i already merged it to my fork :troll:

Have bloating issues

**Comment by ShadowMilky** [comment]
> > too bad i already merged it to my fork :troll:
> 
> Have bloating issues

yeah, let me check again

**Comment by ShadowMilky** [comment]
oh I realized it does have bloating problems

**Pull request closed without merging**
