### PR TITLE
Update Project.xml

### PR DESCRIPTION
**Pull request by PandaTellez**

### CODE REVIEW

**Comment by MemeHovy** [comment]
https://user-images.githubusercontent.com/124418090/218669891-83bdc86f-287e-4d02-96d9-a9b652e0d859.mp4

**Comment by TheKitBoi** [comment]
> No description provided.

That’s laughable

**Review by libauror-a — CHANGES_REQUESTED** [review]
FIX YOR SEPLING!!!1!

**Comment by KookerFoxYT** [comment]
spellcheck hater found!!!!!

**Comment by MemeHovy** [comment]
> spellcheck hater found!!!!!

PITBULL GO--

**Comment by trayfellow** [comment]
this pr is so realistic i could feel it coming inside of me

**Review by fartermasterfar — APPROVED** [review]

**Comment by ManMaster707** [comment]
Psych Engin

**Comment by DisIsNOt** [comment]
epic

**Comment by Hackx2** [comment]
> _ No description provided. _

Psych Engin

**Pull request closed without merging**
