### PR TITLE
Fixed LibVLC so Linux can also play mp4 cutscenes

### PR DESCRIPTION
**Pull request by Erizur**
I updated libvlccore to the latest version that most linux distributions use at the moment, however without installing libvlc/libvlccore from your package manager, the game's prone to crash (on linux) since I don't know how to link it to the executable like how windows does yet.

Anyways, this also allows this to libvlc to be more cross platform, macOS does not work at the moment as I ran into even more issues.

### CODE REVIEW

**Review by superpowers04 — APPROVED** [review]

**Comment by Stilic** [comment]
HOWWWWWWW so cool

**Review by stilic — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by TheKitBoi — APPROVED** [review]

**Review by GO-Miles — APPROVED** [review]
yes

**Review by MAJigsaw77 — APPROVED** [review]

**Review by Raltyro — APPROVED** [review]
poggers

**Review by Erizur — COMMENTED** [review]
oops

**Comment by trayfellow** [comment]
you should prob pr this too on here which is where the mp4 stuffs came from

https://github.com/brightfyregit/Friday-Night-Funkin-Mp4-Video-Support

**Comment by polybiusproxy** [comment]
> I updated libvlccore to the latest version that most linux distributions use at the moment, however without installing libvlc/libvlccore from your package manager, the game's prone to crash (on linux) since I don't know how to link it to the executable like how windows does yet.
> 
> Anyways, this also allows this to libvlc to be more cross platform, macOS does not work at the moment as I ran into even more issues.

cool pr but it shouldn't be here, make the pr at my original repo https://github.com/brightfyregit/Friday-Night-Funkin-Mp4-Video-Support

**Review by ghost — APPROVED** [review]
this should be added

**Review by lunacynne — APPROVED** [review]

**Comment by Stilic** [comment]
pls close this
this is useless since now there is hxcodec
i also made a pr for change to that lib: #8377.

**Review by lunacynne — APPROVED** [review]

**Comment by polybiusproxy** [comment]
Please, do not approve this pull request. @cyn-8 
This pull request has been moved to the main hxCodec repo, and now, an update must be applied to Psych Engine.

**Comment by cyn-8** [comment]
> Please, do not approve this pull request. @cyn-8 This pull request has been moved to the main hxCodec repo, and now, an update must be applied to Psych Engine.

oh i see

**Comment by BeastlyGhost** [comment]
can be closed now, since 0.6 onwards uses hxCodec

**Pull request closed without merging**
