### PR TITLE
Mouse wheel support in more menus + remove dumb vars

### PR DESCRIPTION
**Pull request by Intancote**
Added the support for mouse wheel scrolling in more menus so that using mouse feels more consistent.
Also removed two vars that were very much not needed to be made (Because they only were used once).

This PR adds support for mouse scrolling in:
* Main Menu
* Mods Menu
* Awards
* Credits

And removes 2 vars in:
* CreditsState.hx

### CODE REVIEW

**Review by BombasticTomDev — APPROVED** [review]
pretty good pr i'd only suggest adding mouse click controls (example: left click to enter a song/enable a mod/redirect to credits link, and right click to change the song difficulty)

**Review by NexIsDumb — APPROVED** [review]

**Review by TheLeerName — APPROVED** [review]

**Review by DetectiveBaldi — APPROVED** [review]
yummm

**Review by moxie-coder — APPROVED** [review]

**Review by Justine101213k — APPROVED** [review]

**Comment by Stefan2008Git** [comment]
> Added the support for mouse wheel scrolling in more menus so that using mouse feels more consistent. Also removed two vars that were very much not needed to be made (Because they only were used once).
> 
> This PR adds support for mouse scrolling in:
> 
> * Main Menu
> * Mods Menu
> * Awards
> * Credits
> 
> And removes 2 vars in:
> 
> * CreditsState.hx

Pretty good idea for scrolling with mouse

**Review by ACoolioDude — APPROVED** [review]

**Review by rodney528 — APPROVED** [review]

**Review by charlesisfeline — APPROVED** [review]

**Comment by ShadowMario** [comment]
Some of these menus got reworked on experimental and Main Menu will be reworked too sometime in the future so i'm gonna close this

**Comment by Stefan2008Git** [comment]
> Some of these menus got reworked on experimental and Main Menu will be reworked too sometime in the future so i'm gonna close this

Makes sense

**Comment by Intancote** [comment]
> Some of these menus got reworked on experimental and Main Menu will be reworked too sometime in the future so i'm gonna close this

Alr
I'll wait until that's finished and remake this when that's done. Wanted to actually do more to this like adding a actual cursor and LClick/RClick to certain controls

**Pull request closed without merging**
