### PR TITLE
fix sscript 4.1.0 breaking http and itself

### PR DESCRIPTION
**Pull request by TehPuertoRicanSpartan**
people has been getting this error and now i'm here to fix this

### CODE REVIEW

**Comment by TehPuertoRicanSpartan** [comment]
yes, you need to set sscript to 4.0.1 when you reinstall the libraries from hmm.json

**Comment by TheWorldMachinima** [comment]
SScript 5.0.0 is going to fix this issues, so this change is unnecessary.

**Comment by TehPuertoRicanSpartan** [comment]
wait, sscript **_5.0.0_**?

**Comment by TheWorldMachinima** [comment]
> wait, sscript **_5.0.0_**?

Yes.

**Comment by TehPuertoRicanSpartan** [comment]
never heard of it

**Comment by CrowPlexus** [comment]
fixed in 5.0

**Pull request closed without merging**
