### PR TITLE
Allow Compilation Without MODS_ALLOWED

### PR DESCRIPTION
**Pull request by steviegt6**
This PR fixes issues with misplaces or missing usages of the `sys` and `MODS_ALLOWED` compilation preprocessors in order to allow compilation of the project without `MODS_ALLOWED`.

## Purpose
Generally just to ensure functionality in the future. This also opens the door for more compatibility between different transpiling targets (namely JS, see Remarks as well).

## Remarks
This does not resolve misusage of classes within the `sys` package namespace, and that should be looked at in a different PR.

### CODE REVIEW

**Comment by AToska21** [comment]
@ShadowMario 
might want to take a look at this

**Comment by nintendofan44** [comment]
i tested this and
it kinda broke the lua script loading

**Comment by Steviegt6** [comment]
> i tested this and it kinda broke the lua script loading

There's no reason for it not to function, mind elaborating?

**Comment by Steviegt6** [comment]
Alright, well, in an attempt to make sure Lua stays working, I've removed the extra `MODS_ALLOWED` check for `LUA_ALLOWED`, especially since there should never be a case where `MODS_ALLOWED` is false and `LUA_ALLOWED` would be true othrewise.

**Comment by prokube** [comment]
I did my own version of this and it works at least on Mac. then again this is on mac which nobody uses

**Comment by FuseIsHere813** [comment]
Which means if it gets merged, There might be Mac support.

I approve this, even the bugfixes are great.

**Review by FuseIsHere813 — APPROVED** [review]

**Comment by ShadowMario** [comment]
what is the `#if sys` on ChartingState for

**Comment by prokube** [comment]
> Which means if it gets merged, There might be Mac support.

Mac is already technically supported. My fixes just worked on Mac.

**Comment by Steviegt6** [comment]
> what is the `#if sys` on ChartingState for

`sys.FileSystem` isn't important if `MODS_ALLOWED` isn't true, which prevents compilation.

**Comment by osc-omb** [comment]
> I did my own version of this and it works at least on Mac. then again this is on mac which nobody uses

That's because Mac doesn't read Lua.

**Comment by prokube** [comment]
> > I did my own version of this and it works at least on Mac. then again this is on mac which nobody uses
> 
> That's because Mac doesn't read Lua.

i know it doesnt

**Comment by Steviegt6** [comment]
> > I did my own version of this and it works at least on Mac. then again this is on mac which nobody uses
> 
> That's because Mac doesn't read Lua.

The issue is that the library being used doesn't have Mac support (for some God-forsaken reason). Any platform can "read" Lua.

**Comment by MayoALT** [comment]
> > > I did my own version of this and it works at least on Mac. then again this is on mac which nobody uses
> > 
> > 
> > That's because Mac doesn't read Lua.
> 
> The issue is that the library being used doesn't have Mac support (for some God-forsaken reason). Any platform can "read" Lua.

[its currently being fixed from what i know](https://github.com/AndreiRudenko/linc_luajit/issues/10)

**Pull request closed without merging**
