### PR TITLE
STAGE EDITOR!!!

### PR DESCRIPTION
**Pull request by ghost**
youve been waiting for this since well alot so im doing one

### CODE REVIEW

**Comment by MemeHoovy** [comment]
epic

**Comment by Eventretta** [comment]
also uhhh help wanted for graphic help dm on discord if u want ig Eventy#8888

**Comment by BeepSheep254** [comment]
i dont think shadow mario is gonna merge this tho 
i mean he said that he just doesnt want a stage editor in his engine (even though he said that he'll do it very soon, which i think its probably deconfirmed

**Comment by Eventretta** [comment]
@ShadowMario 

> i dont think shadow mario is gonna merge this tho
> i mean he said that he just doesnt want a stage editor in his engine (even though he said that he'll do it very soon, which i think its not completely true)

nah i don't think since everyone asking

**Comment by CaptainBaldi** [comment]
meh personally im not a fan of stage editors

**Comment by ShadowMilky** [comment]
> meh personally im not a fan of stage editors

yeah same

**Comment by Raltyro** [comment]
uh can you please atleast make git ignore ds store?

**Comment by Eventretta** [comment]
> uh can you please atleast make git ignore ds store?

idk to do it can you make a pr on my fork

**Comment by TheKitBoi** [comment]
> > uh can you please atleast make git ignore ds store?
> 
> idk to do it can you make a pr on my fork

did it https://github.com/Eventretta/FNF-PsychEngine/pull/1

**Comment by Eventretta** [comment]
btw this also features a new lua function "promptSaveFile" that prompts for a file save

**Comment by jmxamongusmodder** [comment]
what is .DsStore

**Comment by tposejank** [comment]
> what is .DsStore

mac os hidden file which stores the folder data

**Comment by lime360** [comment]
i have the lua-based stage editor, but i will try adding this one into my mod

**Comment by ShadowMilky** [comment]
image
why does it say .pyst

**Comment by Eventretta** [comment]
> image why does it only support .pyst you could have put .lua support for this stage editor sheesh

i would need to do lua compiling in game which is complicated

**Comment by ShadowMilky** [comment]
> > image why does it only support .pyst you could have put .lua support for this stage editor sheesh
> 
> i would need to do lua compiling in game which is complicated

then implement the .pyst file support in places where the lua stage support code is present

**Review by rodney528 — APPROVED** [review]
I'm pretty sure this won't get approved but whatever.

**Comment by Eventretta** [comment]
anyways i dont think im finishing it

**Comment by ImaginationSuperHero528** [comment]
> anyways i dont think im finishing it

Fair.

**Pull request closed without merging**
