### PR TITLE
clean up

### PR DESCRIPTION
**Pull request by kem0x**
Formatted all files with vscode formatter, removed 2 unused files, removed unneeded code

### CODE REVIEW

**Comment by tposejank** [comment]
Why adding a space after // is important
this is useless

**Comment by kem0x** [comment]
the formatter does that automatically

**Comment by Steviegt6** [comment]
This PR is a good example of why blindly running a linter isn't always useful. Large (and arguably poorly-designed) arrays such as the one containing achievement data is manually formatted in a human-readable manner. Your linter removed this formatting entirely.

**Comment by kem0x** [comment]
you can blame that on whomever did the array for taking a bad approach, huge files such as playstate are way more readable when formatted.

**Comment by Steviegt6** [comment]
> you can blame that on whomever did the array for taking a bad approach, huge files such as playstate are way more readable when formatted.

This is *really* ignorant. It's generally distasteful to go around parading on open-source repositories with a linter and expecting people to appreciate it, especially when you ignore existing formatting and decide that whatever your linter presets are is what should dictate the de facto formatting rules.

**Comment by tposejank** [comment]
image

**Comment by kem0x** [comment]
just shut the fuck up I don't have time for this shit weirdo

**Comment by JamzOhJamz** [comment]
seethe and mald

**Comment by Steviegt6** [comment]
> seethe and mald

> just shut the fuck up I don't have time for this shit weirdo

**Comment by RighteousRyan1** [comment]
ZAMN

**Pull request closed without merging**
