### PR TITLE
Implement Pixel Splashes (without XML)

### PR DESCRIPTION
**Pull request by DM-kun**
This PR adds Pixel Notesplashes that are actually pixels AND they don't use an XML like the Pixel Notes
Here is a little showcase:

https://user-images.githubusercontent.com/86197998/178114893-ff1dd294-bd37-4608-8c66-f03644448549.mp4

Original Pixel Splashes by me, Improved version by [xChillax](https://github.com/xChillax)
Pixel Hurt Splashes by [xChillax](https://github.com/xChillax)

### CODE REVIEW

**Review by CrusherNotDrip — APPROVED** [review]

**Review by DabbinDude316B — APPROVED** [review]

**Review by SwickTheGreat — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by TheKitBoi — APPROVED** [review]

**Review by Trayfellow — APPROVED** [review]

**Review by CowSoftware — APPROVED** [review]

**Review by xRaRxTeos — APPROVED** [review]

**Review by Raltyro — APPROVED** [review]

**Review by rodney528 — COMMENTED** [review]
Needs some shading.

**Review by rodney528 — APPROVED** [review]

**Comment by frantastic24** [comment]
What
Not even the normal ones have shading what are you talking about

**Comment by ImaginationSuperHero528** [comment]
> What Not even the normal ones have shading what are you talking about

The notes do the opposite though.

**Comment by xChillax** [comment]
I polished it a bit. I added shading and made the movement in certain frames smoother. I also made it have a lil' circle on the first frame, it's a subtle way to represent its "exploding". It probably can't be seen due to the fact that the arrows have this same white color when pressed but oh well. lol

noteSplashes

noteSplashes-sheet-export

**Comment by ImaginationSuperHero528** [comment]
Oo0

**Comment by DMMaster636** [comment]
> I decided to polish up your sprites, pretty much remade them since I reanimated every drop from the splashes. I added shading, a subtle brightness change, and made the movement in certain frames smoother. I also added a lil' circle on the first frame, it's a subtle way to represent its "exploding". It probably can't be seen due to the fact that the arrows have this same white color when pressed but oh well. lol
> 
> noteSplashes noteSplashes [ ](https://user-images.githubusercontent.com/6830124/176978151-57ae6ae1-0a82-4632-b973-1643d2c1a9f1.gif) noteSplashes [ ](https://user-images.githubusercontent.com/6830124/176978151-57ae6ae1-0a82-4632-b973-1643d2c1a9f1.gif)

looks good
gonna add this, but i'm removing the circle from the middle if you don't mind

**Comment by xChillax** [comment]
Sounds good!

It wasn't visible and a test anyways. lol

I might make the hurt note splash later (since that's also a default one) if I have time.

**Comment by xChillax** [comment]
I went ahead and made the hurt note "splash". I took inspiration from the original one and made it look more like an electric explosion/impact. It has the same size and frames as the normal pixel note splashes.

HURTnoteSplashes

HURTnoteSplashes-export-export

**Review by rodney528 — APPROVED** [review]

**Comment by DMMaster636** [comment]
> 

cool, i'll just have to figure out how to make it work, cause now it's not using an xml and the way the original did was simple

**Comment by DMMaster636** [comment]
> cool, i'll just have to figure out how to make it work, cause now it's not using an xml and the way the original did was simple

when looking at it... they also were lazy with making the note pixel, so imma be lazy too and do what they did

**Review by rodney528 — APPROVED** [review]

**Comment by xChillax** [comment]
Could you add a video to the main post btw?

**Comment by ImaginationSuperHero528** [comment]
> Could you add a video to the main post btw?

Why should there be a video?

**Comment by xChillax** [comment]
So people can see how this looks in-game which helps seeing how it works without having to compile this code.

**Comment by DMMaster636** [comment]
> So people can see how this looks in-game. Which will help showcasing how it looks without having to compile this code.

Good point, gonna record a vid now

**Comment by DMMaster636** [comment]
So, I have noticed that it's possible to switch between normal and pixel mid-song, but there's a problem with this. If it loads up the pixel splashes, it makes the image bigger, but when I switch back, the normal splashes turn giant. If you've seen the "I may be stupid" commits, then you see how I tried fixing it... Well, the problem then was that the normal splashes just never appeared... So yeah.

If anyone knows a fix for this, so switching between normal and pixel and so doesn't break the splashes, then either make a pr for this branch or just comment the solution please :/

**Comment by DMMaster636** [comment]
AAAAALRIGHT
Thanks to realizing scale.set(); exists, I have now fixed the problem, meaning there should be no more problems that can make the splashes act weird!
So this PR is now really complete

**Review by rodney528 — APPROVED** [review]

**Review by MemeHoovy — APPROVED** [review]

**Review by Intancote — APPROVED** [review]

**Review by Parsellol — APPROVED** [review]

**Comment by DMMaster636** [comment]
renamed the branch, gonna make a new pr in a sec

**Pull request closed without merging**
