### PR TITLE
make changing bpm a setter instead of an entire function

### PR DESCRIPTION
**Pull request by Rudyrue**
this allows for lerping/tweening the bpm which would be really helpful on sliding bpms, like in too slow from sonic.exe

also it's just better to use overall cuz it's just setting a variable lmfa

### CODE REVIEW

**Review by crowplexus — APPROVED** [review]
should be like that from the start

**Review by moxie-coder — APPROVED** [review]

**Review by Sword352 — APPROVED** [review]
goATED 🗣🔥🫵💯

**Review by DetectiveBaldi — APPROVED** [review]
tbh a easy way to tween bpm would be really useful

**Review by charlesisfeline — APPROVED** [review]
yes

**Review by NexIsDumb — APPROVED** [review]
GODDAMIT finally

**Pull request merged**
