### PR TITLE
Character Editor pointer graphic fix on flixel 5.7.0+

### LINKED ISSUE #14703: Character Editor Screen Blacked Out
### Describe your problem here.

Screenshot 2024-05-19 at 1 47 22 pm
Not exactly sure whats going on with it, everything else works fine but just this. I saw one other post but I couldn't figure out what was wrong or if its even possible on mac!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

_No response_

### PR DESCRIPTION
**Pull request by richTrash21**
Fixes #14703 and #14689 by creating a local pointer graphic bitmap class in Character Editor and embedding an image into it the same way as it was done in HaxeFlixel versions prior to 5.7.0 (non debug platforms only).

### CODE REVIEW

**Review by ACoolioDude — APPROVED** [review]
Nice

**Comment by SlickSquid35** [comment]
I tried replacing the CharacterEditorState.hx file with the one provided here, but I ran into the same screen without any changes, I'm still new to source code so I don't really have an idea on how to fix this. 

And just to clarify, I am using the source code for FNF Psych engine 0.7.2h, so I'm not sure if this fix is meant for a newer or older version than the one I have. 

Could someone help me out?

**Comment by richTrash21** [comment]
> And just to clarify, I am using the source code for FNF Psych engine 0.7.2h, so I'm not sure if this fix is meant for a newer or older version than the one I have.

this fix is meant for future versions of Psych engine, so directly copying whole class won't work since it got changes from upcoming version, so just copy these lines and it should work
image
image

**Comment by MikExpungedMoment** [comment]
i'm getting this error about ConfirmationPopupSubstate
Screenshot 2024-05-22 155136

**Comment by kpsm485** [comment]
states/editors/CharacterEditorState.hx:26: character 1 : Uncaught exception File not found 'assets/shared/images/debugger/cursorCross.png'

C:\HaxeToolkit\haxe\std/haxe/macro/Context.hx:117: characters 10-39 : Called from here

C:/Users/PC/Downloads/FNF-PsychEngine-main/FNF-PsychEngine-main/setup/openfl/9,3,3/src/openfl/utils/_internal/AssetsMacro.hx:157: characters 16-45 : Called from here

C:/Users/PC/Downloads/FNF-PsychEngine-main/FNF-PsychEngine-main/setup/openfl/9,3,3/src/openfl/utils/_internal/AssetsMacro.hx:41: characters 16-36 : Called from here

states/editors/CharacterEditorState.hx:26: character 1 : Called from here

is what im getting i have NO IDEA what to do

**Comment by richTrash21** [comment]
> why doesnt this work (im on the latest version of psych and flixel) im trying to fix the "black screen of death" and it wont work even after i redid this like a million times too and did everything that was shown please help Näyttökuva 2024-05-21 151100 Näyttökuva 2024-05-27 121514
> 
> (i use visual studio 2019) please help i wanna mod the game

Can you show me line 106 please? It's probably still loading graphic from GraphicCursorCross class instance which is blank on non debug targets.

**Comment by richTrash21** [comment]
> i'm getting this error about ConfirmationPopupSubstate Screenshot 2024-05-22 155136

Seems like you're using an older Psych version or a version that doesn't have this class. Try copying only this PR's changes, not the whole class.

**Comment by richTrash21** [comment]
> states/editors/CharacterEditorState.hx:26: character 1 : Uncaught exception File not found 'assets/shared/images/debugger/cursorCross.png'
> 
> C:\HaxeToolkit\haxe\std/haxe/macro/Context.hx:117: characters 10-39 : Called from here
> 
> C:/Users/PC/Downloads/FNF-PsychEngine-main/FNF-PsychEngine-main/setup/openfl/9,3,3/src/openfl/utils/_internal/AssetsMacro.hx:157: characters 16-45 : Called from here
> 
> C:/Users/PC/Downloads/FNF-PsychEngine-main/FNF-PsychEngine-main/setup/openfl/9,3,3/src/openfl/utils/_internal/AssetsMacro.hx:41: characters 16-36 : Called from here
> 
> states/editors/CharacterEditorState.hx:26: character 1 : Called from here
> 
> is what im getting i have NO IDEA what to do

'cursorCross.png' is not a locally stored graphic in this PR, so it should not mention any FNF/Psych related asset paths (like 'shared' in this case). Just use the default HaxeFlixel's pointer graphic path - 'assets/images/debugger/cursorCross.png'.

**Comment by MikExpungedMoment** [comment]
> > i'm getting this error about ConfirmationPopupSubstate Screenshot 2024-05-22 155136
> 
> Seems like you're using an older Psych version or a version that doesn't have this class. Try copying only this PR's changes, not the whole class.

i'm using the most recent version of psych (0.7.3) but i'll still try that

**Comment by mikaelrokkaa** [comment]
> Fixes #14703 and #14689 by creating a local pointer graphic bitmap class in Character Editor and embedding an image into it the same way as it was done in HaxeFlixel versions prior to 5.7.0 (non debug platforms only).

also what the hell do you mean by everything u just wrote there
(i do not understand haxe / coding i just want to make a cool mod)

**Comment by MikExpungedMoment** [comment]
> > i'm getting this error about ConfirmationPopupSubstate Screenshot 2024-05-22 155136
> 
> Seems like you're using an older Psych version or a version that doesn't have this class. Try copying only this PR's changes, not the whole class.

also, is there any way i could download conformationpopupsubstate and abb it to my build

**Comment by CreamslyCream** [comment]
TYSM!!!!!!!!!!!

**Comment by VioletaCarmesim** [comment]
ok now what do i do with this information
how do i apply things here to fix my blacked out char edtior bug

**Comment by VioletaCarmesim** [comment]
image
what do i do

**Pull request closed without merging**
