### PR TITLE
Lock hmm.json to specific versions to improve install process.

### PR DESCRIPTION
**Pull request by EliteMasterEric**
Now you can just install Haxe 4.2.5 and do this:

```
haxelib install hmm
haxelib run hmm install
```

and it will install the correct library versions for you, automatically, into a local haxelib folder so it doesn't interfere with your other projects.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
yummy but change branch to exp please

**Comment by MemeHovy** [comment]
bro you forgot to change the branch

**Comment by EliteMasterEric** [comment]
Oopsie, I made the base branch experimental then targeted main on accident!

Should be fixed now.

**Review by moxie-coder — COMMENTED** [review]
brilliant 👍🏻 
(forgot to approve oops)

**Review by moxie-coder — APPROVED** [review]

**Comment by mcagabe19** [comment]
@EliteMasterEric don't forget close this too

**Review by charlesisfeline — APPROVED** [review]

**Pull request closed without merging**
