### PR TITLE
Implement hscript-improved

### PR DESCRIPTION
**Pull request by TheLeerName**
as u can see in this [repo](https://github.com/TheWorldMachinima/SScript), SScript is not exists anymore, so i got idea implement `hscript-improved` lib from Codename Engine cuz it have the same things as in SScript like `import` and such

So **now** with this library we can use this script:
```hx
function onCreatePost() {
	gf.visible = false;
}
```
and yes, as you can see, we can avoid using `game` variable 😱
classes still bugged and dont work normally (skill issue)
also i rewritted error messages (lol as in #13017), and i know about bug with duplicated file name in haxe 4.3.X lol
also `getTextFromFile` lua function and `Paths.getTextFromFile` now has 3rd argument, if it `true`, then it gets file by absolute path
also `addHaxeLibrary` can import enums now

### UPD: 17:49 - 19.09.2023
- errors on hscript now traces to console
- if u got error in `runHaxeCode`, it stops executing
- `Lua_helper.add_callback()` now just `set()`
- `setOnLuas` now not crashes when u trying to set function with it
- trace of elapsed time after loading script

## WARNING: USE THIS COMMAND BEFORE COMPILING PLS
```
haxelib git hscript-improved https://github.com/TheLeerName/hscript-improved
```
*will use original hscript-improved if my pr in original repo will be merged*

### CODE REVIEW

**Review by DetectiveBaldi — APPROVED** [review]
👍

**Review by moxie-coder — APPROVED** [review]

**Review by Karim-Akra — APPROVED** [review]

**Review by charlesisfeline — APPROVED** [review]
yea creator of sscript deleted their account for some reason and that may make future commits not able to compile in this condition so ig this should do

**Comment by TheLeerName** [comment]
bro got Http Error #502

**Review by ghost — APPROVED** [review]
hell yea

**Review by MaybeMaru — APPROVED** [review]

**Review by frantastic24 — APPROVED** [review]
seems to work with no problems
thank god because sscript just kept getting worse and worse

**Review by HomuHomu833 — APPROVED** [review]

**Review by DM-kun — APPROVED** [review]

**Comment by TheLeerName** [comment]
so BrewScript already implemented im closing this, but i copied some changes to another prs:
#13325
#13326

**Comment by TerminallyAwesome** [comment]
still doesnt work for me

**Comment by MemeHovy** [comment]
> still doesnt work for me

install brewscript

**Comment by Karim-Akra** [comment]
> still doesnt work for me

You need to merge experimental branch

**Comment by TerminallyAwesome** [comment]
nevermind I just got it

**Pull request closed without merging**
