### PR TITLE
Skip Song option

### PR DESCRIPTION
**Pull request by Joalor64**
yeah that's all this is

### CODE REVIEW

**Comment by CaptainBaldi** [comment]
Isn't this literally useless, as ending the song while in Charting Mode (which unless I'm stupid, is the only instance where this option appears), sends the player into the Chart Editor?

**Comment by AltronMaxX** [comment]
> Isn't this literally useless, as ending the song while in Charting Mode (which is the only instance where this option appears), sends the user back into the Chart Editor?

This option not for charting, it's for story mode. It will be legal cheat for skip difficult songs.

**Comment by Joalor64GH** [comment]
> This option not for charting, it's for story mode. It will be legal cheat for skip difficult songs.

Yeah, what he said.

**Comment by ShadowMilky** [comment]
oh well
first joalor64gh pull request to be useful (well, a little bit but umm yeah)

**Comment by antoSKRLOL** [comment]
I'm going to use this in FNF: Project plus, I hope you don't mind (I'll leave credits)

**Comment by RodneyAnImaginativePerson** [comment]
> Isn't this literally useless, as ending the song while in Charting Mode (which is the only instance where this option appears), sends the user back into the Chart Editor?

Using endSong() in charting mode from the pause menu kills you.

**Review by rodney528 — APPROVED** [review]

**Comment by KookerFoxYT** [comment]
> bro this is very useless.
> 
> if your using an debug compiled build, just press 1.
this pr applies to those who use the release builds

**Comment by RodneyAnImaginativePerson** [comment]
> bro this is very useless.
> 
> if your using an debug compiled build, just press 1.

Your missing the point here.

**Pull request closed without merging**
