### PR TITLE
Extension Webm

### PR DESCRIPTION
**Pull request by Joalor64**
This is just an implementation of  `extension-webm` in Psych Engine. To do this, I just borrowed code from Kade Engine. So, yeah. Here it is.
(Note: It doesn't really work for Linux, so that's why there's no installation for it in `main.yml`.)

### CODE REVIEW

**Comment by Raltyro** [comment]
Unnecessary because hxCodec/Vlc already supports webm file format
image

**Comment by Joalor64GH** [comment]
ohhh

**Comment by trayfellow** [comment]
its not necessary to have this anymore, the current dev version of hxcodec is about to have mac support soon

**Review by stilic — COMMENTED** [review]
very useless because hxcodec uses vlc, so webm format is already supported

**Comment by Joalor64GH** [comment]
oh okay

**Review by rodney528 — CHANGES_REQUESTED** [review]
Are you gonna close this or what?

**Comment by Joalor64GH** [comment]
ok imma do it rn

**Pull request closed without merging**
