### PR TITLE
Fix for videos in example mods and made other videos work

### PR DESCRIPTION
**Pull request by br4dnblehh**

### CODE REVIEW

**Comment by BeastlyGhost** [comment]
image
I already made it pretty clear, please, **use** the stable version of hxCodec, read the repository description, videos do work on mods

**Comment by BushTrain460615** [comment]
being honest the git build is pretty stable

**Comment by BeastlyGhost** [comment]
> being honest the git build is pretty stable

the big issue with the git version is that, it **can** (but won't necessarily..) break compiling as a whole, plus, any updates to it could potentially break everything, and people would once again have a lot of problems

giving people a product that is in development is pretty much asking for more and more issues

**Comment by BeastlyGhost** [comment]
I really want hxCodec to fully update so I can add video sprites by myself already, but that's the issue, I don't know exactly when it's even going to update, so i'm holding my own build of Psych that already has support for video sprites and such, because I don't really wanna give people a product that is still in development and is probably unstable

**Comment by BushTrain460615** [comment]
ah ok I get it now

**Comment by BushTrain460615** [comment]
when they update it I might push this later

**Comment by BeastlyGhost** [comment]
also hoping for it to update soon, really wanna bring video sprites to public already cuz that's cool shit

**Pull request closed without merging**
