### PR TITLE
Unused imports

### PR DESCRIPTION
**Pull request by Intancote**
Literally what the title says. They are unused. The game is the same without these imports.

If they were going to be used at a later date then this pull request can be closed.

### CODE REVIEW

**Comment by Intancote** [comment]
I basically did this since I was bored and had literally nothing else to do. I'm not hoping that these changes make it in, but if they do then...I guess, cool?

**Comment by Raltyro** [comment]
was this been tested, does it compile?

**Comment by Intancote** [comment]
I tested it with lime test and it worked like it normally does. Even tried lime build and adding some mods to see if that worked, which it did.

**Comment by Intancote** [comment]
Made the code be the same as how the main code currently is so there are fewer issues with it and also fixed a merge conflict with MusicBeatState.hx

Also has been tested with no issues so far.

**Comment by Intancote** [comment]
I feel like I should just remove this PR if not even one person approves of this.
I mean, the game still is and plays the same without these imports, it just makes it more noticeable of what's being used and what's not.
Gonna probably close this after like a week so the PRs don't get clutterd.

**Review by DaRealDotZ — APPROVED** [review]

**Review by rodney528 — APPROVED** [review]

**Review by MemeHoovy — APPROVED** [review]

**Comment by ShadowMario** [comment]
Compiling time isn't affected by this because they're not used, so there's no big reason to approve this.

**Pull request closed without merging**
