### PR TITLE
Alphabet spanish accent and ñ support

### PR DESCRIPTION
**Pull request by tposejank**
What the title says.

https://user-images.githubusercontent.com/81495861/190867174-4a376cab-5218-43d6-8e23-eca6ea4614bd.mp4

Alphabet accents and ñ image and xml by @MaybeMaru
(the menus that showcase the accent and ñ were not edited)

### CODE REVIEW

**Review by DetectiveBaldi — APPROVED** [review]

**Review by MaybeMaru — APPROVED** [review]
really ñ, bf approves
image

**Review by Meloomazy — APPROVED** [review]

**Comment by CaptainBaldi** [comment]
guys tpose forced me to approve otherwise i would turn gay :screa

**Comment by tposejank** [comment]
> guys tpose forced me to approve otherwise i would turn gay :screa

i force you to shut

**Review by MemeHoovy — APPROVED** [review]

**Comment by SakuraSkry** [comment]
ñ

**Review by stilic — APPROVED** [review]

**Comment by Raltyro** [comment]
can you reexport the alphabet spritesheet so it doesnt consume much of shit

**Review by MemeHoovy — CHANGES_REQUESTED** [review]
what @Raltyro said

**Comment by tposejank** [comment]
> can you reexport the alphabet spritesheet so it doesnt consume much of shit

ask @MaybeMaru

**Review by system32unknown — APPROVED** [review]

**Review by ghost — APPROVED** [review]
Looks good, Mewo approves!

**Comment by BoloVEVO** [comment]
enie ññññññññññññññññññññññññññññññññññññññññññññññññññññ

**Review by BoloVEVO — APPROVED** [review]

**Review by Luisinhi010 — APPROVED** [review]

**Comment by MemeHoovy** [comment]
> enie ññññññññññññññññññññññññññññññññññññññññññññññññññññ

ñ

**Comment by Luisinhi010** [comment]
thanks for adding Ç lol

**Review by Luisinhi010 — APPROVED** [review]

**Review by min89xd — APPROVED** [review]

**Review by TheKitBoi — APPROVED** [review]

**Comment by probablynotbetopia** [comment]
ñ

**Review by betpowo — APPROVED** [review]

**Comment by tposejank** [comment]
woah look at that
Uploading Friday Night Funkin'_ Psych Engine 2022-09-22 16-23-41_Trim.mp4…

**Comment by tposejank** [comment]
woah look at that portuguese????!?!
https://user-images.githubusercontent.com/81495861/191854523-a48f3fa0-9226-4e17-b2b3-c5be0f50ee0f.mp4

**Comment by Luisinhi010** [comment]
Yooo, all checks have failed but that's nice

**Review by MemeHoovy — APPROVED** [review]

**Review by Raltyro — APPROVED** [review]

**Review by min89xd — APPROVED** [review]

**Comment by RiachuC4D** [comment]
wtf psych engine si fuera peak

**Comment by ShadowMilky** [comment]
> Yooo, all checks have failed but that's nice

he forgot the haxe library 💀

**Review by charlesisfeline — APPROVED** [review]

**Comment by tposejank** [comment]
reminder
ths failed because the actions did not install a library for some reason

**Comment by BeepSheep254** [comment]
> reminder ths failed because the actions did not install a library for some reason

probably the flixel library, maybe it missed that part

**Review by SanicBTW — APPROVED** [review]

**Comment by BoloVEVO** [comment]
stfu

**Comment by SanicBTW** [comment]
ok :cry: :broken_heart:

**Pull request closed without merging**
