### PR TITLE
Replace `hxCodec` with `hxvlc`.

### PR DESCRIPTION
**Pull request by MAJigsaw77**
Replacing the video lib adds the following futures:

* Better rendering.
* Fixed the plugins on windows from being added to the asset's manifest `default.json`.
* Fixed the weird dll error on windows when it couldn't find the `libqt4_plugin.dll`.
* Pre-caching videos using the `load` function.
* The ability to play multiple videos at once.
* Linux is able to use libvlc plugins now.
* Better sound quality on the flixel backend.

There's more stuff but i can't enum all of them here.

### CODE REVIEW

**Comment by MAJigsaw77** [comment]
Idk why CI is failing.

**Review by ghost — APPROVED** [review]
good for desktop bad for mobile

**Comment by crowplexus** [comment]
> good for desktop bad for mobile

although why bother, psych doesn't officially support mobile

**Comment by mcagabe19** [comment]
> > good for desktop bad for mobile
> 
> although why bother, psych doesn't officially support mobile

I'm talking about our psych mobile port

**Comment by Raltyro** [comment]
I wonder why you guys don't make a pr for hxCodec rather than just psych switching to hxVlc

**Comment by TheRealJake12** [comment]
> I wonder why you guys don't make a pr for hxCodec rather than just psych switching to hxVlc

because hxvlc is superior in almost every way. hxCodec is old and slower with less features.

**Comment by Raltyro** [comment]
Yeah like, why not make a pr instead of making another haxelib that almost does the same thing

**Comment by MAJigsaw77** [comment]
> Yeah like, why not make a pr instead of making another haxelib that almost does the same thing

The libs are different

**Comment by Raltyro** [comment]
I think you should collaborate with other peoples that sounds fun

**Comment by MAJigsaw77** [comment]
> I think you should collaborate with other peoples that sounds fun

No

**Comment by Raltyro** [comment]
bowomp

**Comment by TheRealJake12** [comment]
> bowomp

I was there for hxCodec's beginning
I'll be there for it's downfall

**Review by Sword352 — APPROVED** [review]

**Comment by MAJigsaw77** [comment]
No longer needed since it got implemented already.

**Pull request closed without merging**
