### PR TITLE
fix my stupidity (softcoded achievements pt2)

### PR DESCRIPTION
**Pull request by tposejank**
the icon will now need to be the same as the json name
and fixed ()plication bug

@bbpanzu please merge

### CODE REVIEW

**Comment by Gui-iago** [comment]
@bbpanzu

**Comment by Gui-iago** [comment]
@bbpanzu ayo

**Comment by tposejank** [comment]
wait dont merge it yet im gonna check some stuff

**Comment by MrClogsworthYT** [comment]
> wait dont merge it yet im gonna check some stuff

there is something called make it a draft :D

**Comment by MasterDirector99** [comment]
Yeah baby!

**Comment by tposejank** [comment]
OMG
WHY THE FUCK DOES IT DUPLICATE

WHY DO THE ICONS DON'T LOAD THE CODE IS RIGHT IN MANY WAYS

WHAT THE FUCK

**Comment by tposejank** [comment]
it is technically ready to be pulled if it isnt for these dumb errors which i have no idea why they are here

**Comment by MrClogsworthYT** [comment]
> OMG WHY THE FUCK DOES IT DUPLICATE
> 
> WHY DO THE ICONS DON'T LOAD THE CODE IS RIGHT IN MANY WAYS
> 
> WHAT THE FUCK

MAKE THIS A DRAFT IF IT DOESNT WORK YET

**Comment by tposejank** [comment]
> > OMG WHY THE FUCK DOES IT DUPLICATE
> > WHY DO THE ICONS DON'T LOAD THE CODE IS RIGHT IN MANY WAYS
> > WHAT THE FUCK
> 
> MAKE THIS A DRAFT IF IT DOESNT WORK YET

IDK HOW

**Comment by MrClogsworthYT** [comment]
> > > OMG WHY THE FUCK DOES IT DUPLICATE
> > > WHY DO THE ICONS DON'T LOAD THE CODE IS RIGHT IN MANY WAYS
> > > WHAT THE FUCK
> > 
> > 
> > MAKE THIS A DRAFT IF IT DOESNT WORK YET
> 
> IDK HOW

https://github.blog/changelog/2020-04-08-convert-pull-request-to-draft/
https://github.blog/changelog/2020-04-08-convert-pull-request-to-draft/

**Pull request closed without merging**
