### PR TITLE
we can't report issues to the psych engine port so I'mma do this.

### PR DESCRIPTION
**Pull request by DeceptedPar**
the engine crashes when you zoom in on the debug menu

### CODE REVIEW

**Comment by FuseIsHere813** [comment]
why port extra keys psych port as a PR, he doesn't want extra keys into here bruh??

**Comment by TheZoroForce240** [comment]
didn't realise you had to turn on issues, sorry about that, so you should be able to report issues on the fork now
Il take a look at fixing the issue anyway.

**Comment by HiroOfc** [comment]
i think i'm bein obvious but it definitely will not be merged to the main branch lmao

**Comment by ShadowMario** [comment]
The fuck?

**Comment by FuseIsHere813** [comment]
> The fuck?

i know right?

**Pull request closed without merging**
