### PR TITLE
Add Linux Video Support

### PR DESCRIPTION
**Pull request by avereyishere**

### CODE REVIEW

**Comment by 12abz** [comment]
Testing With Script
 Screenshot from 2023-07-08 07-09-05

**Review by moxie-coder — APPROVED** [review]
good enough

**Review by NexIsDumb — APPROVED** [review]

**Comment by NexIsDumb** [comment]
Though, wait a second
Why are you using your own fork?
How can you tell that somedays there wont be viruses

image

**Review by NexIsDumb — CHANGES_REQUESTED** [review]
Why your fork

**Comment by 12abz** [comment]
becaus the project.xml file has || linux in the video support

**Comment by NexIsDumb** [comment]
> becaus the project.xml file has || linux in the video support

???
And? Can't you edit the one in psych too?

**Comment by NexIsDumb** [comment]
This sounds pretty sus yk

**Comment by 12abz** [comment]
i cant

**Comment by 12abz** [comment]
i was able to

**Comment by NexIsDumb** [comment]
Why not?

**Comment by 12abz** [comment]
because my old account Gibberditosslumber got banned

**Comment by 12abz** [comment]
do not know why

**Comment by 12abz** [comment]
but yeah

**Comment by NexIsDumb** [comment]
Thats not a good reason💀
You aint fooling us

**Comment by NexIsDumb** [comment]
Just change the url

**Comment by NexIsDumb** [comment]
Whats so hard in that?

**Comment by 12abz** [comment]
if i do it wont have linux video

**Comment by NexIsDumb** [comment]
Uhm we're not so stupid yk
Plus ban evading is not allowed too yk?

**Comment by 12abz** [comment]
oh i meant disabled
:skull_and_crossbones:

**Comment by NexIsDumb** [comment]
Ofccc
Now drop the act
Someone closes this pr please

**Comment by 12abz** [comment]
not joking

**Comment by NexIsDumb** [comment]
Still using components linked directly to your own repo is not possible to merge, it will never happen

**Comment by NexIsDumb** [comment]
Ok gosh finally
But why ru installing the whole engine as a lib?

**Comment by 12abz** [comment]
well thats what haxe want's you to do
image

**Comment by NexIsDumb** [comment]
Uhhh no
Hold on, you're doing it in the wrong way, thats not how it works

**Comment by NexIsDumb** [comment]
Plus downloading the engine as a lib its bad

**Comment by 12abz** [comment]
ok

**Comment by NexIsDumb** [comment]
Just delete lines 24 and 25

**Comment by NexIsDumb** [comment]
Bro💀💀

**Comment by NexIsDumb** [comment]
Gosh thanks

**Comment by Raltyro** [comment]
Wait, why installing the same haxelibs again in the linuxsetup.sh?
It's already implemented in hmm

**Comment by NexIsDumb** [comment]
> Wait, why installing the same haxelibs again in the linuxsetup.sh?
> It's already implemented in `haxelib run hmm install`

this pr its old af and he didnt know what he was doing since he was making downloading the whole psych engine source as a lib if i disnt tell him💀

**Comment by NexIsDumb** [comment]
first even his own copy from his github link

**Comment by 12abz** [comment]
Ok We Don't Need This Commit Anymore.

**Pull request closed without merging**
