### PR TITLE
Add better null protection in TitleState.hx

### PR DESCRIPTION
**Pull request by Sezei**
How did you even manage that...

### CODE REVIEW

**Review by voxovistired — APPROVED** [review]

**Review by Lokitot — APPROVED** [review]

**Review by UmbratheUmbreon — APPROVED** [review]

**Review by charlesisfeline — APPROVED** [review]

**Review by Grape-Boy — APPROVED** [review]
crazy:bangbang:

**Review by Raltyro — APPROVED** [review]
IM A DUMB IDIDOT OH MY FUCKING GOS

**Review by TheKitBoi — APPROVED** [review]

**Review by DillyzThe1 — APPROVED** [review]
bruh what were they on

**Review by YanniZ06 — APPROVED** [review]
psych being at its peak of making sense again

**Pull request closed without merging**
