### PR TITLE
Add option to toggle HaxeFlixel's autopause

### PR DESCRIPTION
**Pull request by RagdollClash**
Normally enabled by default (disabled for HTML5 compilation), this is now an option that anyone can toggle on or off.

If auto pause is enabled (default), HaxeFlixel will automatically pause the game when it loses focus.
If auto pause is disabled, HaxeFlixel will no longer automatically pause the game when it loses focus.

https://user-images.githubusercontent.com/15317421/152661143-574510a8-c275-4af4-81dc-a88ffd7b4f21.mp4

However if it's disabled, the game itself will automatically pause during a song to prevent the user from accidently clicking off and missing notes. This functionality is ignored if Botplay is enabled, so that people can record mod footage in the background.

Enabled:

https://user-images.githubusercontent.com/15317421/152661135-0c206b71-a565-488b-ae1a-5ed6dff48280.mp4

Disabled:

https://user-images.githubusercontent.com/15317421/152661137-3f5f0cb1-ee03-4b5d-8a6f-803f0701abb7.mp4

### CODE REVIEW

**Comment by ImaginationSuperHero528** [comment]
if botplay on can it just continue cause it makes sense if you just want to hear some tunes

**Comment by ActualMandM** [comment]
There is pressing space on the Freeplay menu but I'm gonna do this regardless as it'll be helpful towards recording botplay footage

**Review by GamerZoneMusic — APPROVED** [review]
now THIS is a good pull request

**Review by stilic — APPROVED** [review]

**Review by crowplexus — APPROVED** [review]

**Review by lunacynne — APPROVED** [review]

**Review by HiroMizuki — APPROVED** [review]
looks nice

**Comment by ActualMandM** [comment]
#7924 was closed with won't fix, so this will close as well.

**Pull request closed without merging**
