### PR TITLE
Prevent Crash on Chart Editor and Make it able to switch diff thru song name field

### PR DESCRIPTION
**Pull request by Raltyro**
https://user-images.githubusercontent.com/78720179/177026102-2bcb28b7-4333-477a-a941-faae7b7655c9.mp4

### CODE REVIEW

**Comment by ImaginationSuperHero528** [comment]
I feel like for diff it should be another box to type in for just-in-case reasons.

**Review by rodney528 — APPROVED** [review]

**Comment by Raltyro** [comment]
> I feel like for diff it should be another box to type in for just-in-case reasons.

yeah but i dont feel like making another box field soo

**Review by Wither362 — APPROVED** [review]
I like it very much

**Review by TheKitBoi — APPROVED** [review]

**Review by dummmmdum — APPROVED** [review]

**Comment by Raltyro** [comment]
Maded it so PlayState.storyDifficulty automatically sets to the difficulty you inputted in the songname

**Review by HaxLua — APPROVED** [review]

**Review by rodney528 — APPROVED** [review]

**Review by Luisinhi010 — APPROVED** [review]

**Comment by RodneyAnImaginativePerson** [comment]
me when branch had merge conflicts

**Pull request closed without merging**
