### PR TITLE
incluindo o funkin,vis e o grig direto na Source

### PR DESCRIPTION
**Pull request by Kaua6000YT**
Eu estava tendo um problema relacionado ao funkin,vis que impossibilitava a source de ser compilada, após pesquisas, vi que isso acontecia pq a source não conseguia acessar a pasta da funkin,vis na minha haxelib. Então resolvi adicionar o funkin,vis e a dependência grig direto na source, tornando assim mais fácil da source acessar essas haxelibs.

### CODE REVIEW

**Comment by LarryFrosty** [comment]
What the fuck

**Comment by CobaltBar** [comment]
according to google translate

this mf copied the entirety of funkin.vis into source instead of installing it

wtf

**Comment by LarryFrosty** [comment]
> according to google translate
> 
> this mf copied the entirety of funkin.vis into source instead of installing it
> 
> wtf

saves one line in the cmd, very efficient 💯

**Comment by crowplexus** [comment]
this is a real problem that is happening chat, i see where this could be useful, but the execution sucks

**Comment by Kaua6000YT** [comment]
> this is a real problem that is happening chat, i see where this could be useful, but the execution sucks

yeah, I'm not very experienced with haxelib, and after 2 hours installing "funkin,vis" in every possible way and it not working, I ended up installing it directly from the source to test if the source could access the files that it wasn't able to access before.
with that said, how could I execute this idea in a better way? I'd be very grateful for any advice that helps me improve!

**Pull request closed without merging**
