### PR TITLE
Add `BUILDING.md` for Build Instructions

### PR DESCRIPTION
**Pull request by crowplexus**
yea

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
curl(.exe) exists in powershell not in cmd

**Comment by CharlesCatYT** [comment]
> curl(.exe) exists in powershell not in cmd

i used curl in cmd, whats your excuse

**Comment by mcagabe19** [comment]
> > curl(.exe) exists in powershell not in cmd
> 
> i used curl in cmd, whats your excuse

curl isn't installed in windows 10 at default in version 1803 or earlier. That means u have newer windows bleh

**Comment by CharlesCatYT** [comment]
> > > curl(.exe) exists in powershell not in cmd
> > 
> > 
> > i used curl in cmd, whats your excuse
> 
> curl isn't installed in windows 10 at default in version 1803 or earlier. That means u have newer windows bleh

22H2

**Comment by crowplexus** [comment]
> > > curl(.exe) exists in powershell not in cmd
> > 
> > 
> > i used curl in cmd, whats your excuse
> 
> curl isn't installed in windows 10 at default in version 1803 or earlier. That means u have newer windows bleh

`git` installs it for you, that's why I made the step for windows be done specifically after installing git

**Review by ghost — APPROVED** [review]
then fair

**Pull request merged**
