### PR TITLE
Achievement Icons

### PR DESCRIPTION
**Pull request by crowplexus**
achievements will now use icons instead of a full icon grid, making them easier to set up

### CODE REVIEW

**Review by CrusherNotDrip — APPROVED** [review]
This would be nice to merge

**Review by thatsacrylic — APPROVED** [review]

**Comment by Joalor64GH** [comment]
beastly at it again with the amazingful prs

**Review by Joalor64 — APPROVED** [review]

**Review by HiroMizuki — APPROVED** [review]

**Review by BoloVEVO — APPROVED** [review]
This pr needs to be merged. Funkin approved.

**Review by stilic — APPROVED** [review]

**Review by TheKitBoi — APPROVED** [review]

**Review by charlesisfeline — APPROVED** [review]
this needs to be merged

**Review by MAJigsaw77 — APPROVED** [review]

**Review by Itz-NOT-Miles — APPROVED** [review]
yes

**Review by ghost — APPROVED** [review]

**Review by DM-kun — APPROVED** [review]
this 100% needs to get merged

**Review by Trayfellow — APPROVED** [review]
this.

**Review by BombasticTom — APPROVED** [review]

**Review by EyeDaleHim — APPROVED** [review]

**Review by ThatOneSillyGuyDon — APPROVED** [review]

**Review by HaxLua — APPROVED** [review]
Hell yeah

**Review by ghost — APPROVED** [review]
I can see why somebody would want this, as they don't have to edit the image just to make a new one. Nicely done.

**Comment by jigsaw-4277821** [comment]
@ShadowMario please merge this

**Review by Wither362 — APPROVED** [review]

**Review by HeliProGamer — APPROVED** [review]

**Comment by Fridox-lol** [comment]
lets go

**Comment by Joalor64GH** [comment]
IT GOT FREAKING MERGED LETS GOOOOOOOOOOO

**Pull request merged**
