### PR TITLE
Add cut-copy-paste functionality to FlxInputText

### PR DESCRIPTION
**Pull request by libauror-a**
Inplements cut-copy-paste. Simple.

Like every program: 
- Crtl+C copies the text to the clipboard
- Crtl+V pastes the current clipboard content to the input
- Crtl+X cuts the current input text to the clipboard

I was too lazy to make a caret selector, so it just copies the entire text

Please contact me if i need to remove my signature from the files

[demonstration](https://streamable.com/c2o0bn)

### CODE REVIEW

**Review by aubreec88 — APPROVED** [review]
Nice job

**Review by TheKitBoi — APPROVED** [review]

**Review by ManMaster707 — APPROVED** [review]
finally

**Review by MemeFlavor — APPROVED** [review]

**Comment by ThePlank** [comment]
me waiting for a repository admin to check the pull requests be like

https://user-images.githubusercontent.com/75984453/174588948-0cdc0dba-08b8-453e-bcdd-ea95ab126d2c.mp4

**Comment by BeastlyGhost** [comment]
found a minor error
image

**Review by ghost — APPROVED** [review]

**Review by BombasticTom — APPROVED** [review]

**Comment by Stilic** [comment]
@ThePlank I know a library with things for text input handling: https://github.com/ShaharMS/texter.

**Comment by ThePlank** [comment]
> @ThePlank I know a library with things for text input handling: https://github.com/ShaharMS/texter.

Hmm.. I'll look into that to see if i can ~~steal~~ borrow some code.

**Comment by Stilic** [comment]
> > @ThePlank I know a library with things for text input handling: https://github.com/ShaharMS/texter.
> 
> Hmm.. I'll look into that to see if i can ~steal~ borrow some code.

You can also just use it as a Haxelib, no?

**Pull request merged**
