### PR TITLE
Replace Some LQ Songs/Musics with Newer/HQ one (from KawaiSprite Stems)

### PR DESCRIPTION
**Pull request by Raltyro**
^ also changes to the bopeebo event json just to fit the new one
(also changes to tutorial song so instrumental and voices are seperated)

Preview:
https://cdn.discordapp.com/attachments/860848418687680543/956410625876172820/bopeebo.mp4

### CODE REVIEW

**Review by stilic — APPROVED** [review]

**Review by Blossomical — APPROVED** [review]

**Review by DaveFan19 — APPROVED** [review]

**Review by mayo78 — APPROVED** [review]

**Review by HeliProGamer — APPROVED** [review]

**Review by GamerZoneMusic — APPROVED** [review]

**Review by DM-kun — APPROVED** [review]

**Review by TheKitBoi — APPROVED** [review]

**Review by jayrattt — APPROVED** [review]

**Review by MasterDirector99 — COMMENTED** [review]
I will put this in my Psych Engine Revision Build soon!

**Review by MasterDirector99 — APPROVED** [review]

**Comment by Theoyeah** [comment]
you sould add the new voices

**Review by lunacynne — APPROVED** [review]

**Comment by Raltyro** [comment]
> If you want to implement every week with better quality and mixing on the songs, I've remastered all the songs a month or two ago. These also are made to fit the standard charts and are PROPERLY synced to the charts for week 2-6 unlike the default files.
> 
> These were remastered with Kawai sprites official stems too. Inst/Voice for in game usage: https://drive.google.com/drive/folders/1wWFZZaBgLcp2giu5-i3CKcmmH1u3FQS3?usp=sharing FLAC files for listening purposes: https://drive.google.com/drive/folders/15W_bnkGhz3ip9mavzgKqI-YnRgYjnDCJ?usp=sharing
> 
>  remastered.audio.in.action.mp4

Shits rockin, im adding this to the pr asap

**Comment by Lokitot** [comment]
download of the hitsound?

**Pull request closed without merging**
