### PR TITLE
Added loadCredits in FunkinLua.hx

### PR DESCRIPTION
**Pull request by Blossomical**
### How To use
Make a lua script and put loadCredits('SongName') in your script Or just leave 'SongName' empty if you want to have the default Music in it

- **Example**
```lua
function onEvent(name, v1, v2)
  if name == 'loadCredits' then
         loadCredits(v1) --v1 is the song ex: offsetSong
         end
      end
```

### CODE REVIEW

**Review by stilic — CHANGES_REQUESTED** [review]
lol indentation

**Review by DM-kun — APPROVED** [review]
Would be pretty nice, especially for mods when finishing it.

**Comment by Cherif107** [comment]
if there is any bugs report it here https://github.com/ShadowMario/FNF-PsychEngine/discussions/6781

**Review by stilic — APPROVED** [review]

**Review by GO-Miles — APPROVED** [review]
VERY COOL PR. FunkinLua is starting to compete with source modding considering these new features.

**Review by GamerZoneMusic — APPROVED** [review]

**Comment by DaveFan19** [comment]
niiice

**Review by DaveFan19 — APPROVED** [review]
i like it, and it might be useful for some begginer coders out there

**Review by TheKitBoi — APPROVED** [review]

**Pull request closed without merging**
