### PR TITLE
Added a video callback

### PR DESCRIPTION
**Pull request by Lelmaster3457**
I figured it'd be nice to have a video callback feature in the engine and adding one seemed pretty simple so I figured I'd make a request to add it.

### CODE REVIEW

**Comment by LarryFrosty** [comment]
`Paths.video` returns a string. I don't see how that would precache amything

**Comment by Lelmaster3457** [comment]
Fair oof, I thought I was being smart with that but yea it doesn't actually do anything.

**Comment by TheRealJake12** [comment]
if only we had [hxvlc](https://github.com/MAJigsaw77/hxvlc) to allow for actual precaching videos. with better performance too.

**Comment by Lelmaster3457** [comment]
How would I implement that? Like what command would I use, and would I put it into the precache function I deleted?

**Comment by Lelmaster3457** [comment]
Just skimmed the code, I could probably add it to playstate if that's what ur reccommending

**Comment by Lelmaster3457** [comment]
Started adding the hxvlc stuffs, it's currently functional but not amazingly so

**Comment by LarryFrosty** [comment]
Uhh, `hxvlc` has already been added in the experimental branch

**Comment by Lelmaster3457** [comment]
Aw man, I was getting ready to go all in on this. Thx for the heads up tho.

**Pull request closed without merging**
