### PR TITLE
fixes global scripts running twice

### PR DESCRIPTION
**Pull request by KarimAkra**

### CODE REVIEW

**Review by ghost — APPROVED** [review]
karim said to me approve blame him-

**Comment by KarimAkra** [comment]
> karim said to me approve blame him-

**Comment by ShadowMario** [comment]
If I am correct, it only would run global scripts twice if said scripts are from a week inside the global mod's folder, right?

**Comment by KarimAkra** [comment]
ye they run twice in the global mod only when they're in the mod's scripts folder

**Pull request merged**
