### PR TITLE
Fix cringe BF and GF offsets

### PR DESCRIPTION
**Pull request by stilic**
ok i just discovered there was cringe offsets to fix
@ShadowMario pls merge this asap

### CODE REVIEW

**Comment by BombasticTom** [comment]
lol cringe!

**Review by BombasticTom — APPROVED** [review]
so cringe!

**Review by CrusherNotDrip — APPROVED** [review]
cring!

**Review by CrusherNotDrip — APPROVED** [review]

**Review by CrusherNotDrip — APPROVED** [review]

**Comment by CrusherMods** [comment]
approving every commit made in this pr lol

**Comment by LeanDapper** [comment]
lol!!!!

**Review by LeanDapper — APPROVED** [review]

**Comment by ShadowMario** [comment]
retard

**Pull request closed without merging**
