### PR TITLE
Create my mod

### PR DESCRIPTION
**Pull request by FarizGaming331**

### CODE REVIEW

**Comment by CrusherMods** [comment]
tf does this do?

**Comment by PoleyMagik** [comment]
Block this one, he just wants someone to write a mine note script for him

**Comment by tposejank** [comment]
@ShadowMario

**Comment by ArezalGame89** [comment]
can someone give me a anti-cringe pill?

**Comment by DaBanana64** [comment]
You're creating a mod with 0 effort and trying to merge this into the main repo? Damn bruh this is new to me.

**Comment by HiroMizuki** [comment]
lol clearly not a good PR

**Comment by NS-Unfair** [comment]
This pull request doesn't add anything or fix anything, please close this pull request.

**Comment by lemz1** [comment]
Guys what are you talking about. This is the best Pull Request. I mean **nothing** was committed. That is unbelievable. I didn't think it was possible to commit **nothing**. Pls teach me your ways.

**Comment by HiroMizuki** [comment]
> Guys what are you talking about. This is the best Pull Request. I mean **nothing** was committed. That is unbelievable. I didn't think it was possible to commit **nothing**. Pls teach me your ways.

first step: make something useful
second step:

**Comment by ArezalGame89** [comment]
YES FINALLY! NO MORE MINECRAFT KID

**Comment by skedgyedgy** [comment]
ArezalGame89

**Comment by ArezalGame89** [comment]
> ArezalGame89

What? @skedgyedgy ?

**Pull request closed without merging**
