### PR TITLE
Mods setup menu

### PR DESCRIPTION
**Pull request by Joalor64**
you can make your own mod folder with a few buttons or something idk??
(no screenshots because i'm on my school chromebook rn)

### CODE REVIEW

**Comment by CharlesCatYT** [comment]
dude didnt you realize, making a mod folder is as easy as it can be, theres literally a mod template archive in the damn mods folder!!!!!

but eh sure

**Comment by RodneyAnImaginativePerson** [comment]
This is cool and all but... this isn't really needed.

**Comment by CharlesCatYT** [comment]
> This is cool and all but... this isn't really needed.

yeah agreed, like i said. making a mod folder is super easy, whats the point of this if theres a mod template zip file included in the repo, come on...

**Comment by Joalor64GH** [comment]
wait, you have a point

**Pull request closed without merging**
