### PR TITLE
sussy

### PR DESCRIPTION
**Pull request by NimuFurrySoftUwU**

### CODE REVIEW

**Comment by DaRealDotZ** [comment]
you're not funny

**Comment by BoloVEVO** [comment]
image

**Comment by Raltyro** [comment]
please stop

**Comment by CrusherMods** [comment]
please just stop like holy shit go outside, get bitches, touch grass, become a adult and not a kid, find your father & delete your github account

**Comment by BeastlyGhost** [comment]
@HiroMizuki point and laugh

**Comment by HiroMizuki** [comment]
stop making me die of asphyxia pls

**Comment by ShadowMario** [comment]
Minor spotted, ew

**Comment by CrusherMods** [comment]
> Minor spotted, ew

OUR HERO YES

**Comment by BeastlyGhost** [comment]
LET'S FUCKING GOOOOOOOOOOOOOO

**Comment by BoloVEVO** [comment]
Noise

**Comment by Fridox-lol** [comment]
LETS GOOOOOOOOOOOOOOOOOOOOOOO HE CLOSED IT

**Comment by Wither362** [comment]
@ShadowMario, if you ban this person (@NimuDevUwU), it would never bother you in this repository, so, why don’t you ban it and finish with this torture?

**Comment by GhostExpungedCycba** [comment]
someone give me context on this for a moment

**Comment by TheKitBoi** [comment]
> someone give me context on this for a moment

Ok
So @NimuFurrySoftUwU Made a pull request of one fucking file and people that chatted in here hated that person because he made other useless pull request on other engine

Here’s the links of the pull requests that made the drama
https://github.com/MAJigsaw77/FNF-PsychEngine-With-Android-Support/pull/8
https://github.com/MAJigsaw77/FNF-PsychEngine-With-Android-Support/pull/9
https://github.com/MAJigsaw77/FNF-PsychEngine-With-Android-Support/pull/17
https://github.com/YoshiCrafter29/YoshiCrafterEngine/pull/196
https://github.com/Yoshubs/Forever-Engine-Legacy/pull/107
https://github.com/MAJigsaw77/FNF-PsychEngine-With-Android-Support/pull/29
https://github.com/MAJigsaw77/FNF-PsychEngine-With-Android-Support/pull/30
https://github.com/KadeDev/Kade-Engine/pull/2922
https://github.com/KadeDev/Kade-Engine/pull/2924
https://github.com/KadeDev/Kade-Engine/pull/2925
https://github.com/KadeDev/Kade-Engine/pull/2936
https://github.com/ShadowMario/FNF-PsychEngine/pull/8506
https://github.com/ShadowMario/FNF-PsychEngine/pull/8528
https://github.com/ShadowMario/FNF-PsychEngine/pull/8601
https://github.com/ShadowMario/FNF-PsychEngine/pull/8602
https://github.com/ShadowMario/FNF-PsychEngine/pull/8726
https://github.com/ShadowMario/FNF-PsychEngine/pull/8744

**Pull request closed without merging**
