### PR TITLE
increase/bypass song bpm and change bpm limit

### PR DESCRIPTION
**Pull request by NAEL2XD**
hi would you increase or bypass song/change bpm? so i can make faster ones like youve made in agony song

### CODE REVIEW

**Comment by Rom4chek** [comment]
Is this bro fr merged that psych engine no botplay branch and did no changes at all

**Comment by TheKitBoi** [comment]
> hi would you increase or bypass song/change bpm? so i can make faster ones like youve made in agony song

JSON editing exist and I’m not bothered to help you

**Comment by MemeHovy** [comment]
> Is this bro fr merged that psych engine no botplay branch and did no changes at all

fr

**Comment by KookerFoxYT** [comment]
> hi would you increase or bypass song/change bpm? so i can make faster ones like youve made in agony song

issues tab exists 

also EDIT THE FUCKING JSON
GDFUDGTIDGYIFTOYTO

**Comment by NAEL2XD** [comment]
> > hi would you increase or bypass song/change bpm? so i can make faster ones like youve made in agony song
> 
> issues tab exists 
> 
> also EDIT THE FUCKING JSON
> GDFUDGTIDGYIFTOYTO
> 
> and i aint helping you either

# oh ok

**Comment by JordanSantiagoYT** [comment]
i prefer you not try to merge js engine with this engines github thanks

**Pull request closed without merging**
