### PR TITLE
fix of 25 min music length cap

### PR DESCRIPTION
**Pull request by TheLeerName**
music length and time was negative when music length was higher than 1521742ms (25:21.742)
idk maybe psych dont needed that but ok
with this fix music length cap will be 12173936ms (3:22:53.936), and if you crazy guys exceeds this limit then song length will be equals max music length lol

### CODE REVIEW

**Review by moxie-coder — APPROVED** [review]

**Comment by KookerFoxYT** [comment]
man d&b fans would have a field day with this one

**Review by charlesisfeline — APPROVED** [review]
i forgot to approve oops

**Comment by KookerFoxYT** [comment]
one thing
shouldn't this be able to be merged to the experimental branch (v0.7b) instead of the main one because 0.7 is coming out soon

**Comment by TheLeerName** [comment]
i did preventing negative value cool swag

**Comment by TheLeerName** [comment]
> one thing shouldn't this be able to be merged to the experimental branch (v0.7b) instead of the main one because 0.7 is coming out soon

when experimental will be pushed in main, i edit it

**Comment by CaptainBaldi** [comment]
tbh this seems like something that should just be added to a mod and not the base engine

**Comment by TheLeerName** [comment]
> tbh this seems like something that should just be added to a mod and not the base engine

why not, more features more fun

**Comment by NeeEoo** [comment]
Fyi: iirc the limit with this is 50 minutes, since the length of the song sample array overflows.

`@:privateAccess FlxG.sound.music._sound.__buffer.length` (fun fact: times 4 == ram usage)

And also the limit depends on the sample rate.

The number of 50 minutes was from when i made the same kind of fix, but used int64 instead of haxe's Ints (which are int32)

Where the line looked like this

`samples = Int64.toInt((Int64.make(0, dataLength) * Int64.ofInt(8)) / Int64.ofInt(parent.buffer.channels * parent.buffer.bitsPerSample));`

Only way to make it support longer songs would be to rewrite the way the song is loaded into memory, like by using either multiple arrays, or making it return an int64 when it gets the length in c++

**Review by libauror-a — APPROVED** [review]

**Review by lunacynne — APPROVED** [review]

**Review by aaaproooo — APPROVED** [review]

**Review by hackx2 — APPROVED** [review]

**Comment by jimmyjamescool** [comment]
Mfs finna chart fatal finale. A 40 minute song into a funny beep boop newgrounds rhythm game modification

**Review by jimmyjamescool — APPROVED** [review]

**Comment by ShadowMario** [comment]
Unnecessary, i fear it could cause any weird issues

**Pull request closed without merging**
