### PR TITLE
Pull on add fullscreen in engine

### PR DESCRIPTION
**Pull request by Fearester2008**

### CODE REVIEW

**Comment by CharlesCatYT** [comment]
no.

**Comment by mcagabe19** [comment]
tf?

**Comment by Fearester2008** [comment]
> no.

Why no?

**Comment by NexIsDumb** [comment]
Fyi if you press Alt + Enter it still activates full screen

**Comment by KELOTOMU** [comment]
Im pretty sure psych/flixel has a save feature so that when you exit the game in fullscreen, youll be in fullscreen once you open the game again

**Comment by NexIsDumb** [comment]
> Im pretty sure psych/flixel has a save feature so that when you exit the game in fullscreen, youll be in fullscreen once you open the game again

and? still pressing Alt + Enter will enable/diasble fullscreen

**Comment by ShadowMario** [comment]
Alt + Enter exists

**Comment by Fearester2008** [comment]
Where fullscreen code in source?

**Comment by NexIsDumb** [comment]
> Where fullscreen code in source? 

its not inside psych's one
iirc it was inside lime, cant be sure

**Pull request closed without merging**
