### PR TITLE
Bring the combo sprite back + be able to customize where you can place it

### PR DESCRIPTION
**Pull request by Trayfellow**
Adds the missing combo sprite back, and you can also adjust where its position is at on the options menu

Offset Menu (default positions)
bringComboBack-prPreview1
Offset Menu (customized positions)
bringComboBack-prPreview2
Gameplay
bringComboBack-prPreview3
Editor Gameplay
bringComboBack-prPreview4

### CODE REVIEW

**Review by stilic — APPROVED** [review]

**Review by TheKitBoi — APPROVED** [review]

**Review by Raltyro — APPROVED** [review]

**Review by Starveldt — APPROVED** [review]

**Review by ManMaster707 — APPROVED** [review]

**Review by iym1337 — APPROVED** [review]

**Review by DM-kun — APPROVED** [review]

**Review by BalancedLight — APPROVED** [review]

**Review by Parsellol — APPROVED** [review]

**Comment by antoSKRLOL** [comment]
cool!!

**Review by MemeHoovy — APPROVED** [review]

**Review by Joalor64 — APPROVED** [review]

**Review by system32unknown — APPROVED** [review]

**Comment by Raltyro** [comment]
Sad this is closed... :(

**Comment by MemeHovy** [comment]
yeah

**Comment by trayfellow** [comment]
> Sad this is closed... :(

this pr is pretty much at the rock bottom section of the pull requests so with the fact that shadow mario doesnt check pr's often i doubt this will even be found lol

**Comment by Paracosm-Daemon** [comment]
> > Sad this is closed... :(
> 
> this pr is pretty much at the rock bottom section of the pull requests so with the fact that shadow mario doesnt check pr's often i doubt this will even be found lol

funny you say that, i've incorporated this pr into my fork of psych personally because it's pretty nice, good job on it btw

**Pull request closed without merging**
