### PR TITLE
Use the HxCodec haxelib + add video sprites

### PR DESCRIPTION
**Pull request by stilic**
Didn't tested video sprites for now.
I need some people for test this PR by the way.

### CODE REVIEW

**Review by TheKitBoi — APPROVED** [review]

**Review by Itz-NOT-Miles — APPROVED** [review]
yes

**Comment by McJonnycat** [comment]
yes please add this

**Comment by Stilic** [comment]
i smoked after they upgraded the shit duh

**Comment by EyeDaleHim** [comment]
> i smoked after they upgraded the shit duh

One thing to take note of, huh.

**Comment by Stilic** [comment]
> I got a problem with the compiling it says source/PlayState.hx:1353: characters 3-7 : Expected } I don't really understand why this happens. Does anyone know why? Also when I tested the code in my build it was able to compile (weird?) but then application.hx bugs out and says type Main is not found. Shish Kebab

computer issue

**Review by Itz-NOT-Miles — APPROVED** [review]
yes(2)

**Comment by Randomxdp** [comment]
It didnt work?

**Comment by Stilic** [comment]
> It didnt work?

yes
i messed up with things
i forgot somet

**Comment by Stilic** [comment]
> It didnt work?

yes cuz i fucked up something
before it was working bruh

**Comment by TheKitBoi** [comment]
rip

**Pull request closed without merging**
