### PR TITLE
Fuck this shit

### PR DESCRIPTION
**Pull request by Joalor64**

### CODE REVIEW

**Comment by Joalor64GH** [comment]
Well, if you put a folder that contains your mod, for example, "vs-tricky-expanded", just replace the "your-mod-here|1" with "vs-tricky-expanded|1". Then, if you go to the Mods menu, the mod will appear there. And if you want to add other mod folders, type in the folders name, but instead of a "|1", add a "|2". Or a "|3", a "|4", and so on.

**Comment by TahirArch** [comment]
You need to code in to make it work though.

**Comment by Joalor64GH** [comment]
wdym??

**Comment by TahirArch** [comment]
How the engine supposed the recognize mods without coding mod stuff? You just created a text file which will not do anything.

**Comment by Joalor64GH** [comment]
bruh it does do something

**Comment by frantastic24** [comment]
This is pointless the engine already manages a mod lost

**Comment by TheKitBoi** [comment]
you attempting to fool shadowmario to merging a uncapped bpm (no limit) commit

**Comment by Joalor64GH** [comment]
im actually not trying to fool

**Comment by Joalor64GH** [comment]
i was just dumb and didn't make the commits in another branch

**Comment by Joalor64GH** [comment]
okay nvm

**Pull request closed without merging**
