### PR TITLE
Fix Psych engine 0.7.X build with haxe 4.3.1 and updated libraries (flixel 5.3.1, flixel-addons 3.1.1, etc.)

### PR DESCRIPTION
**Pull request by Gabo137**
just add #if (!macro) in import.hx

### CODE REVIEW

**Comment by Vortex2Oblivion** [comment]
couldn't you just...
put #if !macro around everything?
and not need to do it like 7 times?

**Comment by Gabo137** [comment]
I did it and for some strange reason it gave me an error.
And the only thing that came out was this

**Comment by mcagabe19** [comment]
duplicate of https://github.com/ShadowMario/FNF-PsychEngine/pull/13015

**Comment by Gabo137** [comment]
oh, I didn't realize there was one just like it...
I think I'm going to close it

**Comment by mcagabe19** [comment]
> > duplicate of #13015
> 
> the only difference is that theres 7 `#if (!macro)`s

more simplied version

**Comment by NexIsDumb** [comment]
and erm
the other day shadow merged a pr that fixed haxe 4.3.1
so this and #13015 are both useless

**Pull request closed without merging**
