### PR TITLE
add a hardcoded keybind to reset controls in the main menu

### PR DESCRIPTION
**Pull request by crowplexus**
because apparently people can bind `ENTER` to the back button and basically hardlock their copy of psych easily

### CODE REVIEW

**Review by moxie-coder — COMMENTED** [review]
were the extra things you added intentional?

**Comment by CrowPlexus** [comment]
> were the extra things you added intentional?

had to adjust the texts so it wouldn't look weird with the keybind reset indicator

**Review by rodney528 — APPROVED** [review]

**Review by DetectiveBaldi — APPROVED** [review]
imo it would be better on the title menu, still fine tho

**Review by moxie-coder — APPROVED** [review]

**Comment by RodneyAnImaginativePerson** [comment]
Can you also do the same thing for skins? As a problem can occur where your completely locked out of songs and options visuals menu.

**Review by NexIsDumb — APPROVED** [review]

**Comment by crowplexus** [comment]
bup.

**Pull request closed without merging**
