### PR TITLE
Fix for Switch Controllers

### PR DESCRIPTION
**Pull request by rodney528**
Someone was tried hu?

### CODE REVIEW

**Comment by ImaginationSuperHero528** [comment]
Basically when playing in a song it would swap the binds instead of just in the menus.

[Click here to see what I mean](https://media.discordapp.net/attachments/931776524527489036/991925940500299806/export202206300039043990.png)

**Comment by ImaginationSuperHero528** [comment]
Maintainers can edit it since ya know resolve conflict stuff plus I did this on my phone 🥲

**Comment by ImaginationSuperHero528** [comment]
Also changed death to select instead of click on left joystick

**Review by rodney528 — COMMENTED** [review]
I will try to figure this out...

**Comment by Raltyro** [comment]
wait why was funkinlua removed

**Comment by ImaginationSuperHero528** [comment]
> wait why was funkinlua removed

Idk it was there help

**Comment by Raltyro** [comment]
revert the commit that deleted funkinlua? it isnt that hard to revert

**Comment by ImaginationSuperHero528** [comment]
> revert the commit that deleted funkinlua? it isnt that hard to revert

1. IDK HOW! 😭
2. Are you a maintainer? If so you might be able to do it.

**Comment by Raltyro** [comment]
im not but i can make a pr inside of a pr
but feeling lazy

**Comment by ImaginationSuperHero528** [comment]
Also in the thing it says I deleted FunkinLua.hx but
[Click here for a video](https://streamable.com/oqhzyn)

**Comment by trayfellow** [comment]
> > revert the commit that deleted funkinlua? it isnt that hard to revert
> 
> 1. IDK HOW! 😭
> 2. Are you a maintainer? If so you might be able to do it.



> > revert the commit that deleted funkinlua? it isnt that hard to revert
> 
> 1. IDK HOW! 😭
> 2. Are you a maintainer? If so you might be able to do it.

https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/reverting-a-commit maybe try following this

**Comment by ImaginationSuperHero528** [comment]
> > > revert the commit that deleted funkinlua? it isnt that hard to revert
> > 
> > 
> > 
> > 1. IDK HOW! 😭
> > 2. Are you a maintainer? If so you might be able to do it.
> 
> > > revert the commit that deleted funkinlua? it isnt that hard to revert
> > 
> > 
> > 
> > 1. IDK HOW! 😭
> > 2. Are you a maintainer? If so you might be able to do it.
> 
> https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/reverting-a-commit maybe try following this

It gives errors when trying to revert!

**Review by rodney528 — COMMENTED** [review]
It's now only a one file change thank god I fixed that.

**Comment by ImaginationSuperHero528** [comment]
@ShadowMario, I think you should look at this.

**Comment by ShadowMario** [comment]
It's okay, you tried.

**Comment by ImaginationSuperHero528** [comment]
> It's okay, you tried.

@ShadowMario... ya know the face buttons for switch are messed up right?

**Comment by ImaginationSuperHero528** [comment]
🤦🏻

**Comment by frantastic24** [comment]
No?

**Pull request closed without merging**
