### PR TITLE
Lua Animation Finished Callback and Lane Underlay Option

### PR DESCRIPTION
**Pull request by BombasticTom**
Lua Callback for when an Animation is finished could be cool
Also Lane Underlay Option because I'm a hardcore fan for that option

It's fine if this doesn't merge with the base repo, this is my first pull request after all.

The Animation callback works similarly to the Tween and Timer callbacks
Here's an example:

```
function onAnimCompleted(obj, anim)
        debugPrint(obj, ' played ', anim);
end
```

Here's a screenshot of the Lane Underlay Transparency option:
image

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Huh, neat.

**Comment by BombasticTom** [comment]
> Huh, neat.

specifically inspired by indie cross porters!

**Comment by antipatski** [comment]
if getProperty("obj.animation.curAnim.curFrame") == getProperty("obj.animation.curAnim.frames") then

**Comment by MilkyTheMilkBlob** [comment]
image
can you fix this please?

**Comment by BombasticTom** [comment]
NOOOOO IT GOT OUTDATED

**Comment by BombasticTom** [comment]
ye ok fixed it now

**Comment by MilkyTheMilkBlob** [comment]
les gooooo

**Comment by ImaginationSuperHero528** [comment]
> NOOOOO IT GOT OUTDATED

Ourdated again.

**Review by rodney528 — APPROVED** [review]
Half needed I'ma be honest

**Pull request closed without merging**
