### PR TITLE
add lua function loadSong

### PR DESCRIPTION
**Pull request by craftersshaft**
might need a better name but loads in a new song from a json file. first variable is the json's filename, second variable is the folder, third variable is whether or not to skip the transition. could be useful for more cases than just this tutorial (a song select sub-menu in something like a story mode where you need to choose a path, switching to a song as a replacement to death, notes that mess up your entire run and get you to complete a joke song, switching to a different chart on character change, etc)

```lua
function onUpdate(elapsed)
	if keyJustPressed('space') then
		loadSong('tutorial', 'tutorial', true);
	end
end

### CODE REVIEW

**Comment by SilkyIncorprated** [comment]
yoooo this is just what i need bro, hope this gets added

**Comment by ProgramerGamerZone** [comment]
ADD THISSSSSSSSS

**Comment by fnaffan29** [comment]
we need this

**Comment by jigsaw-4277821** [comment]
Add this

**Comment by PoleyMagik** [comment]
Dunno if the code is good or not but this shit is hella pog, always wanted to make like a week with branching pathes and this would allow that

**Comment by craftersshaft** [comment]
im not sure how i would go about it, but for making another addition should i merge it with this pull request or make a new one? basically having a new function like isColliding called isOverlapping and instead of calling FlxG.collide, it calls FlxG.overlap which only checks if they overlap instead of being directly on the edge

**Comment by Steviegt6** [comment]
> im not sure how i would go about it, but for making another addition should i merge it with this pull request or make a new one? basically having a new function like isColliding called isOverlapping and instead of calling FlxG.collide, it calls FlxG.overlap which only checks if they overlap instead of being directly on the edge cause i cant get isColliding to work how i want it to

Make a new pull request on a different branch.

**Comment by supajimmy** [comment]
I think that will be nice tbh

**Review by GamerZoneMusic — APPROVED** [review]
Why isn't this merged yet everyone in the discussions keeps asking for this, it is currently one of the most requested features

**Comment by frantastic24** [comment]
> Why isn't this merged yet

Bug fixing comes first from what I can tell, nothing is stopping people from adding it to their fork anyhow

**Comment by olliesus11131** [comment]
i tried using it it broke the scroll speed of songs but it works

**Comment by craftersshaft** [comment]
> i tried using it it broke the scroll speed of songs but it works

odd, will check why it happens but i mostly just stole the code from how weeks progress to different songs

**Review by lunacynne — APPROVED** [review]

**Review by zephyr-zeph — APPROVED** [review]
but really, this is fucking amazing so many people need this for their literal mod. i dunno how to compile source code so yeah

**Review by Lila-Rogers — APPROVED** [review]

**Review by Lila-Rogers — APPROVED** [review]

**Review by GO-Miles — APPROVED** [review]

**Comment by lolbruhfart** [comment]
I NEED THIS PLS OMFG

**Review by GO-Miles — APPROVED** [review]

**Comment by PrismLight** [comment]
👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀

**Review by ghost — APPROVED** [review]
This is just what the Dave and Bambi fans always wanted.

**Review by lolbruhfart — APPROVED** [review]

**Review by Blossomical — APPROVED** [review]
this should be added

**Comment by ProgramerGamerZone** [comment]
Ok it's been a month why did no one add this yet

**Review by megasssdev — APPROVED** [review]
poggers

**Review by JorosTheModderPH — APPROVED** [review]

**Review by trippinreal — APPROVED** [review]

**Comment by Dragonteam1708** [comment]
Yo, do you know what you would put for like credits?

Example: 
You click on a credit
Takes you to song

**Review by HeliProGamer — APPROVED** [review]

**Review by ZAngryCadet — APPROVED** [review]

**Comment by ProgramerGamerZone** [comment]
THEY ADDED IT

**Pull request closed without merging**
