### PR TITLE
lol

### PR DESCRIPTION
**Pull request by NimuFurrySoftUwU**
Hi im gonna use your engine for my mod you want no use your engine sent me message my twitter Twitter:CherryDevUwU
<3 thank for your time

### CODE REVIEW

**Comment by CrusherMods** [comment]
fun fact: this isn't how this repo works
if your gonna use psych engine you don't need to upload it to this repository just leave it in your own

**Comment by Gibberditoslumber** [comment]
please leave im a kid who some what knows how to code 'YOU DONT'

**Comment by CrusherMods** [comment]
another fun fact:

```
var bitches:Int = 1;
var family:Bool = true;
var gotalife:Bool = true;
var adopted:Bool = false;
var STUPID:Bool = false;
var ratio:Int = 0;
var hasBrain:Bool = true;
var stupidKid:String = 'NimuDevUwU';

if (stupidKid == 'NimuDevUwu') 
{
    bitches = 0;
    family = false;
    gotalife = false;
    adopted = true;
    STUPID = true;
    ratio++;
    hasBrain = false;
}
```

**Comment by Gibberditoslumber** [comment]
BURNED IN CODE FORM

**Comment by Gibberditoslumber** [comment]
var bitches:Int = 1;
var family:Bool = true;
var gotalife:Bool = true;
var adopted:Bool = false;
var STUPID:Bool = false;
var ratio:Int = 0;
var hasBrain:Bool = true;
var stupidKid:String = 'NimuDevUwU';

override function create()
{
    if (stupidKid == 'NimuDevUwU') 
    {
        bitches = 0;
        family = false;
        gotalife = false;
        adopted = true;
        STUPID = true;
        ratio++;
        hasBrain = false;
    }
}

ima make that actual usable code

**Comment by Gibberditoslumber** [comment]
for me its this:

package;

class SmartKid extends RealSmartass
{
    var bitches:Int = 1;
    var family:Bool = true;
    var gotalife:Bool = true;
    var adopted:Bool = false;
    var STUPID:Bool = false;
    var ratio:Int = 0;
    var hasBrain:Bool = true;
    var smartKid:String = 'Averey';

    override function create()
    {
        if (smartKid == 'Averey') 
        {
            bitches = 1;
            family = true;
            gotalife = true;
            adopted = false;
            SMART = true;
            ratio++ = false;
            hasBrain = true;
        }
    }
}

**Comment by Gibberditoslumber** [comment]
HTML Editing is way too easy image

**Comment by CrusherMods** [comment]
> HTML Editing is way too easy image

bro just gave him the perfect username

**Comment by Gibberditoslumber** [comment]
TRUE

**Comment by Gibberditoslumber** [comment]
ahh much much better now image

**Comment by CrusherMods** [comment]
WAIT DID IT GET CLOSED??? WAHOOO

**Pull request closed without merging**
