### PR TITLE
make supported versions list

### PR DESCRIPTION
**Pull request by ssdrive-flaktra**
just saying these versions should be the ones most compatible.

### CODE REVIEW

**Comment by MeowcaTheoRange** [comment]
You kinda, uh, *forgot to change the version list*. We're currently on 0.4.2, and according to the list, it's not fully supported, which is kind of silly.

**Comment by AToska21** [comment]
> You kinda, uh, _forgot to change the version list_. We're currently on 0.4.2, and according to the list, it's not fully supported, which is kind of silly.

oops

**Comment by AToska21** [comment]
should be fixed now

**Comment by Steviegt6** [comment]
This is pretty useless. It just completes a generic GitHub repository security task they always ask you to do (which doesn't accomplish anything seeing as this program offers no security in the first place).

**Comment by Steviegt6** [comment]
> This is pretty useless. It just completes a generic GitHub repository security task they always ask you to do (which doesn't accomplish anything seeing as this program offers no security in the first place).

Furthermore, supported versions aren't relevant since different mods will be based on different versions of the engine. This doesn't aid in anything worthwhile.

**Pull request closed without merging**
