### PR TITLE
Fixed Cocoa Charts

### PR DESCRIPTION
**Pull request by MasterDirector99**
It fixes all the difficulty charts for the one song called Cocoa!

### CODE REVIEW

**Comment by MasterDirector99** [comment]
Don't merge it yet, I had to fix both normal & hard

**Comment by ShadowMario** [comment]
What was the issue with it???

**Comment by tposejank** [comment]
they probably weren't like the chart generating right now. It wasn't even a issue either

**Comment by MasterDirector99** [comment]
Some changes

Normal: Left Right Left Right Up was changed to just Left Left Up
Easy & Hard: Alt Animation enables when Mommy Mearest finished sang

**Comment by HiroMizuki** [comment]
removing the left right left right up on normal is rlly unnecessary cuz it's normal mode, it would be understandable if that chart was at easy

**Comment by ShadowMario** [comment]
No.

**Pull request closed without merging**
