### PR TITLE
Tiny oversight that probably doesn't effing matter

### PR DESCRIPTION
**Pull request by rodney528**
I think that should be a 3... not a 4.

### CODE REVIEW

**Comment by ImaginationSuperHero528** [comment]
Fun Fact I did this all off of my phone :D surprisingly didn't run into much difficulty. Since I only really changed one number.

**Comment by Raltyro** [comment]
i think it does matter, haxe loop is kinda odd
when you do 0...4 it will end at 3, and 0...3 will end at 2

**Comment by lemz1** [comment]
4 is right.
for loops in haxe work differently than other programming languages.
in this case ***i*** will equal to
0,1,2,3
so yeah close this pr

**Comment by ImaginationSuperHero528** [comment]
> 4 is right. for loops in haxe work differently than other programming languages. in this case _**i**_ will equal to 0,1,2,3 so yeah close this pr

Oh... ok.

**Pull request closed without merging**
