### PR TITLE
Create 1.

### PR DESCRIPTION
**Pull request by MAUROPORT**

### CODE REVIEW

**Comment by MAUROPORT** [comment]
Ns

**Comment by MAUROPORT** [comment]
Ta weno

**Review by moxie-coder — COMMENTED** [review]
No

**Comment by Rom4chek** [comment]
Kys

**Comment by TheKitBoi** [comment]
> Ta weno

Lā shǐ zìjǐ

**Comment by Burgerballs** [comment]
Perfect pr, inspired me on so many levels

1.

**Comment by jimmyjamescool** [comment]
When will they create 2

**Review by jimmyjamescool — APPROVED** [review]
I can't fucking believe this. Pink from 'Among Us' ruined my marriage.  A couple months ago, my wife said she was going out for a ladies' night. She asked me to take care of my son, so I immediately obliged. "Yes Ma'am," I told her. After a while of waiting, she finally left and I could play my favourite game, Among Us. I hopped on my laptop, booted it up and my desktop loaded, complete with the 'Red Sus' background and all my Among Us Impostor fan-art. I was shaking in excitement. I slowly dragged my finger across the track pad, and watched the cursor as it glided over to the Among Us icon. Among Us. My absolute favourite game of all time and quite possibly the best and most well-made game in the entire world. As I clicked the button my body twitched with joy at the thought of being the impostor again. My fingers drummed impatiently on my desk as the Innersloth logo faded in, and then out. Then the main title appeared. I immediately looked at pink as she slowly floated across the screen. Oh, how I wish I could feel those luscious, soft asscheeks. Pink is my queen. The real woman in my life. My wife could never be as sexy as Pink is; her soft footfalls in electrical as I peek at her curvy form from inside a vent, waiting for the right time to strike. I could never get close to Pink, however, as if she had some kind of sixth sense, she would always leave before I could reveal myself to her as the impostor. I press Practice, to warm up my fingers before my first intense game of Among Us. I hit Blue in Comms, then cross the hall and vent to Specimen, murdering Green in cold blood. The thrill of killing an animated character in an online game has never been such a rush. I then move towards Reactor, stabbing Yellow in the back and then running down the corridor to the right to access Decontamination. I move quietly through the halls, like a snake about to strike its prey, and I see- Oh no. It's Pink. Standing there motionlessly as I face her directly. Her visor shows no emotion. But she knows. I can feel it in the air. I can't kill her. She is too beautiful, too angelic, the light reflecting off of her pink bodysuit, like stars on a voided sky. She doesn't run. I am moved to tears as I caress the screen, kissing it tenderly. "Goodbye, Pink. See you soon. It will all be okay," I whisper in a soft, reassuring voice. Then as my cursor hovers over the kill button, I hesitate. Thoughts of love go through my head. Red having reddish-pink sus children with Pink. But I have to. As the impostor, it is my duty to kill. I press the 'Kill' button and watch as my character beheads Pink silently. All I hear is the spurt of blood. There is no rush. There is only Red, standing by himself in Fuel. Pink's lifeless body laying on the floor beside him. I feel nothing at first, then immense sadness, like I'm at a loved one's funeral. My son knocks on the door, interrupting my brief moment of mourning. He asks, "Dad? Are you going to make me a snack?" I tell him to shut up, and my voice cracks. I break down sobbing. I killed her. I killed my one true love. God, forgive me. I open the door to my son, and he has a confused look on his face. I say nothing, and walk to the kitchen to make him a sandwich. Tears roll off my face into the bread as I lay it onto the counter. Lettuce, cheese and meat, followed by a sad swirl of mustard on top. My son is quiet. He sits on the couch, and stares at the floor. There is a depressing air around us. I serve him the sandwich and walk back to my room, contemplating life. If I killed Pink, how am I to be trusted around my family? I cry for hours, and finally my wife comes back. She sees me bawling on the bed like a child who dropped his ice cream. She then asks me why I'm crying and mutter, "I killed her. I killed my only love, Pink, in Among Us." She is filled with rage and slaps me across my face. I feel numb. She asks for a divorce. I don't reply. Instead, I take my laptop and get into my car, driving to a nearby hotel. Fast forward a few months to the divorce. It was quick and painless. After court, I ask my former wife to take me back.  "I can't take you back. You've always been this way. I was sus of you from the start."  Edit: Found this on steam, in the Among Us reviews section.

**Comment by ThePlank** [comment]
war

**Pull request closed without merging**
