### PR TITLE
Update CoolUtil.hx

### PR DESCRIPTION
**Pull request by liew757**

### CODE REVIEW

**Comment by HiroOfc** [comment]
what

**Comment by franjavierr** [comment]
We don't need more difficulties to the base game, add it to your mod or something

**Comment by Doritojoey** [comment]
every song would crash if there wasnt a chart made this would just be a whole other load of work for psych 5

**Comment by nintendofan44** [comment]
@liew757 yknow there is a thing for loading custom diffs in the freeplaystate
and it works on the storymode menu too
even if you need to add the texture on a folder
still, there already is something that you can add more diffs
and you can like add 2 more to a song and 5 more to another and that would work fine

**Comment by HiroOfc** [comment]
yea, they're right
but something i think nobody noted: **he forgot a comma at the code**

**Comment by SrtHero278** [comment]
Welp, we know what request is being closed.

**Comment by DaBanana64** [comment]
You can literally add custom difficulties on the latest commit. (Only works in Freeplay, I think it's still being worked on) Close this please.

**Comment by Steviegt6** [comment]
@ShadowMario

**Comment by ShadowMario** [comment]
Stupid + Outdated + Ratio + Take this L

**Pull request closed without merging**
