### PR TITLE
A few improvements

### LINKED ISSUE #1237: Optimization Mode for really shit PC's
### What feature do you want to get added on the base engine?

I would like an optimization mode to get added to Psych Engine, which removes backgrounds and characters entirely.

This could have the potential to help with performance on comically bad PC's...like mine and also focus.

If not optimization atleast some overlay below the arrows?, Low quality being on and anti-aliasing being off don't help with performance a whole lot.

I don't have anything else to say here

### LINKED ISSUE #1510: intro text mod support
### What feature do you want to get added on the base engine?

Currently from what ive tried, you cant have a custom intro text using the mod folder. i place it into the mods/data folder, and when i load up the game. its just the base text. (unless im doing this wrong, sorry if i am). but if you can, could you add the ability to use custom intro text using the mod folder?

### LINKED ISSUE #1761: Gamepad inputs are very buggy
### Describe your bug here.

On the latest source code build, the gamepad inputs are very buggy: i can only hit visible notes and can't miss when there are not notes.

### Command Prompt/Terminal logs (if existing)

_No response_

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

### LINKED ISSUE #1773: Icons in Freeplay work like they do in-game if you can listen to it
### What feature do you want to get added on the base engine?

If just listening to a song in freeplay comes back you should add a feature while listening to a song the icons will bump (I dont know how to put this lmao) to the way it is in-game, Like literally every request this is optional

(I bet your gonna come and say no ShadowMario lmao)

### LINKED ISSUE #4005: intro text doesnt appear on beat
### Describe your bug here.

dunno if this has been talked about yet but sometimes does appear on beat but very rarely, the last build to not have this issue is 0.4.2

this is me using version 0.4.2
https://user-images.githubusercontent.com/48515908/151290755-ac4f3f6e-29dc-4876-a527-a7c5a1ce58c9.mp4

this is me using version 0.5.1
https://user-images.githubusercontent.com/48515908/151290853-ec07138a-dfc4-4e3e-a3f9-8f1f39a78133.mp4

### Command Prompt/Terminal logs (if existing)

_No response_

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no i didn't mod anything

### PR DESCRIPTION
**Pull request by stilic**
- Add Freeplay bumping based on the current played song's BPM (closes #1773).
- Add "Max Optimization" option (closes #1237).
- Add modding support for introText (place file in `mods/introText.txt`) (closes #1510).
- Make controller working without using an option.
- Fix the delayed title screen intro (closes #4005).

### CODE REVIEW

**Comment by CrusherMods** [comment]
I'll close mine if this gets merged but epic

**Comment by CrusherMods** [comment]
Can I use the freeplay bump for a mod???

**Comment by Stilic** [comment]
> Can I use the freeplay bump for a mod???

Yes, you can!

**Comment by Gui-iago** [comment]
there's this weird bug with the inputs on your fork @Stilic 

https://user-images.githubusercontent.com/45212377/145148829-d82fefae-a005-4dd6-9237-56fae1fba963.mp4

happens with songs that have double notes, or multiple notes stacked on top of one another (like Thorns)

**Comment by Stilic** [comment]
> there's this weird bug with the inputs on your fork @Stilic
> 
>  2021-12-08.00-35-07.mp4 
> happens with songs that have double notes, or multiple notes stacked on top of one another (like Thorns), no matter the Scroll Direction, Up or Down, it still happens
> 
> Settings: Controls: DFJK, Left Down Up Right Note Splashes: On Ghost Tapping: On Rating Offset: 0ms (default) Sick! Hit Window: 45ms (default) Good Hit Window: 90ms (default) Bad Hit Window: 135ms (default) Safe Frames: 10 (default)
> 
> System: Arch Linux

I don't think it is related to my fork but to the original engine instead.

**Comment by bbpanzu** [comment]
finna take a look at this. seems like pogger stuff

**Comment by HiroOfc** [comment]
> > there's this weird bug with the inputs on your fork @Stilic
> > 2021-12-08.00-35-07.mp4
> > happens with songs that have double notes, or multiple notes stacked on top of one another (like Thorns), no matter the Scroll Direction, Up or Down, it still happens
> > Settings: Controls: DFJK, Left Down Up Right Note Splashes: On Ghost Tapping: On Rating Offset: 0ms (default) Sick! Hit Window: 45ms (default) Good Hit Window: 90ms (default) Bad Hit Window: 135ms (default) Safe Frames: 10 (default)
> > System: Arch Linux
> 
> I don't think it is related to my fork but to the original engine instead.

well, yes, it is
but don't worry, i discovered what it is

these functions made the input broke and it will make the player miss a lot (like me, that i've got 110 errors at roses)
```
private function keyPress(keyCodeValue:Int) {
		var event:KeyboardEvent = new KeyboardEvent(KeyboardEvent.KEY_DOWN, false, false, 0, keyCodeValue);
		FlxG.stage.dispatchEvent(event);
	}

	private function keyRelease(keyCodeValue:Int) {
		var event:KeyboardEvent = new KeyboardEvent(KeyboardEvent.KEY_UP, false, false, 0, keyCodeValue);
		FlxG.stage.dispatchEvent(event);
	}
```

**Comment by HiroOfc** [comment]
so to fix this, i've put it on my source and just deleted the lines with the functions and the lines that mentioned the functions (lines 3578 - 3588 and 3602 - 3611)

**Comment by Stilic** [comment]
Oh ok. I will add a if for detect if gamepad is used (because I originally made this for fix gamepad bug).

**Comment by Stilic** [comment]
@Gui-iago @HiroOfc Please retest and say to me if the bug persist.

**Comment by HiroOfc** [comment]
> @Gui-iago @HiroOfc Please retest and say to me if the bug persist.

sure, i'll test here

**Comment by HiroOfc** [comment]
well, still got the same thing here

**Comment by Stilic** [comment]
> well, still got the same thing here

OK, I will try to fix that.

**Comment by Stilic** [comment]
@HiroOfc Now retry please.

**Comment by HiroOfc** [comment]
> @HiroOfc Now retry please.

i'll test later bud, i'm kinda busy right now

**Comment by Gui-iago** [comment]
> > @Gui-iago @HiroOfc Please retest and say to me if the bug persist.
> 
> sure, i'll test here

now it crashes when trying to play any song

**Comment by Stilic** [comment]
Maybe retry now? @HiroOfc
Also, as I see, ShadowMario fixed the controller support by adding a controller mode option. I improved it for detect use of controller directly, whitout the need for a manual setting from player.

**Comment by HiroOfc** [comment]
ok, i'll test it

**Comment by HiroOfc** [comment]
bruh, i'll need to reinstall the engine cuz it has broken
it's not the pr's fault, just wait a sec

**Comment by Doritojoey** [comment]
Why exactly are you putting so many changes into a completely unrelated pr
No reason to touch the inputs either

**Comment by HiroOfc** [comment]
welp, it is working properly now bud, good work

**Comment by Stilic** [comment]
> Why exactly are you putting so many changes into a completely unrelated pr No reason to touch the inputs either

These chnages are maybe unrelated sometimes but these changes are improvements to the engine, not really useless changes.

**Comment by Stilic** [comment]
@ShadowMario Please, can you check this PR?

**Comment by prokube** [comment]
> there's this weird bug with the inputs on your fork @Stilic
> 
>  2021-12-08.00-35-07.mp4 
> happens with songs that have double notes, or multiple notes stacked on top of one another (like Thorns), no matter the Scroll Direction, Up or Down, it still happens
> 
> Settings: Controls: DFJK, Left Down Up Right Note Splashes: On Ghost Tapping: On Rating Offset: 0ms (default) Sick! Hit Window: 45ms (default) Good Hit Window: 90ms (default) Bad Hit Window: 135ms (default) Safe Frames: 10 (default)
> 
> System: Arch Linux

Playing Test on ProjectFNF 1 be like

**Comment by Stilic** [comment]
@bbpanzu Can you take a look at this please?

**Comment by Gui-iago** [comment]
@Stilic 
I made a fork of the upstream repo with your changes, is that ok?

**Comment by Stilic** [comment]
> @Stilic I made a fork of the upstream repo with your changes, is that ok?

You should wait merge of this PR before.

**Comment by Stilic** [comment]
If someone could merge this ASAP, It can be really good for Psych Engine!

**Comment by Doritojoey** [comment]
I really don't think any of these are necessary like whatsoever, seems like it would just require a lot more elbow grease to work with the expanded features
Especially like, input, Psych's input is unmatched

**Comment by Doritojoey** [comment]
No offense by the way I think there was a lot of work put into the code it just seems like excess though wouldn't really improve Psych that much compared to other things that can be done
Then again I can't code so

**Comment by Stilic** [comment]
> I really don't think any of these are necessary like whatsoever, seems like it would just require a lot more elbow grease to work with the expanded features Especially like, input, Psych's input is unmatched

I agree!

**Comment by DaBanana64** [comment]
I think these changes are ok, but the whole bumping icons while the song is playing (Just like FNF HD) is really a neat change.

**Comment by Stilic** [comment]
Only the screen is bumping, not the icons. I should add it later.

**Comment by DaBanana64** [comment]
> Only the screen is bumping, not the icons. I should add it later.

Oh.

**Comment by nintendofan44** [comment]
> Only the screen is bumping, not the icons. I should add it later.

i figured that out

i can send the code if you want

**Comment by Stilic** [comment]
> > Only the screen is bumping, not the icons. I should add it later.
> 
> i figured that out
> 
> i can send the code if you want

If you can, yes! (My Discord server link is on my GitHub profile README)

**Comment by Stilic** [comment]
@ShadowMario @bbpanzu Ok, now it's done. This PR can be merged!

**Comment by Gui-iago** [comment]
this happens on HTML5 

https://user-images.githubusercontent.com/45212377/146865239-0ffb4223-6718-402c-991b-1f6d0ff892da.mp4

compiled build is fine
https://user-images.githubusercontent.com/45212377/146865551-3a19f2de-fd30-4a38-bf37-b566cf7929f5.mp4

**Comment by Stilic** [comment]
> this happens on HTML5
> 
>  2021-12-20.23-17-33.mp4 
> compiled build is fine
> 
>  2021-12-20.23-21-13.mp4

Mhhhh... I don't know why this happen...

**Comment by DMMaster636** [comment]
i hope this gets updated
i really wanna merge this with my fork again

**Comment by Stilic** [comment]
> i hope this gets updated i really wanna merge this with my fork again

It is already updated.

**Comment by DMMaster636** [comment]
> > i hope this gets updated i really wanna merge this with my fork again
> 
> It is already updated.

YEEEEEE

**Comment by Stilic** [comment]
deadlight pr!!!!!!!!!!!

**Comment by MrClogsworthYT** [comment]
beep

**Comment by SonicProYT** [comment]
make it compatible with 0.5.2

it has conflicts that must be resolved to be used in psych engine forks

**Comment by Stilic** [comment]
> make it compatible with 0.5.2
> 
> it has conflicts that must be resolved to be used in psych engine forks

me when im on mobile: bruh, going to do that in a few days

**Pull request closed without merging**
