### PR TITLE
Fix BPM setter setting the BPM twice

### PR DESCRIPTION
**Pull request by crowplexus**
yeah

### CODE REVIEW

**Review by moxie-coder — APPROVED** [review]
I didn’t notice that lol

**Review by libauror-a — APPROVED** [review]
https://github.com/ShadowMario/FNF-PsychEngine/assets/75984453/9ae4ff48-1b23-4f93-8d02-3882da547b01

**Review by Sword352 — APPROVED** [review]

**Comment by Akhia11** [comment]
@MemeHovy do you even check before approving and why the fuck are you approving every pr?@?@?@?@?@??@?@?@?@?@!?!??!?!?!?!?!??!?!

**Comment by MemeHovy** [comment]
> @MemeHovy do you even check before approving and why the fuck are you approving every pr?@?@?@?@?@??@?@?@?@?@!?!??!?!?!?!?!??!?!

I do check, and not every one

**Comment by Akhia11** [comment]
You almost approved ever pr dude ik its not every pr but almost every pr I see in my face has "memehoovy approved changes" like chill damn

**Review by NexIsDumb — APPROVED** [review]
dang💀

**Review by rodney528 — APPROVED** [review]

**Comment by crowplexus** [comment]
bup.

**Pull request closed without merging**
